/* Emulated cycles of each original instruction in the subphase 3.16 routines, from the
 * cpu8086.c cost model; generated by tools/gen_editor_cycles.py (do not edit): address,
 * cost (for a conditional jump or LOOP: when it falls through), cost when it jumps. */
#ifndef FS1_EDITOR_CYCLES_H
#define FS1_EDITOR_CYCLES_H

#include <stdint.h>

typedef struct EdInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} EdInsCost;

static const EdInsCost ed_ins_cost[] = {
    { 0x00BE, 21, 21 }, /* call sub_00F8 */
    { 0x00C1, 4, 4 }, /* mov bx, 0x1c */
    { 0x00C4, 12, 12 }, /* mov al, byte ptr [disk_track] */
    { 0x00C7, 18, 18 }, /* mov byte ptr [bx + 0x3c5], al */
    { 0x00CB, 6, 6 }, /* sub bx, 4 */
    { 0x00CE, 4, 16 }, /* jns loc_00C7 */
    { 0x00D0, 4, 4 }, /* mov bx, 0x3c5 */
    { 0x00D3, 4, 4 }, /* mov ax, 0x508 */
    { 0x00D6, 17, 17 }, /* mov dx, word ptr [0x3c0] */
    { 0x00DA, 17, 17 }, /* mov ch, byte ptr [disk_track] */
    { 0x00DE, 4, 4 }, /* mov cl, 1 */
    { 0x00E0, 4, 4 }, /* mov cl, 8 */
    { 0x00E2, 53, 53 }, /* int 0x13 */
    { 0x00E4, 4, 4 }, /* mov cl, 1 */
    { 0x00E6, 4, 4 }, /* mov ah, 1 */
    { 0x00E8, 4, 16 }, /* jae loc_0109 */
    { 0x00EA, 19, 19 }, /* mov byte ptr [disk_error], 1 */
    { 0x00EF, 20, 20 }, /* ret */
    { 0x00F0, 21, 21 }, /* call sub_00F8 */
    { 0x00F3, 5, 5 }, /* xor ah, ah */
    { 0x00F5, 53, 53 }, /* int 0x13 */
    { 0x00F7, 20, 20 }, /* ret */
    { 0x00F8, 5, 5 }, /* xor ax, ax */
    { 0x00FA, 4, 4 }, /* mov ds, ax */
    { 0x00FC, 12, 12 }, /* mov ax, word ptr [0x120] */
    { 0x00FF, 4, 4 }, /* mov es, ax */
    { 0x0101, 4, 4 }, /* mov ds, ax */
    { 0x0103, 20, 20 }, /* ret */
    { 0x0104, 21, 21 }, /* call sub_00F8 */
    { 0x0107, 5, 5 }, /* xor ah, ah */
    { 0x0109, 18, 18 }, /* mov byte ptr [0x3b2], ah */
    { 0x010D, 19, 19 }, /* mov word ptr [screen_seg], 0xb800 */
    { 0x0113, 4, 4 }, /* mov al, 8 */
    { 0x0115, 6, 6 }, /* add ah, 2 */
    { 0x0118, 4, 4 }, /* mov dx, cs */
    { 0x011A, 6, 6 }, /* cmp dx, 0x50 */
    { 0x011D, 4, 16 }, /* jne loc_0125 */
    { 0x011F, 19, 19 }, /* mov word ptr [0x3c0], 0 */
    { 0x0125, 17, 17 }, /* mov dx, word ptr [0x3c0] */
    { 0x0129, 17, 17 }, /* mov ch, byte ptr [disk_track] */
    { 0x012D, 4, 4 }, /* mov cl, 1 */
    { 0x012F, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x0133, 5, 5 }, /* xor bx, bx */
    { 0x0135, 53, 53 }, /* int 0x13 */
    { 0x0137, 4, 16 }, /* jb loc_00EA */
    { 0x0139, 15, 15 }, /* shr byte ptr [0x3b2], 1 */
    { 0x013D, 4, 16 }, /* jae loc_0152 */
    { 0x013F, 21, 21 }, /* call track_checksum */
    { 0x0142, 15, 15 }, /* push ax */
    { 0x0143, 4, 4 }, /* mov ax, 0x208 */
    { 0x0146, 53, 53 }, /* int 0x13 */
    { 0x0148, 12, 12 }, /* pop cx */
    { 0x0149, 4, 16 }, /* jb loc_00EA */
    { 0x014B, 21, 21 }, /* call track_checksum */
    { 0x014E, 5, 5 }, /* cmp ax, cx */
    { 0x0150, 4, 16 }, /* jne loc_00EA */
    { 0x0152, 12, 12 }, /* inc byte ptr [disk_track] */
    { 0x0156, 20, 20 }, /* ret */
    { 0x0157, 15, 15 }, /* push bx */
    { 0x0158, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x015C, 4, 4 }, /* mov bx, 0xffe */
    { 0x015F, 5, 5 }, /* xor ax, ax */
    { 0x0161, 18, 18 }, /* add ax, word ptr es:[bx] */
    { 0x0164, 6, 6 }, /* sub bx, 2 */
    { 0x0167, 4, 16 }, /* jns loc_0161 */
    { 0x0169, 12, 12 }, /* pop bx */
    { 0x016A, 20, 20 }, /* ret */
    { 0x016B, 4, 4 }, /* mov dx, 0x3f2 */
    { 0x016E, 4, 4 }, /* mov al, 0xc */
    { 0x017C, 16, 16 }, /* push es */
    { 0x017D, 17, 17 }, /* mov bx, word ptr [0x3b0] */
    { 0x0181, 2, 2 }, /* inc bx */
    { 0x0182, 6, 6 }, /* cmp bh, 0x10 */
    { 0x0185, 4, 16 }, /* je loc_0195 */
    { 0x0187, 4, 4 }, /* mov ax, 0xb800 */
    { 0x018A, 4, 4 }, /* mov es, ax */
    { 0x018C, 17, 17 }, /* mov al, byte ptr es:[bx] */
    { 0x018F, 18, 18 }, /* mov word ptr [0x3b0], bx */
    { 0x0193, 14, 14 }, /* pop es */
    { 0x0194, 20, 20 }, /* ret */
    { 0x0195, 15, 15 }, /* push cx */
    { 0x0196, 15, 15 }, /* push di */
    { 0x0197, 21, 21 }, /* call boot_read_track */
    { 0x019A, 5, 5 }, /* xor bx, bx */
    { 0x019C, 12, 12 }, /* pop di */
    { 0x019D, 12, 12 }, /* pop cx */
    { 0x019E, 17, 17 }, /* jmp loc_0187 */
    { 0x01AD, 16, 16 }, /* push es */
    { 0x01AE, 17, 17 }, /* mov bx, word ptr [0x3b0] */
    { 0x01B2, 2, 2 }, /* inc bx */
    { 0x01B3, 6, 6 }, /* cmp bh, 0x10 */
    { 0x01B6, 4, 16 }, /* je loc_01C6 */
    { 0x01B8, 4, 4 }, /* mov di, 0xb800 */
    { 0x01BB, 4, 4 }, /* mov es, di */
    { 0x01BD, 18, 18 }, /* mov byte ptr es:[bx], al */
    { 0x01C0, 18, 18 }, /* mov word ptr [0x3b0], bx */
    { 0x01C4, 14, 14 }, /* pop es */
    { 0x01C5, 20, 20 }, /* ret */
    { 0x01C6, 15, 15 }, /* push ax */
    { 0x01C7, 15, 15 }, /* push si */
    { 0x01C8, 15, 15 }, /* push cx */
    { 0x01C9, 16, 16 }, /* push ds */
    { 0x01CA, 21, 21 }, /* call disk_format_write_track */
    { 0x01CD, 14, 14 }, /* pop ds */
    { 0x01CE, 12, 12 }, /* pop cx */
    { 0x01CF, 12, 12 }, /* pop si */
    { 0x01D0, 12, 12 }, /* pop ax */
    { 0x01D1, 5, 5 }, /* xor bx, bx */
    { 0x01D3, 17, 17 }, /* jmp loc_01B8 */
    { 0x01D5, 15, 15 }, /* push ax */
    { 0x01D6, 21, 21 }, /* call boot_stream_put_byte */
    { 0x01D9, 12, 12 }, /* pop ax */
    { 0x01DA, 4, 4 }, /* mov al, ah */
    { 0x01DC, 17, 17 }, /* jmp boot_stream_put_byte */
    { 0x01DE, 21, 21 }, /* call disk_format_write_track */
    { 0x01E1, 19, 19 }, /* mov word ptr [0x3b0], 0xffff */
    { 0x01E7, 20, 20 }, /* ret */
    { 0x3640, 21, 21 }, /* call editor_capture_state */
    { 0x3643, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x3647, 21, 21 }, /* call sub_5619 */
    { 0x364A, 21, 21 }, /* call sub_369F */
    { 0x364D, 21, 21 }, /* call editor_get_input */
    { 0x3650, 12, 12 }, /* mov al, byte ptr [0x2018] */
    { 0x3653, 5, 5 }, /* or al, al */
    { 0x3655, 4, 16 }, /* je loc_366A */
    { 0x3657, 21, 21 }, /* call sub_3916 */
    { 0x365A, 12, 12 }, /* mov al, byte ptr [editor_page] */
    { 0x365D, 5, 5 }, /* or al, al */
    { 0x365F, 4, 16 }, /* jne loc_366A */
    { 0x3661, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x3664, 6, 6 }, /* cmp al, 2 */
    { 0x3666, 4, 16 }, /* jne loc_366A */
    { 0x3668, 17, 17 }, /* jmp loc_364D */
    { 0x366A, 12, 12 }, /* mov al, byte ptr [0x2011] */
    { 0x366D, 5, 5 }, /* or al, al */
    { 0x366F, 4, 16 }, /* je loc_3674 */
    { 0x3671, 17, 17 }, /* jmp editor_apply_state */
    { 0x3674, 12, 12 }, /* mov al, byte ptr [0x2010] */
    { 0x3677, 5, 5 }, /* or al, al */
    { 0x3679, 4, 16 }, /* je loc_3685 */
    { 0x367B, 19, 19 }, /* mov byte ptr [0x2010], 0 */
    { 0x3680, 21, 21 }, /* call sub_36C1 */
    { 0x3683, 17, 17 }, /* jmp loc_364D */
    { 0x3685, 21, 21 }, /* call sub_368A */
    { 0x3688, 17, 17 }, /* jmp loc_364D */
    { 0x368A, 21, 21 }, /* call sub_36E3 */
    { 0x368D, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x3690, 6, 6 }, /* add al, 2 */
    { 0x3692, 6, 6 }, /* cmp al, 0x2e */
    { 0x3694, 4, 16 }, /* jne loc_36AC */
    { 0x3696, 12, 12 }, /* mov al, byte ptr [editor_page] */
    { 0x3699, 6, 6 }, /* add al, 2 */
    { 0x369B, 6, 6 }, /* cmp al, 4 */
    { 0x369D, 4, 16 }, /* jne loc_36A1 */
    { 0x369F, 5, 5 }, /* xor al, al */
    { 0x36A1, 12, 12 }, /* mov byte ptr [editor_page], al */
    { 0x36A4, 21, 21 }, /* call sub_39DB */
    { 0x36A7, 21, 21 }, /* call editor_draw_fields */
    { 0x36AA, 4, 4 }, /* mov al, 2 */
    { 0x36AC, 12, 12 }, /* mov byte ptr [editor_row], al */
    { 0x36AF, 21, 21 }, /* call sub_36F4 */
    { 0x36B2, 19, 19 }, /* mov byte ptr es:[bx], 0x2d */
    { 0x36B6, 19, 19 }, /* mov byte ptr es:[bx + 2], 0x2d */
    { 0x36BB, 19, 19 }, /* mov byte ptr es:[bx + 4], 0x3e */
    { 0x36C0, 20, 20 }, /* ret */
    { 0x36C1, 21, 21 }, /* call sub_36E3 */
    { 0x36C4, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x36C7, 6, 6 }, /* sub al, 2 */
    { 0x36C9, 6, 6 }, /* cmp al, 0 */
    { 0x36CB, 4, 16 }, /* jne loc_36AC */
    { 0x36CD, 12, 12 }, /* mov al, byte ptr [editor_page] */
    { 0x36D0, 6, 6 }, /* sub al, 2 */
    { 0x36D2, 4, 16 }, /* jns loc_36D6 */
    { 0x36D4, 4, 4 }, /* mov al, 2 */
    { 0x36D6, 12, 12 }, /* mov byte ptr [editor_page], al */
    { 0x36D9, 21, 21 }, /* call sub_39DB */
    { 0x36DC, 21, 21 }, /* call editor_draw_fields */
    { 0x36DF, 4, 4 }, /* mov al, 0x2c */
    { 0x36E1, 17, 17 }, /* jmp loc_36AC */
    { 0x36E3, 21, 21 }, /* call sub_36F4 */
    { 0x36E6, 4, 4 }, /* mov dl, 0x20 */
    { 0x36E8, 18, 18 }, /* mov byte ptr es:[bx], dl */
    { 0x36EB, 18, 18 }, /* mov byte ptr es:[bx + 2], dl */
    { 0x36EF, 18, 18 }, /* mov byte ptr es:[bx + 4], dl */
    { 0x36F3, 20, 20 }, /* ret */
    { 0x36F4, 17, 17 }, /* mov bl, byte ptr [editor_row] */
    { 0x36F8, 5, 5 }, /* xor bh, bh */
    { 0x36FA, 17, 17 }, /* mov bx, word ptr [bx + 0x28e4] */
    { 0x36FE, 18, 18 }, /* mov word ptr [0x2020], bx */
    { 0x3702, 20, 20 }, /* ret */
    { 0x3703, 19, 19 }, /* mov byte ptr [0x2018], 0 */
    { 0x3708, 21, 21 }, /* call sub_36F4 */
    { 0x370B, 19, 19 }, /* mov word ptr [0x2032], 5 */
    { 0x3711, 19, 19 }, /* mov byte ptr [0x202b], 0 */
    { 0x3716, 19, 19 }, /* mov byte ptr [0x2011], 0 */
    { 0x371B, 4, 4 }, /* mov di, 5 */
    { 0x371E, 19, 19 }, /* mov byte ptr [di + editor_digits], 0x30 */
    { 0x3723, 2, 2 }, /* dec di */
    { 0x3724, 4, 16 }, /* jns loc_371E */
    { 0x3726, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x3729, 5, 5 }, /* or al, al */
    { 0x372B, 4, 16 }, /* jns loc_3726 */
    { 0x372D, 19, 19 }, /* mov byte ptr [editor_key], 0 */
    { 0x3732, 6, 6 }, /* and al, 0x7f */
    { 0x3734, 6, 6 }, /* cmp al, 0xd */
    { 0x3736, 4, 16 }, /* je loc_374E */
    { 0x3738, 6, 6 }, /* cmp al, 0x3d */
    { 0x373A, 4, 16 }, /* je loc_374E */
    { 0x373C, 6, 6 }, /* cmp al, 0x2d */
    { 0x373E, 4, 16 }, /* jne loc_3746 */
    { 0x3740, 12, 12 }, /* mov byte ptr [0x2010], al */
    { 0x3743, 17, 17 }, /* jmp loc_374E */
    { 0x3746, 6, 6 }, /* cmp al, 0x1b */
    { 0x3748, 4, 16 }, /* jne loc_3752 */
    { 0x374A, 12, 12 }, /* inc byte ptr [0x2011] */
    { 0x374E, 21, 21 }, /* call editor_digits_to_bin */
    { 0x3751, 20, 20 }, /* ret */
    { 0x3752, 6, 6 }, /* cmp al, 8 */
    { 0x3754, 4, 16 }, /* jne loc_3789 */
    { 0x3756, 12, 12 }, /* mov al, byte ptr [0x202b] */
    { 0x3759, 5, 5 }, /* or al, al */
    { 0x375B, 4, 16 }, /* je loc_3726 */
    { 0x375D, 12, 12 }, /* dec byte ptr [0x202b] */
    { 0x3761, 4, 4 }, /* mov al, 0x20 */
    { 0x3763, 12, 12 }, /* dec word ptr [0x2032] */
    { 0x3767, 17, 17 }, /* mov si, word ptr [0x2032] */
    { 0x376B, 8, 8 }, /* shl si, 1 */
    { 0x376D, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x3770, 4, 4 }, /* mov di, 1 */
    { 0x3773, 17, 17 }, /* mov al, byte ptr [di + editor_digits] */
    { 0x3777, 18, 18 }, /* mov byte ptr [di + 0x202b], al */
    { 0x377B, 2, 2 }, /* inc di */
    { 0x377C, 6, 6 }, /* cmp di, 6 */
    { 0x377F, 4, 16 }, /* jne loc_3773 */
    { 0x3781, 19, 19 }, /* mov byte ptr [0x2031], 0x30 */
    { 0x3786, 17, 17 }, /* jmp loc_3800 */
    { 0x3789, 4, 4 }, /* mov cx, 0x30b4 */
    { 0x378C, 4, 4 }, /* mov si, 0x2916 */
    { 0x378F, 5, 5 }, /* sub cx, si */
    { 0x3791, 19, 19 }, /* mov byte ptr [disk_track], 0x26 */
    { 0x3796, 6, 6 }, /* cmp al, 0x73 */
    { 0x3798, 4, 16 }, /* jne loc_37B1 */
    { 0x379A, 21, 21 }, /* call cga_program_regs */
    { 0x379D, 21, 21 }, /* call disk_reset */
    { 0x37A0, 19, 19 }, /* mov word ptr [0x3b0], 0xffff */
    { 0x37A6, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x37A7, 21, 21 }, /* call boot_stream_put_byte */
    { 0x37AA, 5, 17 }, /* loop loc_37A6 */
    { 0x37AC, 21, 21 }, /* call sub_01DE */
    { 0x37AF, 17, 17 }, /* jmp loc_37C9 */
    { 0x37B1, 6, 6 }, /* cmp al, 0x6c */
    { 0x37B3, 4, 16 }, /* jne loc_37D0 */
    { 0x37B5, 21, 21 }, /* call cga_program_regs */
    { 0x37B8, 21, 21 }, /* call disk_reset */
    { 0x37BB, 4, 4 }, /* mov di, si */
    { 0x37BD, 19, 19 }, /* mov word ptr [0x3b0], 0xfff */
    { 0x37C3, 21, 21 }, /* call boot_stream_byte */
    { 0x37C6, 12, 12 }, /* stosb byte ptr es:[di], al */
    { 0x37C7, 5, 17 }, /* loop loc_37C3 */
    { 0x37C9, 12, 12 }, /* pop ax */
    { 0x37CA, 21, 21 }, /* call sub_016B */
    { 0x37CD, 17, 17 }, /* jmp loc_3643 */
    { 0x37D0, 6, 6 }, /* cmp al, 0x2a */
    { 0x37D2, 4, 16 }, /* jne loc_37D9 */
    { 0x37D4, 21, 21 }, /* call usermode_recall */
    { 0x37D7, 17, 17 }, /* jmp loc_37EC */
    { 0x37D9, 6, 6 }, /* cmp al, 0x11 */
    { 0x37DB, 4, 16 }, /* jne loc_37FC */
    { 0x37DD, 19, 19 }, /* cmp byte ptr [wind_layers+17], 0xa */
    { 0x37E2, 4, 16 }, /* jae loc_37E9 */
    { 0x37E4, 12, 12 }, /* inc byte ptr [0x2018] */
    { 0x37E8, 20, 20 }, /* ret */
    { 0x37E9, 21, 21 }, /* call usermode_store */
    { 0x37EC, 19, 19 }, /* mov byte ptr [0x2018], 0 */
    { 0x37F1, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x37F4, 6, 6 }, /* sub al, 2 */
    { 0x37F6, 12, 12 }, /* mov byte ptr [0x2028], al */
    { 0x37F9, 17, 17 }, /* jmp loc_3954 */
    { 0x37FC, 6, 6 }, /* cmp al, 0x30 */
    { 0x37FE, 4, 16 }, /* jae loc_3803 */
    { 0x3800, 17, 17 }, /* jmp loc_3726 */
    { 0x3803, 6, 6 }, /* cmp al, 0x3a */
    { 0x3805, 4, 16 }, /* jae loc_3800 */
    { 0x3807, 17, 17 }, /* mov si, word ptr [0x2032] */
    { 0x380B, 6, 6 }, /* cmp si, 0xb */
    { 0x380E, 4, 16 }, /* je loc_3800 */
    { 0x3810, 12, 12 }, /* inc byte ptr [0x2018] */
    { 0x3814, 12, 12 }, /* mov byte ptr [0x2024], al */
    { 0x3817, 12, 12 }, /* mov al, byte ptr [0x202b] */
    { 0x381A, 5, 5 }, /* or al, al */
    { 0x381C, 4, 16 }, /* jne loc_382E */
    { 0x381E, 4, 4 }, /* mov si, 0x18 */
    { 0x3821, 4, 4 }, /* mov al, 0x20 */
    { 0x3823, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x3826, 6, 6 }, /* sub si, 2 */
    { 0x3829, 6, 6 }, /* cmp si, 8 */
    { 0x382C, 4, 16 }, /* jne loc_3823 */
    { 0x382E, 4, 4 }, /* mov di, 4 */
    { 0x3831, 17, 17 }, /* mov al, byte ptr [di + editor_digits] */
    { 0x3835, 18, 18 }, /* mov byte ptr [di + 0x202d], al */
    { 0x3839, 2, 2 }, /* dec di */
    { 0x383A, 4, 16 }, /* jns loc_3831 */
    { 0x383C, 12, 12 }, /* mov al, byte ptr [0x2024] */
    { 0x383F, 12, 12 }, /* mov byte ptr [editor_digits], al */
    { 0x3842, 12, 12 }, /* inc byte ptr [0x202b] */
    { 0x3846, 17, 17 }, /* mov si, word ptr [0x2032] */
    { 0x384A, 8, 8 }, /* shl si, 1 */
    { 0x384C, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x384F, 12, 12 }, /* inc word ptr [0x2032] */
    { 0x3853, 17, 17 }, /* jmp loc_3800 */
    { 0x3855, 5, 5 }, /* xor cx, cx */
    { 0x3857, 18, 18 }, /* mov word ptr [editor_value], cx */
    { 0x385B, 18, 18 }, /* mov byte ptr [0x2014], cl */
    { 0x385F, 5, 5 }, /* xor di, di */
    { 0x3861, 17, 17 }, /* mov ch, byte ptr [di + editor_digits] */
    { 0x3865, 6, 6 }, /* and ch, 0x7f */
    { 0x3868, 6, 6 }, /* sub ch, 0x30 */
    { 0x386B, 4, 16 }, /* je loc_3889 */
    { 0x386D, 17, 17 }, /* mov al, byte ptr [di + pow10_lo] */
    { 0x3871, 18, 18 }, /* add byte ptr [editor_value], al */
    { 0x3875, 17, 17 }, /* mov al, byte ptr [di + 0x203c] */
    { 0x3879, 18, 18 }, /* adc byte ptr [0x2013], al */
    { 0x387D, 17, 17 }, /* mov al, byte ptr [di + 0x2042] */
    { 0x3881, 18, 18 }, /* adc byte ptr [0x2014], al */
    { 0x3885, 5, 5 }, /* dec ch */
    { 0x3887, 4, 16 }, /* jne loc_386D */
    { 0x3889, 2, 2 }, /* inc di */
    { 0x388A, 6, 6 }, /* cmp di, 6 */
    { 0x388D, 4, 16 }, /* jne loc_3861 */
    { 0x388F, 20, 20 }, /* ret */
    { 0x3890, 21, 21 }, /* call sub_36F4 */
    { 0x3893, 19, 19 }, /* mov byte ptr [0x2019], 0 */
    { 0x3898, 19, 19 }, /* mov word ptr [0x2032], 0xa */
    { 0x389E, 4, 4 }, /* mov si, 0xa */
    { 0x38A1, 4, 4 }, /* mov al, 0x20 */
    { 0x38A3, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x38A6, 6, 6 }, /* add si, 2 */
    { 0x38A9, 6, 6 }, /* cmp si, 0x16 */
    { 0x38AC, 4, 16 }, /* jne loc_38A3 */
    { 0x38AE, 4, 4 }, /* mov di, 5 */
    { 0x38B1, 19, 19 }, /* mov byte ptr [0x201a], 0x30 */
    { 0x38B6, 17, 17 }, /* mov dl, byte ptr [editor_value] */
    { 0x38BA, 18, 18 }, /* sub dl, byte ptr [di + pow10_lo] */
    { 0x38BE, 17, 17 }, /* mov dh, byte ptr [0x2013] */
    { 0x38C2, 18, 18 }, /* sbb dh, byte ptr [di + 0x203c] */
    { 0x38C6, 12, 12 }, /* mov al, byte ptr [0x2014] */
    { 0x38C9, 18, 18 }, /* sbb al, byte ptr [di + 0x2042] */
    { 0x38CD, 4, 16 }, /* js loc_38E0 */
    { 0x38CF, 12, 12 }, /* mov byte ptr [0x2014], al */
    { 0x38D2, 18, 18 }, /* mov byte ptr [0x2013], dh */
    { 0x38D6, 18, 18 }, /* mov byte ptr [editor_value], dl */
    { 0x38DA, 12, 12 }, /* inc byte ptr [0x201a] */
    { 0x38DE, 4, 16 }, /* jne loc_38B6 */
    { 0x38E0, 12, 12 }, /* mov al, byte ptr [0x201a] */
    { 0x38E3, 5, 5 }, /* or di, di */
    { 0x38E5, 4, 16 }, /* je loc_38F2 */
    { 0x38E7, 6, 6 }, /* cmp al, 0x30 */
    { 0x38E9, 4, 16 }, /* jne loc_38F2 */
    { 0x38EB, 12, 12 }, /* mov al, byte ptr [0x2019] */
    { 0x38EE, 5, 5 }, /* or al, al */
    { 0x38F0, 4, 16 }, /* je loc_3905 */
    { 0x38F2, 12, 12 }, /* inc byte ptr [0x2019] */
    { 0x38F6, 17, 17 }, /* mov si, word ptr [0x2032] */
    { 0x38FA, 12, 12 }, /* mov al, byte ptr [0x201a] */
    { 0x38FD, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x3900, 19, 19 }, /* add word ptr [0x2032], 2 */
    { 0x3905, 2, 2 }, /* dec di */
    { 0x3906, 4, 16 }, /* jns loc_38B1 */
    { 0x3908, 20, 20 }, /* ret */
    { 0x3909, 4, 4 }, /* mov ah, 0xf */
    { 0x390B, 4, 4 }, /* mov cx, 0x3e8 */
    { 0x390E, 4, 4 }, /* mov di, 0 */
    { 0x3911, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x3912, 12, 12 }, /* stosw word ptr es:[di], ax */
    { 0x3913, 5, 17 }, /* loop loc_3911 */
    { 0x3915, 20, 20 }, /* ret */
    { 0x3916, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x3919, 12, 12 }, /* mov byte ptr [0x2028], al */
    { 0x391C, 21, 21 }, /* call editor_read_fields */
    { 0x391F, 12, 12 }, /* mov al, byte ptr [wind_layers+17] */
    { 0x3922, 6, 6 }, /* cmp al, 0x81 */
    { 0x3924, 4, 16 }, /* ja loc_392E */
    { 0x3926, 6, 6 }, /* cmp al, 0x6d */
    { 0x3928, 4, 16 }, /* ja loc_3930 */
    { 0x392A, 6, 6 }, /* cmp al, 0x1e */
    { 0x392C, 4, 16 }, /* jb loc_3930 */
    { 0x392E, 5, 5 }, /* xor al, al */
    { 0x3930, 18, 18 }, /* cmp al, byte ptr [usermode_cur] */
    { 0x3934, 4, 16 }, /* je loc_395E */
    { 0x3936, 12, 12 }, /* mov byte ptr [usermode_cur], al */
    { 0x3939, 6, 6 }, /* cmp al, 0x6e */
    { 0x393B, 4, 16 }, /* jae loc_3949 */
    { 0x393D, 21, 21 }, /* call usermode_recall */
    { 0x3940, 12, 12 }, /* mov al, byte ptr [usermode_cur] */
    { 0x3943, 12, 12 }, /* mov byte ptr [wind_layers+17], al */
    { 0x3946, 17, 17 }, /* jmp loc_3954 */
    { 0x3949, 6, 6 }, /* sub al, 0x64 */
    { 0x394B, 12, 12 }, /* mov byte ptr [usermode_cur], al */
    { 0x394E, 12, 12 }, /* mov byte ptr [wind_layers+17], al */
    { 0x3951, 21, 21 }, /* call usermode_store */
    { 0x3954, 21, 21 }, /* call editor_draw_fields */
    { 0x3957, 12, 12 }, /* mov al, byte ptr [0x2028] */
    { 0x395A, 12, 12 }, /* mov byte ptr [editor_row], al */
    { 0x395D, 20, 20 }, /* ret */
    { 0x395E, 6, 6 }, /* cmp al, 0xa */
    { 0x3960, 4, 16 }, /* jae loc_3954 */
    { 0x3962, 6, 6 }, /* add al, 0xa */
    { 0x3964, 12, 12 }, /* mov byte ptr [usermode_cur], al */
    { 0x3967, 12, 12 }, /* mov byte ptr [wind_layers+17], al */
    { 0x396A, 21, 21 }, /* call usermode_store */
    { 0x396D, 17, 17 }, /* jmp loc_3954 */
    { 0x396F, 17, 17 }, /* mov bl, byte ptr [editor_page] */
    { 0x3973, 5, 5 }, /* xor bh, bh */
    { 0x3975, 17, 17 }, /* mov bx, word ptr [bx + wind_layers+21] */
    { 0x3979, 18, 18 }, /* mov word ptr [0x2026], bx */
    { 0x397D, 17, 17 }, /* mov bx, word ptr [0x2026] */
    { 0x3981, 17, 17 }, /* mov dl, byte ptr [bx] */
    { 0x3983, 5, 5 }, /* xor dh, dh */
    { 0x3985, 5, 5 }, /* or dl, dl */
    { 0x3987, 4, 16 }, /* jne loc_398A */
    { 0x3989, 20, 20 }, /* ret */
    { 0x398A, 21, 21 }, /* call sub_39B2 */
    { 0x398D, 4, 4 }, /* mov cl, 0 */
    { 0x398F, 18, 18 }, /* mov byte ptr [editor_value], cl */
    { 0x3993, 18, 18 }, /* mov byte ptr [0x2013], cl */
    { 0x3997, 18, 18 }, /* mov byte ptr [0x2014], cl */
    { 0x399B, 4, 4 }, /* mov si, 0 */
    { 0x399E, 17, 17 }, /* mov bx, word ptr [0x2020] */
    { 0x39A2, 17, 17 }, /* mov al, byte ptr [bx + si] */
    { 0x39A4, 18, 18 }, /* mov byte ptr [si + editor_value], al */
    { 0x39A8, 2, 2 }, /* inc si */
    { 0x39A9, 5, 5 }, /* cmp si, dx */
    { 0x39AB, 4, 16 }, /* jne loc_399E */
    { 0x39AD, 21, 21 }, /* call editor_bin_to_digits */
    { 0x39B0, 17, 17 }, /* jmp loc_397D */
    { 0x39B2, 17, 17 }, /* mov bx, word ptr [0x2026] */
    { 0x39B6, 17, 17 }, /* mov al, byte ptr [bx + 1] */
    { 0x39B9, 12, 12 }, /* mov byte ptr [editor_row], al */
    { 0x39BC, 5, 5 }, /* xor ah, ah */
    { 0x39BE, 4, 4 }, /* mov di, ax */
    { 0x39C0, 17, 17 }, /* mov ax, word ptr [di + 0x28e4] */
    { 0x39C4, 6, 6 }, /* add ax, 0xa */
    { 0x39C7, 12, 12 }, /* mov word ptr [0x2022], ax */
    { 0x39CA, 17, 17 }, /* mov al, byte ptr [bx + 2] */
    { 0x39CD, 5, 5 }, /* xor ah, ah */
    { 0x39CF, 6, 6 }, /* add ax, 0x2049 */
    { 0x39D2, 12, 12 }, /* mov word ptr [0x2020], ax */
    { 0x39D5, 19, 19 }, /* add word ptr [0x2026], 3 */
    { 0x39DA, 20, 20 }, /* ret */
    { 0x39DB, 17, 17 }, /* mov bl, byte ptr [editor_page] */
    { 0x39DF, 5, 5 }, /* xor bh, bh */
    { 0x39E1, 17, 17 }, /* mov si, word ptr [bx + 0x2110] */
    { 0x39E5, 21, 21 }, /* call sub_3909 */
    { 0x39E8, 20, 20 }, /* ret */
    { 0x39E9, 17, 17 }, /* mov bl, byte ptr [editor_page] */
    { 0x39ED, 5, 5 }, /* xor bh, bh */
    { 0x39EF, 17, 17 }, /* mov bx, word ptr [bx + wind_layers+21] */
    { 0x39F3, 18, 18 }, /* mov word ptr [0x2026], bx */
    { 0x39F7, 17, 17 }, /* mov bx, word ptr [0x2026] */
    { 0x39FB, 17, 17 }, /* mov dl, byte ptr [bx] */
    { 0x39FD, 5, 5 }, /* xor dh, dh */
    { 0x39FF, 5, 5 }, /* or dl, dl */
    { 0x3A01, 4, 16 }, /* jne loc_3A04 */
    { 0x3A03, 20, 20 }, /* ret */
    { 0x3A04, 21, 21 }, /* call sub_39B2 */
    { 0x3A07, 4, 4 }, /* mov di, 5 */
    { 0x3A0A, 19, 19 }, /* mov byte ptr [di + editor_digits], 0x30 */
    { 0x3A0F, 2, 2 }, /* dec di */
    { 0x3A10, 4, 16 }, /* jns loc_3A0A */
    { 0x3A12, 4, 4 }, /* mov si, 0 */
    { 0x3A15, 17, 17 }, /* mov bx, word ptr [0x2022] */
    { 0x3A19, 17, 17 }, /* mov al, byte ptr es:[bx + si] */
    { 0x3A1C, 6, 6 }, /* cmp al, 0x20 */
    { 0x3A1E, 4, 16 }, /* je loc_3A36 */
    { 0x3A20, 4, 4 }, /* mov di, 4 */
    { 0x3A23, 17, 17 }, /* mov ah, byte ptr [di + editor_digits] */
    { 0x3A27, 18, 18 }, /* mov byte ptr [di + 0x202d], ah */
    { 0x3A2B, 2, 2 }, /* dec di */
    { 0x3A2C, 4, 16 }, /* jns loc_3A23 */
    { 0x3A2E, 12, 12 }, /* mov byte ptr [editor_digits], al */
    { 0x3A31, 6, 6 }, /* add si, 2 */
    { 0x3A34, 17, 17 }, /* jmp loc_3A15 */
    { 0x3A36, 21, 21 }, /* call editor_digits_to_bin */
    { 0x3A39, 4, 4 }, /* mov si, 0 */
    { 0x3A3C, 17, 17 }, /* mov al, byte ptr [si + editor_value] */
    { 0x3A40, 17, 17 }, /* mov bx, word ptr [0x2020] */
    { 0x3A44, 18, 18 }, /* mov byte ptr [bx + si], al */
    { 0x3A46, 2, 2 }, /* inc si */
    { 0x3A47, 5, 5 }, /* cmp si, dx */
    { 0x3A49, 4, 16 }, /* jne loc_3A3C */
    { 0x3A4B, 17, 17 }, /* jmp loc_39F7 */
    { 0x3A4D, 4, 4 }, /* mov dl, 1 */
    { 0x3A4F, 17, 17 }, /* jmp loc_3A54 */
    { 0x3A52, 5, 5 }, /* xor dl, dl */
    { 0x3A54, 19, 19 }, /* mov word ptr [0x2020], 0x2916 */
    { 0x3A5A, 17, 17 }, /* mov cl, byte ptr [usermode_cur] */
    { 0x3A5E, 5, 5 }, /* dec cl */
    { 0x3A60, 4, 16 }, /* js loc_3A69 */
    { 0x3A62, 19, 19 }, /* add word ptr [0x2020], 0x41 */
    { 0x3A67, 17, 17 }, /* jmp loc_3A5E */
    { 0x3A69, 4, 4 }, /* mov cl, 0x40 */
    { 0x3A6B, 5, 5 }, /* xor ch, ch */
    { 0x3A6D, 4, 4 }, /* mov si, cx */
    { 0x3A6F, 5, 5 }, /* or dl, dl */
    { 0x3A71, 4, 16 }, /* je loc_3A80 */
    { 0x3A73, 17, 17 }, /* mov al, byte ptr [si + editor_values] */
    { 0x3A77, 17, 17 }, /* mov bx, word ptr [0x2020] */
    { 0x3A7B, 18, 18 }, /* mov byte ptr [bx + si], al */
    { 0x3A7D, 17, 17 }, /* jmp loc_3A8A */
    { 0x3A80, 17, 17 }, /* mov bx, word ptr [0x2020] */
    { 0x3A84, 17, 17 }, /* mov al, byte ptr [bx + si] */
    { 0x3A86, 18, 18 }, /* mov byte ptr [si + editor_values], al */
    { 0x3A8A, 2, 2 }, /* dec si */
    { 0x3A8B, 4, 16 }, /* jns loc_3A6F */
    { 0x3A8D, 19, 19 }, /* mov byte ptr [gear_down], 0xff */
    { 0x3A92, 21, 21 }, /* call sub_0D01 */
    { 0x3A95, 20, 20 }, /* ret */
    { 0x3A96, 21, 21 }, /* call slew_to_editor_pos */
    { 0x3A99, 12, 12 }, /* mov ax, word ptr [altitude+1] */
    { 0x3A9C, 18, 18 }, /* add ax, word ptr [ground_elev] */
    { 0x3AA0, 4, 4 }, /* mov dx, 0xd1eb */
    { 0x3AA3, 120, 120 }, /* mul dx */
    { 0x3AA5, 8, 8 }, /* shl ax, 1 */
    { 0x3AA7, 8, 8 }, /* rcl dx, 1 */
    { 0x3AA9, 8, 8 }, /* shl ax, 1 */
    { 0x3AAB, 8, 8 }, /* rcl dx, 1 */
    { 0x3AAD, 6, 6 }, /* sub dx, 9 */
    { 0x3AB0, 18, 18 }, /* mov word ptr [editor_alt], dx */
    { 0x3AB4, 4, 4 }, /* mov cx, 0x168 */
    { 0x3AB7, 12, 12 }, /* mov ax, word ptr [heading] */
    { 0x3ABA, 18, 18 }, /* sub ax, word ptr [wind_gust_offset] */
    { 0x3ABE, 18, 18 }, /* sub ax, word ptr [wind_dir_offset] */
    { 0x3AC2, 120, 120 }, /* mul cx */
    { 0x3AC4, 18, 18 }, /* mov word ptr [0x205a], dx */
    { 0x3AC8, 12, 12 }, /* mov ax, word ptr [bank] */
    { 0x3ACB, 120, 120 }, /* mul cx */
    { 0x3ACD, 18, 18 }, /* mov word ptr [0x2058], dx */
    { 0x3AD1, 12, 12 }, /* mov ax, word ptr [pitch] */
    { 0x3AD4, 120, 120 }, /* mul cx */
    { 0x3AD6, 18, 18 }, /* mov word ptr [0x2056], dx */
    { 0x3ADA, 4, 4 }, /* mov cx, 0x259 */
    { 0x3ADD, 12, 12 }, /* mov ax, word ptr [airspeed] */
    { 0x3AE0, 120, 120 }, /* mul cx */
    { 0x3AE2, 18, 18 }, /* mov word ptr [0x205c], dx */
    { 0x3AE6, 12, 12 }, /* mov ax, word ptr [throttle] */
    { 0x3AE9, 12, 12 }, /* mov word ptr [0x205e], ax */
    { 0x3AEC, 12, 12 }, /* mov ax, word ptr [flaps] */
    { 0x3AEF, 12, 12 }, /* mov word ptr [0x2064], ax */
    { 0x3AF2, 12, 12 }, /* mov ax, word ptr [rudder] */
    { 0x3AF5, 6, 6 }, /* add ax, 0x7fff */
    { 0x3AF8, 12, 12 }, /* mov word ptr [0x2060], ax */
    { 0x3AFB, 12, 12 }, /* mov ax, word ptr [aileron] */
    { 0x3AFE, 6, 6 }, /* add ax, 0x7fff */
    { 0x3B01, 12, 12 }, /* mov word ptr [0x2062], ax */
    { 0x3B04, 12, 12 }, /* mov ax, word ptr [elevator] */
    { 0x3B07, 6, 6 }, /* add ax, 0x7fff */
    { 0x3B0A, 12, 12 }, /* mov word ptr [0x2066], ax */
    { 0x3B0D, 19, 19 }, /* mov byte ptr [0x547], 0 */
    { 0x3B12, 21, 21 }, /* call sub_3B29 */
    { 0x3B15, 14, 14 }, /* test byte ptr [demo_mode], 0xff */
    { 0x3B1A, 4, 16 }, /* jne loc_3B22 */
    { 0x3B1C, 12, 12 }, /* mov ax, word ptr [demo_script] */
    { 0x3B1F, 12, 12 }, /* mov word ptr [demo_ptr], ax */
    { 0x3B22, 4, 4 }, /* mov di, 0 */
    { 0x3B25, 21, 21 }, /* call sub_3C2F */
    { 0x3B28, 20, 20 }, /* ret */
    { 0x3B29, 19, 19 }, /* mov word ptr [spk_pattern], 0 */
    { 0x3B2F, 12, 12 }, /* in al, 0x61 */
    { 0x3B31, 6, 6 }, /* and al, 0xfc */
    { 0x3B33, 12, 12 }, /* out 0x61, al */
    { 0x3B35, 20, 20 }, /* ret */
    { 0x3B36, 19, 19 }, /* cmp byte ptr [war_mode], 0 */
    { 0x3B3B, 4, 16 }, /* je loc_3B4A */
    { 0x3B3D, 19, 19 }, /* mov byte ptr [wind_layers+17], 7 */
    { 0x3B42, 19, 19 }, /* mov byte ptr [usermode_cur], 7 */
    { 0x3B47, 21, 21 }, /* call usermode_recall */
    { 0x3B4A, 21, 21 }, /* call cga_program_regs */
    { 0x3B4D, 21, 21 }, /* call clock_hm */
    { 0x3B50, 12, 12 }, /* mov ax, word ptr [editor_north] */
    { 0x3B53, 6, 6 }, /* sub ax, 0x4000 */
    { 0x3B56, 12, 12 }, /* mov word ptr [pos_north+2], ax */
    { 0x3B59, 12, 12 }, /* mov ax, word ptr [editor_east] */
    { 0x3B5C, 6, 6 }, /* sub ax, 0x4000 */
    { 0x3B5F, 12, 12 }, /* mov word ptr [pos_east+2], ax */
    { 0x3B62, 5, 5 }, /* xor ax, ax */
    { 0x3B64, 12, 12 }, /* mov word ptr [pos_north], ax */
    { 0x3B67, 12, 12 }, /* mov word ptr [pos_east], ax */
    { 0x3B6A, 21, 21 }, /* call alt_from_editor */
    { 0x3B6D, 4, 4 }, /* mov cx, 0xb60c */
    { 0x3B70, 12, 12 }, /* mov ax, word ptr [0x205a] */
    { 0x3B73, 120, 120 }, /* mul cx */
    { 0x3B75, 4, 4 }, /* mov al, ah */
    { 0x3B77, 4, 4 }, /* mov ah, dl */
    { 0x3B79, 18, 18 }, /* add ax, word ptr [wind_gust_offset] */
    { 0x3B7D, 18, 18 }, /* add ax, word ptr [wind_dir_offset] */
    { 0x3B81, 12, 12 }, /* mov word ptr [heading], ax */
    { 0x3B84, 12, 12 }, /* mov ax, word ptr [0x2058] */
    { 0x3B87, 120, 120 }, /* mul cx */
    { 0x3B89, 4, 4 }, /* mov al, ah */
    { 0x3B8B, 4, 4 }, /* mov ah, dl */
    { 0x3B8D, 12, 12 }, /* mov word ptr [bank], ax */
    { 0x3B90, 12, 12 }, /* mov ax, word ptr [0x2056] */
    { 0x3B93, 120, 120 }, /* mul cx */
    { 0x3B95, 4, 4 }, /* mov al, ah */
    { 0x3B97, 4, 4 }, /* mov ah, dl */
    { 0x3B99, 12, 12 }, /* mov word ptr [pitch], ax */
    { 0x3B9C, 4, 4 }, /* mov cx, 0x6d01 */
    { 0x3B9F, 12, 12 }, /* mov ax, word ptr [0x205c] */
    { 0x3BA2, 120, 120 }, /* mul cx */
    { 0x3BA4, 4, 4 }, /* mov al, ah */
    { 0x3BA6, 4, 4 }, /* mov ah, dl */
    { 0x3BA8, 12, 12 }, /* mov word ptr [airspeed], ax */
    { 0x3BAB, 12, 12 }, /* mov ax, word ptr [0x205e] */
    { 0x3BAE, 12, 12 }, /* mov word ptr [throttle], ax */
    { 0x3BB1, 12, 12 }, /* mov ax, word ptr [0x2064] */
    { 0x3BB4, 12, 12 }, /* mov word ptr [flaps], ax */
    { 0x3BB7, 12, 12 }, /* mov ax, word ptr [0x2060] */
    { 0x3BBA, 6, 6 }, /* sub ax, 0x7fff */
    { 0x3BBD, 12, 12 }, /* mov word ptr [rudder], ax */
    { 0x3BC0, 12, 12 }, /* mov ax, word ptr [0x2062] */
    { 0x3BC3, 6, 6 }, /* sub ax, 0x7fff */
    { 0x3BC6, 12, 12 }, /* mov word ptr [aileron], ax */
    { 0x3BC9, 12, 12 }, /* mov ax, word ptr [0x2066] */
    { 0x3BCC, 6, 6 }, /* sub ax, 0x7fff */
    { 0x3BCF, 12, 12 }, /* mov word ptr [elevator], ax */
    { 0x3BD2, 21, 21 }, /* call sub_0955 */
    { 0x3BD5, 19, 19 }, /* mov byte ptr [0x547], 1 */
    { 0x3BDA, 19, 19 }, /* cmp byte ptr [reality_mode], 0 */
    { 0x3BDF, 4, 16 }, /* je loc_3BF0 */
    { 0x3BE1, 19, 19 }, /* cmp byte ptr [throttle+1], 0 */
    { 0x3BE6, 4, 16 }, /* jne loc_3BF0 */
    { 0x3BE8, 21, 21 }, /* call engine_stop */
    { 0x3BEB, 5, 5 }, /* xor ax, ax */
    { 0x3BED, 21, 21 }, /* call key_set_magnetos */
    { 0x3BF0, 12, 12 }, /* mov al, byte ptr [0x204d] */
    { 0x3BF3, 18, 18 }, /* or al, byte ptr [0x2035] */
    { 0x3BF7, 19, 19 }, /* mov byte ptr [0x2035], 0 */
    { 0x3BFC, 12, 12 }, /* mov byte ptr [demo_mode], al */
    { 0x3BFF, 4, 4 }, /* mov di, 1 */
    { 0x3C02, 21, 21 }, /* call sub_3C2F */
    { 0x3C05, 5, 5 }, /* xor ax, ax */
    { 0x3C07, 12, 12 }, /* mov byte ptr [war_status_line], al */
    { 0x3C0A, 12, 12 }, /* mov word ptr [score], ax */
    { 0x3C0D, 12, 12 }, /* mov byte ptr [kills], al */
    { 0x3C10, 12, 12 }, /* mov byte ptr [wing_damage], al */
    { 0x3C13, 19, 19 }, /* mov word ptr [bomb_state], 0 */
    { 0x3C19, 21, 21 }, /* call war_score_add */
    { 0x3C1C, 21, 21 }, /* call war_ground_reset */
    { 0x3C1F, 12, 12 }, /* mov al, byte ptr [frame_counter] */
    { 0x3C22, 6, 6 }, /* and al, 0x1f */
    { 0x3C24, 6, 6 }, /* sub al, 0x10 */
    { 0x3C26, 12, 12 }, /* mov byte ptr [0x202a], al */
    { 0x3C29, 19, 19 }, /* mov byte ptr [alt_reset], 0xc */
    { 0x3C2E, 20, 20 }, /* ret */
    { 0x3C2F, 4, 4 }, /* mov bx, 0x2079 */
    { 0x3C32, 21, 21 }, /* call sub_3C6C */
    { 0x3C35, 4, 4 }, /* mov bx, 0x207d */
    { 0x3C38, 21, 21 }, /* call sub_3C6C */
    { 0x3C3B, 4, 4 }, /* mov bx, 0x2081 */
    { 0x3C3E, 21, 21 }, /* call sub_3C6C */
    { 0x3C41, 4, 4 }, /* mov bx, 0x2085 */
    { 0x3C44, 21, 21 }, /* call sub_3C6C */
    { 0x3C47, 4, 4 }, /* mov bp, 7 */
    { 0x3C4A, 4, 4 }, /* mov bx, 0x206b */
    { 0x3C4D, 4, 4 }, /* mov cx, 0x4e0c */
    { 0x3C50, 6, 6 }, /* cmp di, 1 */
    { 0x3C53, 4, 16 }, /* je loc_3C5F */
    { 0x3C55, 17, 17 }, /* mov dx, word ptr [bx] */
    { 0x3C57, 5, 5 }, /* xor ax, ax */
    { 0x3C59, 146, 146 }, /* div cx */
    { 0x3C5B, 18, 18 }, /* mov word ptr [bx], ax */
    { 0x3C5D, 17, 17 }, /* jmp loc_3C65 */
    { 0x3C5F, 17, 17 }, /* mov ax, word ptr [bx] */
    { 0x3C61, 120, 120 }, /* mul cx */
    { 0x3C63, 18, 18 }, /* mov word ptr [bx], dx */
    { 0x3C65, 6, 6 }, /* add bx, 2 */
    { 0x3C68, 2, 2 }, /* dec bp */
    { 0x3C69, 4, 16 }, /* jne loc_3C50 */
    { 0x3C6B, 20, 20 }, /* ret */
    { 0x3C6C, 17, 17 }, /* mov bp, word ptr [bx + 2] */
    { 0x3C6F, 17, 17 }, /* mov cx, word ptr [bx] */
    { 0x3C71, 5, 5 }, /* or di, di */
    { 0x3C73, 4, 16 }, /* jne loc_3C89 */
    { 0x3C75, 4, 4 }, /* mov ax, 0x168 */
    { 0x3C78, 120, 120 }, /* mul bp */
    { 0x3C7A, 18, 18 }, /* mov word ptr [bx + 2], dx */
    { 0x3C7D, 4, 4 }, /* mov al, 0x64 */
    { 0x3C7F, 72, 72 }, /* mul ch */
    { 0x3C81, 5, 5 }, /* add al, cl */
    { 0x3C83, 6, 6 }, /* adc ah, 0 */
    { 0x3C86, 18, 18 }, /* mov word ptr [bx], ax */
    { 0x3C88, 20, 20 }, /* ret */
    { 0x3C89, 4, 4 }, /* mov ax, 0xb60c */
    { 0x3C8C, 120, 120 }, /* mul bp */
    { 0x3C8E, 4, 4 }, /* mov al, ah */
    { 0x3C90, 4, 4 }, /* mov ah, dl */
    { 0x3C92, 18, 18 }, /* mov word ptr [bx + 2], ax */
    { 0x3C95, 4, 4 }, /* mov ax, cx */
    { 0x3C97, 4, 4 }, /* mov cl, 0x64 */
    { 0x3C99, 82, 82 }, /* div cl */
    { 0x3C9B, 6, 6 }, /* xchg al, ah */
    { 0x3C9D, 17, 17 }, /* jmp loc_3C86 */
    { 0x3C9F, 4, 4 }, /* mov cx, 0x4e0c */
    { 0x3CA2, 12, 12 }, /* mov ax, word ptr [editor_alt] */
    { 0x3CA5, 6, 6 }, /* add ax, 9 */
    { 0x3CA8, 120, 120 }, /* mul cx */
    { 0x3CAA, 18, 18 }, /* sub dx, word ptr [ground_elev] */
    { 0x3CAE, 6, 6 }, /* cmp dx, 3 */
    { 0x3CB1, 4, 16 }, /* jge loc_3CB6 */
    { 0x3CB3, 4, 4 }, /* mov dx, 3 */
    { 0x3CB6, 18, 18 }, /* mov word ptr [altitude+1], dx */
    { 0x3CBA, 19, 19 }, /* mov byte ptr [altitude], 0 */
    { 0x3CBF, 20, 20 }, /* ret */
    { 0x60F8, 21, 21 }, /* call disk_reset */
    { 0x60FB, 5, 5 }, /* xor cl, cl */
    { 0x60FD, 4, 4 }, /* mov si, 0x40b0 */
    { 0x6100, 4, 4 }, /* mov ax, ds */
    { 0x6102, 8, 8 }, /* shl ax, 1 */
    { 0x6104, 8, 8 }, /* shl ax, 1 */
    { 0x6106, 8, 8 }, /* shl ax, 1 */
    { 0x6108, 8, 8 }, /* shl ax, 1 */
    { 0x610A, 5, 5 }, /* add si, ax */
    { 0x610C, 5, 5 }, /* xor ax, ax */
    { 0x610E, 4, 4 }, /* mov es, ax */
    { 0x6110, 4, 4 }, /* mov di, si */
    { 0x6112, 20, 20 }, /* ret */
    { 0x629C, 4, 4 }, /* mov cx, 5 */
    { 0x629F, 15, 15 }, /* push cx */
    { 0x62A0, 21, 21 }, /* call sub_60F8 */
    { 0x62A3, 19, 19 }, /* mov byte ptr [disk_track], 0x1c */
    { 0x62A8, 19, 19 }, /* mov word ptr [0x3b0], 0xfff */
    { 0x62AE, 21, 21 }, /* call boot_stream_byte */
    { 0x62B1, 12, 12 }, /* pop cx */
    { 0x62B2, 15, 15 }, /* shr byte ptr [disk_error], 1 */
    { 0x62B6, 4, 16 }, /* jae loc_62C4 */
    { 0x62B8, 19, 19 }, /* cmp byte ptr [0x3a21], 1 */
    { 0x62BD, 4, 16 }, /* je loc_62D0 */
    { 0x62BF, 2, 2 }, /* dec cx */
    { 0x62C0, 4, 16 }, /* jne loc_629F */
    { 0x62C2, 17, 17 }, /* jmp loc_6311 */
    { 0x62C4, 6, 6 }, /* cmp al, 1 */
    { 0x62C6, 4, 16 }, /* je loc_62CE */
    { 0x62C8, 6, 6 }, /* cmp al, 2 */
    { 0x62CA, 4, 16 }, /* je loc_62D0 */
    { 0x62CC, 4, 16 }, /* jne loc_62B8 */
    { 0x62CE, 2, 2 }, /* stc */
    { 0x62CF, 20, 20 }, /* ret */
    { 0x62D0, 2, 2 }, /* clc */
    { 0x62D1, 20, 20 }, /* ret */
};

#endif
