/* Natives for subphase 3.16 editor, presets, menus (see docs/PHASE3_PLAN.md and
 * docs/subphases/3.16.md).
 *
 * The routines are transliterated on the emulated registers, so every register, segment
 * register and memory byte (including the stack words written by CALL and PUSH) ends as the
 * original leaves it. Memory goes through the generated accessors of game/state.h, which use
 * the live DS: usermode_recall and editor_apply_state also run at start-up, with DS = 0686.
 *
 * Cycles: run(from, to) adds the cpu8086.c cost of every original instruction in [from, to)
 * (table editor_cycles.h, generated by tools/gen_editor_cycles.py), taken() adds the extra
 * cost of a jump that was taken. Every entry's .cycles is ENTRY_CYCLES and is subtracted
 * again, so a call costs exactly what the original costs.
 *
 * Calls out of a native (CALL in the original) go through call(): it pushes the return
 * address and runs the target the way the CPU would with the natives on: an enabled native
 * at a reached address runs its C function through native_call() (so the other natives of
 * this file, and those of 3.2, 3.9, 3.11, 3.17, ...), anything else is single-stepped as
 * original code. Interrupts are not delivered meanwhile.
 *
 * Interrupts. The timer handler (sound, clock, ATIS rate, flight_forces, demo_step) reads and
 * writes state that some of these routines write or read: the flight state (capture, apply),
 * the sound and ATIS-rate fields and the clock (user-mode recall, commit, ...). A native holds
 * interrupts until it returns, so when an interrupt would have arrived within the routine's
 * cycles, the result could differ from the original's, and the delayed timer ticks can merge.
 * In that case the native's writes are undone and the call is handed back to the original (as
 * 3.14 does; see entry_run): the first instruction is performed and the CPU continues in the
 * original routine, with interrupts. Under --verify the original runs without interrupts, so
 * they never hand back there.
 *
 * Not replaced (see the notes): editor_main 3640 and editor_get_input 3703, and
 * startup_menus 5CE9, wait in a loop for a key from the keyboard interrupt. --verify runs the
 * original without interrupts, so it could never return from a call bound there; such an
 * entry would end every campaign session with a step-cap mismatch. Their parts that end
 * with a RET are natives here; the key loops stay original.
 *
 * Backspace, 's' and 'l' are natives that continue in the key loop (no RET), so --verify cannot
 * check them; they are tested by comparing runs with the natives on and off. 's' and 'l' save
 * and load all presets to a host file (fs1_presets.bin, see preset_path()) instead of disk
 * track 26h. */
#include <SDL3/SDL.h>

#include "native.h"
#include "game/state.h"
#include "editor_cycles.h"

/* ---- registers, memory ------------------------------------------------------------------ */

#define REG(r) (pc->cpu.regs[R_##r])
#define SREG(r) (pc->cpu.sregs[S_##r])
#define SET_LO(r, b) (REG(r) = (uint16_t)((REG(r) & 0xFF00) | (uint8_t)(b)))
#define SET_HI(r, b) (REG(r) = (uint16_t)((REG(r) & 0x00FF) | (uint16_t)((uint8_t)(b)) << 8))
#define AL ((uint8_t)REG(AX))

/* DS-relative with the live DS (the generated accessors' gs_rd* / gs_wr*). */
#define rd8 gs_rd8
#define rd16 gs_rd16
#define wr8 gs_wr8
#define wr16 gs_wr16
static uint8_t erd8(Pc *pc, uint16_t off) { return cpu_read8(&pc->cpu, cpu_linear(SREG(ES), off)); }
static void ewr8(Pc *pc, uint16_t off, uint8_t v) { cpu_write8(&pc->cpu, cpu_linear(SREG(ES), off), v); }

static int dstep(Pc *pc, int size) { return (pc->cpu.flags & F_DF) ? -size : size; }

static void port_out(Pc *pc, uint16_t port, uint8_t v) { pc->cpu.bus.out8(pc->cpu.bus.ctx, port, v); }
static uint8_t port_in(Pc *pc, uint16_t port) { return pc->cpu.bus.in8(pc->cpu.bus.ctx, port); }

/* MUL r/m16: DX:AX = AX * v. */
static void mul16(Pc *pc, uint16_t v)
{
    uint32_t p = (uint32_t)REG(AX) * v;
    REG(AX) = (uint16_t)p;
    REG(DX) = (uint16_t)(p >> 16);
}

/* "mov al,ah; mov ah,dl" after a MUL: the middle 16 bits of DX:AX. */
static void mid16(Pc *pc) { REG(AX) = (uint16_t)((REG(DX) & 0xFF) << 8 | REG(AX) >> 8); }

/* ---- cycles ---------------------------------------------------------------------------- */

#define N_COST (sizeof ed_ins_cost / sizeof ed_ins_cost[0])
#define ENTRY_CYCLES 1

static const EdInsCost *ins_at(uint16_t addr)
{
    size_t lo = 0, hi = N_COST;
    while (lo < hi) {
        size_t mid = (lo + hi) / 2;
        if (ed_ins_cost[mid].addr < addr)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &ed_ins_cost[lo];
}

/* The original executes every instruction in [from, to) in order (jumps fall through). */
static void run(Pc *pc, uint16_t from, uint16_t to)
{
    for (const EdInsCost *i = ins_at(from); i < ed_ins_cost + N_COST && i->addr < to; i++)
        pc->cpu.cycles += i->cost;
}

/* The conditional jump (or LOOP) at addr, already counted by run(), was taken. */
static void taken(Pc *pc, uint16_t addr)
{
    const EdInsCost *i = ins_at(addr);
    pc->cpu.cycles += (uint64_t)i->taken - i->cost;
}

/* ---- calls ----------------------------------------------------------------------------- */

#define STEP_CAP 5000000L

/* Runs from 0050:target until the routine returns to the address on top of the stack, as
 * the CPU would with the natives on (see the top of the file). */
static void run_from(Pc *pc, uint16_t target)
{
    Cpu8086 *c = &pc->cpu;
    uint16_t sp0 = c->regs[R_SP];
    uint16_t ret_ip = mem_read16(pc, c->sregs[S_SS], sp0);
    const uint8_t *map = c->hook_map;
    c->sregs[S_CS] = GAME_CS;
    c->ip = target;
    for (long n = 0; n < STEP_CAP; n++) {
        bool done = false;
        if (map && c->sregs[S_CS] == GAME_CS && map[c->ip])
            done = native_call(pc, c->ip);
        if (!done) {
            c->hook_map = NULL; /* stepped here, so that no nested --verify starts */
            native_or_cpu_step(pc);
            c->hook_map = map;
        }
        uint16_t d = (uint16_t)(c->regs[R_SP] - sp0);
        if (c->ip == ret_ip && c->sregs[S_CS] == GAME_CS && d >= 2 && d < 0x8000)
            break;
    }
}

/* Performs the near CALL instruction at 0050:at (E8 rel16): its cost, the push, the callee. */
static void call(Pc *pc, uint16_t at)
{
    uint16_t ret_ip = (uint16_t)(at + 3);
    uint16_t target = (uint16_t)(ret_ip + mem_read16(pc, GAME_CS, (uint16_t)(at + 1)));
    run(pc, at, ret_ip);
    cpu_push(&pc->cpu, ret_ip);
    run_from(pc, target);
}

/* RET at 0050:at. */
static void ret(Pc *pc, uint16_t at)
{
    run(pc, at, (uint16_t)(at + 1));
    native_ret(pc);
}

/* Single-steps original code (natives off) from 0050:from until IP = until with SP = sp.
 * Used for the divide-error path (DIV overflow -> INT 0 -> IRET to the next instruction). */
static void step_original(Pc *pc, uint16_t from, uint16_t until)
{
    Cpu8086 *c = &pc->cpu;
    const uint8_t *map = c->hook_map;
    uint16_t sp = c->regs[R_SP];
    c->hook_map = NULL;
    c->ip = from;
    for (long n = 0; n < STEP_CAP; n++) {
        native_or_cpu_step(pc);
        if (c->ip == until && c->sregs[S_CS] == GAME_CS && c->regs[R_SP] == sp)
            break;
    }
    c->hook_map = map;
}

/* ---- interrupts ------------------------------------------------------------------------- */

/* --verify attaches its write log only while it runs a routine; in normal play it is NULL. */
static bool under_verify(Pc *pc) { return pc->cpu.write_log != NULL; }

/* True when the timer (PIT channel 0) or the keyboard would raise an interrupt within n
 * cycles of the call that started at cycle `start` (the test of 3.14's irq_hand_back; the PIT
 * is advanced only after a native returns, so its state is still the one at the start). */
static bool irq_due(Pc *pc, uint64_t start, uint64_t n)
{
    if (pc->csched)
        return false; /* C scheduler (3.22): interrupts only come between natives */
    const PitChannel *t = &pc->pit[0];
    bool timer = pc->irq0_backlog || (t->loaded && t->count - (int64_t)((pc->pit_cycle_frac + n) / 4) <= 0);
    bool key = !pc->kbd_full && pc->kbd_head != pc->kbd_tail && start + n >= pc->kbd_next_cycle;
    return timer || key;
}

/* Hands the call back to the original: performs the routine's first instruction (natives
 * off), after which the CPU continues in the original routine, with interrupts. */
static void step_first(Pc *pc)
{
    Cpu8086 *c = &pc->cpu;
    const uint8_t *map = c->hook_map;
    c->hook_map = NULL;
    cpu_step(c);
    c->hook_map = map;
}

/* ---- 0050:36F4 editor_row_ptr, 36E3 editor_cursor_clear --------------------------------- */

static void b_row_ptr(Pc *pc)
{
    run(pc, 0x36F4, 0x3702);
    uint16_t bx = rd16(pc, (uint16_t)(GS_EDITOR_ROW_OFFSETS + gs_editor_row(pc)));
    REG(BX) = bx;
    gs_set_editor_ptr(pc, bx);
    ret(pc, 0x3702);
}

static void b_cursor_clear(Pc *pc)
{
    call(pc, 0x36E3);
    run(pc, 0x36E6, 0x36F3);
    SET_LO(DX, 0x20);
    ewr8(pc, REG(BX), 0x20);
    ewr8(pc, (uint16_t)(REG(BX) + 2), 0x20);
    ewr8(pc, (uint16_t)(REG(BX) + 4), 0x20);
    ret(pc, 0x36F3);
}

/* ---- 0050:369F editor_first_page, 368A editor_next_row, 36C1 editor_prev_row ------------- */

/* 36AC: editor_row = AL, draw the "-->" cursor, RET. */
static void at_36ac(Pc *pc)
{
    run(pc, 0x36AC, 0x36AF);
    gs_set_editor_row(pc, AL);
    call(pc, 0x36AF);
    run(pc, 0x36B2, 0x36C0);
    ewr8(pc, REG(BX), '-');
    ewr8(pc, (uint16_t)(REG(BX) + 2), '-');
    ewr8(pc, (uint16_t)(REG(BX) + 4), '>');
    ret(pc, 0x36C0);
}

/* 36A1: editor_page = AL, page text, fields, cursor on row 2. */
static void at_36a1(Pc *pc)
{
    run(pc, 0x36A1, 0x36A4);
    gs_set_editor_page(pc, AL);
    call(pc, 0x36A4);
    call(pc, 0x36A7);
    run(pc, 0x36AA, 0x36AC);
    SET_LO(AX, 2);
    at_36ac(pc);
}

static void b_first_page(Pc *pc)
{
    run(pc, 0x369F, 0x36A1);
    SET_LO(AX, 0);
    at_36a1(pc);
}

static void b_next_row(Pc *pc)
{
    call(pc, 0x368A);
    run(pc, 0x368D, 0x3696);
    SET_LO(AX, gs_editor_row(pc) + 2);
    if (AL != 0x2E) {
        taken(pc, 0x3694);
        at_36ac(pc);
        return;
    }
    run(pc, 0x3696, 0x369F);
    SET_LO(AX, gs_editor_page(pc) + 2);
    if (AL != 4) {
        taken(pc, 0x369D);
        at_36a1(pc);
        return;
    }
    b_first_page(pc);
}

static void b_prev_row(Pc *pc)
{
    call(pc, 0x36C1);
    run(pc, 0x36C4, 0x36CD);
    SET_LO(AX, gs_editor_row(pc) - 2);
    if (AL != 0) {
        taken(pc, 0x36CB);
        at_36ac(pc);
        return;
    }
    run(pc, 0x36CD, 0x36D4);
    SET_LO(AX, gs_editor_page(pc) - 2);
    if (!(AL & 0x80)) {
        taken(pc, 0x36D2);
    } else {
        run(pc, 0x36D4, 0x36D6);
        SET_LO(AX, 2);
    }
    run(pc, 0x36D6, 0x36D9);
    gs_set_editor_page(pc, AL);
    call(pc, 0x36D9);
    call(pc, 0x36DC);
    run(pc, 0x36DF, 0x36E3);
    SET_LO(AX, 0x2C);
    at_36ac(pc);
}

/* ---- 0050:3909 editor_page_text, 39DB editor_draw_page ------------------------------------ */

static void b_page_text(Pc *pc)
{
    run(pc, 0x3909, 0x3911);
    SET_HI(AX, 0x0F);
    REG(CX) = 0x3E8;
    REG(DI) = 0;
    for (;;) {
        run(pc, 0x3911, 0x3915);
        SET_LO(AX, rd8(pc, REG(SI)));
        REG(SI) = (uint16_t)(REG(SI) + dstep(pc, 1));
        ewr8(pc, REG(DI), AL);
        ewr8(pc, (uint16_t)(REG(DI) + 1), (uint8_t)(REG(AX) >> 8));
        REG(DI) = (uint16_t)(REG(DI) + dstep(pc, 2));
        if (--REG(CX) == 0)
            break;
        taken(pc, 0x3913);
    }
    ret(pc, 0x3915);
}

static void b_draw_page(Pc *pc)
{
    run(pc, 0x39DB, 0x39E5);
    uint8_t page = gs_editor_page(pc);
    REG(BX) = page;
    REG(SI) = rd16(pc, (uint16_t)(GS_EDITOR_PAGE_TEXTS + page));
    call(pc, 0x39E5);
    ret(pc, 0x39E8);
}

/* ---- 0050:39B2 editor_field_next, 396F editor_draw_fields, 39E9 editor_read_fields ------ */

static void b_field_next(Pc *pc)
{
    run(pc, 0x39B2, 0x39DA);
    uint16_t bx = gs_editor_field_rec(pc);
    uint8_t row = rd8(pc, (uint16_t)(bx + 1));
    REG(BX) = bx;
    gs_set_editor_row(pc, row);
    REG(DI) = row;
    gs_set_editor_field_scr(pc, (uint16_t)(rd16(pc, (uint16_t)(GS_EDITOR_ROW_OFFSETS + row)) + 0x0A));
    REG(AX) = (uint16_t)(rd8(pc, (uint16_t)(bx + 2)) + GS_EDITOR_VALUES);
    gs_set_editor_ptr(pc, REG(AX));
    gs_set_editor_field_rec(pc, (uint16_t)(gs_editor_field_rec(pc) + 3));
    ret(pc, 0x39DA);
}

/* 396F..397D / 39E9..39F7: editor_field_rec = the page's field list. */
static void field_list_start(Pc *pc, uint16_t at)
{
    run(pc, at, (uint16_t)(at + 0x0E));
    uint16_t bx = rd16(pc, (uint16_t)(GS_EDITOR_FIELD_LISTS + gs_editor_page(pc)));
    REG(BX) = bx;
    gs_set_editor_field_rec(pc, bx);
}

/* 397D / 39F7: DX = width of the next record; false (after RET) at the end of the list. */
static bool field_list_next(Pc *pc, uint16_t at)
{
    run(pc, at, (uint16_t)(at + 0x0C));
    REG(BX) = gs_editor_field_rec(pc);
    REG(DX) = rd8(pc, REG(BX));
    if (REG(DX) == 0) {
        ret(pc, (uint16_t)(at + 0x0C));
        return false;
    }
    taken(pc, (uint16_t)(at + 0x0A));
    return true;
}

static void b_draw_fields(Pc *pc)
{
    field_list_start(pc, 0x396F);
    while (field_list_next(pc, 0x397D)) {
        call(pc, 0x398A);
        run(pc, 0x398D, 0x399E);
        SET_LO(CX, 0);
        wr8(pc, GS_EDITOR_VALUE, 0);
        wr8(pc, (uint16_t)(GS_EDITOR_VALUE + 1), 0);
        wr8(pc, (uint16_t)(GS_EDITOR_VALUE + 2), 0);
        REG(SI) = 0;
        for (;;) {
            run(pc, 0x399E, 0x39AD);
            REG(BX) = gs_editor_ptr(pc);
            SET_LO(AX, rd8(pc, (uint16_t)(REG(BX) + REG(SI))));
            wr8(pc, (uint16_t)(GS_EDITOR_VALUE + REG(SI)), AL);
            REG(SI)++;
            if (REG(SI) == REG(DX))
                break;
            taken(pc, 0x39AB);
        }
        call(pc, 0x39AD);
        run(pc, 0x39B0, 0x39B2);
    }
}

static void b_read_fields(Pc *pc)
{
    field_list_start(pc, 0x39E9);
    while (field_list_next(pc, 0x39F7)) {
        call(pc, 0x3A04);
        run(pc, 0x3A07, 0x3A0A);
        REG(DI) = 5;
        for (;;) {
            run(pc, 0x3A0A, 0x3A12);
            wr8(pc, (uint16_t)(GS_EDITOR_DIGITS + REG(DI)), '0');
            if (--REG(DI) & 0x8000)
                break;
            taken(pc, 0x3A10);
        }
        run(pc, 0x3A12, 0x3A15);
        REG(SI) = 0;
        for (;;) {
            run(pc, 0x3A15, 0x3A20);
            REG(BX) = gs_editor_field_scr(pc);
            SET_LO(AX, erd8(pc, (uint16_t)(REG(BX) + REG(SI))));
            if (AL == 0x20) {
                taken(pc, 0x3A1E);
                break;
            }
            run(pc, 0x3A20, 0x3A23);
            REG(DI) = 4;
            for (;;) {
                run(pc, 0x3A23, 0x3A2E);
                uint8_t ah = rd8(pc, (uint16_t)(GS_EDITOR_DIGITS + REG(DI)));
                SET_HI(AX, ah);
                wr8(pc, (uint16_t)(GS_EDITOR_DIGITS + 1 + REG(DI)), ah);
                if (--REG(DI) & 0x8000)
                    break;
                taken(pc, 0x3A2C);
            }
            run(pc, 0x3A2E, 0x3A36);
            wr8(pc, GS_EDITOR_DIGITS, AL);
            REG(SI) = (uint16_t)(REG(SI) + 2);
        }
        call(pc, 0x3A36);
        run(pc, 0x3A39, 0x3A3C);
        REG(SI) = 0;
        for (;;) {
            run(pc, 0x3A3C, 0x3A4B);
            SET_LO(AX, rd8(pc, (uint16_t)(GS_EDITOR_VALUE + REG(SI))));
            REG(BX) = gs_editor_ptr(pc);
            wr8(pc, (uint16_t)(REG(BX) + REG(SI)), AL);
            REG(SI)++;
            if (REG(SI) == REG(DX))
                break;
            taken(pc, 0x3A49);
        }
        run(pc, 0x3A4B, 0x3A4D);
    }
}

/* ---- 0050:3A4D usermode_store, 3A52 usermode_recall ---------------------------------------- */

#define SLOT_SIZE 0x41

static void usermode_copy(Pc *pc, bool store)
{
    if (store)
        run(pc, 0x3A4D, 0x3A51);
    else
        run(pc, 0x3A52, 0x3A54);
    SET_LO(DX, store ? 1 : 0);
    run(pc, 0x3A54, 0x3A5E);
    gs_set_editor_ptr(pc, GS_USERMODE_SLOTS);
    SET_LO(CX, gs_usermode_cur(pc));
    for (;;) {
        run(pc, 0x3A5E, 0x3A62);
        SET_LO(CX, (uint8_t)REG(CX) - 1);
        if (REG(CX) & 0x80) {
            taken(pc, 0x3A60);
            break;
        }
        run(pc, 0x3A62, 0x3A69);
        gs_set_editor_ptr(pc, (uint16_t)(gs_editor_ptr(pc) + SLOT_SIZE));
    }
    run(pc, 0x3A69, 0x3A6F);
    REG(CX) = SLOT_SIZE - 1;
    REG(SI) = SLOT_SIZE - 1;
    for (;;) {
        run(pc, 0x3A6F, 0x3A73);
        if ((uint8_t)REG(DX) == 0) {
            taken(pc, 0x3A71);
            run(pc, 0x3A80, 0x3A8A);
            REG(BX) = gs_editor_ptr(pc);
            SET_LO(AX, rd8(pc, (uint16_t)(REG(BX) + REG(SI))));
            gs_set_editor_values_b(pc, REG(SI), AL);
        } else {
            run(pc, 0x3A73, 0x3A7F);
            SET_LO(AX, gs_editor_values_b(pc, REG(SI)));
            REG(BX) = gs_editor_ptr(pc);
            wr8(pc, (uint16_t)(REG(BX) + REG(SI)), AL);
        }
        run(pc, 0x3A8A, 0x3A8D);
        if (--REG(SI) & 0x8000)
            break;
        taken(pc, 0x3A8B);
    }
    run(pc, 0x3A8D, 0x3A92);
    gs_set_gear_down(pc, 0xFF);
    call(pc, 0x3A92);
    ret(pc, 0x3A95);
}

static void b_usermode_store(Pc *pc) { usermode_copy(pc, true); }
static void b_usermode_recall(Pc *pc) { usermode_copy(pc, false); }

/* ---- 0050:3916 editor_commit, editor_get_input's '*' and Ins keys ------------------------- */

/* 3954: draw the fields, editor_row = editor_saved_row, RET (from editor_get_input when
 * reached from its key handlers). */
static void at_3954(Pc *pc)
{
    call(pc, 0x3954);
    run(pc, 0x3957, 0x395D);
    SET_LO(AX, gs_editor_saved_row(pc));
    gs_set_editor_row(pc, AL);
    ret(pc, 0x395D);
}

static void b_commit(Pc *pc)
{
    run(pc, 0x3916, 0x391C);
    SET_LO(AX, gs_editor_row(pc));
    gs_set_editor_saved_row(pc, AL);
    call(pc, 0x391C);
    run(pc, 0x391F, 0x3926);
    uint8_t al = gs_editor_usermode(pc);
    SET_LO(AX, al);
    if (al > 0x81) {
        taken(pc, 0x3924);
    } else {
        run(pc, 0x3926, 0x392A);
        if (al > 0x6D) {
            taken(pc, 0x3928);
            goto l3930;
        }
        run(pc, 0x392A, 0x392E);
        if (al < 0x1E) {
            taken(pc, 0x392C);
            goto l3930;
        }
    }
    run(pc, 0x392E, 0x3930);
    SET_LO(AX, 0);
l3930:
    run(pc, 0x3930, 0x3936);
    if (AL == gs_usermode_cur(pc)) {
        taken(pc, 0x3934);
        run(pc, 0x395E, 0x3962);
        if (AL >= 0x0A) {
            taken(pc, 0x3960);
        } else {
            run(pc, 0x3962, 0x396A);
            SET_LO(AX, AL + 0x0A);
            gs_set_usermode_cur(pc, AL);
            gs_set_editor_usermode(pc, AL);
            call(pc, 0x396A);
            run(pc, 0x396D, 0x396F);
        }
        at_3954(pc);
        return;
    }
    run(pc, 0x3936, 0x393D);
    gs_set_usermode_cur(pc, AL);
    if (AL >= 0x6E) {
        taken(pc, 0x393B);
        run(pc, 0x3949, 0x3951);
        SET_LO(AX, AL - 0x64);
        gs_set_usermode_cur(pc, AL);
        gs_set_editor_usermode(pc, AL);
        call(pc, 0x3951);
    } else {
        call(pc, 0x393D);
        run(pc, 0x3940, 0x3948);
        SET_LO(AX, gs_usermode_cur(pc));
        gs_set_editor_usermode(pc, AL);
    }
    at_3954(pc);
}

/* 37EC: after '*' / Ins: editor_typed = 0, editor_saved_row = editor_row - 2, redraw, RET. */
static void at_37ec(Pc *pc)
{
    run(pc, 0x37EC, 0x37FC);
    gs_set_editor_typed(pc, 0);
    SET_LO(AX, gs_editor_row(pc) - 2);
    gs_set_editor_saved_row(pc, AL);
    at_3954(pc);
}

/* 37D4 ('*'): recall the current user mode into the editor. */
static void b_key_star(Pc *pc)
{
    call(pc, 0x37D4);
    run(pc, 0x37D7, 0x37D9);
    at_37ec(pc);
}

/* 37DD (Ins, editor key 11h): user mode < 10: editor_typed++ (editor_main then commits);
 * otherwise store the editor values into the current user mode. */
static void b_key_ins(Pc *pc)
{
    run(pc, 0x37DD, 0x37E4);
    if (gs_editor_usermode(pc) >= 0x0A) {
        taken(pc, 0x37E2);
        call(pc, 0x37E9);
        at_37ec(pc);
        return;
    }
    run(pc, 0x37E4, 0x37E8);
    gs_set_editor_typed(pc, (uint8_t)(gs_editor_typed(pc) + 1));
    ret(pc, 0x37E8);
}

/* 374E (Enter, '=', '-', Esc): editor_digits_to_bin, RET. */
static void b_key_accept(Pc *pc)
{
    call(pc, 0x374E);
    ret(pc, 0x3751);
}

/* 3740 ('-'): editor_up = '-', then as 374E. */
static void b_key_up(Pc *pc)
{
    run(pc, 0x3740, 0x3745);
    gs_set_editor_up(pc, AL);
    b_key_accept(pc);
}

/* 3756 (Backspace): drop the last digit typed. Continues at the key loop 3726 (no RET). */
static void b_key_backspace(Pc *pc)
{
    run(pc, 0x3756, 0x375D);
    SET_LO(AX, gs_editor_ndigits(pc));
    if (AL == 0) {
        taken(pc, 0x375B);
        pc->cpu.ip = 0x3726;
        return;
    }
    run(pc, 0x375D, 0x3773);
    gs_set_editor_ndigits(pc, (uint8_t)(AL - 1));
    SET_LO(AX, 0x20);
    gs_set_editor_cell(pc, (uint16_t)(gs_editor_cell(pc) - 1));
    REG(SI) = (uint16_t)(gs_editor_cell(pc) << 1);
    ewr8(pc, (uint16_t)(REG(BX) + REG(SI)), 0x20);
    REG(DI) = 1;
    for (;;) {
        run(pc, 0x3773, 0x3781);
        SET_LO(AX, rd8(pc, (uint16_t)(GS_EDITOR_DIGITS + REG(DI))));
        wr8(pc, (uint16_t)(GS_EDITOR_DIGITS - 1 + REG(DI)), AL);
        if (++REG(DI) == 6)
            break;
        taken(pc, 0x377F);
    }
    run(pc, 0x3781, 0x3788);
    wr8(pc, (uint16_t)(GS_EDITOR_DIGITS + 5), '0');
    run(pc, 0x3800, 0x3803);
    pc->cpu.ip = 0x3726;
}

/* ---- 0050:379A / 37B5: 's' / 'l', presets to / from a host file ------------------------------ */

#define PRESET_FILE "fs1_presets.bin"
#define PRESET_BYTES (0x30B4 - GS_USERMODE_SLOTS) /* 79Eh: 30 slots of 41h bytes */
#define TRACK_PRESETS 0x26
#define SCREEN_SEG 0xB800

/* The preset file: $FS1_PRESETS if set; else fs1_presets.bin next to the executable
 * (SDL_GetBasePath), or in the user's preference folder (SDL_GetPrefPath) when the
 * executable's folder is not writable (saving) or has no file (loading). Returns an
 * SDL_malloc'ed path, or NULL. */
static char *preset_path(bool pref)
{
    const char *env = SDL_getenv("FS1_PRESETS");
    char *path = NULL;
    if (env && *env)
        return pref ? NULL : SDL_strdup(env);
    if (!pref) {
        const char *base = SDL_GetBasePath();
        if (base)
            SDL_asprintf(&path, "%s%s", base, PRESET_FILE);
    } else {
        char *dir = SDL_GetPrefPath("fs1-sdl3", "Flight Simulator 1");
        if (dir)
            SDL_asprintf(&path, "%s%s", dir, PRESET_FILE);
        SDL_free(dir);
    }
    return path;
}

static bool preset_write(const uint8_t *data)
{
    for (int pref = 0; pref < 2; pref++) {
        char *path = preset_path(pref);
        if (!path)
            continue;
        bool ok = SDL_SaveFile(path, data, PRESET_BYTES);
        if (ok)
            SDL_Log("editor: presets saved to %s", path);
        SDL_free(path);
        if (ok)
            return true;
    }
    SDL_Log("editor: presets not saved: %s", SDL_GetError());
    return false;
}

/* Reads the preset file into data; false if there is none (or it has the wrong size). */
static bool preset_read(uint8_t *data)
{
    for (int pref = 0; pref < 2; pref++) {
        char *path = preset_path(pref);
        if (!path)
            continue;
        size_t size = 0;
        void *buf = SDL_LoadFile(path, &size);
        if (buf && size == PRESET_BYTES) {
            SDL_memcpy(data, buf, PRESET_BYTES);
            SDL_Log("editor: presets loaded from %s", path);
            SDL_free(buf);
            SDL_free(path);
            return true;
        }
        if (buf)
            SDL_Log("editor: %s has %u bytes, not %u; ignored", path, (unsigned)size, (unsigned)PRESET_BYTES);
        SDL_free(buf);
        SDL_free(path);
    }
    return false;
}

/* The cycles of the original's disk code that the natives replace, on the paths a good
 * write, a good read and a failed read take, so that the timeline stays the original's. An
 * INT 13h costs its INT (in the table) plus the BIOS stub "0F nn" and IRET. */
#define INT13_STUB_CYCLES (2 + 34)

static void cost_disk_ds(Pc *pc) { run(pc, 0x00F8, 0x0104); } /* sub_00F8 */

static void cost_checksum(Pc *pc) /* track_checksum 0157: 800h words */
{
    run(pc, 0x0157, 0x0161);
    for (int i = 0; i < 0x800; i++) {
        run(pc, 0x0161, 0x0169);
        if (i + 1 < 0x800)
            taken(pc, 0x0167);
    }
    run(pc, 0x0169, 0x016B);
}

/* sub_01DE: disk_format_write_track (format, write, read back, compare), stream_pos = FFFF */
static void cost_track_write(Pc *pc)
{
    run(pc, 0x01DE, 0x01E1);
    run(pc, 0x00BE, 0x00C1);
    cost_disk_ds(pc);
    run(pc, 0x00C1, 0x00C7);
    for (int i = 0; i < 8; i++) {
        run(pc, 0x00C7, 0x00D0);
        if (i < 7)
            taken(pc, 0x00CE);
    }
    run(pc, 0x00D0, 0x00EA);
    pc->cpu.cycles += INT13_STUB_CYCLES;
    taken(pc, 0x00E8);
    run(pc, 0x0109, 0x0137);
    pc->cpu.cycles += INT13_STUB_CYCLES;
    run(pc, 0x0137, 0x0142);
    cost_checksum(pc);
    run(pc, 0x0142, 0x0148);
    pc->cpu.cycles += INT13_STUB_CYCLES;
    run(pc, 0x0148, 0x014E);
    cost_checksum(pc);
    run(pc, 0x014E, 0x0157);
    run(pc, 0x01E1, 0x01E8);
}

/* the first boot_stream_byte of a load: boot_read_track, good or failed, then the byte */
static void cost_first_read(Pc *pc, bool ok)
{
    run(pc, 0x017C, 0x0187);
    taken(pc, 0x0185);
    run(pc, 0x0195, 0x019A);
    run(pc, 0x0104, 0x0107);
    cost_disk_ds(pc);
    run(pc, 0x0107, 0x0137);
    pc->cpu.cycles += INT13_STUB_CYCLES;
    if (ok) {
        run(pc, 0x0137, 0x013F);
        taken(pc, 0x013D);
        run(pc, 0x0152, 0x0157);
    } else {
        run(pc, 0x0137, 0x0139);
        taken(pc, 0x0137);
        run(pc, 0x00EA, 0x00F0);
    }
    run(pc, 0x019A, 0x01A0);
    run(pc, 0x0187, 0x0195);
}

/* 37C9: pop ax; call 016B (drive motor off); jmp 3643 (redraw, key loop). */
static void preset_tail(Pc *pc)
{
    run(pc, 0x37C9, 0x37CA);
    REG(AX) = cpu_pop(&pc->cpu);
    call(pc, 0x37CA);
    run(pc, 0x37CD, 0x37D0);
    pc->cpu.ip = 0x3643;
}

/* 379A: entered with CX = 79Eh, SI = 2916h. The original copies the presets through the
 * stream buffer (B800:0000, put_byte) and writes them to track 26h (format, write, read back,
 * checksum). The native writes the host file and leaves memory as the original's successful
 * write does: B800:0000..079D = presets, stream_pos = FFFF, disk_track = 27h, format_table
 * tracks = 26h, track_verify = 0, disk_dx = 0. */
static void b_preset_save(Pc *pc)
{
    call(pc, 0x379A); /* cga_program_regs */
    call(pc, 0x379D); /* disk_reset: DS = ES = [0000:0120] */
    run(pc, 0x37A0, 0x37A6);
    uint8_t data[PRESET_BYTES];
    for (unsigned i = 0; i < PRESET_BYTES; i++) {
        data[i] = rd8(pc, (uint16_t)(REG(SI) + i));
        cpu_write8(&pc->cpu, cpu_linear(SCREEN_SEG, (uint16_t)i), data[i]);
        run(pc, 0x37A6, 0x37AC);
        run(pc, 0x01AD, 0x01C6);
        if (i + 1 < PRESET_BYTES)
            taken(pc, 0x37AA);
    }
    SET_LO(AX, data[PRESET_BYTES - 1]);
    REG(SI) = (uint16_t)(REG(SI) + PRESET_BYTES);
    REG(CX) = 0;
    REG(DI) = SCREEN_SEG;
    preset_write(data);
    /* sub_01DE / disk_format_write_track, as after a successful write */
    run(pc, 0x37AC, 0x37AF);
    cost_track_write(pc);
    for (int k = 0; k < 8; k++)
        gs_set_format_table_b(pc, 4u * k, TRACK_PRESETS);
    gs_set_track_verify(pc, 0);
    gs_set_screen_seg(pc, SCREEN_SEG);
    gs_set_disk_dx(pc, 0);
    gs_set_disk_track(pc, TRACK_PRESETS + 1);
    gs_set_stream_pos(pc, 0xFFFF);
    REG(BX) = 0;
    REG(DX) = 0;
    SREG(ES) = SCREEN_SEG;
    run(pc, 0x37AF, 0x37B1);
    preset_tail(pc);
}

/* 37B5: entered with CX = 79Eh, SI = 2916h. The original streams track 26h through
 * boot_stream_byte into the presets. With a preset file, memory ends as after a good read:
 * B800:0000..079D = file, presets = file, disk_track = 27h. Without one it ends as the
 * original with an unformatted track: the read fails (disk_error = 1, disk_track stays 26h)
 * and the presets get whatever is in the track buffer B800:0000..079D, which is the editor's
 * text screen (characters and attribute bytes 0Fh). */
static void b_preset_load(Pc *pc)
{
    call(pc, 0x37B5); /* cga_program_regs */
    call(pc, 0x37B8); /* disk_reset */
    run(pc, 0x37BB, 0x37C3);
    REG(DI) = REG(SI);
    uint8_t data[PRESET_BYTES];
    bool ok = preset_read(data);
    gs_set_track_verify(pc, 0);
    gs_set_screen_seg(pc, SCREEN_SEG);
    gs_set_disk_dx(pc, 0);
    if (ok) {
        gs_set_disk_track(pc, TRACK_PRESETS + 1);
        for (unsigned i = 0; i < PRESET_BYTES; i++)
            cpu_write8(&pc->cpu, cpu_linear(SCREEN_SEG, (uint16_t)i), data[i]);
    } else {
        SDL_Log("editor: no preset file; loading as from an unformatted track");
        gs_set_disk_error(pc, 1);
        for (unsigned i = 0; i < PRESET_BYTES; i++)
            data[i] = cpu_read8(&pc->cpu, cpu_linear(SCREEN_SEG, (uint16_t)i));
    }
    for (unsigned i = 0; i < PRESET_BYTES; i++) {
        cpu_write8(&pc->cpu, cpu_linear(SREG(ES), REG(DI)), data[i]);
        REG(DI) = (uint16_t)(REG(DI) + dstep(pc, 1));
        run(pc, 0x37C3, 0x37C9);
        if (i == 0)
            cost_first_read(pc, ok);
        else
            run(pc, 0x017C, 0x0195);
        if (i + 1 < PRESET_BYTES)
            taken(pc, 0x37C7);
    }
    gs_set_stream_pos(pc, PRESET_BYTES - 1);
    REG(BX) = PRESET_BYTES - 1;
    SET_LO(AX, data[PRESET_BYTES - 1]);
    REG(CX) = 0;
    preset_tail(pc);
}

/* ---- 0050:3A96 editor_capture_state, 3B29 speaker_off, 3C2F / 3C6C scaling --------------- */

static void b_speaker_off(Pc *pc)
{
    run(pc, 0x3B29, 0x3B35);
    gs_set_spk_pattern(pc, 0);
    uint8_t v = (uint8_t)(port_in(pc, 0x61) & 0xFC);
    SET_LO(AX, v);
    port_out(pc, 0x61, v);
    ret(pc, 0x3B35);
}

/* DIV overflow: the original's INT 0 handler runs (AX = 7FFFh or 8001h), then IRET. */
static void b_scale_wind(Pc *pc)
{
    run(pc, 0x3C6C, 0x3C75);
    REG(BP) = rd16(pc, (uint16_t)(REG(BX) + 2));
    REG(CX) = rd16(pc, REG(BX));
    if (REG(DI) == 0) {
        run(pc, 0x3C75, 0x3C88);
        REG(AX) = 0x168;
        mul16(pc, REG(BP));
        wr16(pc, (uint16_t)(REG(BX) + 2), REG(DX));
        SET_LO(AX, 0x64);
        REG(AX) = (uint16_t)(0x64 * (REG(CX) >> 8));
        REG(AX) = (uint16_t)(REG(AX) + (uint8_t)REG(CX));
    } else {
        taken(pc, 0x3C73);
        run(pc, 0x3C89, 0x3C99);
        REG(AX) = 0xB60C;
        mul16(pc, REG(BP));
        mid16(pc);
        wr16(pc, (uint16_t)(REG(BX) + 2), REG(AX));
        REG(AX) = REG(CX);
        SET_LO(CX, 0x64);
        uint16_t q = REG(AX) / 0x64;
        if (q > 0xFF) {
            step_original(pc, 0x3C99, 0x3C9B);
        } else {
            run(pc, 0x3C99, 0x3C9B);
            REG(AX) = (uint16_t)((REG(AX) % 0x64) << 8 | q);
        }
        run(pc, 0x3C9B, 0x3C9F);
        REG(AX) = (uint16_t)(REG(AX) >> 8 | REG(AX) << 8);
        run(pc, 0x3C86, 0x3C88);
    }
    wr16(pc, REG(BX), REG(AX));
    ret(pc, 0x3C88);
}

static void b_scale_values(Pc *pc)
{
    static const uint16_t wind[4] = { 0x2079, 0x207D, 0x2081, 0x2085 };
    for (int i = 0; i < 4; i++) {
        uint16_t at = (uint16_t)(0x3C2F + 6 * i);
        run(pc, at, (uint16_t)(at + 3));
        REG(BX) = wind[i];
        call(pc, (uint16_t)(at + 3));
    }
    run(pc, 0x3C47, 0x3C50);
    REG(BP) = 7;
    REG(BX) = GS_CLOUD_TOPS;
    REG(CX) = 0x4E0C;
    for (;;) {
        run(pc, 0x3C50, 0x3C55);
        if (REG(DI) == 1) {
            taken(pc, 0x3C53);
            run(pc, 0x3C5F, 0x3C65);
            REG(AX) = rd16(pc, REG(BX));
            mul16(pc, REG(CX));
            wr16(pc, REG(BX), REG(DX));
        } else {
            run(pc, 0x3C55, 0x3C59);
            REG(DX) = rd16(pc, REG(BX));
            REG(AX) = 0;
            if (REG(DX) >= REG(CX)) {
                step_original(pc, 0x3C59, 0x3C5B);
            } else {
                run(pc, 0x3C59, 0x3C5B);
                uint32_t n = (uint32_t)REG(DX) << 16;
                REG(AX) = (uint16_t)(n / REG(CX));
                REG(DX) = (uint16_t)(n % REG(CX));
            }
            run(pc, 0x3C5B, 0x3C5F);
            wr16(pc, REG(BX), REG(AX));
        }
        run(pc, 0x3C65, 0x3C6B);
        REG(BX) = (uint16_t)(REG(BX) + 2);
        if (--REG(BP) == 0)
            break;
        taken(pc, 0x3C69);
    }
    ret(pc, 0x3C6B);
}

static void b_capture_state(Pc *pc)
{
    call(pc, 0x3A96); /* slew_to_editor_pos */
    run(pc, 0x3A99, 0x3AB4);
    REG(AX) = (uint16_t)(rd16(pc, (uint16_t)(GS_ALTITUDE + 1)) + gs_ground_elev(pc));
    mul16(pc, 0xD1EB);
    uint32_t v = ((uint32_t)REG(DX) << 16 | REG(AX)) << 2;
    REG(AX) = (uint16_t)v;
    REG(DX) = (uint16_t)((v >> 16) - 9);
    gs_set_editor_alt(pc, REG(DX));
    run(pc, 0x3AB4, 0x3AC8);
    REG(CX) = 0x168;
    REG(AX) = (uint16_t)((uint16_t)gs_heading(pc) - gs_wind_gust_offset(pc) - gs_wind_dir_offset(pc));
    mul16(pc, REG(CX));
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x11), REG(DX));
    run(pc, 0x3AC8, 0x3AD1);
    REG(AX) = (uint16_t)gs_bank(pc);
    mul16(pc, REG(CX));
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x0F), REG(DX));
    run(pc, 0x3AD1, 0x3ADA);
    REG(AX) = (uint16_t)gs_pitch(pc);
    mul16(pc, REG(CX));
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x0D), REG(DX));
    run(pc, 0x3ADA, 0x3AE6);
    REG(CX) = 0x259;
    REG(AX) = gs_airspeed(pc);
    mul16(pc, REG(CX));
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x13), REG(DX));
    run(pc, 0x3AE6, 0x3B0D);
    REG(AX) = gs_throttle(pc);
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x15), REG(AX));
    REG(AX) = gs_flaps(pc);
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x1B), REG(AX));
    REG(AX) = (uint16_t)((uint16_t)gs_rudder(pc) + 0x7FFF);
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x17), REG(AX));
    REG(AX) = (uint16_t)((uint16_t)gs_aileron(pc) + 0x7FFF);
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x19), REG(AX));
    REG(AX) = (uint16_t)((uint16_t)gs_elevator(pc) + 0x7FFF);
    wr16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x1D), REG(AX));
    run(pc, 0x3B0D, 0x3B12);
    gs_set_spk_restart(pc, 0);
    call(pc, 0x3B12);
    run(pc, 0x3B15, 0x3B1C);
    if (gs_demo_mode(pc)) {
        taken(pc, 0x3B1A);
    } else {
        run(pc, 0x3B1C, 0x3B22);
        REG(AX) = gs_demo_script(pc);
        gs_set_demo_ptr(pc, REG(AX));
    }
    run(pc, 0x3B22, 0x3B25);
    REG(DI) = 0;
    call(pc, 0x3B25);
    ret(pc, 0x3B28);
}

/* ---- 0050:3B36 editor_apply_state, 3C9F alt_from_editor ----------------------------------- */

static void b_alt_from_editor(Pc *pc)
{
    run(pc, 0x3C9F, 0x3CB3);
    REG(CX) = 0x4E0C;
    REG(AX) = (uint16_t)(gs_editor_alt(pc) + 9);
    mul16(pc, REG(CX));
    REG(DX) = (uint16_t)(REG(DX) - gs_ground_elev(pc));
    if ((int16_t)REG(DX) >= 3) {
        taken(pc, 0x3CB1);
    } else {
        run(pc, 0x3CB3, 0x3CB6);
        REG(DX) = 3;
    }
    run(pc, 0x3CB6, 0x3CBF);
    wr16(pc, (uint16_t)(GS_ALTITUDE + 1), REG(DX));
    wr8(pc, GS_ALTITUDE, 0);
    ret(pc, 0x3CBF);
}

/* editor degrees * B60Ch, middle 16 bits: the binary angle (10000h = 360 deg). */
static uint16_t to_angle(Pc *pc, uint16_t deg)
{
    REG(AX) = deg;
    mul16(pc, REG(CX));
    mid16(pc);
    return REG(AX);
}

static void b_apply_state(Pc *pc)
{
    run(pc, 0x3B36, 0x3B3D);
    if (gs_war_mode(pc) == 0) {
        taken(pc, 0x3B3B);
    } else {
        run(pc, 0x3B3D, 0x3B47);
        gs_set_editor_usermode(pc, 7);
        gs_set_usermode_cur(pc, 7);
        call(pc, 0x3B47);
    }
    call(pc, 0x3B4A); /* cga_program_regs */
    call(pc, 0x3B4D); /* clock_hm */
    run(pc, 0x3B50, 0x3B6A);
    REG(AX) = (uint16_t)(gs_editor_north(pc) - 0x4000);
    wr16(pc, (uint16_t)(GS_POS_NORTH + 2), REG(AX));
    REG(AX) = (uint16_t)(gs_editor_east(pc) - 0x4000);
    wr16(pc, (uint16_t)(GS_POS_EAST + 2), REG(AX));
    REG(AX) = 0;
    wr16(pc, GS_POS_NORTH, 0);
    wr16(pc, GS_POS_EAST, 0);
    call(pc, 0x3B6A); /* alt_from_editor */
    run(pc, 0x3B6D, 0x3B84);
    REG(CX) = 0xB60C;
    to_angle(pc, rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x11)));
    REG(AX) = (uint16_t)(REG(AX) + gs_wind_gust_offset(pc) + gs_wind_dir_offset(pc));
    gs_set_heading(pc, (int16_t)REG(AX));
    run(pc, 0x3B84, 0x3B90);
    gs_set_bank(pc, (int16_t)to_angle(pc, rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x0F))));
    run(pc, 0x3B90, 0x3B9C);
    gs_set_pitch(pc, (int16_t)to_angle(pc, rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x0D))));
    run(pc, 0x3B9C, 0x3BAB);
    REG(CX) = 0x6D01;
    REG(AX) = rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x13));
    mul16(pc, REG(CX));
    mid16(pc);
    gs_set_airspeed(pc, REG(AX));
    run(pc, 0x3BAB, 0x3BD2);
    REG(AX) = rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x15));
    gs_set_throttle(pc, REG(AX));
    REG(AX) = rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x1B));
    gs_set_flaps(pc, REG(AX));
    REG(AX) = (uint16_t)(rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x17)) - 0x7FFF);
    gs_set_rudder(pc, (int16_t)REG(AX));
    REG(AX) = (uint16_t)(rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x19)) - 0x7FFF);
    gs_set_aileron(pc, (int16_t)REG(AX));
    REG(AX) = (uint16_t)(rd16(pc, (uint16_t)(GS_EDITOR_VALUES + 0x1D)) - 0x7FFF);
    gs_set_elevator(pc, (int16_t)REG(AX));
    call(pc, 0x3BD2);
    run(pc, 0x3BD5, 0x3BE1);
    gs_set_spk_restart(pc, 1);
    if (gs_reality_mode(pc) == 0) {
        taken(pc, 0x3BDF);
    } else {
        run(pc, 0x3BE1, 0x3BE8);
        if (rd8(pc, (uint16_t)(GS_THROTTLE + 1)) != 0) {
            taken(pc, 0x3BE6);
        } else {
            call(pc, 0x3BE8); /* engine_stop */
            run(pc, 0x3BEB, 0x3BED);
            REG(AX) = 0;
            call(pc, 0x3BED); /* key_set_magnetos */
        }
    }
    run(pc, 0x3BF0, 0x3C02);
    SET_LO(AX, gs_editor_demo(pc) | gs_demo_request(pc));
    gs_set_demo_request(pc, 0);
    gs_set_demo_mode(pc, AL);
    REG(DI) = 1;
    call(pc, 0x3C02); /* editor_scale_values */
    run(pc, 0x3C05, 0x3C19);
    REG(AX) = 0;
    gs_set_war_status_line(pc, 0);
    gs_set_score(pc, 0);
    gs_set_kills(pc, 0);
    gs_set_wing_damage(pc, 0);
    gs_set_bomb_state(pc, 0);
    call(pc, 0x3C19); /* war_score_add */
    call(pc, 0x3C1C); /* war_ground_reset */
    run(pc, 0x3C1F, 0x3C2E);
    SET_LO(AX, ((uint8_t)gs_frame_counter(pc) & 0x1F) - 0x10);
    gs_set_apply_phase(pc, AL);
    gs_set_alt_reset(pc, 0x0C);
    ret(pc, 0x3C2E);
}

/* ---- 0050:629C check_master_disk (start-up) ----------------------------------------------- */

/* 60F8: disk_reset; CL = 0; SI = DI = 40B0h + DS * 16; ES = AX = 0. */
static void b_startup_disk_reset(Pc *pc)
{
    call(pc, 0x60F8);
    run(pc, 0x60FB, 0x6112);
    SET_LO(CX, 0);
    REG(SI) = (uint16_t)(0x40B0 + (uint16_t)(SREG(DS) << 4));
    REG(AX) = 0;
    SREG(ES) = 0;
    REG(DI) = REG(SI);
    ret(pc, 0x6112);
}

/* Up to 5 tries to read byte 0 of track 1Ch: 1 = master (CF = 1), 2 = copy (CF = 0). After
 * 5 failures (with backup_option != 1) the original shows an error and halts at 6311; the
 * native continues there in the original (no RET). */
static void b_check_master_disk(Pc *pc)
{
    run(pc, 0x629C, 0x629F);
    REG(CX) = 5;
    for (;;) {
        run(pc, 0x629F, 0x62A0);
        cpu_push(&pc->cpu, REG(CX));
        run(pc, 0x62A0, 0x62A3);
        cpu_push(&pc->cpu, 0x62A3);
        b_startup_disk_reset(pc);
        run(pc, 0x62A3, 0x62AE);
        gs_set_disk_track(pc, 0x1C);
        gs_set_stream_pos(pc, 0x0FFF);
        call(pc, 0x62AE); /* boot_stream_byte */
        run(pc, 0x62B1, 0x62B8);
        REG(CX) = cpu_pop(&pc->cpu);
        uint8_t e = gs_disk_error(pc);
        gs_set_disk_error(pc, (uint8_t)(e >> 1));
        bool retry = true;
        if (!(e & 1)) {
            taken(pc, 0x62B6);
            run(pc, 0x62C4, 0x62C8);
            if (AL == 1) {
                taken(pc, 0x62C6);
                run(pc, 0x62CE, 0x62CF);
                pc->cpu.flags |= F_CF;
                ret(pc, 0x62CF);
                return;
            }
            run(pc, 0x62C8, 0x62CC);
            if (AL == 2) {
                taken(pc, 0x62CA);
                retry = false;
            } else {
                run(pc, 0x62CC, 0x62CE);
                taken(pc, 0x62CC);
            }
        }
        if (retry) {
            run(pc, 0x62B8, 0x62BF);
            if (gs_backup_option(pc) == 1) {
                taken(pc, 0x62BD);
                retry = false;
            }
        }
        if (retry) {
            run(pc, 0x62BF, 0x62C2);
            if (--REG(CX) != 0) {
                taken(pc, 0x62C0);
                continue;
            }
            run(pc, 0x62C2, 0x62C4);
            pc->cpu.ip = 0x6311; /* error message, then JMP $ */
            return;
        }
        run(pc, 0x62D0, 0x62D1);
        pc->cpu.flags &= (uint16_t)~F_CF;
        ret(pc, 0x62D1);
        return;
    }
}

/* ---- entries ----------------------------------------------------------------------------- */

/* FS1_EDITOR_CYCLE_CHECK=1 (debugging aid): before each call the original routine is
 * single-stepped with a write log, undone, and its cycles are compared with the native's.
 * Interrupt hand-back is off meanwhile; the non-returning natives are not checked. */
static int cycle_check = -1;
static CpuWriteLog check_log;

static bool log_ready(CpuWriteLog *l)
{
    if (!l->addr) {
        l->cap = 1u << 20;
        l->addr = SDL_malloc(l->cap * sizeof *l->addr);
        l->old = SDL_malloc(l->cap);
        if (!l->addr || !l->old) {
            SDL_free(l->addr);
            SDL_free(l->old);
            l->addr = NULL;
            l->old = NULL;
            return false;
        }
    }
    l->count = 0;
    l->overflow = false;
    return true;
}

static bool check_original(Pc *pc, uint64_t *cycles)
{
    Cpu8086 *c = &pc->cpu;
    if (!log_ready(&check_log))
        return false;
    Cpu8086 pre = *c;
    uint16_t sp0 = c->regs[R_SP];
    uint16_t ret_ip = mem_read16(pc, c->sregs[S_SS], sp0);
    c->write_log = &check_log;
    const uint8_t *map = c->hook_map;
    bool returned = false;
    for (long n = 0; n < STEP_CAP && !returned; n++) {
        /* other natives run as with the natives on (their costs are what they charge) */
        if (!(n && map && c->sregs[S_CS] == GAME_CS && map[c->ip] && native_call(pc, c->ip))) {
            c->hook_map = NULL;
            native_or_cpu_step(pc);
            c->hook_map = map;
        }
        uint16_t d = (uint16_t)(c->regs[R_SP] - sp0);
        returned = c->ip == ret_ip && c->sregs[S_CS] == GAME_CS && d >= 2 && d < 0x8000;
    }
    *cycles = c->cycles - pre.cycles;
    for (uint32_t i = check_log.count; i-- > 0;)
        pc->mem[check_log.addr[i]] = check_log.old[i];
    bool ok = returned && !check_log.overflow;
    *c = pre;
    return ok;
}

/* Interrupts (see the top of the file). A returning native runs with an undo log; if an
 * interrupt would have arrived within its cycles, its memory writes are undone and the call
 * is handed back to the original (step_first), which then runs with interrupts. Port writes
 * (CGA registers, port 61h) are repeated by the original with the same values. Natives nested
 * in one that keeps the log run plain: the outermost one decides, since interrupts are held
 * until it returns. This keeps the timeline the original's: a native that holds interrupts
 * delays the timer handler (which reads and writes the flight state, the sound and ATIS
 * fields and the clock), and a timer tick that falls due while the delayed ones are still
 * being handled is merged into them. */
static CpuWriteLog irq_log;

static void entry_run(Pc *pc, const char *name, void (*body)(Pc *), bool returns)
{
    Cpu8086 *c = &pc->cpu;
    if (cycle_check < 0)
        cycle_check = SDL_getenv("FS1_EDITOR_CYCLE_CHECK") != NULL;
    uint64_t start = c->cycles;
    if (under_verify(pc) || !returns) {
        /* --verify, nested in a native that keeps a log, or a native that does not return */
        body(pc);
    } else if (cycle_check) {
        uint64_t orig = 0;
        bool check = check_original(pc, &orig);
        if (check && log_ready(&check_log))
            c->write_log = &check_log; /* nested natives run plain */
        body(pc);
        c->write_log = NULL;
        if (check && c->cycles - start != orig)
            SDL_Log("cycle-check %s: original %llu native %llu", name, (unsigned long long)orig,
                    (unsigned long long)(c->cycles - start));
    } else if (!pc->csched && log_ready(&irq_log)) {
        Cpu8086 pre = *c;
        c->write_log = &irq_log;
        body(pc);
        c->write_log = NULL;
        if (!irq_log.overflow && irq_due(pc, start, c->cycles - start)) {
            for (uint32_t i = irq_log.count; i-- > 0;)
                pc->mem[irq_log.addr[i]] = irq_log.old[i];
            *c = pre;
            step_first(pc);
        }
    } else {
        body(pc);
    }
    c->cycles -= ENTRY_CYCLES;
}

#define ENTRY_FN(name) \
    static void n_##name(Pc *pc) { entry_run(pc, #name, b_##name, true); }
#define ENTRY_FN_NORET(name) \
    static void n_##name(Pc *pc) { entry_run(pc, #name, b_##name, false); }
ENTRY_FN(row_ptr)
ENTRY_FN(cursor_clear)
ENTRY_FN(first_page)
ENTRY_FN(next_row)
ENTRY_FN(prev_row)
ENTRY_FN(page_text)
ENTRY_FN(draw_page)
ENTRY_FN(field_next)
ENTRY_FN(draw_fields)
ENTRY_FN(read_fields)
ENTRY_FN(commit)
ENTRY_FN(usermode_store)
ENTRY_FN(usermode_recall)
ENTRY_FN(key_accept)
ENTRY_FN(key_up)
ENTRY_FN(key_star)
ENTRY_FN(key_ins)
ENTRY_FN_NORET(key_backspace)
ENTRY_FN_NORET(preset_save)
ENTRY_FN_NORET(preset_load)
ENTRY_FN(capture_state)
ENTRY_FN(speaker_off)
ENTRY_FN(scale_values)
ENTRY_FN(apply_state)
ENTRY_FN(alt_from_editor)
ENTRY_FN(check_master_disk)
ENTRY_FN(scale_wind)

#define ENTRY(nm, o, f) { .name = nm, .seg = GAME_CS, .off = o, .fn = n_##f, .enabled = true, .cycles = ENTRY_CYCLES }

NativeEntry native_editor[] = {
    ENTRY("editor_row_ptr", 0x36F4, row_ptr),
    ENTRY("editor_cursor_clear", 0x36E3, cursor_clear),
    ENTRY("editor_first_page", 0x369F, first_page),
    ENTRY("editor_next_row", 0x368A, next_row),
    ENTRY("editor_prev_row", 0x36C1, prev_row),
    ENTRY("editor_page_text", 0x3909, page_text),
    ENTRY("editor_draw_page", 0x39DB, draw_page),
    ENTRY("editor_field_next", 0x39B2, field_next),
    ENTRY("editor_draw_fields", 0x396F, draw_fields),
    ENTRY("editor_read_fields", 0x39E9, read_fields),
    ENTRY("editor_commit", 0x3916, commit),
    ENTRY("usermode_store", 0x3A4D, usermode_store),
    ENTRY("usermode_recall", 0x3A52, usermode_recall),
    ENTRY("editor_key_accept", 0x374E, key_accept),
    ENTRY("editor_key_up", 0x3740, key_up),
    ENTRY("editor_key_star", 0x37D4, key_star),
    ENTRY("editor_key_ins", 0x37DD, key_ins),
    ENTRY("editor_key_backspace", 0x3756, key_backspace),
    ENTRY("preset_save", 0x379A, preset_save),
    ENTRY("preset_load", 0x37B5, preset_load),
    ENTRY("editor_capture_state", 0x3A96, capture_state),
    ENTRY("speaker_off", 0x3B29, speaker_off),
    ENTRY("editor_scale_values", 0x3C2F, scale_values),
    ENTRY("editor_scale_wind", 0x3C6C, scale_wind),
    ENTRY("editor_apply_state", 0x3B36, apply_state),
    ENTRY("alt_from_editor", 0x3C9F, alt_from_editor),
    { .name = "check_master_disk", .seg = GAME_CS, .off = 0x629C, .fn = n_check_master_disk, .enabled = true,
      .flag_mask = F_CF, .cycles = ENTRY_CYCLES },
    { .name = NULL },
};
