/* Emulated cycles of each original instruction in the 3.14 routines (subphase 3.14), from the
 * cpu8086.c cost model, generated by single-stepping every instruction: address, cost (for a
 * conditional jump or LOOP: when it falls through), cost when the jump is taken (for SAR r,CL:
 * with CL = 3). */
#ifndef FS1_FLIGHT_MOTION_CYCLES_H
#define FS1_FLIGHT_MOTION_CYCLES_H

#include <stdint.h>

typedef struct FmInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} FmInsCost;

static const FmInsCost fm_ins_cost[] = {
    { 0x0625, 17, 17 }, /* mov bl, byte ptr [crash_code] */
    { 0x0629, 5, 5 }, /* or bl, bl */
    { 0x062B, 4, 16 }, /* je loc_0657 */
    { 0x062D, 5, 5 }, /* xor bh, bh */
    { 0x062F, 17, 17 }, /* mov si, word ptr [bx + crash_messages] */
    { 0x0633, 21, 21 }, /* call clear_screen */
    { 0x0636, 21, 21 }, /* call print_str */
    { 0x0639, 4, 4 }, /* mov cx, 0xffff */
    { 0x063C, 72, 72 }, /* mul cl */
    { 0x063E, 72, 72 }, /* mul cl */
    { 0x0640, 72, 72 }, /* mul cl */
    { 0x0642, 5, 17 }, /* loop loc_063C */
    { 0x0644, 21, 21 }, /* call usermode_recall */
    { 0x0647, 21, 21 }, /* call editor_apply_state */
    { 0x064A, 19, 19 }, /* mov byte ptr [crash_code], 0 */
    { 0x064F, 19, 19 }, /* mov byte ptr [gear_down], 0xff */
    { 0x0654, 21, 21 }, /* call sub_0D01 */
    { 0x0657, 20, 20 }, /* ret */
    { 0x0D93, 14, 14 }, /* test byte ptr [on_ground], 0xff */
    { 0x0D98, 4, 16 }, /* je loc_0DA7 */
    { 0x0D9A, 12, 12 }, /* mov ax, word ptr [airspeed] */
    { 0x0D9D, 6, 6 }, /* sub ax, 0x100 */
    { 0x0DA0, 4, 16 }, /* jns loc_0DA4 */
    { 0x0DA2, 5, 5 }, /* xor ax, ax */
    { 0x0DA4, 12, 12 }, /* mov word ptr [airspeed], ax */
    { 0x0DA7, 20, 20 }, /* ret */
    { 0x1906, 19, 19 }, /* mov byte ptr [0x8f6], 1 */
    { 0x190B, 2, 2 }, /* cli */
    { 0x190C, 12, 12 }, /* mov ax, word ptr [pit_accum] */
    { 0x190F, 17, 17 }, /* mov dx, word ptr [tick18] */
    { 0x1913, 2, 2 }, /* sti */
    { 0x1914, 4, 4 }, /* mov bx, ax */
    { 0x1916, 4, 4 }, /* mov cx, dx */
    { 0x1918, 26, 26 }, /* xchg word ptr [0x896], bx */
    { 0x191C, 26, 26 }, /* xchg word ptr [0x898], cx */
    { 0x1920, 5, 5 }, /* sub ax, bx */
    { 0x1922, 5, 5 }, /* sbb dx, cx */
    { 0x1924, 8, 8 }, /* sar dx, 1 */
    { 0x1926, 8, 8 }, /* rcr ax, 1 */
    { 0x1928, 8, 8 }, /* sar dx, 1 */
    { 0x192A, 8, 8 }, /* rcr ax, 1 */
    { 0x192C, 8, 8 }, /* sar dx, 1 */
    { 0x192E, 8, 8 }, /* rcr ax, 1 */
    { 0x1930, 8, 8 }, /* sar dx, 1 */
    { 0x1932, 8, 8 }, /* rcr ax, 1 */
    { 0x1934, 8, 8 }, /* sar dx, 1 */
    { 0x1936, 8, 8 }, /* rcr ax, 1 */
    { 0x1938, 12, 12 }, /* mov word ptr [frame_dt], ax */
    { 0x193B, 12, 12 }, /* mov ax, word ptr [turn_rate] */
    { 0x193E, 17, 17 }, /* mov dx, word ptr [frame_dt] */
    { 0x1942, 130, 130 }, /* imul dx */
    { 0x1944, 8, 8 }, /* shl ax, 1 */
    { 0x1946, 8, 8 }, /* rcl dx, 1 */
    { 0x1948, 18, 18 }, /* add word ptr [heading], dx */
    { 0x194C, 12, 12 }, /* mov ax, word ptr [frame_dt] */
    { 0x194F, 17, 17 }, /* mov dx, word ptr [airspeed] */
    { 0x1953, 130, 130 }, /* imul dx */
    { 0x1955, 8, 8 }, /* shl ax, 1 */
    { 0x1957, 8, 8 }, /* rcl dx, 1 */
    { 0x1959, 18, 18 }, /* mov word ptr [0x86c], dx */
    { 0x195D, 12, 12 }, /* mov ax, word ptr [0x8a2] */
    { 0x1960, 137, 137 }, /* imul word ptr [0x89c] */
    { 0x1964, 4, 4 }, /* mov bx, dx */
    { 0x1966, 18, 18 }, /* add bx, word ptr [heading] */
    { 0x196A, 21, 21 }, /* call sincos */
    { 0x196D, 12, 12 }, /* mov word ptr [0x89e], ax */
    { 0x1970, 18, 18 }, /* mov word ptr [0x846], cx */
    { 0x1974, 12, 12 }, /* mov ax, word ptr [0x840] */
    { 0x1977, 17, 17 }, /* mov dx, word ptr [0x86c] */
    { 0x197B, 130, 130 }, /* imul dx */
    { 0x197D, 8, 8 }, /* shl ax, 1 */
    { 0x197F, 8, 8 }, /* rcl dx, 1 */
    { 0x1981, 18, 18 }, /* mov word ptr [0x842], dx */
    { 0x1985, 12, 12 }, /* mov ax, word ptr [0x89e] */
    { 0x1988, 130, 130 }, /* imul dx */
    { 0x198A, 8, 8 }, /* shl ax, 1 */
    { 0x198C, 8, 8 }, /* rcl dx, 1 */
    { 0x198E, 18, 18 }, /* mov word ptr [0x860], dx */
    { 0x1992, 12, 12 }, /* mov ax, word ptr [0x846] */
    { 0x1995, 17, 17 }, /* mov dx, word ptr [0x842] */
    { 0x1999, 130, 130 }, /* imul dx */
    { 0x199B, 8, 8 }, /* shl ax, 1 */
    { 0x199D, 8, 8 }, /* rcl dx, 1 */
    { 0x199F, 18, 18 }, /* mov word ptr [0x894], dx */
    { 0x19A3, 12, 12 }, /* mov ax, word ptr [0x89a] */
    { 0x19A6, 17, 17 }, /* mov dx, word ptr [0x86c] */
    { 0x19AA, 130, 130 }, /* imul dx */
    { 0x19AC, 8, 8 }, /* shl ax, 1 */
    { 0x19AE, 8, 8 }, /* rcl dx, 1 */
    { 0x19B0, 18, 18 }, /* mov word ptr [0x830], dx */
    { 0x19B4, 12, 12 }, /* mov ax, word ptr [0x890] */
    { 0x19B7, 137, 137 }, /* imul word ptr [0x892] */
    { 0x19BB, 8, 8 }, /* shl ax, 1 */
    { 0x19BD, 8, 8 }, /* rcl dx, 1 */
    { 0x19BF, 18, 18 }, /* mov word ptr [roll_rate], dx */
    { 0x19C3, 12, 12 }, /* mov ax, word ptr [roll_rate] */
    { 0x19C6, 17, 17 }, /* mov dx, word ptr [0x86c] */
    { 0x19CA, 130, 130 }, /* imul dx */
    { 0x19CC, 8, 8 }, /* shl ax, 1 */
    { 0x19CE, 8, 8 }, /* rcl dx, 1 */
    { 0x19D0, 8, 8 }, /* shl ax, 1 */
    { 0x19D2, 8, 8 }, /* rcl dx, 1 */
    { 0x19D4, 18, 18 }, /* add word ptr [bank], dx */
    { 0x19D8, 12, 12 }, /* mov ax, word ptr [0x894] */
    { 0x19DB, 5, 5 }, /* cdq */
    { 0x19DC, 18, 18 }, /* add word ptr [pos_north], ax */
    { 0x19E0, 18, 18 }, /* adc word ptr [pos_north+2], dx */
    { 0x19E4, 12, 12 }, /* mov ax, word ptr [0x860] */
    { 0x19E7, 5, 5 }, /* cdq */
    { 0x19E8, 18, 18 }, /* add word ptr [pos_east], ax */
    { 0x19EC, 18, 18 }, /* adc word ptr [pos_east+2], dx */
    { 0x19F0, 12, 12 }, /* mov ax, word ptr [0x830] */
    { 0x19F3, 5, 5 }, /* cdq */
    { 0x19F4, 18, 18 }, /* add word ptr [altitude], ax */
    { 0x19F8, 18, 18 }, /* adc word ptr [altitude+2], dx */
    { 0x19FC, 4, 16 }, /* jns loc_1A0A */
    { 0x19FE, 5, 5 }, /* xor dx, dx */
    { 0x1A00, 4, 4 }, /* mov ax, 0x300 */
    { 0x1A03, 12, 12 }, /* mov word ptr [altitude], ax */
    { 0x1A06, 18, 18 }, /* mov word ptr [altitude+2], dx */
    { 0x1A0A, 19, 19 }, /* cmp byte ptr [0x8f9], 0 */
    { 0x1A0F, 4, 16 }, /* je loc_1A18 */
    { 0x1A11, 21, 21 }, /* call sub_3C9F */
    { 0x1A14, 12, 12 }, /* dec byte ptr [0x8f9] */
    { 0x1A18, 17, 17 }, /* mov dx, word ptr [angle_of_attack] */
    { 0x1A1C, 137, 137 }, /* imul word ptr [0x8c6] */
    { 0x1A20, 18, 18 }, /* mov word ptr [0x83a], dx */
    { 0x1A24, 4, 4 }, /* mov ax, 0x300 */
    { 0x1A27, 18, 18 }, /* sub ax, word ptr [pitch] */
    { 0x1A2B, 18, 18 }, /* add ax, word ptr [0x83a] */
    { 0x1A2F, 14, 14 }, /* test byte ptr [on_ground], 0xff */
    { 0x1A34, 4, 16 }, /* jne loc_1A3A */
    { 0x1A36, 18, 18 }, /* add ax, word ptr [0x868] */
    { 0x1A3A, 18, 18 }, /* add ax, word ptr [0x88a] */
    { 0x1A3E, 12, 12 }, /* mov word ptr [view_pitch], ax */
    { 0x1A41, 12, 12 }, /* mov ax, word ptr [bank] */
    { 0x1A44, 5, 5 }, /* neg ax */
    { 0x1A46, 12, 12 }, /* mov word ptr [view_bank], ax */
    { 0x1A49, 12, 12 }, /* mov ax, word ptr [heading] */
    { 0x1A4C, 12, 12 }, /* mov word ptr [view_heading], ax */
    { 0x1A4F, 12, 12 }, /* mov ax, word ptr [altitude] */
    { 0x1A52, 17, 17 }, /* mov dl, byte ptr [altitude+2] */
    { 0x1A56, 6, 6 }, /* sub ax, 0x301 */
    { 0x1A59, 6, 6 }, /* sbb dl, 0 */
    { 0x1A5C, 4, 4 }, /* mov al, 0 */
    { 0x1A5E, 4, 16 }, /* jae loc_1A62 */
    { 0x1A60, 5, 5 }, /* dec al */
    { 0x1A62, 12, 12 }, /* mov byte ptr [on_ground], al */
    { 0x1A65, 5, 5 }, /* or al, al */
    { 0x1A67, 4, 16 }, /* je loc_1AD2 */
    { 0x1A69, 5, 5 }, /* xor ax, ax */
    { 0x1A6B, 12, 12 }, /* mov word ptr [bank], ax */
    { 0x1A6E, 12, 12 }, /* mov word ptr [roll_rate], ax */
    { 0x1A71, 14, 14 }, /* test word ptr [pitch], 0xffff */
    { 0x1A77, 4, 16 }, /* jns loc_1A7C */
    { 0x1A79, 12, 12 }, /* mov word ptr [pitch], ax */
    { 0x1A7C, 19, 19 }, /* cmp byte ptr [0x8f9], 0 */
    { 0x1A81, 4, 16 }, /* je loc_1A88 */
    { 0x1A83, 21, 21 }, /* call key_period_brakes */
    { 0x1A86, 17, 17 }, /* jmp loc_1AAC */
    { 0x1A88, 19, 19 }, /* cmp byte ptr [gear_down], 0 */
    { 0x1A8D, 4, 16 }, /* jne loc_1A94 */
    { 0x1A8F, 19, 19 }, /* mov byte ptr [crash_code], 0xa */
    { 0x1A94, 12, 12 }, /* mov al, byte ptr [vertical_speed+1] */
    { 0x1A97, 5, 5 }, /* or al, al */
    { 0x1A99, 4, 16 }, /* jns loc_1AAC */
    { 0x1A9B, 6, 6 }, /* add al, 6 */
    { 0x1A9D, 4, 16 }, /* js loc_1ACC */
    { 0x1A9F, 12, 12 }, /* mov al, byte ptr [view_bank+1] */
    { 0x1AA2, 5, 5 }, /* or al, al */
    { 0x1AA4, 4, 16 }, /* jns loc_1AA8 */
    { 0x1AA6, 5, 5 }, /* neg al */
    { 0x1AA8, 6, 6 }, /* cmp al, 0xa */
    { 0x1AAA, 4, 16 }, /* jns loc_1ACC */
    { 0x1AAC, 12, 12 }, /* mov al, byte ptr [on_ground] */
    { 0x1AAF, 18, 18 }, /* cmp al, byte ptr [0x86e] */
    { 0x1AB3, 12, 12 }, /* mov byte ptr [0x86e], al */
    { 0x1AB6, 4, 4 }, /* mov ax, 0 */
    { 0x1AB9, 4, 16 }, /* je loc_1AC6 */
    { 0x1ABB, 19, 19 }, /* mov byte ptr [sound_state], 8 */
    { 0x1AC0, 17, 17 }, /* mov ah, byte ptr [vertical_speed+1] */
    { 0x1AC4, 8, 8 }, /* shl ax, 1 */
    { 0x1AC6, 12, 12 }, /* mov word ptr [0x88a], ax */
    { 0x1AC9, 17, 17 }, /* jmp loc_1AF6 */
    { 0x1ACC, 19, 19 }, /* mov byte ptr [crash_code], 4 */
    { 0x1AD1, 20, 20 }, /* ret */
    { 0x1AD2, 19, 19 }, /* cmp byte ptr [0x86e], 0 */
    { 0x1AD7, 4, 16 }, /* je loc_1AF5 */
    { 0x1AD9, 5, 5 }, /* xor ax, ax */
    { 0x1ADB, 12, 12 }, /* mov word ptr [0x88a], ax */
    { 0x1ADE, 12, 12 }, /* mov byte ptr [0x86e], al */
    { 0x1AE1, 12, 12 }, /* mov ax, word ptr [pos_north+1] */
    { 0x1AE4, 4, 4 }, /* test al, 7 */
    { 0x1AE6, 4, 16 }, /* jne loc_1AF5 */
    { 0x1AE8, 18, 18 }, /* add ax, word ptr [pos_east+1] */
    { 0x1AEC, 6, 6 }, /* and ax, 0xff */
    { 0x1AEF, 6, 6 }, /* sub ax, 0x80 */
    { 0x1AF2, 12, 12 }, /* mov word ptr [0x1e22], ax */
    { 0x1AF5, 20, 20 }, /* ret */
    { 0x1AF6, 20, 20 }, /* ret */
    { 0x1AF7, 14, 14 }, /* test byte ptr [slew_mode], 0xff */
    { 0x1AFC, 4, 16 }, /* je loc_1AFF */
    { 0x1AFE, 20, 20 }, /* ret */
    { 0x1AFF, 12, 12 }, /* mov ax, word ptr [0x900] */
    { 0x1B02, 4, 4 }, /* mov cx, ax */
    { 0x1B04, 8, 8 }, /* shl ax, 1 */
    { 0x1B06, 8, 8 }, /* shl ax, 1 */
    { 0x1B08, 5, 5 }, /* add ax, cx */
    { 0x1B0A, 5, 5 }, /* neg ax */
    { 0x1B0C, 6, 6 }, /* add ax, 0x7fff */
    { 0x1B0F, 12, 12 }, /* mov word ptr [air_density], ax */
    { 0x1B12, 12, 12 }, /* mov ax, word ptr [0x8ee] */
    { 0x1B15, 18, 18 }, /* add ax, word ptr [0x8b6] */
    { 0x1B19, 12, 12 }, /* mov word ptr [weight], ax */
    { 0x1B1C, 17, 17 }, /* mov dx, word ptr [0x8c0] */
    { 0x1B20, 5, 5 }, /* xor ax, ax */
    { 0x1B22, 17, 17 }, /* mov cx, word ptr [weight] */
    { 0x1B26, 21, 21 }, /* call div_q15 */
    { 0x1B29, 18, 18 }, /* mov word ptr [inv_mass], dx */
    { 0x1B2D, 17, 17 }, /* mov dx, word ptr [0x8c2] */
    { 0x1B31, 5, 5 }, /* xor ax, ax */
    { 0x1B33, 17, 17 }, /* mov cx, word ptr [weight] */
    { 0x1B37, 21, 21 }, /* call div_q15 */
    { 0x1B3A, 18, 18 }, /* mov word ptr [0x88e], dx */
    { 0x1B3E, 17, 17 }, /* mov dx, word ptr [0x8c4] */
    { 0x1B42, 5, 5 }, /* xor ax, ax */
    { 0x1B44, 17, 17 }, /* mov cx, word ptr [weight] */
    { 0x1B48, 21, 21 }, /* call div_q15 */
    { 0x1B4B, 18, 18 }, /* mov word ptr [0x890], dx */
    { 0x1B4F, 12, 12 }, /* mov ax, word ptr [airspeed] */
    { 0x1B52, 17, 17 }, /* mov dx, word ptr [0x89a] */
    { 0x1B56, 130, 130 }, /* imul dx */
    { 0x1B58, 8, 8 }, /* shl ax, 1 */
    { 0x1B5A, 8, 8 }, /* rcl dx, 1 */
    { 0x1B5C, 18, 18 }, /* mov word ptr [vertical_speed], dx */
    { 0x1B60, 14, 14 }, /* test byte ptr [rudder+1], 0xff */
    { 0x1B65, 4, 16 }, /* jne loc_1B84 */
    { 0x1B67, 12, 12 }, /* mov ax, word ptr [bank] */
    { 0x1B6A, 5, 5 }, /* or ax, ax */
    { 0x1B6C, 4, 16 }, /* je loc_1B84 */
    { 0x1B6E, 4, 16 }, /* js loc_1B79 */
    { 0x1B70, 18, 18 }, /* add ax, word ptr [0x8d8] */
    { 0x1B74, 4, 16 }, /* js loc_1B7F */
    { 0x1B76, 17, 17 }, /* jmp loc_1B81 */
    { 0x1B79, 18, 18 }, /* add ax, word ptr [0x8d6] */
    { 0x1B7D, 4, 16 }, /* js loc_1B81 */
    { 0x1B7F, 5, 5 }, /* xor ax, ax */
    { 0x1B81, 12, 12 }, /* mov word ptr [bank], ax */
    { 0x1B84, 19, 19 }, /* cmp byte ptr [0x406], 0 */
    { 0x1B89, 4, 16 }, /* je loc_1BAF */
    { 0x1B8B, 19, 19 }, /* cmp word ptr [airspeed], 0 */
    { 0x1B90, 4, 16 }, /* jne loc_1BAA */
    { 0x1B92, 21, 21 }, /* call sub_1BB0 */
    { 0x1B95, 19, 19 }, /* cmp byte ptr [0x406], 2 */
    { 0x1B9A, 4, 16 }, /* jne loc_1BAA */
    { 0x1B9C, 19, 19 }, /* mov word ptr [ammo], 0x65 */
    { 0x1BA2, 21, 21 }, /* call war_ammo_dec */
    { 0x1BA5, 19, 19 }, /* mov byte ptr [bombs_left], 0x35 */
    { 0x1BAA, 19, 19 }, /* mov byte ptr [0x406], 0 */
    { 0x1BAF, 20, 20 }, /* ret */
    { 0x1BB0, 19, 19 }, /* mov byte ptr [0x1dd4], 1 */
    { 0x1BB5, 19, 19 }, /* mov byte ptr [0x1dd5], 1 */
    { 0x1BBA, 19, 19 }, /* mov byte ptr [0x1dce], 0x23 */
    { 0x1BBF, 19, 19 }, /* mov byte ptr [0x1dd1], 0x23 */
    { 0x1BC4, 19, 19 }, /* mov word ptr [0x19a0], 0xffff */
    { 0x1BCA, 19, 19 }, /* mov word ptr [0x41b], 0xffff */
    { 0x1BD0, 19, 19 }, /* mov byte ptr [0x1e5c], 0 */
    { 0x1BD5, 19, 19 }, /* mov byte ptr [0x1dc8], 0 */
    { 0x1BDA, 19, 19 }, /* mov word ptr [0x1dc4], 3 */
    { 0x1BE0, 4, 4 }, /* mov bx, 0x91 */
    { 0x1BE3, 19, 19 }, /* mov byte ptr [bx + enemy_table+25], 1 */
    { 0x1BE8, 6, 6 }, /* sub bx, 0x1d */
    { 0x1BEB, 4, 16 }, /* jns loc_1BE3 */
    { 0x1BED, 20, 20 }, /* ret */
    { 0x1C35, 14, 14 }, /* test byte ptr [0x8f6], 0xff */
    { 0x1C3A, 4, 16 }, /* je loc_1C52 */
    { 0x1C3C, 5, 5 }, /* xor ax, ax */
    { 0x1C3E, 12, 12 }, /* mov byte ptr [0x8f6], al */
    { 0x1C41, 12, 12 }, /* mov word ptr [elevator], ax */
    { 0x1C44, 12, 12 }, /* mov word ptr [rudder], ax */
    { 0x1C47, 12, 12 }, /* mov word ptr [aileron], ax */
    { 0x1C4A, 4, 4 }, /* mov ah, 0x40 */
    { 0x1C4C, 12, 12 }, /* mov word ptr [flaps], ax */
    { 0x1C4F, 12, 12 }, /* mov word ptr [throttle_target], ax */
    { 0x1C52, 12, 12 }, /* mov ax, word ptr [aileron] */
    { 0x1C55, 21, 21 }, /* call sub_1CFF */
    { 0x1C58, 18, 18 }, /* add word ptr [pos_east+1], ax */
    { 0x1C5C, 18, 18 }, /* adc byte ptr [pos_east+3], dl */
    { 0x1C60, 12, 12 }, /* mov ax, word ptr [elevator] */
    { 0x1C63, 21, 21 }, /* call sub_1CFF */
    { 0x1C66, 18, 18 }, /* sub word ptr [pos_north+1], ax */
    { 0x1C6A, 18, 18 }, /* sbb byte ptr [pos_north+3], dl */
    { 0x1C6E, 12, 12 }, /* mov ax, word ptr [throttle_target] */
    { 0x1C71, 6, 6 }, /* sub ah, 0x40 */
    { 0x1C74, 8, 8 }, /* sar ax, 1 */
    { 0x1C76, 8, 8 }, /* sar ax, 1 */
    { 0x1C78, 5, 5 }, /* cdq */
    { 0x1C79, 18, 18 }, /* sub word ptr [altitude], ax */
    { 0x1C7D, 18, 18 }, /* sbb word ptr [altitude+2], dx */
    { 0x1C81, 4, 16 }, /* jns loc_1C8F */
    { 0x1C83, 19, 19 }, /* mov word ptr [altitude], 0 */
    { 0x1C89, 19, 19 }, /* mov word ptr [altitude+2], 0 */
    { 0x1C8F, 19, 19 }, /* cmp word ptr [altitude+2], 0x2f */
    { 0x1C94, 4, 16 }, /* jl loc_1CA2 */
    { 0x1C96, 19, 19 }, /* mov word ptr [altitude], 0xffff */
    { 0x1C9C, 19, 19 }, /* mov word ptr [altitude+2], 0x2e */
    { 0x1CA2, 12, 12 }, /* mov al, byte ptr [flaps+1] */
    { 0x1CA5, 6, 6 }, /* sub al, 0x40 */
    { 0x1CA7, 2, 2 }, /* cwde */
    { 0x1CA8, 8, 8 }, /* shl ax, 1 */
    { 0x1CAA, 8, 8 }, /* shl ax, 1 */
    { 0x1CAC, 17, 17 }, /* mov bx, word ptr [view_bank] */
    { 0x1CB0, 6, 6 }, /* add bx, 0x4000 */
    { 0x1CB4, 4, 16 }, /* jns loc_1CB8 */
    { 0x1CB6, 5, 5 }, /* neg ax */
    { 0x1CB8, 18, 18 }, /* add ax, word ptr [view_pitch] */
    { 0x1CBC, 4, 16 }, /* js loc_1CC5 */
    { 0x1CBE, 6, 6 }, /* cmp ax, 0x4000 */
    { 0x1CC1, 4, 16 }, /* jle loc_1CDB */
    { 0x1CC3, 17, 17 }, /* jmp loc_1CCA */
    { 0x1CC5, 6, 6 }, /* cmp ax, 0xc000 */
    { 0x1CC8, 4, 16 }, /* jge loc_1CDB */
    { 0x1CCA, 5, 5 }, /* neg ax */
    { 0x1CCC, 6, 6 }, /* add ax, 0x8000 */
    { 0x1CCF, 19, 19 }, /* add word ptr [view_bank], 0x8000 */
    { 0x1CD5, 19, 19 }, /* add word ptr [view_heading], 0x8000 */
    { 0x1CDB, 12, 12 }, /* mov word ptr [view_pitch], ax */
    { 0x1CDE, 12, 12 }, /* mov ax, word ptr [slew_rate_a] */
    { 0x1CE1, 18, 18 }, /* add word ptr [view_bank], ax */
    { 0x1CE5, 12, 12 }, /* mov ax, word ptr [slew_rate_b] */
    { 0x1CE8, 18, 18 }, /* sub word ptr [view_heading], ax */
    { 0x1CEC, 12, 12 }, /* mov ax, word ptr [pos_north+2] */
    { 0x1CEF, 6, 6 }, /* add ax, 0x4000 */
    { 0x1CF2, 12, 12 }, /* mov word ptr [0x2050], ax */
    { 0x1CF5, 12, 12 }, /* mov ax, word ptr [pos_east+2] */
    { 0x1CF8, 6, 6 }, /* add ax, 0x4000 */
    { 0x1CFB, 12, 12 }, /* mov word ptr [0x2052], ax */
    { 0x1CFE, 20, 20 }, /* ret */
    { 0x1CFF, 4, 4 }, /* mov cl, 3 */
    { 0x1D01, 8, 16 }, /* sar ax, cl */
    { 0x1D03, 5, 5 }, /* cdq */
    { 0x1D04, 4, 16 }, /* jns loc_1D08 */
    { 0x1D06, 5, 5 }, /* neg ah */
    { 0x1D08, 2, 2 }, /* stc */
    { 0x1D09, 5, 5 }, /* dec ah */
    { 0x1D0B, 4, 16 }, /* jns loc_1D11 */
    { 0x1D0D, 4, 4 }, /* mov ax, dx */
    { 0x1D0F, 5, 5 }, /* cdq */
    { 0x1D10, 20, 20 }, /* ret */
    { 0x1D11, 8, 8 }, /* rcl dx, 1 */
    { 0x1D13, 2, 2 }, /* cmc */
    { 0x1D14, 17, 17 }, /* jmp loc_1D09 */
    { 0x2D00, 19, 19 }, /* cmp byte ptr [war_mode], 1 */
    { 0x2D05, 4, 16 }, /* je loc_2D2E */
    { 0x2D07, 19, 19 }, /* cmp byte ptr [0x204c], 0 */
    { 0x2D0C, 4, 16 }, /* je loc_2D37 */
    { 0x2D0E, 19, 19 }, /* cmp byte ptr [magnetos], 5 */
    { 0x2D13, 4, 16 }, /* je loc_2D29 */
    { 0x2D15, 12, 12 }, /* mov al, byte ptr [0x1dd2] */
    { 0x2D18, 18, 18 }, /* and al, byte ptr [0x1dd4] */
    { 0x2D1C, 4, 4 }, /* mov ah, al */
    { 0x2D1E, 12, 12 }, /* mov al, byte ptr [0x1dd3] */
    { 0x2D21, 18, 18 }, /* and al, byte ptr [0x1dd5] */
    { 0x2D25, 5, 5 }, /* or al, ah */
    { 0x2D27, 4, 16 }, /* jne loc_2D2E */
    { 0x2D29, 21, 21 }, /* call sub_2EDB */
    { 0x2D2C, 17, 17 }, /* jmp loc_2D7B */
    { 0x2D2E, 12, 12 }, /* mov al, byte ptr [0x1dce] */
    { 0x2D31, 18, 18 }, /* or al, byte ptr [0x1dd1] */
    { 0x2D35, 4, 16 }, /* je loc_2D29 */
    { 0x2D37, 12, 12 }, /* mov al, byte ptr [0x204c] */
    { 0x2D3A, 18, 18 }, /* or al, byte ptr [0x1dd8] */
    { 0x2D3E, 4, 16 }, /* je loc_2D70 */
    { 0x2D40, 19, 19 }, /* cmp byte ptr [0x1dd8], 0 */
    { 0x2D45, 4, 16 }, /* jne loc_2D7B */
    { 0x2D47, 19, 19 }, /* cmp word ptr [0x902], 0x4b */
    { 0x2D4C, 4, 16 }, /* jg loc_2D70 */
    { 0x2D4E, 19, 19 }, /* cmp byte ptr [magnetos], 4 */
    { 0x2D53, 4, 16 }, /* jne loc_2D7B */
    { 0x2D55, 4, 4 }, /* mov cx, 0xfde8 */
    { 0x2D58, 72, 72 }, /* mul al */
    { 0x2D5A, 5, 17 }, /* loop loc_2D58 */
    { 0x2D5C, 4, 4 }, /* mov ah, 3 */
    { 0x2D5E, 21, 21 }, /* call sub_0A19 */
    { 0x2D61, 19, 19 }, /* cmp byte ptr [0x206a], 1 */
    { 0x2D66, 4, 16 }, /* jne loc_2D70 */
    { 0x2D68, 14, 14 }, /* test word ptr [frame_counter], 4 */
    { 0x2D6E, 4, 16 }, /* je loc_2D7B */
    { 0x2D70, 19, 19 }, /* mov byte ptr [0x1dd8], 1 */
    { 0x2D75, 19, 19 }, /* mov word ptr [0x1dd6], 0xa140 */
    { 0x2D7B, 17, 17 }, /* mov bx, word ptr [0x902] */
    { 0x2D7F, 8, 8 }, /* sar bx, 1 */
    { 0x2D81, 8, 8 }, /* sar bx, 1 */
    { 0x2D83, 8, 8 }, /* sar bx, 1 */
    { 0x2D85, 8, 8 }, /* sar bx, 1 */
    { 0x2D87, 6, 6 }, /* cmp bx, 0x1f */
    { 0x2D8A, 4, 16 }, /* jle loc_2D8F */
    { 0x2D8C, 4, 4 }, /* mov bx, 0x1f */
    { 0x2D8F, 17, 17 }, /* mov cl, byte ptr [bx + 0x1dfd] */
    { 0x2D93, 17, 17 }, /* mov bx, word ptr [throttle] */
    { 0x2D97, 14, 14 }, /* test byte ptr [0x1dd8], 0xff */
    { 0x2D9C, 4, 16 }, /* je loc_2DBA */
    { 0x2D9E, 19, 19 }, /* cmp byte ptr [carb_heat], 0 */
    { 0x2DA3, 4, 16 }, /* je loc_2DBC */
    { 0x2DA5, 4, 4 }, /* mov cx, 0x800 */
    { 0x2DA8, 19, 19 }, /* cmp byte ptr [0x1dca], 0 */
    { 0x2DAD, 4, 16 }, /* je loc_2DB6 */
    { 0x2DAF, 4, 4 }, /* mov cx, 0x2000 */
    { 0x2DB2, 12, 12 }, /* dec byte ptr [0x1dca] */
    { 0x2DB6, 5, 5 }, /* sub bx, cx */
    { 0x2DB8, 4, 16 }, /* jns loc_2DBC */
    { 0x2DBA, 5, 5 }, /* xor bx, bx */
    { 0x2DBC, 14, 14 }, /* test byte ptr [0x1dc8], 3 */
    { 0x2DC1, 4, 16 }, /* je loc_2DC7 */
    { 0x2DC3, 6, 6 }, /* and bx, 0xfff */
    { 0x2DC7, 12, 12 }, /* mov al, byte ptr [0x1dd2] */
    { 0x2DCA, 18, 18 }, /* and al, byte ptr [0x1dd4] */
    { 0x2DCE, 4, 16 }, /* je loc_2DD9 */
    { 0x2DD0, 12, 12 }, /* mov al, byte ptr [0x1dd3] */
    { 0x2DD3, 18, 18 }, /* and al, byte ptr [0x1dd5] */
    { 0x2DD7, 4, 16 }, /* jne loc_2DE1 */
    { 0x2DD9, 6, 6 }, /* sub bx, 0x400 */
    { 0x2DDD, 4, 16 }, /* jns loc_2DE1 */
    { 0x2DDF, 5, 5 }, /* xor bx, bx */
    { 0x2DE1, 18, 18 }, /* mov word ptr [0x1dc2], bx */
    { 0x2DE5, 12, 12 }, /* mov ax, word ptr [0x8e0] */
    { 0x2DE8, 130, 130 }, /* imul bx */
    { 0x2DEA, 18, 18 }, /* mov word ptr [thrust], dx */
    { 0x2DEE, 4, 4 }, /* mov bl, bh */
    { 0x2DF0, 5, 5 }, /* xor bh, bh */
    { 0x2DF2, 8, 8 }, /* sar bl, 1 */
    { 0x2DF4, 8, 8 }, /* sar bl, 1 */
    { 0x2DF6, 17, 17 }, /* mov ch, byte ptr [bx + 0x1ddd] */
    { 0x2DFA, 19, 19 }, /* cmp byte ptr [0x1dd8], 0 */
    { 0x2DFF, 4, 16 }, /* jne loc_2E03 */
    { 0x2E01, 4, 4 }, /* mov ch, 5 */
    { 0x2E03, 5, 5 }, /* cmp ch, cl */
    { 0x2E05, 4, 16 }, /* jge loc_2E14 */
    { 0x2E07, 18, 18 }, /* mov byte ptr [0x1dc1], cl */
    { 0x2E0B, 5, 5 }, /* sub cl, ch */
    { 0x2E0D, 18, 18 }, /* mov byte ptr [0x1dcb], cl */
    { 0x2E11, 17, 17 }, /* jmp loc_2E1D */
    { 0x2E14, 18, 18 }, /* mov byte ptr [0x1dc1], ch */
    { 0x2E18, 19, 19 }, /* mov byte ptr [0x1dcb], 0 */
    { 0x2E1D, 4, 4 }, /* mov al, 0x64 */
    { 0x2E1F, 19, 19 }, /* cmp byte ptr [0x1dd8], 0 */
    { 0x2E24, 4, 16 }, /* je loc_2E3D */
    { 0x2E26, 4, 4 }, /* mov al, 0xaf */
    { 0x2E28, 19, 19 }, /* mov word ptr [0x1dc4], 7 */
    { 0x2E2E, 14, 14 }, /* test byte ptr [0x1dc8], 1 */
    { 0x2E33, 4, 16 }, /* je loc_2E3D */
    { 0x2E35, 4, 4 }, /* mov al, 0xef */
    { 0x2E37, 19, 19 }, /* mov word ptr [0x1dc4], 0x19 */
    { 0x2E3D, 5, 5 }, /* xor ah, ah */
    { 0x2E3F, 8, 8 }, /* shl ax, 1 */
    { 0x2E41, 8, 8 }, /* shl ax, 1 */
    { 0x2E43, 8, 8 }, /* shl ax, 1 */
    { 0x2E45, 8, 8 }, /* shl ax, 1 */
    { 0x2E47, 8, 8 }, /* shl ax, 1 */
    { 0x2E49, 8, 8 }, /* shl ax, 1 */
    { 0x2E4B, 6, 6 }, /* sub ax, 0x1900 */
    { 0x2E4E, 18, 18 }, /* cmp ax, word ptr [0x1dd9] */
    { 0x2E52, 12, 12 }, /* mov ax, word ptr [0x1dc4] */
    { 0x2E55, 4, 16 }, /* jg loc_2E5E */
    { 0x2E57, 18, 18 }, /* sub word ptr [0x1dd9], ax */
    { 0x2E5B, 17, 17 }, /* jmp loc_2E62 */
    { 0x2E5E, 18, 18 }, /* add word ptr [0x1dd9], ax */
    { 0x2E62, 4, 4 }, /* mov al, 0 */
    { 0x2E64, 19, 19 }, /* cmp byte ptr [0x1dd8], 0 */
    { 0x2E69, 4, 16 }, /* je loc_2E74 */
    { 0x2E6B, 14, 14 }, /* test byte ptr [0x1dc8], 2 */
    { 0x2E70, 4, 16 }, /* jne loc_2E74 */
    { 0x2E72, 4, 4 }, /* mov al, 0x32 */
    { 0x2E74, 4, 4 }, /* mov dl, 0x59 */
    { 0x2E76, 72, 72 }, /* mul dl */
    { 0x2E78, 18, 18 }, /* cmp ax, word ptr [0x1ddb] */
    { 0x2E7C, 12, 12 }, /* mov ax, word ptr [0x1dc6] */
    { 0x2E7F, 4, 16 }, /* jg loc_2E88 */
    { 0x2E81, 18, 18 }, /* sub word ptr [0x1ddb], ax */
    { 0x2E85, 17, 17 }, /* jmp loc_2E8C */
    { 0x2E88, 18, 18 }, /* add word ptr [0x1ddb], ax */
    { 0x2E8C, 19, 19 }, /* cmp byte ptr [0x1dd8], 0 */
    { 0x2E91, 4, 16 }, /* je loc_2EDA */
    { 0x2E93, 12, 12 }, /* mov al, byte ptr [0x1dc9] */
    { 0x2E96, 19, 19 }, /* cmp byte ptr [war_mode], 0 */
    { 0x2E9B, 4, 16 }, /* je loc_2EA1 */
    { 0x2E9D, 8, 8 }, /* shl ax, 1 */
    { 0x2E9F, 8, 8 }, /* shl ax, 1 */
    { 0x2EA1, 89, 89 }, /* imul byte ptr [throttle+1] */
    { 0x2EA5, 5, 5 }, /* cdq */
    { 0x2EA6, 14, 14 }, /* test byte ptr [0x1dc8], 4 */
    { 0x2EAB, 4, 16 }, /* je loc_2EB1 */
    { 0x2EAD, 12, 12 }, /* dec byte ptr [0x1dce] */
    { 0x2EB1, 18, 18 }, /* add word ptr [0x1dcc], ax */
    { 0x2EB5, 18, 18 }, /* adc byte ptr [0x1dce], dl */
    { 0x2EB9, 4, 16 }, /* jns loc_2EC0 */
    { 0x2EBB, 19, 19 }, /* mov byte ptr [0x1dce], 0 */
    { 0x2EC0, 14, 14 }, /* test byte ptr [0x1dc8], 8 */
    { 0x2EC5, 4, 16 }, /* je loc_2ECB */
    { 0x2EC7, 12, 12 }, /* dec byte ptr [0x1dd1] */
    { 0x2ECB, 18, 18 }, /* add word ptr [0x1dcf], ax */
    { 0x2ECF, 18, 18 }, /* adc byte ptr [0x1dd1], dl */
    { 0x2ED3, 4, 16 }, /* jns loc_2EDA */
    { 0x2ED5, 19, 19 }, /* mov byte ptr [0x1dd1], 0 */
    { 0x2EDA, 20, 20 }, /* ret */
    { 0x2EDB, 19, 19 }, /* mov word ptr [0x1dd6], 0 */
    { 0x2EE1, 19, 19 }, /* mov byte ptr [0x1dcb], 0 */
    { 0x2EE6, 19, 19 }, /* mov byte ptr [0x1dd8], 0 */
    { 0x2EEB, 20, 20 }, /* ret */
    { 0x2F10, 19, 19 }, /* cmp byte ptr [on_ground], 0 */
    { 0x2F15, 4, 16 }, /* jne loc_2F55 */
    { 0x2F17, 12, 12 }, /* mov ax, word ptr [wind_dx] */
    { 0x2F1A, 5, 5 }, /* cdq */
    { 0x2F1B, 18, 18 }, /* sub word ptr [pos_east], ax */
    { 0x2F1F, 18, 18 }, /* sbb word ptr [pos_east+2], dx */
    { 0x2F23, 12, 12 }, /* mov ax, word ptr [wind_dy] */
    { 0x2F26, 5, 5 }, /* cdq */
    { 0x2F27, 18, 18 }, /* sub word ptr [pos_north], ax */
    { 0x2F2B, 18, 18 }, /* sbb word ptr [pos_north+2], dx */
    { 0x2F2F, 12, 12 }, /* mov al, byte ptr [pos_north] */
    { 0x2F32, 18, 18 }, /* add al, byte ptr [frame_counter] */
    { 0x2F36, 89, 89 }, /* imul byte ptr [0x1e26] */
    { 0x2F3A, 18, 18 }, /* add word ptr [bank], ax */
    { 0x2F3E, 19, 19 }, /* cmp byte ptr [0x1e26], 5 */
    { 0x2F43, 4, 16 }, /* jle loc_2F55 */
    { 0x2F45, 14, 14 }, /* test word ptr [frame_counter], 0x3f */
    { 0x2F4B, 4, 16 }, /* jne loc_2F55 */
    { 0x2F4D, 8, 8 }, /* sar ax, 1 */
    { 0x2F4F, 8, 8 }, /* sar ax, 1 */
    { 0x2F51, 18, 18 }, /* add word ptr [pitch], ax */
    { 0x2F55, 20, 20 }, /* ret */
    { 0x2F56, 12, 12 }, /* mov ax, word ptr [altitude+1] */
    { 0x2F59, 18, 18 }, /* cmp ax, word ptr [0x2073] */
    { 0x2F5D, 4, 16 }, /* jle loc_2F8C */
    { 0x2F5F, 18, 18 }, /* cmp ax, word ptr [0x2075] */
    { 0x2F63, 4, 16 }, /* jle loc_2F81 */
    { 0x2F65, 18, 18 }, /* cmp ax, word ptr [0x2077] */
    { 0x2F69, 4, 16 }, /* jle loc_2F76 */
    { 0x2F6B, 17, 17 }, /* mov bx, word ptr [0x207b] */
    { 0x2F6F, 17, 17 }, /* mov cx, word ptr [0x2079] */
    { 0x2F73, 17, 17 }, /* jmp loc_2F98 */
    { 0x2F76, 17, 17 }, /* mov bx, word ptr [0x207f] */
    { 0x2F7A, 17, 17 }, /* mov cx, word ptr [0x207d] */
    { 0x2F7E, 17, 17 }, /* jmp loc_2F98 */
    { 0x2F81, 17, 17 }, /* mov bx, word ptr [0x2083] */
    { 0x2F85, 17, 17 }, /* mov cx, word ptr [0x2081] */
    { 0x2F89, 17, 17 }, /* jmp loc_2F98 */
    { 0x2F8C, 17, 17 }, /* mov bx, word ptr [0x2087] */
    { 0x2F90, 17, 17 }, /* mov cx, word ptr [0x2085] */
    { 0x2F94, 12, 12 }, /* inc byte ptr [0x1e2b] */
    { 0x2F98, 15, 15 }, /* push cx */
    { 0x2F99, 18, 18 }, /* add bx, word ptr [0x915] */
    { 0x2F9D, 15, 15 }, /* shr byte ptr [0x1e2b], 1 */
    { 0x2FA1, 4, 16 }, /* jae loc_2FA7 */
    { 0x2FA3, 18, 18 }, /* add bx, word ptr [0x917] */
    { 0x2FA7, 21, 21 }, /* call sincos */
    { 0x2FAA, 12, 12 }, /* pop bx */
    { 0x2FAB, 18, 18 }, /* mov byte ptr [0x1e26], bh */
    { 0x2FAF, 4, 4 }, /* mov al, ah */
    { 0x2FB1, 82, 82 }, /* imul bl */
    { 0x2FB3, 137, 137 }, /* imul word ptr [frame_dt] */
    { 0x2FB7, 8, 8 }, /* shl ax, 1 */
    { 0x2FB9, 8, 8 }, /* rcl dx, 1 */
    { 0x2FBB, 18, 18 }, /* mov word ptr [wind_dx], dx */
    { 0x2FBF, 4, 4 }, /* mov al, ch */
    { 0x2FC1, 82, 82 }, /* imul bl */
    { 0x2FC3, 137, 137 }, /* imul word ptr [frame_dt] */
    { 0x2FC7, 8, 8 }, /* shl ax, 1 */
    { 0x2FC9, 8, 8 }, /* rcl dx, 1 */
    { 0x2FCB, 18, 18 }, /* mov word ptr [wind_dy], dx */
    { 0x2FCF, 20, 20 }, /* ret */
    { 0x3555, 5, 5 }, /* cdq */
    { 0x3556, 4, 4 }, /* mov cx, 0x3e8 */
    { 0x3559, 146, 146 }, /* div cx */
    { 0x355B, 4, 4 }, /* mov cl, al */
    { 0x355D, 4, 4 }, /* mov ax, dx */
    { 0x355F, 5, 5 }, /* cdq */
    { 0x3560, 4, 4 }, /* mov bp, 0x64 */
    { 0x3563, 146, 146 }, /* div bp */
    { 0x3565, 4, 4 }, /* mov ch, al */
    { 0x3567, 4, 4 }, /* mov ax, dx */
    { 0x3569, 85, 85 }, /* aam 0xa */
    { 0x356B, 6, 6 }, /* add ax, 0x3030 */
    { 0x356E, 6, 6 }, /* add cx, 0x3030 */
    { 0x3572, 6, 6 }, /* xchg al, ah */
    { 0x3574, 20, 20 }, /* ret */
    { 0x3575, 15, 15 }, /* push cx */
    { 0x3576, 15, 15 }, /* push bp */
    { 0x3577, 15, 15 }, /* push dx */
    { 0x3578, 18, 18 }, /* add ax, word ptr [0x1e57] */
    { 0x357C, 6, 6 }, /* cmp ax, 0x2710 */
    { 0x357F, 4, 16 }, /* jle loc_3584 */
    { 0x3581, 6, 6 }, /* sub ax, 0x2710 */
    { 0x3584, 12, 12 }, /* mov word ptr [0x1e57], ax */
    { 0x3587, 21, 21 }, /* call sub_3555 */
    { 0x358A, 18, 18 }, /* mov word ptr [0x1ec5], cx */
    { 0x358E, 12, 12 }, /* mov word ptr [0x1ec7], ax */
    { 0x3591, 12, 12 }, /* pop dx */
    { 0x3592, 12, 12 }, /* pop bp */
    { 0x3593, 12, 12 }, /* pop cx */
    { 0x3594, 20, 20 }, /* ret */
    { 0x3595, 12, 12 }, /* mov ax, word ptr [ammo] */
    { 0x3598, 2, 2 }, /* dec ax */
    { 0x3599, 4, 16 }, /* jns loc_359D */
    { 0x359B, 5, 5 }, /* xor ax, ax */
    { 0x359D, 12, 12 }, /* mov word ptr [ammo], ax */
    { 0x35A0, 21, 21 }, /* call sub_3555 */
    { 0x35A3, 12, 12 }, /* mov word ptr [0x1ed4], ax */
    { 0x35A6, 18, 18 }, /* mov byte ptr [0x1ed3], ch */
    { 0x35AA, 20, 20 }, /* ret */
    { 0x3C9F, 4, 4 }, /* mov cx, 0x4e0c */
    { 0x3CA2, 12, 12 }, /* mov ax, word ptr [0x2054] */
    { 0x3CA5, 6, 6 }, /* add ax, 9 */
    { 0x3CA8, 120, 120 }, /* mul cx */
    { 0x3CAA, 18, 18 }, /* sub dx, word ptr [0x906] */
    { 0x3CAE, 6, 6 }, /* cmp dx, 3 */
    { 0x3CB1, 4, 16 }, /* jge loc_3CB6 */
    { 0x3CB3, 4, 4 }, /* mov dx, 3 */
    { 0x3CB6, 18, 18 }, /* mov word ptr [altitude+1], dx */
    { 0x3CBA, 19, 19 }, /* mov byte ptr [altitude], 0 */
    { 0x3CBF, 20, 20 }, /* ret */
};

#endif
