/* Emulated cycles of each original instruction in the subphase 3.18 routines (0050:0955-10B6),
 * from the cpu8086.c cost model; generated by tools/gen_keys_cycles.py (do not edit): address,
 * cost (for a conditional jump: when it falls through), cost when it jumps. */
#ifndef FS1_KEYS_CYCLES_H
#define FS1_KEYS_CYCLES_H

#include <stdint.h>

typedef struct KeyInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} KeyInsCost;

static const KeyInsCost key_ins_cost[] = {
    { 0x0955, 21, 21 }, /* call key_ignore */
    { 0x0958, 21, 21 }, /* call sub_0F25 */
    { 0x095B, 21, 21 }, /* call set_flaps */
    { 0x095E, 21, 21 }, /* call sub_0E6A */
    { 0x0961, 21, 21 }, /* call sub_0F8A */
    { 0x0964, 20, 20 }, /* ret */
    { 0x0970, 15, 15 }, /* push ax */
    { 0x0971, 15, 15 }, /* push bx */
    { 0x0972, 15, 15 }, /* push cx */
    { 0x0973, 15, 15 }, /* push dx */
    { 0x0974, 15, 15 }, /* push bp */
    { 0x0975, 15, 15 }, /* push si */
    { 0x0976, 15, 15 }, /* push di */
    { 0x0977, 16, 16 }, /* push ds */
    { 0x0978, 16, 16 }, /* push es */
    { 0x0979, 5, 5 }, /* xor ax, ax */
    { 0x097B, 4, 4 }, /* mov ds, ax */
    { 0x097D, 11, 11 }, /* mov ds, word ptr [0x120] */
    { 0x0981, 12, 12 }, /* in al, 0x60 */
    { 0x0983, 15, 15 }, /* push ax */
    { 0x0984, 12, 12 }, /* in al, 0x61 */
    { 0x0986, 4, 4 }, /* mov ah, al */
    { 0x0988, 6, 6 }, /* or al, 0x80 */
    { 0x098A, 12, 12 }, /* out 0x61, al */
    { 0x098C, 6, 6 }, /* xchg al, ah */
    { 0x098E, 12, 12 }, /* out 0x61, al */
    { 0x0990, 12, 12 }, /* pop ax */
    { 0x0991, 5, 5 }, /* or al, al */
    { 0x0993, 4, 16 }, /* js loc_099D */
    { 0x0995, 19, 19 }, /* mov byte ptr [demo_mode], 0 */
    { 0x099A, 21, 21 }, /* call key_dispatch */
    { 0x099D, 4, 4 }, /* mov al, 0x20 */
    { 0x099F, 12, 12 }, /* out 0x20, al */
    { 0x09A1, 14, 14 }, /* pop es */
    { 0x09A2, 14, 14 }, /* pop ds */
    { 0x09A3, 12, 12 }, /* pop di */
    { 0x09A4, 12, 12 }, /* pop si */
    { 0x09A5, 12, 12 }, /* pop bp */
    { 0x09A6, 12, 12 }, /* pop dx */
    { 0x09A7, 12, 12 }, /* pop cx */
    { 0x09A8, 12, 12 }, /* pop bx */
    { 0x09A9, 12, 12 }, /* pop ax */
    { 0x09AA, 34, 34 }, /* iret */
    { 0x09AB, 17, 17 }, /* mov bx, word ptr [last_scancodes] */
    { 0x09AF, 6, 6 }, /* cmp al, 0x53 */
    { 0x09B1, 4, 16 }, /* jne loc_09C8 */
    { 0x09B3, 6, 6 }, /* cmp bx, 0x381d */
    { 0x09B7, 4, 16 }, /* jne loc_09C8 */
    { 0x09B9, 11, 11 }, /* mov ds, word ptr [0x595] */
    { 0x09BD, 19, 19 }, /* mov word ptr [0x72], 0x1234 */
    { 0x09C3, 17, 17 }, /* ljmp 0xf000:0xe05b */
    { 0x09C8, 4, 4 }, /* mov bl, bh */
    { 0x09CA, 4, 4 }, /* mov bh, al */
    { 0x09CC, 18, 18 }, /* mov word ptr [last_scancodes], bx */
    { 0x09D0, 5, 5 }, /* xor ah, ah */
    { 0x09D2, 14, 14 }, /* test byte ptr [editor_active], 1 */
    { 0x09D7, 4, 16 }, /* je loc_09ED */
    { 0x09D9, 6, 6 }, /* cmp al, 0x52 */
    { 0x09DB, 4, 16 }, /* jne loc_09E1 */
    { 0x09DD, 4, 4 }, /* mov al, 0x11 */
    { 0x09DF, 17, 17 }, /* jmp loc_09E7 */
    { 0x09E1, 4, 4 }, /* mov bx, ax */
    { 0x09E3, 17, 17 }, /* mov al, byte ptr [bx + editor_key_table] */
    { 0x09E7, 6, 6 }, /* or al, 0x80 */
    { 0x09E9, 12, 12 }, /* mov byte ptr [editor_key], al */
    { 0x09EC, 20, 20 }, /* ret */
    { 0x09ED, 16, 16 }, /* push ds */
    { 0x09EE, 5, 5 }, /* xor ah, ah */
    { 0x09F0, 6, 6 }, /* cmp al, 0x53 */
    { 0x09F2, 4, 16 }, /* jg loc_0A02 */
    { 0x09F4, 6, 6 }, /* cmp al, 0 */
    { 0x09F6, 4, 16 }, /* jle loc_0A02 */
    { 0x09F8, 8, 8 }, /* shl ax, 1 */
    { 0x09FA, 4, 4 }, /* mov bx, ax */
    { 0x09FC, 17, 17 }, /* mov ax, word ptr [bx + key_handlers] */
    { 0x0A00, 23, 23 }, /* call ax */
    { 0x0A02, 14, 14 }, /* pop ds */
    { 0x0A03, 20, 20 }, /* ret */
    { 0x0A04, 19, 19 }, /* mov byte ptr [editor_active], 1 */
    { 0x0A09, 20, 20 }, /* ret */
    { 0x0A0A, 4, 4 }, /* mov ax, 0 */
    { 0x0A0D, 8, 8 }, /* shr al, 1 */
    { 0x0A0F, 12, 12 }, /* mov byte ptr [mag_switches+1], al */
    { 0x0A12, 8, 8 }, /* rcl al, 1 */
    { 0x0A14, 6, 6 }, /* and al, 1 */
    { 0x0A16, 12, 12 }, /* mov byte ptr [mag_switches], al */
    { 0x0A19, 18, 18 }, /* mov byte ptr [magnetos], ah */
    { 0x0A1D, 21, 21 }, /* call switch_text */
    { 0x0A20, 20, 20 }, /* ret */
    { 0x0A21, 4, 4 }, /* mov ax, 0x102 */
    { 0x0A24, 17, 17 }, /* jmp key_set_magnetos */
    { 0x0A26, 4, 4 }, /* mov ax, 0x201 */
    { 0x0A29, 17, 17 }, /* jmp key_set_magnetos */
    { 0x0A2B, 4, 4 }, /* mov ax, 0x303 */
    { 0x0A2E, 17, 17 }, /* jmp key_set_magnetos */
    { 0x0A30, 4, 4 }, /* mov ax, 0x403 */
    { 0x0A33, 17, 17 }, /* jmp key_set_magnetos */
    { 0x0A35, 4, 4 }, /* mov ax, 0x500 */
    { 0x0A38, 17, 17 }, /* jmp key_set_magnetos */
    { 0x0A3A, 12, 12 }, /* mov al, byte ptr [selected_item] */
    { 0x0A3D, 19, 19 }, /* mov byte ptr [0x551], 0 */
    { 0x0A42, 19, 19 }, /* cmp byte ptr [war_mode], 1 */
    { 0x0A47, 4, 16 }, /* je loc_0A4D */
    { 0x0A49, 6, 6 }, /* sub al, 2 */
    { 0x0A4B, 4, 16 }, /* jne loc_0A5D */
    { 0x0A4D, 2, 2 }, /* stc */
    { 0x0A4E, 15, 15 }, /* rcl word ptr [radar_zoom] */
    { 0x0A52, 15, 15 }, /* rcl word ptr [radar_zoom+2] */
    { 0x0A56, 19, 19 }, /* and word ptr [radar_zoom+2], 0x7fff */
    { 0x0A5C, 20, 20 }, /* ret */
    { 0x0A5D, 6, 6 }, /* sub al, 2 */
    { 0x0A5F, 4, 16 }, /* jne loc_0A7C */
    { 0x0A61, 12, 12 }, /* mov ax, word ptr [com_freq] */
    { 0x0A64, 6, 6 }, /* cmp ax, 0x3831 */
    { 0x0A67, 4, 16 }, /* jne loc_0A6E */
    { 0x0A69, 4, 4 }, /* mov ax, 0x3533 */
    { 0x0A6C, 17, 17 }, /* jmp loc_0A79 */
    { 0x0A6E, 5, 5 }, /* dec ah */
    { 0x0A70, 6, 6 }, /* cmp ah, 0x2f */
    { 0x0A73, 4, 16 }, /* jne loc_0A79 */
    { 0x0A75, 4, 4 }, /* mov ah, 0x39 */
    { 0x0A77, 5, 5 }, /* dec al */
    { 0x0A79, 17, 17 }, /* jmp loc_0B91 */
    { 0x0A7C, 5, 5 }, /* dec al */
    { 0x0A7E, 4, 16 }, /* jne loc_0A9E */
    { 0x0A80, 12, 12 }, /* mov ax, word ptr [com_freq+5] */
    { 0x0A83, 6, 6 }, /* cmp ax, 0x3030 */
    { 0x0A86, 4, 16 }, /* jne loc_0A8D */
    { 0x0A88, 4, 4 }, /* mov ax, 0x3539 */
    { 0x0A8B, 17, 17 }, /* jmp loc_0A9B */
    { 0x0A8D, 6, 6 }, /* cmp ah, 0x30 */
    { 0x0A90, 4, 16 }, /* je loc_0A97 */
    { 0x0A92, 4, 4 }, /* mov ah, 0x30 */
    { 0x0A94, 17, 17 }, /* jmp loc_0A9B */
    { 0x0A97, 4, 4 }, /* mov ah, 0x35 */
    { 0x0A99, 5, 5 }, /* dec al */
    { 0x0A9B, 17, 17 }, /* jmp loc_0BB5 */
    { 0x0A9E, 5, 5 }, /* dec al */
    { 0x0AA0, 4, 16 }, /* jne loc_0ABD */
    { 0x0AA2, 12, 12 }, /* mov ax, word ptr [nav_freq] */
    { 0x0AA5, 6, 6 }, /* cmp ax, 0x3830 */
    { 0x0AA8, 4, 16 }, /* jne loc_0AAF */
    { 0x0AAA, 4, 4 }, /* mov ax, 0x3731 */
    { 0x0AAD, 17, 17 }, /* jmp loc_0ABA */
    { 0x0AAF, 5, 5 }, /* dec ah */
    { 0x0AB1, 6, 6 }, /* cmp ah, 0x2f */
    { 0x0AB4, 4, 16 }, /* jne loc_0ABA */
    { 0x0AB6, 4, 4 }, /* mov ah, 0x39 */
    { 0x0AB8, 5, 5 }, /* dec al */
    { 0x0ABA, 17, 17 }, /* jmp loc_0BD7 */
    { 0x0ABD, 5, 5 }, /* dec al */
    { 0x0ABF, 4, 16 }, /* jne loc_0ADF */
    { 0x0AC1, 12, 12 }, /* mov ax, word ptr [nav_freq+5] */
    { 0x0AC4, 6, 6 }, /* cmp ax, 0x3030 */
    { 0x0AC7, 4, 16 }, /* jne loc_0ACE */
    { 0x0AC9, 4, 4 }, /* mov ax, 0x3539 */
    { 0x0ACC, 17, 17 }, /* jmp loc_0ADC */
    { 0x0ACE, 6, 6 }, /* cmp ah, 0x30 */
    { 0x0AD1, 4, 16 }, /* je loc_0AD8 */
    { 0x0AD3, 4, 4 }, /* mov ah, 0x30 */
    { 0x0AD5, 17, 17 }, /* jmp loc_0ADC */
    { 0x0AD8, 4, 4 }, /* mov ah, 0x35 */
    { 0x0ADA, 5, 5 }, /* dec al */
    { 0x0ADC, 17, 17 }, /* jmp loc_0BFB */
    { 0x0ADF, 5, 5 }, /* dec al */
    { 0x0AE1, 4, 16 }, /* jne loc_0AF6 */
    { 0x0AE3, 12, 12 }, /* mov al, byte ptr [transponder+1] */
    { 0x0AE6, 6, 6 }, /* cmp al, 0x30 */
    { 0x0AE8, 4, 16 }, /* jne loc_0AEE */
    { 0x0AEA, 4, 4 }, /* mov al, 0x37 */
    { 0x0AEC, 17, 17 }, /* jmp loc_0AF0 */
    { 0x0AEE, 5, 5 }, /* dec al */
    { 0x0AF0, 12, 12 }, /* mov byte ptr [transponder+1], al */
    { 0x0AF3, 17, 17 }, /* jmp text_07c5 */
    { 0x0AF6, 5, 5 }, /* dec al */
    { 0x0AF8, 4, 16 }, /* jne loc_0B0D */
    { 0x0AFA, 12, 12 }, /* mov al, byte ptr [transponder+3] */
    { 0x0AFD, 6, 6 }, /* cmp al, 0x30 */
    { 0x0AFF, 4, 16 }, /* jne loc_0B05 */
    { 0x0B01, 4, 4 }, /* mov al, 0x37 */
    { 0x0B03, 17, 17 }, /* jmp loc_0B07 */
    { 0x0B05, 5, 5 }, /* dec al */
    { 0x0B07, 12, 12 }, /* mov byte ptr [transponder+3], al */
    { 0x0B0A, 17, 17 }, /* jmp text_07c5 */
    { 0x0B0D, 5, 5 }, /* dec al */
    { 0x0B0F, 4, 16 }, /* jne loc_0B24 */
    { 0x0B11, 12, 12 }, /* mov al, byte ptr [transponder+5] */
    { 0x0B14, 6, 6 }, /* cmp al, 0x30 */
    { 0x0B16, 4, 16 }, /* jne loc_0B1C */
    { 0x0B18, 4, 4 }, /* mov al, 0x37 */
    { 0x0B1A, 17, 17 }, /* jmp loc_0B1E */
    { 0x0B1C, 5, 5 }, /* dec al */
    { 0x0B1E, 12, 12 }, /* mov byte ptr [transponder+5], al */
    { 0x0B21, 17, 17 }, /* jmp text_07c5 */
    { 0x0B24, 5, 5 }, /* dec al */
    { 0x0B26, 4, 16 }, /* jne loc_0B3B */
    { 0x0B28, 12, 12 }, /* mov al, byte ptr [transponder+7] */
    { 0x0B2B, 6, 6 }, /* cmp al, 0x30 */
    { 0x0B2D, 4, 16 }, /* jne loc_0B33 */
    { 0x0B2F, 4, 4 }, /* mov al, 0x37 */
    { 0x0B31, 17, 17 }, /* jmp loc_0B35 */
    { 0x0B33, 5, 5 }, /* dec al */
    { 0x0B35, 12, 12 }, /* mov byte ptr [transponder+7], al */
    { 0x0B38, 17, 17 }, /* jmp text_07c5 */
    { 0x0B3B, 5, 5 }, /* dec al */
    { 0x0B3D, 4, 16 }, /* jne loc_0B52 */
    { 0x0B3F, 12, 12 }, /* dec byte ptr [obi_course] */
    { 0x0B43, 19, 19 }, /* cmp byte ptr [obi_course], 0xff */
    { 0x0B48, 4, 16 }, /* jne loc_0B4F */
    { 0x0B4A, 19, 19 }, /* mov byte ptr [obi_course], 0xb3 */
    { 0x0B4F, 17, 17 }, /* jmp obi_readout */
    { 0x0B52, 20, 20 }, /* ret */
    { 0x0B53, 12, 12 }, /* mov al, byte ptr [selected_item] */
    { 0x0B56, 19, 19 }, /* mov byte ptr [0x551], 0 */
    { 0x0B5B, 19, 19 }, /* cmp byte ptr [war_mode], 1 */
    { 0x0B60, 4, 16 }, /* je loc_0B66 */
    { 0x0B62, 6, 6 }, /* sub al, 2 */
    { 0x0B64, 4, 16 }, /* jne loc_0B75 */
    { 0x0B66, 15, 15 }, /* sar word ptr [radar_zoom+2], 1 */
    { 0x0B6A, 15, 15 }, /* rcr word ptr [radar_zoom], 1 */
    { 0x0B6E, 19, 19 }, /* or word ptr [radar_zoom], 0x1fff */
    { 0x0B74, 20, 20 }, /* ret */
    { 0x0B75, 6, 6 }, /* sub al, 2 */
    { 0x0B77, 4, 16 }, /* jne loc_0B97 */
    { 0x0B79, 12, 12 }, /* mov ax, word ptr [com_freq] */
    { 0x0B7C, 6, 6 }, /* cmp ax, 0x3533 */
    { 0x0B7F, 4, 16 }, /* jne loc_0B86 */
    { 0x0B81, 4, 4 }, /* mov ax, 0x3831 */
    { 0x0B84, 17, 17 }, /* jmp loc_0B91 */
    { 0x0B86, 5, 5 }, /* inc ah */
    { 0x0B88, 6, 6 }, /* cmp ah, 0x3a */
    { 0x0B8B, 4, 16 }, /* jne loc_0B91 */
    { 0x0B8D, 4, 4 }, /* mov ah, 0x30 */
    { 0x0B8F, 5, 5 }, /* inc al */
    { 0x0B91, 12, 12 }, /* mov word ptr [com_freq], ax */
    { 0x0B94, 17, 17 }, /* jmp loc_0BB8 */
    { 0x0B97, 5, 5 }, /* dec al */
    { 0x0B99, 4, 16 }, /* jne loc_0BBB */
    { 0x0B9B, 12, 12 }, /* mov ax, word ptr [com_freq+5] */
    { 0x0B9E, 6, 6 }, /* cmp ax, 0x3539 */
    { 0x0BA1, 4, 16 }, /* jne loc_0BA8 */
    { 0x0BA3, 4, 4 }, /* mov ax, 0x3030 */
    { 0x0BA6, 17, 17 }, /* jmp loc_0BB5 */
    { 0x0BA8, 6, 6 }, /* cmp ah, 0x35 */
    { 0x0BAB, 4, 16 }, /* je loc_0BB1 */
    { 0x0BAD, 4, 4 }, /* mov ah, 0x35 */
    { 0x0BAF, 17, 17 }, /* jmp loc_0BB5 */
    { 0x0BB1, 4, 4 }, /* mov ah, 0x30 */
    { 0x0BB3, 5, 5 }, /* inc al */
    { 0x0BB5, 12, 12 }, /* mov word ptr [com_freq+5], ax */
    { 0x0BB8, 17, 17 }, /* jmp com_tune */
    { 0x0BBB, 5, 5 }, /* dec al */
    { 0x0BBD, 4, 16 }, /* jne loc_0BDC */
    { 0x0BBF, 12, 12 }, /* mov ax, word ptr [nav_freq] */
    { 0x0BC2, 6, 6 }, /* cmp ax, 0x3731 */
    { 0x0BC5, 4, 16 }, /* jne loc_0BCC */
    { 0x0BC7, 4, 4 }, /* mov ax, 0x3830 */
    { 0x0BCA, 17, 17 }, /* jmp loc_0BD7 */
    { 0x0BCC, 5, 5 }, /* inc ah */
    { 0x0BCE, 6, 6 }, /* cmp ah, 0x3a */
    { 0x0BD1, 4, 16 }, /* jne loc_0BD7 */
    { 0x0BD3, 4, 4 }, /* mov ah, 0x30 */
    { 0x0BD5, 5, 5 }, /* inc al */
    { 0x0BD7, 12, 12 }, /* mov word ptr [nav_freq], ax */
    { 0x0BDA, 17, 17 }, /* jmp loc_0BFE */
    { 0x0BDC, 5, 5 }, /* dec al */
    { 0x0BDE, 4, 16 }, /* jne loc_0C01 */
    { 0x0BE0, 12, 12 }, /* mov ax, word ptr [nav_freq+5] */
    { 0x0BE3, 6, 6 }, /* cmp ax, 0x3539 */
    { 0x0BE6, 4, 16 }, /* jne loc_0BEE */
    { 0x0BE8, 4, 4 }, /* mov ax, 0x3030 */
    { 0x0BEB, 17, 17 }, /* jmp loc_0BFB */
    { 0x0BEE, 6, 6 }, /* cmp ah, 0x35 */
    { 0x0BF1, 4, 16 }, /* je loc_0BF7 */
    { 0x0BF3, 4, 4 }, /* mov ah, 0x35 */
    { 0x0BF5, 17, 17 }, /* jmp loc_0BFB */
    { 0x0BF7, 4, 4 }, /* mov ah, 0x30 */
    { 0x0BF9, 5, 5 }, /* inc al */
    { 0x0BFB, 12, 12 }, /* mov word ptr [nav_freq+5], ax */
    { 0x0BFE, 17, 17 }, /* jmp nav_tune */
    { 0x0C01, 5, 5 }, /* dec al */
    { 0x0C03, 4, 16 }, /* jne loc_0C19 */
    { 0x0C05, 12, 12 }, /* mov al, byte ptr [transponder+1] */
    { 0x0C08, 6, 6 }, /* cmp al, 0x37 */
    { 0x0C0A, 4, 16 }, /* jne loc_0C11 */
    { 0x0C0C, 4, 4 }, /* mov al, 0x30 */
    { 0x0C0E, 17, 17 }, /* jmp loc_0C13 */
    { 0x0C11, 5, 5 }, /* inc al */
    { 0x0C13, 12, 12 }, /* mov byte ptr [transponder+1], al */
    { 0x0C16, 17, 17 }, /* jmp text_07c5 */
    { 0x0C19, 5, 5 }, /* dec al */
    { 0x0C1B, 4, 16 }, /* jne loc_0C31 */
    { 0x0C1D, 12, 12 }, /* mov al, byte ptr [transponder+3] */
    { 0x0C20, 6, 6 }, /* cmp al, 0x37 */
    { 0x0C22, 4, 16 }, /* jne loc_0C29 */
    { 0x0C24, 4, 4 }, /* mov al, 0x30 */
    { 0x0C26, 17, 17 }, /* jmp loc_0C2B */
    { 0x0C29, 5, 5 }, /* inc al */
    { 0x0C2B, 12, 12 }, /* mov byte ptr [transponder+3], al */
    { 0x0C2E, 17, 17 }, /* jmp text_07c5 */
    { 0x0C31, 5, 5 }, /* dec al */
    { 0x0C33, 4, 16 }, /* jne loc_0C49 */
    { 0x0C35, 12, 12 }, /* mov al, byte ptr [transponder+5] */
    { 0x0C38, 6, 6 }, /* cmp al, 0x37 */
    { 0x0C3A, 4, 16 }, /* jne loc_0C41 */
    { 0x0C3C, 4, 4 }, /* mov al, 0x30 */
    { 0x0C3E, 17, 17 }, /* jmp loc_0C43 */
    { 0x0C41, 5, 5 }, /* inc al */
    { 0x0C43, 12, 12 }, /* mov byte ptr [transponder+5], al */
    { 0x0C46, 17, 17 }, /* jmp text_07c5 */
    { 0x0C49, 5, 5 }, /* dec al */
    { 0x0C4B, 4, 16 }, /* jne loc_0C61 */
    { 0x0C4D, 12, 12 }, /* mov al, byte ptr [transponder+7] */
    { 0x0C50, 6, 6 }, /* cmp al, 0x37 */
    { 0x0C52, 4, 16 }, /* jne loc_0C59 */
    { 0x0C54, 4, 4 }, /* mov al, 0x30 */
    { 0x0C56, 17, 17 }, /* jmp loc_0C5B */
    { 0x0C59, 5, 5 }, /* inc al */
    { 0x0C5B, 12, 12 }, /* mov byte ptr [transponder+7], al */
    { 0x0C5E, 17, 17 }, /* jmp text_07c5 */
    { 0x0C61, 5, 5 }, /* dec al */
    { 0x0C63, 4, 16 }, /* jne loc_0C78 */
    { 0x0C65, 12, 12 }, /* inc byte ptr [obi_course] */
    { 0x0C69, 19, 19 }, /* cmp byte ptr [obi_course], 0xb4 */
    { 0x0C6E, 4, 16 }, /* jne loc_0C75 */
    { 0x0C70, 19, 19 }, /* mov byte ptr [obi_course], 0 */
    { 0x0C75, 17, 17 }, /* jmp obi_readout */
    { 0x0C78, 20, 20 }, /* ret */
    { 0x0C79, 12, 12 }, /* mov al, byte ptr [cga_init_table+13] */
    { 0x0C7C, 5, 5 }, /* dec al */
    { 0x0C7E, 6, 6 }, /* cmp al, 0x27 */
    { 0x0C80, 4, 16 }, /* jge loc_0C84 */
    { 0x0C82, 4, 4 }, /* mov al, 0x2e */
    { 0x0C84, 12, 12 }, /* mov byte ptr [cga_init_table+13], al */
    { 0x0C87, 17, 17 }, /* jmp cga_program_regs */
    { 0x0C8A, 19, 19 }, /* or byte ptr [war_status_line], 1 */
    { 0x0C8F, 20, 20 }, /* ret */
    { 0x0C90, 14, 14 }, /* test byte ptr [slew_mode], 0xff */
    { 0x0C95, 4, 16 }, /* je loc_0CAE */
    { 0x0C97, 12, 12 }, /* mov ax, word ptr [view_pitch] */
    { 0x0C9A, 5, 5 }, /* neg ax */
    { 0x0C9C, 12, 12 }, /* mov word ptr [pitch], ax */
    { 0x0C9F, 12, 12 }, /* mov ax, word ptr [view_bank] */
    { 0x0CA2, 5, 5 }, /* neg ax */
    { 0x0CA4, 12, 12 }, /* mov word ptr [bank], ax */
    { 0x0CA7, 12, 12 }, /* mov ax, word ptr [view_heading] */
    { 0x0CAA, 12, 12 }, /* mov word ptr [heading], ax */
    { 0x0CAD, 20, 20 }, /* ret */
    { 0x0CAE, 19, 19 }, /* cmp byte ptr [0x551], 0 */
    { 0x0CB3, 4, 16 }, /* je loc_0CCA */
    { 0x0CB5, 19, 19 }, /* cmp byte ptr [selected_item], 8 */
    { 0x0CBA, 4, 16 }, /* jl loc_0CCA */
    { 0x0CBC, 19, 19 }, /* cmp byte ptr [selected_item], 0xb */
    { 0x0CC1, 4, 16 }, /* jg loc_0CCA */
    { 0x0CC3, 12, 12 }, /* inc byte ptr [selected_item] */
    { 0x0CC7, 17, 17 }, /* jmp loc_0CCF */
    { 0x0CCA, 19, 19 }, /* mov byte ptr [selected_item], 8 */
    { 0x0CCF, 19, 19 }, /* mov byte ptr [0x551], 0x12 */
    { 0x0CD4, 20, 20 }, /* ret */
    { 0x0CD5, 12, 12 }, /* not byte ptr [paused] */
    { 0x0CD9, 20, 20 }, /* ret */
    { 0x0CDA, 5, 5 }, /* xor ax, ax */
    { 0x0CDC, 12, 12 }, /* mov word ptr [rpm_windmill+35], ax */
    { 0x0CDF, 12, 12 }, /* mov word ptr [takeoff_spot], ax */
    { 0x0CE2, 20, 20 }, /* ret */
    { 0x0CE3, 12, 12 }, /* mov ax, word ptr [hdg_display] */
    { 0x0CE6, 18, 18 }, /* sub ax, word ptr [view_heading] */
    { 0x0CEA, 18, 18 }, /* add ax, word ptr [wind_gust_offset] */
    { 0x0CEE, 18, 18 }, /* add ax, word ptr [wind_dir_offset] */
    { 0x0CF2, 12, 12 }, /* mov word ptr [0x3f9], ax */
    { 0x0CF5, 20, 20 }, /* ret */
    { 0x0CF6, 19, 19 }, /* cmp byte ptr [on_ground], 0 */
    { 0x0CFB, 4, 16 }, /* jne loc_0D0B */
    { 0x0CFD, 12, 12 }, /* not byte ptr [gear_down] */
    { 0x0D01, 12, 12 }, /* mov ax, word ptr [0x8cc] */
    { 0x0D04, 14, 14 }, /* test byte ptr [gear_down], 0xff */
    { 0x0D09, 4, 16 }, /* je loc_0D0E */
    { 0x0D0B, 12, 12 }, /* mov ax, word ptr [0x8ca] */
    { 0x0D0E, 12, 12 }, /* mov word ptr [gear_drag], ax */
    { 0x0D11, 17, 17 }, /* jmp switch_text */
    { 0x0D14, 12, 12 }, /* not byte ptr [carb_heat] */
    { 0x0D18, 17, 17 }, /* jmp loc_0D11 */
    { 0x0D1A, 12, 12 }, /* not byte ptr [lights] */
    { 0x0D1E, 17, 17 }, /* jmp loc_0D11 */
    { 0x0D20, 19, 19 }, /* cmp byte ptr [war_mode], 1 */
    { 0x0D25, 4, 16 }, /* jne loc_0D4A */
    { 0x0D27, 19, 19 }, /* cmp byte ptr [bombs_left], 0x30 */
    { 0x0D2C, 4, 16 }, /* je loc_0D4A */
    { 0x0D2E, 19, 19 }, /* cmp word ptr [bomb_state], 0 */
    { 0x0D33, 4, 16 }, /* jne loc_0D4A */
    { 0x0D35, 12, 12 }, /* dec byte ptr [bombs_left] */
    { 0x0D39, 12, 12 }, /* mov ax, word ptr [alt_m] */
    { 0x0D3C, 12, 12 }, /* mov word ptr [bomb_state], ax */
    { 0x0D3F, 19, 19 }, /* mov word ptr [bomb_whistle], 0x64 */
    { 0x0D45, 19, 19 }, /* mov byte ptr [sound_state], 4 */
    { 0x0D4A, 20, 20 }, /* ret */
    { 0x0D4B, 19, 19 }, /* mov byte ptr [com_search], 1 */
    { 0x0D50, 19, 19 }, /* cmp byte ptr [0x551], 0 */
    { 0x0D55, 4, 16 }, /* je loc_0D63 */
    { 0x0D57, 19, 19 }, /* cmp byte ptr [selected_item], 4 */
    { 0x0D5C, 4, 16 }, /* jne loc_0D63 */
    { 0x0D5E, 12, 12 }, /* inc byte ptr [selected_item] */
    { 0x0D62, 20, 20 }, /* ret */
    { 0x0D63, 19, 19 }, /* mov byte ptr [selected_item], 4 */
    { 0x0D68, 19, 19 }, /* mov byte ptr [0x551], 0x12 */
    { 0x0D6D, 20, 20 }, /* ret */
    { 0x0D6E, 19, 19 }, /* mov byte ptr [selected_item], 0xc */
    { 0x0D73, 20, 20 }, /* ret */
    { 0x0D74, 19, 19 }, /* cmp byte ptr [0x551], 0 */
    { 0x0D79, 4, 16 }, /* je loc_0D87 */
    { 0x0D7B, 19, 19 }, /* cmp byte ptr [selected_item], 6 */
    { 0x0D80, 4, 16 }, /* jne loc_0D87 */
    { 0x0D82, 12, 12 }, /* inc byte ptr [selected_item] */
    { 0x0D86, 20, 20 }, /* ret */
    { 0x0D87, 19, 19 }, /* mov byte ptr [selected_item], 6 */
    { 0x0D8C, 19, 19 }, /* mov byte ptr [0x551], 0x12 */
    { 0x0D91, 20, 20 }, /* ret */
    { 0x0D92, 20, 20 }, /* ret */
    { 0x0D93, 14, 14 }, /* test byte ptr [on_ground], 0xff */
    { 0x0D98, 4, 16 }, /* je loc_0DA7 */
    { 0x0D9A, 12, 12 }, /* mov ax, word ptr [airspeed] */
    { 0x0D9D, 6, 6 }, /* sub ax, 0x100 */
    { 0x0DA0, 4, 16 }, /* jns loc_0DA4 */
    { 0x0DA2, 5, 5 }, /* xor ax, ax */
    { 0x0DA4, 12, 12 }, /* mov word ptr [airspeed], ax */
    { 0x0DA7, 20, 20 }, /* ret */
    { 0x0DA8, 21, 21 }, /* call usermode_recall */
    { 0x0DAB, 21, 21 }, /* call editor_apply_state */
    { 0x0DAE, 20, 20 }, /* ret */
    { 0x0DAF, 14, 14 }, /* test byte ptr [slew_mode], 0xff */
    { 0x0DB4, 4, 16 }, /* je loc_0DC4 */
    { 0x0DB6, 5, 5 }, /* xor ax, ax */
    { 0x0DB8, 12, 12 }, /* mov word ptr [view_bank], ax */
    { 0x0DBB, 12, 12 }, /* mov word ptr [view_heading], ax */
    { 0x0DBE, 19, 19 }, /* mov word ptr [view_pitch], 0x4000 */
    { 0x0DC4, 20, 20 }, /* ret */
    { 0x0DC5, 14, 14 }, /* test word ptr [ammo], 0xff */
    { 0x0DCB, 4, 16 }, /* je loc_0DD2 */
    { 0x0DCD, 19, 19 }, /* mov byte ptr [gun_burst], 3 */
    { 0x0DD2, 20, 20 }, /* ret */
    { 0x0DD3, 19, 19 }, /* mov word ptr [flaps], 0 */
    { 0x0DD9, 4, 4 }, /* mov bp, 0x146d */
    { 0x0DDC, 4, 4 }, /* mov al, 0x7f */
    { 0x0DDE, 18, 18 }, /* sub al, byte ptr [flaps+1] */
    { 0x0DE2, 8, 8 }, /* sar al, 1 */
    { 0x0DE4, 8, 8 }, /* sar al, 1 */
    { 0x0DE6, 8, 8 }, /* sar al, 1 */
    { 0x0DE8, 8, 8 }, /* sar al, 1 */
    { 0x0DEA, 12, 12 }, /* mov byte ptr [0x1473], al */
    { 0x0DED, 21, 21 }, /* call draw_indicator */
    { 0x0DF0, 12, 12 }, /* mov ax, word ptr [0x8f4] */
    { 0x0DF3, 127, 127 }, /* mul word ptr [flaps] */
    { 0x0DF7, 18, 18 }, /* mov word ptr [flaps_cl], dx */
    { 0x0DFB, 21, 21 }, /* call wing_cl_offsets */
    { 0x0DFE, 12, 12 }, /* mov ax, word ptr [flaps] */
    { 0x0E01, 127, 127 }, /* mul word ptr [0x8dc] */
    { 0x0E05, 18, 18 }, /* mov word ptr [flaps_drag], dx */
    { 0x0E09, 12, 12 }, /* mov ax, word ptr [flaps] */
    { 0x0E0C, 137, 137 }, /* imul word ptr [0x8de] */
    { 0x0E10, 18, 18 }, /* mov word ptr [flaps_view], dx */
    { 0x0E14, 20, 20 }, /* ret */
    { 0x0E15, 19, 19 }, /* mov word ptr [flaps], 0x2000 */
    { 0x0E1B, 17, 17 }, /* jmp set_flaps */
    { 0x0E1D, 19, 19 }, /* mov word ptr [flaps], 0x4000 */
    { 0x0E23, 17, 17 }, /* jmp set_flaps */
    { 0x0E25, 19, 19 }, /* mov word ptr [flaps], 0x6000 */
    { 0x0E2B, 17, 17 }, /* jmp set_flaps */
    { 0x0E2D, 19, 19 }, /* mov word ptr [flaps], 0x7fff */
    { 0x0E33, 17, 17 }, /* jmp set_flaps */
    { 0x0E35, 19, 19 }, /* add word ptr [throttle], 0x800 */
    { 0x0E3B, 19, 19 }, /* mov word ptr [throttle_target], 0x2000 */
    { 0x0E41, 4, 16 }, /* jno sub_0E6A */
    { 0x0E43, 17, 17 }, /* jmp loc_0E64 */
    { 0x0E45, 19, 19 }, /* mov word ptr [throttle_target], 0 */
    { 0x0E4B, 19, 19 }, /* cmp byte ptr [reality_mode], 0 */
    { 0x0E50, 4, 16 }, /* je loc_0E64 */
    { 0x0E52, 12, 12 }, /* mov al, byte ptr [frame_counter] */
    { 0x0E55, 6, 6 }, /* and al, 3 */
    { 0x0E57, 4, 16 }, /* jne loc_0E64 */
    { 0x0E59, 19, 19 }, /* cmp word ptr [throttle], 0x3e80 */
    { 0x0E5F, 4, 16 }, /* jge loc_0E64 */
    { 0x0E61, 21, 21 }, /* call engine_stop */
    { 0x0E64, 19, 19 }, /* mov word ptr [throttle], 0x7fff */
    { 0x0E6A, 4, 4 }, /* mov bp, 0x1461 */
    { 0x0E6D, 12, 12 }, /* mov al, byte ptr [throttle+1] */
    { 0x0E70, 8, 8 }, /* sar al, 1 */
    { 0x0E72, 8, 8 }, /* sar al, 1 */
    { 0x0E74, 12, 12 }, /* mov byte ptr [0x1467], al */
    { 0x0E77, 21, 21 }, /* call draw_indicator */
    { 0x0E7A, 20, 20 }, /* ret */
    { 0x0E7B, 19, 19 }, /* add word ptr [throttle], 0x400 */
    { 0x0E81, 19, 19 }, /* mov word ptr [throttle_target], 0x4000 */
    { 0x0E87, 17, 17 }, /* jmp loc_0E41 */
    { 0x0E89, 19, 19 }, /* sub word ptr [throttle], 0x800 */
    { 0x0E8F, 19, 19 }, /* mov word ptr [throttle_target], 0x6000 */
    { 0x0E95, 4, 16 }, /* jns sub_0E6A */
    { 0x0E97, 19, 19 }, /* mov word ptr [throttle], 0 */
    { 0x0E9D, 19, 19 }, /* mov word ptr [throttle_target], 0x7fff */
    { 0x0EA3, 17, 17 }, /* jmp sub_0E6A */
    { 0x0EA5, 19, 19 }, /* mov byte ptr [selected_item], 2 */
    { 0x0EAA, 19, 19 }, /* mov byte ptr [radar_view], 1 */
    { 0x0EAF, 20, 20 }, /* ret */
    { 0x0EB0, 14, 14 }, /* test byte ptr [radar_view], 0xff */
    { 0x0EB5, 4, 16 }, /* jne loc_0EBD */
    { 0x0EB7, 19, 19 }, /* mov byte ptr [selected_item], 1 */
    { 0x0EBC, 20, 20 }, /* ret */
    { 0x0EBD, 19, 19 }, /* mov byte ptr [radar_view], 0 */
    { 0x0EC2, 20, 20 }, /* ret */
    { 0x0EC3, 4, 4 }, /* mov bl, 0xe */
    { 0x0EC5, 21, 21 }, /* call key_repeat_accel */
    { 0x0EC8, 19, 19 }, /* add word ptr [slew_rate_a], 0x80 */
    { 0x0ECE, 19, 19 }, /* add word ptr [elevator_trim], 0xfc00 */
    { 0x0ED4, 4, 16 }, /* jno key_ignore */
    { 0x0ED6, 19, 19 }, /* mov word ptr [elevator_trim], 0x8001 */
    { 0x0EDC, 4, 4 }, /* mov bp, 0x1479 */
    { 0x0EDF, 12, 12 }, /* mov al, byte ptr [elevator_trim+1] */
    { 0x0EE2, 8, 8 }, /* sar al, 1 */
    { 0x0EE4, 8, 8 }, /* sar al, 1 */
    { 0x0EE6, 8, 8 }, /* sar al, 1 */
    { 0x0EE8, 8, 8 }, /* sar al, 1 */
    { 0x0EEA, 6, 6 }, /* add al, 8 */
    { 0x0EEC, 12, 12 }, /* mov byte ptr [0x147f], al */
    { 0x0EEF, 21, 21 }, /* call draw_indicator */
    { 0x0EF2, 20, 20 }, /* ret */
    { 0x0EF4, 4, 4 }, /* mov bl, 2 */
    { 0x0EF6, 21, 21 }, /* call key_repeat_accel */
    { 0x0EF9, 19, 19 }, /* sub word ptr [slew_rate_a], 0x80 */
    { 0x0EFF, 20, 20 }, /* ret */
    { 0x0F00, 4, 4 }, /* mov bl, 0 */
    { 0x0F02, 21, 21 }, /* call key_repeat_accel */
    { 0x0F05, 12, 12 }, /* mov ax, word ptr [elevator] */
    { 0x0F08, 6, 6 }, /* add ax, 0xff00 */
    { 0x0F0B, 19, 19 }, /* cmp byte ptr [0x551], 0 */
    { 0x0F10, 4, 16 }, /* je loc_0F15 */
    { 0x0F12, 6, 6 }, /* add ax, 0xf900 */
    { 0x0F15, 6, 6 }, /* cmp ax, 0xb000 */
    { 0x0F18, 4, 16 }, /* jge loc_0F1D */
    { 0x0F1A, 4, 4 }, /* mov ax, 0xb000 */
    { 0x0F1D, 12, 12 }, /* mov word ptr [elevator], ax */
    { 0x0F20, 19, 19 }, /* mov byte ptr [0x551], 8 */
    { 0x0F25, 4, 4 }, /* mov bp, 0x1455 */
    { 0x0F28, 12, 12 }, /* mov al, byte ptr [elevator+1] */
    { 0x0F2B, 8, 8 }, /* sar al, 1 */
    { 0x0F2D, 8, 8 }, /* sar al, 1 */
    { 0x0F2F, 8, 8 }, /* sar al, 1 */
    { 0x0F31, 6, 6 }, /* add al, 0xb */
    { 0x0F33, 12, 12 }, /* mov byte ptr [0x145b], al */
    { 0x0F36, 21, 21 }, /* call draw_indicator */
    { 0x0F39, 17, 17 }, /* mov dx, word ptr [elevator] */
    { 0x0F3D, 12, 12 }, /* mov ax, word ptr [0x8da] */
    { 0x0F40, 130, 130 }, /* imul dx */
    { 0x0F42, 8, 8 }, /* shl ax, 1 */
    { 0x0F44, 8, 8 }, /* rcl dx, 1 */
    { 0x0F46, 18, 18 }, /* mov word ptr [elev_aoa], dx */
    { 0x0F4A, 20, 20 }, /* ret */
    { 0x0F4B, 4, 4 }, /* mov bl, 0xc */
    { 0x0F4D, 21, 21 }, /* call key_repeat_accel */
    { 0x0F50, 19, 19 }, /* add word ptr [aileron], 0xfc00 */
    { 0x0F56, 4, 16 }, /* jno sub_0FA3 */
    { 0x0F58, 19, 19 }, /* mov word ptr [aileron], 0x8001 */
    { 0x0F5E, 17, 17 }, /* jmp sub_0FA3 */
    { 0x0F61, 4, 4 }, /* mov bl, 0x10 */
    { 0x0F63, 21, 21 }, /* call key_repeat_accel */
    { 0x0F66, 5, 5 }, /* xor ax, ax */
    { 0x0F68, 14, 14 }, /* test byte ptr [slew_mode], 0xff */
    { 0x0F6D, 4, 16 }, /* je loc_0F84 */
    { 0x0F6F, 12, 12 }, /* mov word ptr [elevator], ax */
    { 0x0F72, 19, 19 }, /* mov word ptr [throttle], 0x4000 */
    { 0x0F78, 19, 19 }, /* mov word ptr [flaps], 0x4000 */
    { 0x0F7E, 12, 12 }, /* mov word ptr [slew_rate_a], ax */
    { 0x0F81, 12, 12 }, /* mov word ptr [slew_rate_b], ax */
    { 0x0F84, 12, 12 }, /* mov word ptr [aileron], ax */
    { 0x0F87, 12, 12 }, /* mov word ptr [rudder], ax */
    { 0x0F8A, 21, 21 }, /* call sub_0FA3 */
    { 0x0F8D, 17, 17 }, /* jmp loc_0FE2 */
    { 0x0F90, 4, 4 }, /* mov bl, 4 */
    { 0x0F92, 21, 21 }, /* call key_repeat_accel */
    { 0x0F95, 19, 19 }, /* add word ptr [aileron], 0x400 */
    { 0x0F9B, 4, 16 }, /* jno sub_0FA3 */
    { 0x0F9D, 19, 19 }, /* mov word ptr [aileron], 0x7fff */
    { 0x0FA3, 14, 14 }, /* test byte ptr [auto_coordination], 0xff */
    { 0x0FA8, 4, 16 }, /* je sub_0FB3 */
    { 0x0FAA, 12, 12 }, /* mov ax, word ptr [aileron] */
    { 0x0FAD, 12, 12 }, /* mov word ptr [rudder], ax */
    { 0x0FB0, 21, 21 }, /* call sub_0FF2 */
    { 0x0FB3, 4, 4 }, /* mov bp, 0x143d */
    { 0x0FB6, 12, 12 }, /* mov al, byte ptr [aileron+1] */
    { 0x0FB9, 8, 8 }, /* sar al, 1 */
    { 0x0FBB, 8, 8 }, /* sar al, 1 */
    { 0x0FBD, 6, 6 }, /* add al, 0x21 */
    { 0x0FBF, 12, 12 }, /* mov byte ptr [0x1443], al */
    { 0x0FC2, 21, 21 }, /* call draw_indicator */
    { 0x0FC5, 12, 12 }, /* mov ax, word ptr [aileron] */
    { 0x0FC8, 137, 137 }, /* imul word ptr [0x8f2] */
    { 0x0FCC, 18, 18 }, /* mov word ptr [aileron_cl], dx */
    { 0x0FD0, 21, 21 }, /* call control_coupling */
    { 0x0FD3, 20, 20 }, /* ret */
    { 0x0FD4, 19, 19 }, /* add word ptr [rudder], 0x400 */
    { 0x0FDA, 4, 16 }, /* jno loc_0FE2 */
    { 0x0FDC, 19, 19 }, /* mov word ptr [rudder], 0x7fff */
    { 0x0FE2, 14, 14 }, /* test byte ptr [auto_coordination], 0xff */
    { 0x0FE7, 4, 16 }, /* je sub_0FF2 */
    { 0x0FE9, 12, 12 }, /* mov ax, word ptr [rudder] */
    { 0x0FEC, 12, 12 }, /* mov word ptr [aileron], ax */
    { 0x0FEF, 21, 21 }, /* call sub_0FB3 */
    { 0x0FF2, 4, 4 }, /* mov bp, 0x1449 */
    { 0x0FF5, 12, 12 }, /* mov al, byte ptr [rudder+1] */
    { 0x0FF8, 8, 8 }, /* sar al, 1 */
    { 0x0FFA, 8, 8 }, /* sar al, 1 */
    { 0x0FFC, 6, 6 }, /* add al, 0x21 */
    { 0x0FFE, 12, 12 }, /* mov byte ptr [0x144f], al */
    { 0x1001, 21, 21 }, /* call draw_indicator */
    { 0x1004, 21, 21 }, /* call control_coupling */
    { 0x1007, 20, 20 }, /* ret */
    { 0x1008, 4, 4 }, /* mov bl, 0xa */
    { 0x100A, 21, 21 }, /* call key_repeat_accel */
    { 0x100D, 19, 19 }, /* add word ptr [slew_rate_b], 0x80 */
    { 0x1013, 19, 19 }, /* add word ptr [elevator_trim], 0x400 */
    { 0x1019, 4, 16 }, /* jno loc_1021 */
    { 0x101B, 19, 19 }, /* mov word ptr [elevator_trim], 0x7fff */
    { 0x1021, 17, 17 }, /* jmp key_ignore */
    { 0x1024, 4, 4 }, /* mov bl, 8 */
    { 0x1026, 21, 21 }, /* call key_repeat_accel */
    { 0x1029, 12, 12 }, /* mov ax, word ptr [elevator] */
    { 0x102C, 6, 6 }, /* add ax, 0x100 */
    { 0x102F, 19, 19 }, /* cmp byte ptr [0x551], 0 */
    { 0x1034, 4, 16 }, /* je loc_1039 */
    { 0x1036, 6, 6 }, /* add ax, 0x700 */
    { 0x1039, 6, 6 }, /* cmp ax, 0x5000 */
    { 0x103C, 4, 16 }, /* jle loc_1041 */
    { 0x103E, 4, 4 }, /* mov ax, 0x5000 */
    { 0x1041, 17, 17 }, /* jmp loc_0F1D */
    { 0x1044, 4, 4 }, /* mov bl, 6 */
    { 0x1046, 21, 21 }, /* call key_repeat_accel */
    { 0x1049, 19, 19 }, /* sub word ptr [slew_rate_b], 0x80 */
    { 0x104F, 20, 20 }, /* ret */
    { 0x1050, 19, 19 }, /* add word ptr [rudder], 0xfc00 */
    { 0x1056, 4, 16 }, /* jno loc_0FE2 */
    { 0x1058, 19, 19 }, /* mov word ptr [rudder], 0x8001 */
    { 0x105E, 17, 17 }, /* jmp loc_0FE2 */
    { 0x1060, 19, 19 }, /* cmp byte ptr [0x418], 0 */
    { 0x1065, 4, 16 }, /* je loc_109A */
    { 0x1067, 16, 16 }, /* push es */
    { 0x1068, 4, 4 }, /* mov ax, 0 */
    { 0x106B, 4, 4 }, /* mov es, ax */
    { 0x106D, 12, 12 }, /* mov ax, word ptr [old_int9] */
    { 0x1070, 17, 17 }, /* mov bx, word ptr [old_int9+2] */
    { 0x1074, 12, 12 }, /* mov word ptr es:[0x24], ax */
    { 0x1078, 18, 18 }, /* mov word ptr es:[0x26], bx */
    { 0x107D, 12, 12 }, /* mov ax, word ptr [old_int8] */
    { 0x1080, 17, 17 }, /* mov bx, word ptr [old_int8+2] */
    { 0x1084, 12, 12 }, /* mov word ptr es:[0x20], ax */
    { 0x1088, 18, 18 }, /* mov word ptr es:[0x22], bx */
    { 0x108D, 4, 4 }, /* mov al, 0xff */
    { 0x108F, 12, 12 }, /* out 0x40, al */
    { 0x1091, 12, 12 }, /* out 0x40, al */
    { 0x1093, 19, 19 }, /* mov word ptr [timer_hooked], 0 */
    { 0x1099, 14, 14 }, /* pop es */
    { 0x109A, 20, 20 }, /* ret */
    { 0x109B, 19, 19 }, /* cmp byte ptr [selected_item], 1 */
    { 0x10A0, 4, 16 }, /* je loc_10A3 */
    { 0x10A2, 20, 20 }, /* ret */
    { 0x10A3, 12, 12 }, /* dec byte ptr [selected_item] */
    { 0x10A7, 5, 5 }, /* xor bh, bh */
    { 0x10A9, 17, 17 }, /* mov ax, word ptr [bx + 0x5a1] */
    { 0x10AD, 12, 12 }, /* mov word ptr [0x59b], ax */
    { 0x10B0, 18, 18 }, /* mov word ptr [view_not_forward], bx */
    { 0x10B4, 12, 12 }, /* pop ax */
    { 0x10B5, 20, 20 }, /* ret */
};

#endif
