/* Natives for subphase 3.18 keyboard and controls (see docs/PHASE3_PLAN.md and
 * docs/subphases/3.18.md): the keyboard interrupt int9_keyboard (0050:0970), key_dispatch
 * (09AB), every key handler of the key_handlers table (DS:05B1), the routines they share
 * (set_flaps, the control indicators, ...) and key_repeat_accel (109B).
 *
 * The emulated keyboard path stays: SDL -> pc_key_event -> port 60h -> IRQ1 -> this native.
 *
 * Like 3.16 (editor.c), the routines are transliterated on the emulated registers, so every
 * register, segment register and memory byte (including the stack words written by CALL and
 * PUSH) ends as the original leaves it; flags are not kept except IF (none of the callers reads
 * them, and the interrupt's IRET restores them). Memory goes through the generated accessors of
 * game/state.h, on the live DS.
 *
 * Cycles: run(from, to) adds the cpu8086.c cost of every original instruction in [from, to)
 * (table keys_cycles.h, generated by tools/gen_keys_cycles.py), taken() the extra cost of a
 * conditional jump that was taken. Every entry's .cycles is ENTRY_CYCLES and is subtracted
 * again, so a call costs exactly what the original costs.
 *
 * Calls out of a native (CALL in the original, the handler's CALL AX, and the tail JMPs to
 * switch_text, com_tune, nav_tune, text_07c5, obi_readout and cga_program_regs) run the target
 * the way the CPU would with the natives on: an enabled native at a reached address runs
 * through native_call() (the other entries of this file, draw_indicator, switch_text, ...),
 * anything else is single-stepped as original code. Interrupts are not delivered meanwhile.
 *
 * key_repeat_accel does not always return to its caller: when selected_item = 1 (after Scroll
 * Lock with the radar off) it picks a view direction, pops its return address and returns
 * from the key handler. call_rep() reports which way it went.
 *
 * Ctrl+Alt+Del (Delete with last_scancodes = 381Dh) makes key_dispatch jump to the BIOS reset
 * entry F000:E05B (pc.c traps it to a reboot). The native leaves CS:IP there and returns at
 * once; so does int9_keyboard.
 *
 * Interrupts (same scheme as 3.14 and 3.16). The handlers draw indicators through blit_or,
 * which executes STI, so the timer interrupt can arrive inside the keyboard interrupt; the
 * keyboard can also latch the next scancode meanwhile (kbd_poll after every instruction). A
 * native holds both until it returns. So a native that is not nested in another one runs with
 * an undo log; when the timer or the keyboard would have raised an interrupt within its
 * cycles, its memory writes are undone, the CPU and the device state (PIC, PIT, keyboard,
 * port 61h, speaker log) are restored, and the call is handed back to the original: its first
 * instruction is performed and the CPU continues in the original routine, with interrupts.
 * Under --verify (and nested in a native that keeps a log) they run plain. */
#include <SDL3/SDL.h>
#include <stddef.h>

#include "native.h"
#include "game/state.h"
#include "keys.h"
#include "keys_cycles.h"

/* ---- registers, memory ------------------------------------------------------------------ */

#define REG(r) (pc->cpu.regs[R_##r])
#define SREG(r) (pc->cpu.sregs[S_##r])
#define SET_LO(r, b) (REG(r) = (uint16_t)((REG(r) & 0xFF00) | (uint8_t)(b)))
#define SET_HI(r, b) (REG(r) = (uint16_t)((REG(r) & 0x00FF) | (uint16_t)((uint8_t)(b)) << 8))
#define AL ((uint8_t)REG(AX))
#define AH ((uint8_t)(REG(AX) >> 8))

#define rd8 gs_rd8
#define rd16 gs_rd16
#define wr8 gs_wr8
#define wr16 gs_wr16

static void port_out(Pc *pc, uint16_t port, uint8_t v) { pc->cpu.bus.out8(pc->cpu.bus.ctx, port, v); }
static uint8_t port_in(Pc *pc, uint16_t port) { return pc->cpu.bus.in8(pc->cpu.bus.ctx, port); }

/* ADD r/m16, imm and its overflow flag (for the JNO after it). */
static uint16_t add_of(uint16_t a, uint16_t b, bool *of)
{
    uint16_t r = (uint16_t)(a + b);
    *of = ((a ^ r) & (b ^ r) & 0x8000) != 0;
    return r;
}

/* SAR r/m8 by n. */
static uint8_t sar8(uint8_t v, int n) { return (uint8_t)((int8_t)v >> n); }

/* ---- cycles ---------------------------------------------------------------------------- */

#define N_COST (sizeof key_ins_cost / sizeof key_ins_cost[0])
#define ENTRY_CYCLES 1

static const KeyInsCost *ins_at(uint16_t addr)
{
    size_t lo = 0, hi = N_COST;
    while (lo < hi) {
        size_t mid = (lo + hi) / 2;
        if (key_ins_cost[mid].addr < addr)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &key_ins_cost[lo];
}

/* The original executes every instruction in [from, to) in order (jumps fall through;
 * unconditional jumps cost what they cost). */
static void run(Pc *pc, uint16_t from, uint16_t to)
{
    for (const KeyInsCost *i = ins_at(from); i < key_ins_cost + N_COST && i->addr < to; i++)
        pc->cpu.cycles += i->cost;
}

/* The conditional jump at addr, already counted by run(), was taken. */
static void taken(Pc *pc, uint16_t addr)
{
    const KeyInsCost *i = ins_at(addr);
    pc->cpu.cycles += (uint64_t)i->taken - i->cost;
}

/* ---- calls ----------------------------------------------------------------------------- */

#define STEP_CAP 5000000L
#define RESET_CS 0xF000
#define RESET_IP 0xE05B

static bool at_reset(Pc *pc) { return SREG(CS) == RESET_CS && pc->cpu.ip == RESET_IP; }

/* Runs from 0050:target, as the CPU would with the natives on, until the routine returns
 * past the word on top of the stack (normally to it; key_repeat_accel returns one level
 * higher), or jumps to the reset entry (Ctrl+Alt+Del). */
static void run_from(Pc *pc, uint16_t target)
{
    Cpu8086 *c = &pc->cpu;
    uint16_t sp0 = c->regs[R_SP];
    const uint8_t *map = c->hook_map;
    c->sregs[S_CS] = GAME_CS;
    c->ip = target;
    for (long n = 0; n < STEP_CAP; n++) {
        bool done = false;
        if (map && c->sregs[S_CS] == GAME_CS && map[c->ip])
            done = native_call(pc, c->ip);
        if (!done) {
            c->hook_map = NULL; /* stepped here, so that no nested --verify starts */
            cpu_step(c);
            c->hook_map = map;
        }
        uint16_t d = (uint16_t)(c->regs[R_SP] - sp0);
        if ((d >= 2 && d < 0x8000) || at_reset(pc))
            break;
    }
}

/* Performs the near CALL instruction at 0050:at (E8 rel16): its cost, the push, the callee.
 * Returns true when the callee came back to the instruction after the CALL. */
static bool call(Pc *pc, uint16_t at)
{
    uint16_t ret_ip = (uint16_t)(at + 3);
    uint16_t target = (uint16_t)(ret_ip + mem_read16(pc, GAME_CS, (uint16_t)(at + 1)));
    run(pc, at, ret_ip);
    cpu_push(&pc->cpu, ret_ip);
    run_from(pc, target);
    return pc->cpu.ip == ret_ip && SREG(CS) == GAME_CS;
}

/* JMP rel16 at 0050:at to a routine that returns to our caller (a tail call). */
static void tail(Pc *pc, uint16_t at)
{
    uint16_t target = (uint16_t)(at + 3 + mem_read16(pc, GAME_CS, (uint16_t)(at + 1)));
    run(pc, at, (uint16_t)(at + 3));
    run_from(pc, target);
}

/* RET at 0050:at. */
static void ret(Pc *pc, uint16_t at)
{
    run(pc, at, (uint16_t)(at + 1));
    native_ret(pc);
}

/* ---- interrupts ------------------------------------------------------------------------- */

/* --verify attaches its write log only while it runs a routine; in normal play it is NULL. */
static bool under_verify(Pc *pc) { return pc->cpu.write_log != NULL; }

/* True when the timer (PIT channel 0) or the keyboard would raise an interrupt within n
 * cycles of the call that started at cycle `start` (as in 3.14 and 3.16; the PIT is advanced
 * only after a native returns, so its state is still the one at the start). */
static bool irq_due(Pc *pc, uint64_t start, uint64_t n)
{
    const PitChannel *t = &pc->pit[0];
    bool timer = pc->irq0_backlog || (t->loaded && t->count - (int64_t)((pc->pit_cycle_frac + n) / 4) <= 0);
    bool key = !pc->kbd_full && pc->kbd_head != pc->kbd_tail && start + n >= pc->kbd_next_cycle;
    return timer || key;
}

/* Device state the keyboard interrupt changes (port 60h read, port 61h pulse, EOI, the PIT
 * and vectors of key_enter): everything in Pc after mem/disk up to the speaker events, and
 * from speaker_count on (as native.c's --verify snapshot). */
#define DEV_A_START offsetof(Pc, pic_irr)
#define DEV_A_END offsetof(Pc, speaker)
#define DEV_B_START offsetof(Pc, speaker_count)
typedef struct DevState {
    uint8_t a[DEV_A_END - DEV_A_START];
    uint8_t b[sizeof(Pc) - DEV_B_START];
} DevState;

static void dev_save(const Pc *pc, DevState *d)
{
    SDL_memcpy(d->a, (const uint8_t *)pc + DEV_A_START, sizeof d->a);
    SDL_memcpy(d->b, (const uint8_t *)pc + DEV_B_START, sizeof d->b);
}

static void dev_load(Pc *pc, const DevState *d)
{
    SDL_memcpy((uint8_t *)pc + DEV_A_START, d->a, sizeof d->a);
    SDL_memcpy((uint8_t *)pc + DEV_B_START, d->b, sizeof d->b);
}

/* Hands the call back to the original: performs the routine's first instruction (natives
 * off), after which the CPU continues in the original routine, with interrupts. */
static void step_first(Pc *pc)
{
    Cpu8086 *c = &pc->cpu;
    const uint8_t *map = c->hook_map;
    c->hook_map = NULL;
    cpu_step(c);
    c->hook_map = map;
}

/* ---- 0050:0A0A-0A38 magnetos ---------------------------------------------------------- */

/* 0A19 magnetos_store: magnetos = AH, switch_text. */
static void b_magnetos_store(Pc *pc)
{
    run(pc, 0x0A19, 0x0A1D);
    gs_set_magnetos(pc, AH);
    call(pc, 0x0A1D); /* switch_text */
    ret(pc, 0x0A20);
}

/* 0A0D key_set_magnetos: AL bit 1 -> right switch, bit 0 -> left switch, AH -> magnetos. */
static void b_set_magnetos(Pc *pc)
{
    run(pc, 0x0A0D, 0x0A19);
    uint8_t al = AL;
    wr8(pc, (uint16_t)(GS_MAG_SWITCHES + 1), (uint8_t)(al >> 1));
    wr8(pc, GS_MAG_SWITCHES, (uint8_t)(al & 1));
    SET_LO(AX, al & 1);
    b_magnetos_store(pc);
}

static void mag_key(Pc *pc, uint16_t at, uint16_t ax)
{
    run(pc, at, (uint16_t)(at + 5));
    REG(AX) = ax;
    b_set_magnetos(pc);
}

static void b_key_mag_off(Pc *pc)
{
    run(pc, 0x0A0A, 0x0A0D);
    REG(AX) = 0;
    b_set_magnetos(pc);
}
static void b_key_mag_left(Pc *pc) { mag_key(pc, 0x0A21, 0x0102); }
static void b_key_mag_right(Pc *pc) { mag_key(pc, 0x0A26, 0x0201); }
static void b_key_mag_both(Pc *pc) { mag_key(pc, 0x0A2B, 0x0303); }
static void b_key_mag_start(Pc *pc) { mag_key(pc, 0x0A30, 0x0403); }
static void b_key_0(Pc *pc) { mag_key(pc, 0x0A35, 0x0500); }

/* ---- 0050:0A3A key_minus, 0B53 key_equals ---------------------------------------------- */

/* A transponder digit ('0'-'7'): mov al,[x] / cmp al,c / jne L1 / mov al,v / jmp S /
 * L1: dec|inc al / S: mov [x],al / jmp text_07c5. */
static void digit_step(Pc *pc, uint16_t e, uint16_t jne_at, uint16_t eqset, uint16_t l1, uint16_t store,
                       uint16_t end, uint16_t off, uint8_t cmpv, uint8_t setv, int delta)
{
    run(pc, e, eqset);
    uint8_t al = rd8(pc, off);
    if (al == cmpv) {
        run(pc, eqset, l1);
        al = setv;
    } else {
        taken(pc, jne_at);
        run(pc, l1, store);
        al = (uint8_t)(al + delta);
    }
    SET_LO(AX, al);
    run(pc, store, (uint16_t)(end - 3));
    wr8(pc, off, al);
    tail(pc, (uint16_t)(end - 3)); /* text_07c5 */
}

/* 0B91: store the COM MHz digits, tune. */
static void com_store_hi(Pc *pc)
{
    run(pc, 0x0B91, 0x0B96);
    wr16(pc, GS_COM_FREQ, REG(AX));
    tail(pc, 0x0BB8); /* com_tune */
}

static void com_store_lo(Pc *pc)
{
    run(pc, 0x0BB5, 0x0BB8);
    wr16(pc, (uint16_t)(GS_COM_FREQ + 5), REG(AX));
    tail(pc, 0x0BB8);
}

static void nav_store_hi(Pc *pc)
{
    run(pc, 0x0BD7, 0x0BDC);
    wr16(pc, GS_NAV_FREQ, REG(AX));
    tail(pc, 0x0BFE); /* nav_tune */
}

static void nav_store_lo(Pc *pc)
{
    run(pc, 0x0BFB, 0x0BFE);
    wr16(pc, (uint16_t)(GS_NAV_FREQ + 5), REG(AX));
    tail(pc, 0x0BFE);
}

/* Fractional digits ".00" -> ".95" -> ".90" ... (down) of COM (x = 07AB) or NAV (07B6). */
static void freq_lo_down(Pc *pc, uint16_t e, uint16_t off)
{
    /* e: mov ax,[x] / cmp ax,3030 / jne A / mov ax,3539 / jmp S
     * A (e+0D): cmp ah,30 / je B / mov ah,30 / jmp S / B (e+17): mov ah,35 / dec al / S */
    uint16_t a = (uint16_t)(e + 0x0D), b = (uint16_t)(e + 0x17), s = (uint16_t)(e + 0x1B);
    run(pc, e, (uint16_t)(e + 0x08));
    REG(AX) = rd16(pc, off);
    if (REG(AX) == 0x3030) {
        run(pc, (uint16_t)(e + 0x08), a);
        REG(AX) = 0x3539;
    } else {
        taken(pc, (uint16_t)(e + 0x06));
        run(pc, a, (uint16_t)(a + 5));
        if (AH == 0x30) {
            taken(pc, (uint16_t)(a + 3));
            run(pc, b, s);
            SET_HI(AX, 0x35);
            SET_LO(AX, AL - 1);
        } else {
            run(pc, (uint16_t)(a + 5), b);
            SET_HI(AX, 0x30);
        }
    }
    run(pc, s, (uint16_t)(s + 3)); /* jmp to the store */
}

static void b_key_minus(Pc *pc)
{
    run(pc, 0x0A3A, 0x0A49);
    uint8_t al = gs_selected_item(pc);
    gs_set_key_recent(pc, 0);
    bool zoom;
    if (gs_war_mode(pc) == 1) {
        taken(pc, 0x0A47);
        zoom = true;
    } else {
        run(pc, 0x0A49, 0x0A4D);
        al = (uint8_t)(al - 2);
        zoom = al == 0;
        if (!zoom)
            taken(pc, 0x0A4B);
    }
    SET_LO(AX, al);
    if (zoom) {
        run(pc, 0x0A4D, 0x0A5C);
        uint16_t lo = gs_rd16(pc, GS_RADAR_ZOOM), hi = gs_rd16(pc, (uint16_t)(GS_RADAR_ZOOM + 2));
        uint16_t nlo = (uint16_t)(lo << 1 | 1);
        uint16_t nhi = (uint16_t)(hi << 1 | lo >> 15);
        wr16(pc, GS_RADAR_ZOOM, nlo);
        wr16(pc, (uint16_t)(GS_RADAR_ZOOM + 2), nhi);
        wr16(pc, (uint16_t)(GS_RADAR_ZOOM + 2), (uint16_t)(nhi & 0x7FFF));
        ret(pc, 0x0A5C);
        return;
    }
    /* 0A5D: COM MHz */
    run(pc, 0x0A5D, 0x0A61);
    al = (uint8_t)(al - 2);
    SET_LO(AX, al);
    if (al == 0) {
        run(pc, 0x0A61, 0x0A69);
        REG(AX) = rd16(pc, GS_COM_FREQ);
        if (REG(AX) == 0x3831) {
            run(pc, 0x0A69, 0x0A6E);
            REG(AX) = 0x3533;
        } else {
            taken(pc, 0x0A67);
            run(pc, 0x0A6E, 0x0A75);
            SET_HI(AX, AH - 1);
            if (AH != 0x2F) {
                taken(pc, 0x0A73);
            } else {
                run(pc, 0x0A75, 0x0A79);
                SET_HI(AX, 0x39);
                SET_LO(AX, AL - 1);
            }
        }
        run(pc, 0x0A79, 0x0A7C);
        com_store_hi(pc);
        return;
    }
    taken(pc, 0x0A5F);
    /* 0A7C: COM fraction */
    run(pc, 0x0A7C, 0x0A80);
    SET_LO(AX, --al);
    if (al == 0) {
        freq_lo_down(pc, 0x0A80, (uint16_t)(GS_COM_FREQ + 5));
        com_store_lo(pc);
        return;
    }
    taken(pc, 0x0A7E);
    /* 0A9E: NAV MHz */
    run(pc, 0x0A9E, 0x0AA2);
    SET_LO(AX, --al);
    if (al == 0) {
        run(pc, 0x0AA2, 0x0AAA);
        REG(AX) = rd16(pc, GS_NAV_FREQ);
        if (REG(AX) == 0x3830) {
            run(pc, 0x0AAA, 0x0AAF);
            REG(AX) = 0x3731;
        } else {
            taken(pc, 0x0AA8);
            run(pc, 0x0AAF, 0x0AB6);
            SET_HI(AX, AH - 1);
            if (AH != 0x2F) {
                taken(pc, 0x0AB4);
            } else {
                run(pc, 0x0AB6, 0x0ABA);
                SET_HI(AX, 0x39);
                SET_LO(AX, AL - 1);
            }
        }
        run(pc, 0x0ABA, 0x0ABD);
        nav_store_hi(pc);
        return;
    }
    taken(pc, 0x0AA0);
    /* 0ABD: NAV fraction */
    run(pc, 0x0ABD, 0x0AC1);
    SET_LO(AX, --al);
    if (al == 0) {
        freq_lo_down(pc, 0x0AC1, (uint16_t)(GS_NAV_FREQ + 5));
        nav_store_lo(pc);
        return;
    }
    taken(pc, 0x0ABF);
    /* 0ADF..0B3B: transponder digits 1-4 */
    static const uint16_t tx[4][6] = {
        { 0x0ADF, 0x0AE3, 0x0AE8, 0x0AEA, 0x0AEE, 0x0AF0 },
        { 0x0AF6, 0x0AFA, 0x0AFF, 0x0B01, 0x0B05, 0x0B07 },
        { 0x0B0D, 0x0B11, 0x0B16, 0x0B18, 0x0B1C, 0x0B1E },
        { 0x0B24, 0x0B28, 0x0B2D, 0x0B2F, 0x0B33, 0x0B35 },
    };
    for (int i = 0; i < 4; i++) {
        run(pc, tx[i][0], tx[i][1]);
        SET_LO(AX, --al);
        if (al == 0) {
            digit_step(pc, tx[i][1], tx[i][2], tx[i][3], tx[i][4], tx[i][5], (uint16_t)(tx[i][5] + 6),
                       (uint16_t)(GS_TRANSPONDER + 1 + 2 * i), 0x30, 0x37, -1);
            return;
        }
        taken(pc, (uint16_t)(tx[i][0] + 2));
    }
    /* 0B3B: OBI course */
    run(pc, 0x0B3B, 0x0B3F);
    SET_LO(AX, --al);
    if (al != 0) {
        taken(pc, 0x0B3D);
        ret(pc, 0x0B52);
        return;
    }
    run(pc, 0x0B3F, 0x0B4A);
    uint8_t crs = (uint8_t)(rd8(pc, GS_OBI_COURSE) - 1);
    wr8(pc, GS_OBI_COURSE, crs);
    if (crs != 0xFF) {
        taken(pc, 0x0B48);
    } else {
        run(pc, 0x0B4A, 0x0B4F);
        wr8(pc, GS_OBI_COURSE, 0xB3);
    }
    tail(pc, 0x0B4F); /* obi_readout */
}

/* Fractional digits up: ".95" -> ".00", ".x0" -> ".x5", ".x5" -> ".(x+1)0". */
static void freq_lo_up(Pc *pc, uint16_t e, uint16_t off, bool nop_after_eq)
{
    /* e: mov ax,[x] / cmp ax,3539 / jne A / mov ax,3030 / jmp S [/ nop]
     * A: cmp ah,35 / je B / mov ah,35 / jmp S / B: mov ah,30 / inc al / S */
    uint16_t a = (uint16_t)(e + (nop_after_eq ? 0x0E : 0x0D));
    uint16_t b = (uint16_t)(a + 9), s = (uint16_t)(b + 4);
    run(pc, e, (uint16_t)(e + 0x08));
    REG(AX) = rd16(pc, off);
    if (REG(AX) == 0x3539) {
        run(pc, (uint16_t)(e + 0x08), a);
        REG(AX) = 0x3030;
    } else {
        taken(pc, (uint16_t)(e + 0x06));
        run(pc, a, (uint16_t)(a + 5));
        if (AH == 0x35) {
            taken(pc, (uint16_t)(a + 3));
            run(pc, b, s);
            SET_HI(AX, 0x30);
            SET_LO(AX, AL + 1);
        } else {
            run(pc, (uint16_t)(a + 5), b);
            SET_HI(AX, 0x35);
        }
    }
}

static void b_key_equals(Pc *pc)
{
    run(pc, 0x0B53, 0x0B62);
    uint8_t al = gs_selected_item(pc);
    gs_set_key_recent(pc, 0);
    bool zoom;
    if (gs_war_mode(pc) == 1) {
        taken(pc, 0x0B60);
        zoom = true;
    } else {
        run(pc, 0x0B62, 0x0B66);
        al = (uint8_t)(al - 2);
        zoom = al == 0;
        if (!zoom)
            taken(pc, 0x0B64);
    }
    SET_LO(AX, al);
    if (zoom) {
        run(pc, 0x0B66, 0x0B74);
        uint16_t lo = gs_rd16(pc, GS_RADAR_ZOOM), hi = gs_rd16(pc, (uint16_t)(GS_RADAR_ZOOM + 2));
        uint16_t nhi = (uint16_t)((int16_t)hi >> 1);
        uint16_t nlo = (uint16_t)(lo >> 1 | (hi & 1) << 15);
        wr16(pc, (uint16_t)(GS_RADAR_ZOOM + 2), nhi);
        wr16(pc, GS_RADAR_ZOOM, nlo);
        wr16(pc, GS_RADAR_ZOOM, (uint16_t)(nlo | 0x1FFF));
        ret(pc, 0x0B74);
        return;
    }
    /* 0B75: COM MHz */
    run(pc, 0x0B75, 0x0B79);
    al = (uint8_t)(al - 2);
    SET_LO(AX, al);
    if (al == 0) {
        run(pc, 0x0B79, 0x0B81);
        REG(AX) = rd16(pc, GS_COM_FREQ);
        if (REG(AX) == 0x3533) {
            run(pc, 0x0B81, 0x0B86);
            REG(AX) = 0x3831;
        } else {
            taken(pc, 0x0B7F);
            run(pc, 0x0B86, 0x0B8D);
            SET_HI(AX, AH + 1);
            if (AH != 0x3A) {
                taken(pc, 0x0B8B);
            } else {
                run(pc, 0x0B8D, 0x0B91);
                SET_HI(AX, 0x30);
                SET_LO(AX, AL + 1);
            }
        }
        com_store_hi(pc);
        return;
    }
    taken(pc, 0x0B77);
    /* 0B97: COM fraction */
    run(pc, 0x0B97, 0x0B9B);
    SET_LO(AX, --al);
    if (al == 0) {
        freq_lo_up(pc, 0x0B9B, (uint16_t)(GS_COM_FREQ + 5), false);
        com_store_lo(pc);
        return;
    }
    taken(pc, 0x0B99);
    /* 0BBB: NAV MHz */
    run(pc, 0x0BBB, 0x0BBF);
    SET_LO(AX, --al);
    if (al == 0) {
        run(pc, 0x0BBF, 0x0BC7);
        REG(AX) = rd16(pc, GS_NAV_FREQ);
        if (REG(AX) == 0x3731) {
            run(pc, 0x0BC7, 0x0BCC);
            REG(AX) = 0x3830;
        } else {
            taken(pc, 0x0BC5);
            run(pc, 0x0BCC, 0x0BD3);
            SET_HI(AX, AH + 1);
            if (AH != 0x3A) {
                taken(pc, 0x0BD1);
            } else {
                run(pc, 0x0BD3, 0x0BD7);
                SET_HI(AX, 0x30);
                SET_LO(AX, AL + 1);
            }
        }
        nav_store_hi(pc);
        return;
    }
    taken(pc, 0x0BBD);
    /* 0BDC: NAV fraction */
    run(pc, 0x0BDC, 0x0BE0);
    SET_LO(AX, --al);
    if (al == 0) {
        freq_lo_up(pc, 0x0BE0, (uint16_t)(GS_NAV_FREQ + 5), true);
        nav_store_lo(pc);
        return;
    }
    taken(pc, 0x0BDE);
    /* 0C01..0C61: transponder digits 1-4 */
    static const uint16_t tx[4][6] = {
        { 0x0C01, 0x0C05, 0x0C0A, 0x0C0C, 0x0C11, 0x0C13 },
        { 0x0C19, 0x0C1D, 0x0C22, 0x0C24, 0x0C29, 0x0C2B },
        { 0x0C31, 0x0C35, 0x0C3A, 0x0C3C, 0x0C41, 0x0C43 },
        { 0x0C49, 0x0C4D, 0x0C52, 0x0C54, 0x0C59, 0x0C5B },
    };
    for (int i = 0; i < 4; i++) {
        run(pc, tx[i][0], tx[i][1]);
        SET_LO(AX, --al);
        if (al == 0) {
            digit_step(pc, tx[i][1], tx[i][2], tx[i][3], tx[i][4], tx[i][5], (uint16_t)(tx[i][5] + 6),
                       (uint16_t)(GS_TRANSPONDER + 1 + 2 * i), 0x37, 0x30, +1);
            return;
        }
        taken(pc, (uint16_t)(tx[i][0] + 2));
    }
    /* 0C61: OBI course */
    run(pc, 0x0C61, 0x0C65);
    SET_LO(AX, --al);
    if (al != 0) {
        taken(pc, 0x0C63);
        ret(pc, 0x0C78);
        return;
    }
    run(pc, 0x0C65, 0x0C70);
    uint8_t crs = (uint8_t)(rd8(pc, GS_OBI_COURSE) + 1);
    wr8(pc, GS_OBI_COURSE, crs);
    if (crs != 0xB4) {
        taken(pc, 0x0C6E);
    } else {
        run(pc, 0x0C70, 0x0C75);
        wr8(pc, GS_OBI_COURSE, 0);
    }
    tail(pc, 0x0C75); /* obi_readout */
}

/* ---- 0050:0A04-0DD2 the other keys ------------------------------------------------------ */

static void b_key_esc_editor(Pc *pc)
{
    run(pc, 0x0A04, 0x0A09);
    gs_set_editor_active(pc, 1);
    ret(pc, 0x0A09);
}

/* Tab: CRTC R2 (horizontal sync position) - 1, wrapping from 26h to 2Eh, then
 * cga_program_regs with the BX it was given (the dispatcher's 2 * scancode = 1Eh). */
static void b_key_tab(Pc *pc)
{
    run(pc, 0x0C79, 0x0C82);
    uint8_t al = (uint8_t)(gs_cga_init_table_b(pc, 13) - 1);
    if ((int8_t)al >= 0x27) {
        taken(pc, 0x0C80);
    } else {
        run(pc, 0x0C82, 0x0C84);
        al = 0x2E;
    }
    SET_LO(AX, al);
    run(pc, 0x0C84, 0x0C87);
    gs_set_cga_init_table_b(pc, 13, al);
    tail(pc, 0x0C87); /* cga_program_regs */
}

static void b_key_w(Pc *pc)
{
    run(pc, 0x0C8A, 0x0C8F);
    gs_set_war_status_line(pc, (uint8_t)(gs_war_status_line(pc) | 1));
    ret(pc, 0x0C8F);
}

static void b_key_t(Pc *pc)
{
    run(pc, 0x0C90, 0x0C97);
    if (gs_slew_mode(pc)) {
        /* slew: the aircraft takes the view's attitude */
        run(pc, 0x0C97, 0x0CAD);
        gs_set_pitch(pc, (int16_t)-gs_view_pitch(pc));
        gs_set_bank(pc, (int16_t)-gs_view_bank(pc));
        REG(AX) = (uint16_t)gs_view_heading(pc);
        gs_set_heading(pc, (int16_t)REG(AX));
        ret(pc, 0x0CAD);
        return;
    }
    taken(pc, 0x0C95);
    run(pc, 0x0CAE, 0x0CB5);
    bool next = false;
    if (gs_key_recent(pc) == 0) {
        taken(pc, 0x0CB3);
    } else {
        run(pc, 0x0CB5, 0x0CBC);
        int8_t sel = (int8_t)gs_selected_item(pc);
        if (sel < 8) {
            taken(pc, 0x0CBA);
        } else {
            run(pc, 0x0CBC, 0x0CC3);
            if (sel > 0x0B)
                taken(pc, 0x0CC1);
            else
                next = true;
        }
    }
    if (next) {
        run(pc, 0x0CC3, 0x0CC9);
        gs_set_selected_item(pc, (uint8_t)(gs_selected_item(pc) + 1));
    } else {
        run(pc, 0x0CCA, 0x0CCF);
        gs_set_selected_item(pc, 8);
    }
    run(pc, 0x0CCF, 0x0CD4);
    gs_set_key_recent(pc, 0x12);
    ret(pc, 0x0CD4);
}

static void b_key_p_pause(Pc *pc)
{
    run(pc, 0x0CD5, 0x0CD9);
    gs_set_paused(pc, (uint8_t)~gs_paused(pc));
    ret(pc, 0x0CD9);
}

static void b_key_a(Pc *pc)
{
    run(pc, 0x0CDA, 0x0CE2);
    REG(AX) = 0;
    gs_set_altimeter_offset(pc, 0);
    gs_set_takeoff_spot(pc, 0);
    ret(pc, 0x0CE2);
}

static void b_key_d(Pc *pc)
{
    run(pc, 0x0CE3, 0x0CF5);
    REG(AX) = (uint16_t)(gs_hdg_display(pc) - (uint16_t)gs_view_heading(pc) + (uint16_t)gs_wind_gust_offset(pc) +
                         (uint16_t)gs_wind_dir_offset(pc));
    gs_set_dg_offset(pc, REG(AX));
    ret(pc, 0x0CF5);
}

/* 0D11: jmp switch_text */
static void to_switch_text(Pc *pc) { tail(pc, 0x0D11); }

/* 0D0B: gear_drag = gear_drag_down. */
static void gear_drag_0d0b(Pc *pc, uint16_t ax)
{
    run(pc, 0x0D0E, 0x0D11);
    REG(AX) = ax;
    gs_set_gear_drag(pc, (int16_t)ax);
    to_switch_text(pc);
}

static void b_gear_drag_update(Pc *pc)
{
    run(pc, 0x0D01, 0x0D0B);
    REG(AX) = gs_gear_drag_up(pc);
    if (gs_gear_down(pc) == 0) {
        taken(pc, 0x0D09);
        gear_drag_0d0b(pc, REG(AX));
        return;
    }
    run(pc, 0x0D0B, 0x0D0E);
    gear_drag_0d0b(pc, gs_gear_drag_down(pc));
}

static void b_key_g_gear(Pc *pc)
{
    run(pc, 0x0CF6, 0x0CFD);
    if (gs_on_ground(pc) != 0) {
        taken(pc, 0x0CFB);
        run(pc, 0x0D0B, 0x0D0E);
        gear_drag_0d0b(pc, gs_gear_drag_down(pc));
        return;
    }
    run(pc, 0x0CFD, 0x0D01);
    gs_set_gear_down(pc, (uint8_t)~gs_gear_down(pc));
    b_gear_drag_update(pc);
}

static void b_key_h_carb_heat(Pc *pc)
{
    run(pc, 0x0D14, 0x0D1A);
    gs_set_carb_heat(pc, (uint8_t)~gs_carb_heat(pc));
    to_switch_text(pc);
}

static void b_key_l_lights(Pc *pc)
{
    run(pc, 0x0D1A, 0x0D20);
    gs_set_lights(pc, (uint8_t)~gs_lights(pc));
    to_switch_text(pc);
}

static void b_key_x_bomb(Pc *pc)
{
    run(pc, 0x0D20, 0x0D27);
    if (gs_war_mode(pc) != 1) {
        taken(pc, 0x0D25);
        ret(pc, 0x0D4A);
        return;
    }
    run(pc, 0x0D27, 0x0D2E);
    if (gs_bombs_left(pc) == 0x30) {
        taken(pc, 0x0D2C);
        ret(pc, 0x0D4A);
        return;
    }
    run(pc, 0x0D2E, 0x0D35);
    if (gs_bomb_state(pc) != 0) {
        taken(pc, 0x0D33);
        ret(pc, 0x0D4A);
        return;
    }
    run(pc, 0x0D35, 0x0D4A);
    gs_set_bombs_left(pc, (uint8_t)(gs_bombs_left(pc) - 1));
    REG(AX) = gs_alt_m(pc);
    gs_set_bomb_state(pc, REG(AX));
    gs_set_bomb_whistle(pc, 0x64);
    gs_set_sound_state(pc, 4);
    ret(pc, 0x0D4A);
}

/* C and N: select the radio; again within key_recent frames: its second field. */
static void select_radio(Pc *pc, uint16_t e, uint8_t item)
{
    /* e: [mov com_search,1 /] cmp key_recent,0 / je L / cmp sel,item / jne L / inc sel / ret
     * L: mov sel,item / mov key_recent,12h / ret */
    uint16_t c1 = e, l = (uint16_t)(e + 0x13);
    run(pc, c1, (uint16_t)(c1 + 7));
    if (gs_key_recent(pc) == 0) {
        taken(pc, (uint16_t)(c1 + 5));
    } else {
        run(pc, (uint16_t)(c1 + 7), (uint16_t)(c1 + 0x0E));
        if (gs_selected_item(pc) != item) {
            taken(pc, (uint16_t)(c1 + 0x0C));
        } else {
            run(pc, (uint16_t)(c1 + 0x0E), (uint16_t)(c1 + 0x12));
            gs_set_selected_item(pc, (uint8_t)(item + 1));
            ret(pc, (uint16_t)(c1 + 0x12));
            return;
        }
    }
    run(pc, l, (uint16_t)(l + 0x0A));
    gs_set_selected_item(pc, item);
    gs_set_key_recent(pc, 0x12);
    ret(pc, (uint16_t)(l + 0x0A));
}

static void b_key_c_com(Pc *pc)
{
    run(pc, 0x0D4B, 0x0D50);
    gs_set_com_search(pc, 1);
    select_radio(pc, 0x0D50, 4);
}

static void b_key_v_obi(Pc *pc)
{
    run(pc, 0x0D6E, 0x0D73);
    gs_set_selected_item(pc, 0x0C);
    ret(pc, 0x0D73);
}

static void b_key_n_nav(Pc *pc) { select_radio(pc, 0x0D74, 6); }

static void b_key_m_nop(Pc *pc) { ret(pc, 0x0D92); }

static void b_key_period_brakes(Pc *pc)
{
    run(pc, 0x0D93, 0x0D9A);
    if (!gs_on_ground(pc)) {
        taken(pc, 0x0D98);
        ret(pc, 0x0DA7);
        return;
    }
    run(pc, 0x0D9A, 0x0DA2);
    REG(AX) = (uint16_t)(gs_airspeed(pc) - 0x100);
    if (!(REG(AX) & 0x8000)) {
        taken(pc, 0x0DA0);
    } else {
        run(pc, 0x0DA2, 0x0DA4);
        REG(AX) = 0;
    }
    run(pc, 0x0DA4, 0x0DA7);
    gs_set_airspeed(pc, REG(AX));
    ret(pc, 0x0DA7);
}

static void b_key_kpstar_reset(Pc *pc)
{
    call(pc, 0x0DA8); /* usermode_recall */
    call(pc, 0x0DAB); /* editor_apply_state */
    ret(pc, 0x0DAE);
}

static void b_key_alt_slew_level(Pc *pc)
{
    run(pc, 0x0DAF, 0x0DB6);
    if (!gs_slew_mode(pc)) {
        taken(pc, 0x0DB4);
        ret(pc, 0x0DC4);
        return;
    }
    run(pc, 0x0DB6, 0x0DC4);
    REG(AX) = 0;
    gs_set_view_bank(pc, 0);
    gs_set_view_heading(pc, 0);
    gs_set_view_pitch(pc, 0x4000);
    ret(pc, 0x0DC4);
}

static void b_key_space_guns(Pc *pc)
{
    run(pc, 0x0DC5, 0x0DCD);
    if (!(gs_ammo(pc) & 0xFF)) {
        taken(pc, 0x0DCB);
        ret(pc, 0x0DD2);
        return;
    }
    run(pc, 0x0DCD, 0x0DD2);
    gs_set_gun_burst(pc, 3);
    ret(pc, 0x0DD2);
}

/* ---- 0050:0DD3-0E33 flaps --------------------------------------------------------------- */

static void b_set_flaps(Pc *pc)
{
    run(pc, 0x0DD9, 0x0DED);
    REG(BP) = GS_IND_FLAPS;
    uint8_t al = sar8((uint8_t)(0x7F - (uint8_t)(gs_flaps(pc) >> 8)), 4);
    SET_LO(AX, al);
    gs_set_ind_flaps_b(pc, 6, al);
    call(pc, 0x0DED); /* draw_indicator */
    run(pc, 0x0DF0, 0x0DFB);
    uint32_t p = (uint32_t)gs_flaps_cl_k(pc) * gs_flaps(pc);
    REG(AX) = (uint16_t)p;
    REG(DX) = (uint16_t)(p >> 16);
    gs_set_flaps_cl(pc, (int16_t)REG(DX));
    call(pc, 0x0DFB); /* wing_cl_offsets */
    run(pc, 0x0DFE, 0x0E14);
    p = (uint32_t)gs_flaps(pc) * gs_flaps_drag_k(pc);
    gs_set_flaps_drag(pc, (int16_t)(uint16_t)(p >> 16));
    int32_t s = (int32_t)(int16_t)gs_flaps(pc) * gs_flaps_view_k(pc);
    REG(AX) = (uint16_t)s;
    REG(DX) = (uint16_t)((uint32_t)s >> 16);
    gs_set_flaps_view(pc, (int16_t)REG(DX));
    ret(pc, 0x0E14);
}

static void flaps_key(Pc *pc, uint16_t at, uint16_t to, uint16_t flaps)
{
    run(pc, at, to);
    gs_set_flaps(pc, flaps);
    b_set_flaps(pc);
}

static void b_key_flaps_up(Pc *pc) { flaps_key(pc, 0x0DD3, 0x0DD9, 0); }
static void b_key_flaps_10(Pc *pc) { flaps_key(pc, 0x0E15, 0x0E1D, 0x2000); }
static void b_key_flaps_20(Pc *pc) { flaps_key(pc, 0x0E1D, 0x0E25, 0x4000); }
static void b_key_flaps_30(Pc *pc) { flaps_key(pc, 0x0E25, 0x0E2D, 0x6000); }
static void b_key_flaps_40(Pc *pc) { flaps_key(pc, 0x0E2D, 0x0E35, 0x7FFF); }

/* ---- 0050:0E35-0EA3 throttle ----------------------------------------------------------- */

static void b_throttle_indicator(Pc *pc)
{
    run(pc, 0x0E6A, 0x0E77);
    REG(BP) = GS_IND_THROTTLE;
    uint8_t al = sar8((uint8_t)(gs_throttle(pc) >> 8), 2);
    SET_LO(AX, al);
    gs_set_ind_throttle_b(pc, 6, al);
    call(pc, 0x0E77); /* draw_indicator */
    ret(pc, 0x0E7A);
}

/* 0E64: throttle = 7FFFh. */
static void throttle_full_0e64(Pc *pc)
{
    run(pc, 0x0E64, 0x0E6A);
    gs_set_throttle(pc, 0x7FFF);
    b_throttle_indicator(pc);
}

/* 0E41: jno throttle_indicator / jmp 0E64 */
static void throttle_0e41(Pc *pc, bool of)
{
    run(pc, 0x0E41, 0x0E43);
    if (!of) {
        taken(pc, 0x0E41);
        b_throttle_indicator(pc);
        return;
    }
    run(pc, 0x0E43, 0x0E45);
    throttle_full_0e64(pc);
}

static void throttle_add(Pc *pc, uint16_t at, uint16_t to, uint16_t delta, uint16_t target)
{
    run(pc, at, to);
    bool of;
    gs_set_throttle(pc, add_of(gs_throttle(pc), delta, &of));
    gs_set_throttle_target(pc, target);
    throttle_0e41(pc, of);
}

static void b_key_throttle_inc(Pc *pc) { throttle_add(pc, 0x0E35, 0x0E41, 0x0800, 0x2000); }
static void b_key_throttle_inc_small(Pc *pc) { throttle_add(pc, 0x0E7B, 0x0E89, 0x0400, 0x4000); }

static void b_key_throttle_full(Pc *pc)
{
    run(pc, 0x0E45, 0x0E52);
    gs_set_throttle_target(pc, 0);
    if (gs_reality_mode(pc) == 0) {
        taken(pc, 0x0E50);
        throttle_full_0e64(pc);
        return;
    }
    run(pc, 0x0E52, 0x0E59);
    SET_LO(AX, (uint8_t)gs_frame_counter(pc) & 3);
    if (AL) {
        taken(pc, 0x0E57);
        throttle_full_0e64(pc);
        return;
    }
    run(pc, 0x0E59, 0x0E61);
    if ((int16_t)gs_throttle(pc) >= 0x3E80) {
        taken(pc, 0x0E5F);
    } else {
        call(pc, 0x0E61); /* engine_stop: full throttle at once stalls the engine (reality mode) */
    }
    throttle_full_0e64(pc);
}

static void b_key_throttle_cut(Pc *pc)
{
    run(pc, 0x0E97, 0x0EA5);
    gs_set_throttle(pc, 0);
    gs_set_throttle_target(pc, 0x7FFF);
    b_throttle_indicator(pc);
}

static void b_key_throttle_dec(Pc *pc)
{
    run(pc, 0x0E89, 0x0E97);
    uint16_t t = (uint16_t)(gs_throttle(pc) - 0x0800);
    gs_set_throttle(pc, t);
    gs_set_throttle_target(pc, 0x6000);
    if (!(t & 0x8000)) {
        taken(pc, 0x0E95);
        b_throttle_indicator(pc);
        return;
    }
    b_key_throttle_cut(pc);
}

/* ---- 0050:0EA5-0EC2 radar, view selection ----------------------------------------------- */

static void b_key_radar_on(Pc *pc)
{
    run(pc, 0x0EA5, 0x0EAF);
    gs_set_selected_item(pc, 2);
    gs_set_radar_view(pc, 1);
    ret(pc, 0x0EAF);
}

/* Scroll Lock: radar off, or (radar already off) selected_item = 1: the next keypad key
 * picks a view direction (key_repeat_accel). */
static void b_key_radar_off(Pc *pc)
{
    run(pc, 0x0EB0, 0x0EB7);
    if (gs_radar_view(pc)) {
        taken(pc, 0x0EB5);
        run(pc, 0x0EBD, 0x0EC2);
        gs_set_radar_view(pc, 0);
        ret(pc, 0x0EC2);
        return;
    }
    run(pc, 0x0EB7, 0x0EBC);
    gs_set_selected_item(pc, 1);
    ret(pc, 0x0EBC);
}

/* 0050:109B key_repeat_accel: BL = keypad key index. With selected_item = 1 it takes the
 * key as a view direction and returns from the key handler (pops the return address). */
static void b_key_repeat_accel(Pc *pc)
{
    run(pc, 0x109B, 0x10A2);
    if (gs_selected_item(pc) != 1) {
        ret(pc, 0x10A2);
        return;
    }
    taken(pc, 0x10A0);
    run(pc, 0x10A3, 0x10B5);
    gs_set_selected_item(pc, 0);
    REG(BX) &= 0x00FF;
    REG(AX) = rd16(pc, (uint16_t)(GS_VIEW_DIR_FNS + REG(BX)));
    gs_set_view_dir_fn(pc, REG(AX));
    wr16(pc, GS_VIEW_NOT_FORWARD, REG(BX));
    REG(AX) = cpu_pop(&pc->cpu);
    ret(pc, 0x10B5);
}

/* mov bl,idx / call key_repeat_accel at `at`. False: it returned from the key handler. */
static bool call_rep(Pc *pc, uint16_t at, uint8_t idx)
{
    run(pc, (uint16_t)(at - 2), at);
    SET_LO(BX, idx);
    return call(pc, at);
}

/* ---- 0050:0EC3-0EF2 trim, 0EF4 / 1044 slew rates -------------------------------------- */

/* 0EDC key_ignore: trim indicator (also every unbound key). */
static void b_key_ignore(Pc *pc)
{
    run(pc, 0x0EDC, 0x0EEF);
    REG(BP) = GS_IND_TRIM;
    uint8_t al = (uint8_t)(sar8((uint8_t)((uint16_t)gs_elevator_trim(pc) >> 8), 4) + 8);
    SET_LO(AX, al);
    gs_set_ind_trim_b(pc, 6, al);
    call(pc, 0x0EEF); /* draw_indicator */
    ret(pc, 0x0EF2);
}

static void b_key_trim_down(Pc *pc)
{
    if (!call_rep(pc, 0x0EC5, 0x0E))
        return;
    run(pc, 0x0EC8, 0x0ED6);
    gs_set_slew_rate_a(pc, (int16_t)(gs_slew_rate_a(pc) + 0x80));
    bool of;
    gs_set_elevator_trim(pc, (int16_t)add_of((uint16_t)gs_elevator_trim(pc), 0xFC00, &of));
    if (!of) {
        taken(pc, 0x0ED4);
    } else {
        run(pc, 0x0ED6, 0x0EDC);
        gs_set_elevator_trim(pc, (int16_t)0x8001);
    }
    b_key_ignore(pc);
}

static void b_key_trim_up(Pc *pc)
{
    if (!call_rep(pc, 0x100A, 0x0A))
        return;
    run(pc, 0x100D, 0x101B);
    gs_set_slew_rate_b(pc, (int16_t)(gs_slew_rate_b(pc) + 0x80));
    bool of;
    gs_set_elevator_trim(pc, (int16_t)add_of((uint16_t)gs_elevator_trim(pc), 0x0400, &of));
    if (!of) {
        taken(pc, 0x1019);
    } else {
        run(pc, 0x101B, 0x1021);
        gs_set_elevator_trim(pc, 0x7FFF);
    }
    run(pc, 0x1021, 0x1024);
    b_key_ignore(pc);
}

static void b_key_kp9_slew(Pc *pc)
{
    if (!call_rep(pc, 0x0EF6, 2))
        return;
    run(pc, 0x0EF9, 0x0EFF);
    gs_set_slew_rate_a(pc, (int16_t)(gs_slew_rate_a(pc) - 0x80));
    ret(pc, 0x0EFF);
}

static void b_key_kp3_slew(Pc *pc)
{
    if (!call_rep(pc, 0x1046, 6))
        return;
    run(pc, 0x1049, 0x104F);
    gs_set_slew_rate_b(pc, (int16_t)(gs_slew_rate_b(pc) - 0x80));
    ret(pc, 0x104F);
}

/* ---- 0050:0F00-0F4A, 1024 elevator ------------------------------------------------------ */

static void b_elevator_update(Pc *pc)
{
    run(pc, 0x0F25, 0x0F36);
    REG(BP) = GS_IND_ELEVATOR;
    uint8_t al = (uint8_t)(sar8((uint8_t)((uint16_t)gs_elevator(pc) >> 8), 3) + 0x0B);
    SET_LO(AX, al);
    gs_set_ind_elevator_b(pc, 6, al);
    call(pc, 0x0F36); /* draw_indicator */
    run(pc, 0x0F39, 0x0F4A);
    REG(DX) = (uint16_t)gs_elevator(pc);
    int32_t s = (int32_t)gs_elevator_aoa_k(pc) * (int16_t)REG(DX);
    uint16_t ax = (uint16_t)s, dx = (uint16_t)((uint32_t)s >> 16);
    REG(DX) = (uint16_t)(dx << 1 | ax >> 15);
    REG(AX) = (uint16_t)(ax << 1);
    gs_set_elev_aoa(pc, (int16_t)REG(DX));
    ret(pc, 0x0F4A);
}

/* 0F1D: elevator = AX, key_recent = 8. */
static void elevator_0f1d(Pc *pc)
{
    run(pc, 0x0F1D, 0x0F25);
    gs_set_elevator(pc, (int16_t)REG(AX));
    gs_set_key_recent(pc, 8);
    b_elevator_update(pc);
}

static void b_key_elevator_down(Pc *pc)
{
    if (!call_rep(pc, 0x0F02, 0))
        return;
    run(pc, 0x0F05, 0x0F12);
    REG(AX) = (uint16_t)((uint16_t)gs_elevator(pc) + 0xFF00);
    if (gs_key_recent(pc) == 0) {
        taken(pc, 0x0F10);
    } else {
        run(pc, 0x0F12, 0x0F15);
        REG(AX) = (uint16_t)(REG(AX) + 0xF900);
    }
    run(pc, 0x0F15, 0x0F1A);
    if ((int16_t)REG(AX) >= (int16_t)0xB000) {
        taken(pc, 0x0F18);
    } else {
        run(pc, 0x0F1A, 0x0F1D);
        REG(AX) = 0xB000;
    }
    elevator_0f1d(pc);
}

static void b_key_elevator_up(Pc *pc)
{
    if (!call_rep(pc, 0x1026, 8))
        return;
    run(pc, 0x1029, 0x1036);
    REG(AX) = (uint16_t)((uint16_t)gs_elevator(pc) + 0x100);
    if (gs_key_recent(pc) == 0) {
        taken(pc, 0x1034);
    } else {
        run(pc, 0x1036, 0x1039);
        REG(AX) = (uint16_t)(REG(AX) + 0x700);
    }
    run(pc, 0x1039, 0x103E);
    if ((int16_t)REG(AX) <= 0x5000) {
        taken(pc, 0x103C);
    } else {
        run(pc, 0x103E, 0x1041);
        REG(AX) = 0x5000;
    }
    run(pc, 0x1041, 0x1044);
    elevator_0f1d(pc);
}

/* ---- 0050:0F4B-1007, 1050 ailerons and rudder ------------------------------------------- */

static void b_rudder_indicator(Pc *pc)
{
    run(pc, 0x0FF2, 0x1001);
    REG(BP) = GS_IND_RUDDER;
    uint8_t al = (uint8_t)(sar8((uint8_t)((uint16_t)gs_rudder(pc) >> 8), 2) + 0x21);
    SET_LO(AX, al);
    gs_set_ind_rudder_b(pc, 6, al);
    call(pc, 0x1001); /* draw_indicator */
    call(pc, 0x1004); /* control_coupling */
    ret(pc, 0x1007);
}

static void b_aileron_indicator(Pc *pc)
{
    run(pc, 0x0FB3, 0x0FC2);
    REG(BP) = GS_IND_AILERON;
    uint8_t al = (uint8_t)(sar8((uint8_t)((uint16_t)gs_aileron(pc) >> 8), 2) + 0x21);
    SET_LO(AX, al);
    gs_set_ind_aileron_b(pc, 6, al);
    call(pc, 0x0FC2); /* draw_indicator */
    run(pc, 0x0FC5, 0x0FD0);
    int32_t s = (int32_t)gs_aileron(pc) * gs_aileron_cl_k(pc);
    REG(AX) = (uint16_t)s;
    REG(DX) = (uint16_t)((uint32_t)s >> 16);
    gs_set_aileron_cl(pc, (int16_t)REG(DX));
    call(pc, 0x0FD0); /* control_coupling */
    ret(pc, 0x0FD3);
}

static void b_aileron_update(Pc *pc)
{
    run(pc, 0x0FA3, 0x0FAA);
    if (!gs_auto_coordination(pc)) {
        taken(pc, 0x0FA8);
    } else {
        run(pc, 0x0FAA, 0x0FB0);
        REG(AX) = (uint16_t)gs_aileron(pc);
        gs_set_rudder(pc, (int16_t)REG(AX));
        call(pc, 0x0FB0); /* rudder_indicator */
    }
    b_aileron_indicator(pc);
}

static void b_rudder_update(Pc *pc)
{
    run(pc, 0x0FE2, 0x0FE9);
    if (!gs_auto_coordination(pc)) {
        taken(pc, 0x0FE7);
    } else {
        run(pc, 0x0FE9, 0x0FEF);
        REG(AX) = (uint16_t)gs_rudder(pc);
        gs_set_aileron(pc, (int16_t)REG(AX));
        call(pc, 0x0FEF); /* aileron_indicator */
    }
    b_rudder_indicator(pc);
}

static void b_aileron_rudder_update(Pc *pc)
{
    call(pc, 0x0F8A); /* aileron_update */
    run(pc, 0x0F8D, 0x0F8F);
    b_rudder_update(pc);
}

/* aileron/rudder += delta, saturating at clampv; then jno target / mov clampv / jmp target. */
static void control_add(Pc *pc, uint16_t at, uint16_t jno_end, uint16_t sat_end, uint16_t off, uint16_t delta,
                        uint16_t clampv, void (*next)(Pc *))
{
    run(pc, at, jno_end);
    bool of;
    wr16(pc, off, add_of(rd16(pc, off), delta, &of));
    if (!of) {
        taken(pc, (uint16_t)(jno_end - 2));
    } else {
        run(pc, jno_end, sat_end);
        wr16(pc, off, clampv);
    }
    next(pc);
}

static void b_key_aileron_left(Pc *pc)
{
    if (!call_rep(pc, 0x0F4D, 0x0C))
        return;
    control_add(pc, 0x0F50, 0x0F58, 0x0F60, GS_AILERON, 0xFC00, 0x8001, b_aileron_update);
}

static void b_key_aileron_right(Pc *pc)
{
    if (!call_rep(pc, 0x0F92, 4))
        return;
    control_add(pc, 0x0F95, 0x0F9D, 0x0FA3, GS_AILERON, 0x0400, 0x7FFF, b_aileron_update);
}

static void b_key_rudder_right(Pc *pc)
{
    control_add(pc, 0x0FD4, 0x0FDC, 0x0FE2, GS_RUDDER, 0x0400, 0x7FFF, b_rudder_update);
}

static void b_key_rudder_left(Pc *pc)
{
    control_add(pc, 0x1050, 0x1058, 0x1060, GS_RUDDER, 0xFC00, 0x8001, b_rudder_update);
}

static void b_key_center(Pc *pc)
{
    if (!call_rep(pc, 0x0F63, 0x10))
        return;
    run(pc, 0x0F66, 0x0F6F);
    REG(AX) = 0;
    if (!gs_slew_mode(pc)) {
        taken(pc, 0x0F6D);
    } else {
        run(pc, 0x0F6F, 0x0F84);
        gs_set_elevator(pc, 0);
        gs_set_throttle(pc, 0x4000);
        gs_set_flaps(pc, 0x4000);
        gs_set_slew_rate_a(pc, 0);
        gs_set_slew_rate_b(pc, 0);
    }
    run(pc, 0x0F84, 0x0F8A);
    gs_set_aileron(pc, 0);
    gs_set_rudder(pc, 0);
    b_aileron_rudder_update(pc);
}

/* ---- 0050:0955 controls_redraw, 1060 key_enter ------------------------------------------ */

static void b_controls_redraw(Pc *pc)
{
    call(pc, 0x0955); /* key_ignore: trim */
    call(pc, 0x0958); /* elevator_update */
    call(pc, 0x095B); /* set_flaps */
    call(pc, 0x095E); /* throttle_indicator */
    call(pc, 0x0961); /* aileron_rudder_update */
    ret(pc, 0x0964);
}

/* Enter: with enter_unhooks set, give the keyboard and timer vectors back to the BIOS
 * (never set in any trace; Enter in the editor goes to editor_key instead). */
static void b_key_enter(Pc *pc)
{
    run(pc, 0x1060, 0x1067);
    if (rd8(pc, GS_ENTER_UNHOOKS) == 0) {
        taken(pc, 0x1065);
        ret(pc, 0x109A);
        return;
    }
    run(pc, 0x1067, 0x109A);
    cpu_push(&pc->cpu, SREG(ES));
    REG(AX) = 0;
    SREG(ES) = 0;
    uint32_t v9 = gs_old_int9(pc), v8 = gs_old_int8(pc);
    mem_write16(pc, 0, 0x24, (uint16_t)v9);
    mem_write16(pc, 0, 0x26, (uint16_t)(v9 >> 16));
    mem_write16(pc, 0, 0x20, (uint16_t)v8);
    mem_write16(pc, 0, 0x22, (uint16_t)(v8 >> 16));
    REG(AX) = (uint16_t)v8;
    REG(BX) = (uint16_t)(v8 >> 16);
    SET_LO(AX, 0xFF);
    port_out(pc, 0x40, 0xFF);
    port_out(pc, 0x40, 0xFF);
    gs_set_timer_hooked(pc, 0);
    SREG(ES) = cpu_pop(&pc->cpu);
    ret(pc, 0x109A);
}

/* ---- 0050:09AB key_dispatch, 0970 int9_keyboard ----------------------------------------- */

/* AL = scancode. Ctrl+Alt+Del reboots; in the editor the key goes to editor_key (bit 7 =
 * new key, Insert = 11h); otherwise the key_handlers entry of scancodes 01-53h is called. */
static void b_key_dispatch(Pc *pc)
{
    uint8_t al = AL;
    uint16_t bx = gs_last_scancodes(pc);
    REG(BX) = bx;
    if (al == 0x53 && bx == 0x381D) {
        run(pc, 0x09AB, 0x09C8);
        SREG(DS) = gs_rd16(pc, 0x0595); /* bda_seg */
        gs_wr16(pc, 0x0072, 0x1234);    /* warm boot flag */
        SREG(CS) = RESET_CS;
        pc->cpu.ip = RESET_IP;
        return;
    }
    if (al != 0x53) {
        run(pc, 0x09AB, 0x09B3);
        taken(pc, 0x09B1);
    } else {
        run(pc, 0x09AB, 0x09B9);
        taken(pc, 0x09B7);
    }
    run(pc, 0x09C8, 0x09D9);
    bx = (uint16_t)(al << 8 | bx >> 8);
    REG(BX) = bx;
    gs_set_last_scancodes(pc, bx);
    REG(AX) = al;
    if (gs_editor_active(pc) & 1) {
        if (al == 0x52) {
            run(pc, 0x09D9, 0x09E1);
            al = 0x11;
        } else {
            run(pc, 0x09D9, 0x09DD);
            taken(pc, 0x09DB);
            run(pc, 0x09E1, 0x09E7);
            REG(BX) = REG(AX);
            al = gs_editor_key_table_b(pc, REG(BX));
        }
        run(pc, 0x09E7, 0x09EC);
        al |= 0x80;
        SET_LO(AX, al);
        gs_set_editor_key(pc, al);
        ret(pc, 0x09EC);
        return;
    }
    taken(pc, 0x09D7);
    cpu_push(&pc->cpu, SREG(DS));
    if ((int8_t)al > 0x53) {
        run(pc, 0x09ED, 0x09F4);
        taken(pc, 0x09F2);
    } else if ((int8_t)al <= 0) {
        run(pc, 0x09ED, 0x09F8);
        taken(pc, 0x09F6);
    } else {
        run(pc, 0x09ED, 0x0A02);
        REG(AX) = (uint16_t)(al * 2);
        REG(BX) = REG(AX);
        REG(AX) = rd16(pc, (uint16_t)(GS_KEY_HANDLERS + REG(BX)));
        cpu_push(&pc->cpu, 0x0A02); /* call ax */
        run_from(pc, REG(AX));
    }
    run(pc, 0x0A02, 0x0A03);
    SREG(DS) = cpu_pop(&pc->cpu);
    ret(pc, 0x0A03);
}

static void b_int9_keyboard(Pc *pc)
{
    Cpu8086 *c = &pc->cpu;
    run(pc, 0x0970, 0x0995);
    cpu_push(c, REG(AX));
    cpu_push(c, REG(BX));
    cpu_push(c, REG(CX));
    cpu_push(c, REG(DX));
    cpu_push(c, REG(BP));
    cpu_push(c, REG(SI));
    cpu_push(c, REG(DI));
    cpu_push(c, SREG(DS));
    cpu_push(c, SREG(ES));
    REG(AX) = 0;
    SREG(DS) = mem_read16(pc, 0, 0x0120);
    SET_LO(AX, port_in(pc, 0x60));
    cpu_push(c, REG(AX));
    uint8_t p61 = port_in(pc, 0x61);
    port_out(pc, 0x61, (uint8_t)(p61 | 0x80));
    port_out(pc, 0x61, p61);
    REG(AX) = cpu_pop(c);
    if (AL & 0x80) {
        taken(pc, 0x0993); /* key release: ignored */
    } else {
        run(pc, 0x0995, 0x099A);
        gs_set_demo_mode(pc, 0);
        if (!call(pc, 0x099A) && at_reset(pc))
            return; /* Ctrl+Alt+Del: the BIOS reset entry */
    }
    run(pc, 0x099D, 0x09AB);
    SET_LO(AX, 0x20);
    port_out(pc, 0x20, 0x20); /* EOI */
    SREG(ES) = cpu_pop(c);
    SREG(DS) = cpu_pop(c);
    REG(DI) = cpu_pop(c);
    REG(SI) = cpu_pop(c);
    REG(BP) = cpu_pop(c);
    REG(DX) = cpu_pop(c);
    REG(CX) = cpu_pop(c);
    REG(BX) = cpu_pop(c);
    REG(AX) = cpu_pop(c);
    native_iret(pc);
}

/* ---- entries ----------------------------------------------------------------------------- */

/* FS1_KEYS_CYCLE_CHECK=1 (debugging aid): before each call that is not nested in a native,
 * the original routine is single-stepped with a write log (other natives running as they
 * do), undone, and its cycles are compared with the native's. Hand-back is off meanwhile. */
static int cycle_check = -1;
static CpuWriteLog check_log, irq_log;

static bool log_ready(CpuWriteLog *l)
{
    if (!l->addr) {
        l->cap = 1u << 20;
        l->addr = SDL_malloc(l->cap * sizeof *l->addr);
        l->old = SDL_malloc(l->cap);
        if (!l->addr || !l->old) {
            SDL_free(l->addr);
            SDL_free(l->old);
            l->addr = NULL;
            l->old = NULL;
            return false;
        }
    }
    l->count = 0;
    l->overflow = false;
    return true;
}

static DevState dev_pre;

static bool check_original(Pc *pc, bool iret, uint64_t *cycles)
{
    Cpu8086 *c = &pc->cpu;
    if (!log_ready(&check_log))
        return false;
    Cpu8086 pre = *c;
    dev_save(pc, &dev_pre);
    uint16_t sp0 = c->regs[R_SP];
    uint16_t ret_ip = mem_read16(pc, c->sregs[S_SS], sp0);
    uint16_t ret_cs = iret ? mem_read16(pc, c->sregs[S_SS], (uint16_t)(sp0 + 2)) : GAME_CS;
    c->write_log = &check_log;
    const uint8_t *map = c->hook_map;
    bool returned = false;
    for (long n = 0; n < STEP_CAP && !returned; n++) {
        if (!(n && map && c->sregs[S_CS] == GAME_CS && map[c->ip] && native_call(pc, c->ip))) {
            c->hook_map = NULL;
            cpu_step(c);
            c->hook_map = map;
        }
        uint16_t d = (uint16_t)(c->regs[R_SP] - sp0);
        returned = (c->ip == ret_ip && c->sregs[S_CS] == ret_cs && d >= 2 && d < 0x8000) || at_reset(pc);
    }
    *cycles = c->cycles - pre.cycles;
    for (uint32_t i = check_log.count; i-- > 0;)
        pc->mem[check_log.addr[i]] = check_log.old[i];
    bool ok = returned && !check_log.overflow && !at_reset(pc);
    *c = pre;
    dev_load(pc, &dev_pre);
    return ok;
}

static void entry_run(Pc *pc, const char *name, void (*body)(Pc *), bool iret)
{
    Cpu8086 *c = &pc->cpu;
    if (cycle_check < 0)
        cycle_check = SDL_getenv("FS1_KEYS_CYCLE_CHECK") != NULL;
    uint64_t start = c->cycles;
    if (under_verify(pc)) {
        /* --verify, or nested in a native that keeps a log */
        body(pc);
    } else if (cycle_check) {
        uint64_t orig = 0;
        bool check = check_original(pc, iret, &orig);
        if (check && log_ready(&check_log))
            c->write_log = &check_log; /* nested natives run plain */
        body(pc);
        c->write_log = NULL;
        if (check && c->cycles - start != orig)
            SDL_Log("cycle-check %s: original %llu native %llu", name, (unsigned long long)orig,
                    (unsigned long long)(c->cycles - start));
    } else if (log_ready(&irq_log)) {
        Cpu8086 pre = *c;
        dev_save(pc, &dev_pre);
        c->write_log = &irq_log;
        body(pc);
        c->write_log = NULL;
        if (!irq_log.overflow && irq_due(pc, start, c->cycles - start)) {
            for (uint32_t i = irq_log.count; i-- > 0;)
                pc->mem[irq_log.addr[i]] = irq_log.old[i];
            *c = pre;
            dev_load(pc, &dev_pre);
            step_first(pc);
        }
    } else {
        body(pc);
    }
    c->cycles -= ENTRY_CYCLES;
}

#define ENTRY_FN(name) \
    static void n_##name(Pc *pc) { entry_run(pc, #name, b_##name, false); }

ENTRY_FN(controls_redraw)
ENTRY_FN(key_dispatch)
ENTRY_FN(key_esc_editor)
ENTRY_FN(key_mag_off)
ENTRY_FN(set_magnetos)
ENTRY_FN(magnetos_store)
ENTRY_FN(key_mag_left)
ENTRY_FN(key_mag_right)
ENTRY_FN(key_mag_both)
ENTRY_FN(key_mag_start)
ENTRY_FN(key_0)
ENTRY_FN(key_minus)
ENTRY_FN(key_equals)
ENTRY_FN(key_tab)
ENTRY_FN(key_w)
ENTRY_FN(key_t)
ENTRY_FN(key_p_pause)
ENTRY_FN(key_a)
ENTRY_FN(key_d)
ENTRY_FN(key_g_gear)
ENTRY_FN(gear_drag_update)
ENTRY_FN(key_h_carb_heat)
ENTRY_FN(key_l_lights)
ENTRY_FN(key_x_bomb)
ENTRY_FN(key_c_com)
ENTRY_FN(key_v_obi)
ENTRY_FN(key_n_nav)
ENTRY_FN(key_m_nop)
ENTRY_FN(key_period_brakes)
ENTRY_FN(key_kpstar_reset)
ENTRY_FN(key_alt_slew_level)
ENTRY_FN(key_space_guns)
ENTRY_FN(key_flaps_up)
ENTRY_FN(set_flaps)
ENTRY_FN(key_flaps_10)
ENTRY_FN(key_flaps_20)
ENTRY_FN(key_flaps_30)
ENTRY_FN(key_flaps_40)
ENTRY_FN(key_throttle_inc)
ENTRY_FN(key_throttle_full)
ENTRY_FN(throttle_indicator)
ENTRY_FN(key_throttle_inc_small)
ENTRY_FN(key_throttle_dec)
ENTRY_FN(key_throttle_cut)
ENTRY_FN(key_radar_on)
ENTRY_FN(key_radar_off)
ENTRY_FN(key_trim_down)
ENTRY_FN(key_ignore)
ENTRY_FN(key_kp9_slew)
ENTRY_FN(key_elevator_down)
ENTRY_FN(elevator_update)
ENTRY_FN(key_aileron_left)
ENTRY_FN(key_center)
ENTRY_FN(aileron_rudder_update)
ENTRY_FN(key_aileron_right)
ENTRY_FN(aileron_update)
ENTRY_FN(aileron_indicator)
ENTRY_FN(key_rudder_right)
ENTRY_FN(rudder_indicator)
ENTRY_FN(key_trim_up)
ENTRY_FN(key_elevator_up)
ENTRY_FN(key_kp3_slew)
ENTRY_FN(key_rudder_left)
ENTRY_FN(key_enter)
ENTRY_FN(key_repeat_accel)

static void n_int9_keyboard(Pc *pc) { entry_run(pc, "int9_keyboard", b_int9_keyboard, true); }

#define ENTRY(nm, o) { .name = #nm, .seg = GAME_CS, .off = o, .fn = n_##nm, .enabled = true, .cycles = ENTRY_CYCLES }

NativeEntry native_keys[] = {
    { .name = "int9_keyboard", .seg = GAME_CS, .off = 0x0970, .fn = n_int9_keyboard, .enabled = true, .far = true,
      .cycles = ENTRY_CYCLES },
    ENTRY(controls_redraw, 0x0955),
    ENTRY(key_dispatch, 0x09AB),
    ENTRY(key_esc_editor, 0x0A04),
    ENTRY(key_mag_off, 0x0A0A),
    { .name = "key_set_magnetos", .seg = GAME_CS, .off = 0x0A0D, .fn = n_set_magnetos, .enabled = true,
      .cycles = ENTRY_CYCLES },
    ENTRY(magnetos_store, 0x0A19),
    ENTRY(key_mag_left, 0x0A21),
    ENTRY(key_mag_right, 0x0A26),
    ENTRY(key_mag_both, 0x0A2B),
    ENTRY(key_mag_start, 0x0A30),
    ENTRY(key_0, 0x0A35),
    ENTRY(key_minus, 0x0A3A),
    ENTRY(key_equals, 0x0B53),
    ENTRY(key_tab, 0x0C79),
    ENTRY(key_w, 0x0C8A),
    ENTRY(key_t, 0x0C90),
    ENTRY(key_p_pause, 0x0CD5),
    ENTRY(key_a, 0x0CDA),
    ENTRY(key_d, 0x0CE3),
    ENTRY(key_g_gear, 0x0CF6),
    ENTRY(gear_drag_update, 0x0D01),
    ENTRY(key_h_carb_heat, 0x0D14),
    ENTRY(key_l_lights, 0x0D1A),
    ENTRY(key_x_bomb, 0x0D20),
    ENTRY(key_c_com, 0x0D4B),
    ENTRY(key_v_obi, 0x0D6E),
    ENTRY(key_n_nav, 0x0D74),
    ENTRY(key_m_nop, 0x0D92),
    ENTRY(key_period_brakes, 0x0D93),
    ENTRY(key_kpstar_reset, 0x0DA8),
    ENTRY(key_alt_slew_level, 0x0DAF),
    ENTRY(key_space_guns, 0x0DC5),
    ENTRY(key_flaps_up, 0x0DD3),
    ENTRY(set_flaps, 0x0DD9),
    ENTRY(key_flaps_10, 0x0E15),
    ENTRY(key_flaps_20, 0x0E1D),
    ENTRY(key_flaps_30, 0x0E25),
    ENTRY(key_flaps_40, 0x0E2D),
    ENTRY(key_throttle_inc, 0x0E35),
    ENTRY(key_throttle_full, 0x0E45),
    ENTRY(throttle_indicator, 0x0E6A),
    ENTRY(key_throttle_inc_small, 0x0E7B),
    ENTRY(key_throttle_dec, 0x0E89),
    ENTRY(key_throttle_cut, 0x0E97),
    ENTRY(key_radar_on, 0x0EA5),
    ENTRY(key_radar_off, 0x0EB0),
    ENTRY(key_trim_down, 0x0EC3),
    ENTRY(key_ignore, 0x0EDC),
    ENTRY(key_kp9_slew, 0x0EF4),
    ENTRY(key_elevator_down, 0x0F00),
    ENTRY(elevator_update, 0x0F25),
    ENTRY(key_aileron_left, 0x0F4B),
    ENTRY(key_center, 0x0F61),
    ENTRY(aileron_rudder_update, 0x0F8A),
    ENTRY(key_aileron_right, 0x0F90),
    ENTRY(aileron_update, 0x0FA3),
    ENTRY(aileron_indicator, 0x0FB3),
    ENTRY(key_rudder_right, 0x0FD4),
    ENTRY(rudder_indicator, 0x0FF2),
    ENTRY(key_trim_up, 0x1008),
    ENTRY(key_elevator_up, 0x1024),
    ENTRY(key_kp3_slew, 0x1044),
    ENTRY(key_rudder_left, 0x1050),
    ENTRY(key_enter, 0x1060),
    ENTRY(key_repeat_accel, 0x109B),
    { .name = NULL },
};
