/* Emulated cycles of each original instruction in the subphase 3.21 routines (main loop,
 * crash delay, view_overlay_marks, key-wait loops, draw_view_frame), from the cpu8086.c
 * cost model; generated by tools/gen_mainloop_cycles.py (do not edit): address, cost (for a
 * conditional jump or LOOP: when it falls through; for REP: with CX = 2), cost when it jumps. */
#ifndef FS1_MAINLOOP_CYCLES_H
#define FS1_MAINLOOP_CYCLES_H

#include <stdint.h>

typedef struct MlInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} MlInsCost;

static const MlInsCost ml_ins_cost[] = {
    { 0x01F8, 14, 14 }, /* test byte ptr [editor_active], 1 */
    { 0x01FD, 4, 16 }, /* je loc_020A */
    { 0x01FF, 21, 21 }, /* call editor_main */
    { 0x0202, 21, 21 }, /* call blit_view_to_screen */
    { 0x0205, 19, 19 }, /* mov byte ptr [editor_active], 0 */
    { 0x020A, 12, 12 }, /* mov ax, word ptr [timer_hooked] */
    { 0x020D, 5, 5 }, /* or ax, ax */
    { 0x020F, 4, 16 }, /* jne loc_0213 */
    { 0x0211, 17, 17 }, /* jmp loc_0211 */
    { 0x0213, 14, 14 }, /* test byte ptr [paused], 0xff */
    { 0x0218, 4, 16 }, /* jne main_loop */
    { 0x021A, 14, 14 }, /* test byte ptr [slew_mode], 0xff */
    { 0x021F, 4, 16 }, /* je loc_0226 */
    { 0x0221, 21, 21 }, /* call slew_update */
    { 0x0224, 17, 17 }, /* jmp loc_022C */
    { 0x0226, 21, 21 }, /* call flight_integrate */
    { 0x0229, 21, 21 }, /* call apply_wind */
    { 0x022C, 21, 21 }, /* call build_view_matrix */
    { 0x022F, 21, 21 }, /* call draw_sky_ground */
    { 0x0232, 21, 21 }, /* call draw_view_frame */
    { 0x0235, 21, 21 }, /* call obi_check */
    { 0x0238, 21, 21 }, /* call scenery_reset_ip */
    { 0x023B, 21, 21 }, /* call draw_scenery */
    { 0x023E, 21, 21 }, /* call engine_rpm_step */
    { 0x0241, 21, 21 }, /* call obi_update */
    { 0x0244, 21, 21 }, /* call slew_readout */
    { 0x0247, 21, 21 }, /* call war_frame */
    { 0x024A, 21, 21 }, /* call view_overlay_marks */
    { 0x024D, 21, 21 }, /* call blit_view_to_screen */
    { 0x0250, 21, 21 }, /* call upd_altimeter */
    { 0x0253, 21, 21 }, /* call upd_airspeed */
    { 0x0256, 21, 21 }, /* call obi_check */
    { 0x0259, 21, 21 }, /* call clock_text */
    { 0x025C, 21, 21 }, /* call engine_rpm_step */
    { 0x025F, 12, 12 }, /* mov ax, word ptr [frame_counter] */
    { 0x0262, 8, 8 }, /* sar al, 1 */
    { 0x0264, 4, 16 }, /* jb loc_028B */
    { 0x0266, 8, 8 }, /* sar al, 1 */
    { 0x0268, 4, 16 }, /* jb loc_0280 */
    { 0x026A, 21, 21 }, /* call gauge_upd_1401 */
    { 0x026D, 21, 21 }, /* call upd_obi */
    { 0x0270, 21, 21 }, /* call compute_wind */
    { 0x0273, 14, 14 }, /* test word ptr [frame_counter], 4 */
    { 0x0279, 4, 16 }, /* je loc_02B5 */
    { 0x027B, 21, 21 }, /* call nav_search_start */
    { 0x027E, 17, 17 }, /* jmp loc_02B5 */
    { 0x0280, 21, 21 }, /* call gauge_upd_1419 */
    { 0x0283, 21, 21 }, /* call flight_params */
    { 0x0286, 21, 21 }, /* call panel_update_mask */
    { 0x0289, 17, 17 }, /* jmp loc_02B5 */
    { 0x028B, 8, 8 }, /* sar al, 1 */
    { 0x028D, 4, 16 }, /* jb loc_0297 */
    { 0x028F, 21, 21 }, /* call gauge_upd_140D */
    { 0x0292, 21, 21 }, /* call crash_handler */
    { 0x0295, 17, 17 }, /* jmp loc_02A0 */
    { 0x0297, 21, 21 }, /* call gauge_upd_1425 */
    { 0x029A, 21, 21 }, /* call select_scenery_area */
    { 0x029D, 21, 21 }, /* call sub_04FB */
    { 0x02A0, 21, 21 }, /* call nav_compute */
    { 0x02A3, 21, 21 }, /* call attitude */
    { 0x02A6, 21, 21 }, /* call upd_turn */
    { 0x02A9, 21, 21 }, /* call sound_update */
    { 0x02AC, 21, 21 }, /* call field_elev_follow */
    { 0x02AF, 15, 15 }, /* rol word ptr [blink_bits], 1 */
    { 0x02B3, 17, 17 }, /* jmp loc_02C4 */
    { 0x02B5, 21, 21 }, /* call upd_vsi */
    { 0x02B8, 21, 21 }, /* call gauge_upd_1431 */
    { 0x02BB, 21, 21 }, /* call heading_readout */
    { 0x02BE, 21, 21 }, /* call engine_update */
    { 0x02C1, 21, 21 }, /* call attitude_fast */
    { 0x02C4, 12, 12 }, /* inc word ptr [frame_counter] */
    { 0x02C8, 17, 17 }, /* jmp main_loop */
    { 0x0639, 4, 4 }, /* mov cx, 0xffff */
    { 0x063C, 72, 72 }, /* mul cl */
    { 0x063E, 72, 72 }, /* mul cl */
    { 0x0640, 72, 72 }, /* mul cl */
    { 0x0642, 5, 17 }, /* loop loc_063C */
    { 0x0658, 14, 14 }, /* test byte ptr [radar_view], 0xff */
    { 0x065D, 4, 16 }, /* jne loc_06DE */
    { 0x065F, 17, 17 }, /* mov si, word ptr [view_not_forward] */
    { 0x0663, 6, 6 }, /* cmp si, 0x10 */
    { 0x0666, 4, 16 }, /* jne loc_06D1 */
    { 0x0668, 19, 19 }, /* cmp byte ptr [war_mode], 0 */
    { 0x066D, 4, 16 }, /* je loc_06CA */
    { 0x066F, 16, 16 }, /* push ds */
    { 0x0670, 11, 11 }, /* mov ds, word ptr [view_buf_seg] */
    { 0x0674, 4, 4 }, /* mov ax, 0x7f0 */
    { 0x0677, 18, 18 }, /* and word ptr [0x757], ax */
    { 0x067B, 18, 18 }, /* and word ptr [0x27a7], ax */
    { 0x067F, 18, 18 }, /* and word ptr [0x2897], ax */
    { 0x0683, 18, 18 }, /* and word ptr [asi_needle_desc+8], ax */
    { 0x0687, 4, 4 }, /* mov ax, 0x3ffe */
    { 0x068A, 18, 18 }, /* and word ptr [0x2757], ax */
    { 0x068E, 18, 18 }, /* and word ptr [com_freq+1], ax */
    { 0x0692, 18, 18 }, /* and word ptr [turn_gain+1], ax */
    { 0x0696, 18, 18 }, /* and word ptr [editor_row_offsets+3], ax */
    { 0x069A, 4, 4 }, /* mov ax, 0xfe1f */
    { 0x069D, 18, 18 }, /* and word ptr [0x7f6], ax */
    { 0x06A1, 18, 18 }, /* and word ptr [0x27f6], ax */
    { 0x06A5, 18, 18 }, /* and word ptr [0x2846], ax */
    { 0x06A9, 18, 18 }, /* and word ptr [prev_time], ax */
    { 0x06AD, 4, 4 }, /* mov ax, 0xf83f */
    { 0x06B0, 18, 18 }, /* and word ptr [0x7f8], ax */
    { 0x06B4, 18, 18 }, /* and word ptr [0x27f8], ax */
    { 0x06B8, 18, 18 }, /* and word ptr [0x2848], ax */
    { 0x06BC, 18, 18 }, /* and word ptr [prev_time+2], ax */
    { 0x06C0, 5, 5 }, /* xor ax, ax */
    { 0x06C2, 12, 12 }, /* mov word ptr [cos_track], ax */
    { 0x06C5, 12, 12 }, /* mov word ptr [weight_normal], ax */
    { 0x06C8, 14, 14 }, /* pop ds */
    { 0x06C9, 20, 20 }, /* ret */
    { 0x06CA, 19, 19 }, /* cmp byte ptr [gear_down], 0 */
    { 0x06CF, 4, 16 }, /* je loc_06DE */
    { 0x06D1, 8, 8 }, /* shl si, 1 */
    { 0x06D3, 8, 8 }, /* shl si, 1 */
    { 0x06D5, 6, 6 }, /* add si, 0x4ef */
    { 0x06D9, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x06DA, 5, 5 }, /* or al, al */
    { 0x06DC, 4, 16 }, /* jne loc_06DF */
    { 0x06DE, 20, 20 }, /* ret */
    { 0x06DF, 4, 4 }, /* mov ah, al */
    { 0x06E1, 4, 4 }, /* mov al, 0x80 */
    { 0x06E3, 15, 15 }, /* push ax */
    { 0x06E4, 15, 15 }, /* lodsw ax, word ptr [si] */
    { 0x06E5, 12, 12 }, /* mov word ptr [0x414], ax */
    { 0x06E8, 15, 15 }, /* lodsw ax, word ptr [si] */
    { 0x06E9, 5, 5 }, /* xor bx, bx */
    { 0x06EB, 6, 6 }, /* xchg bl, al */
    { 0x06ED, 4, 4 }, /* mov dx, ax */
    { 0x06EF, 15, 15 }, /* lodsw ax, word ptr [si] */
    { 0x06F0, 12, 12 }, /* mov word ptr [0x401], ax */
    { 0x06F3, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x06F4, 5, 5 }, /* xor ah, ah */
    { 0x06F6, 4, 4 }, /* mov bp, ax */
    { 0x06F8, 4, 4 }, /* mov ax, si */
    { 0x06FA, 12, 12 }, /* pop si */
    { 0x06FB, 15, 15 }, /* push ax */
    { 0x06FC, 11, 11 }, /* mov es, word ptr [view_buf_seg] */
    { 0x0700, 18, 18 }, /* add dx, word ptr [0x401] */
    { 0x0704, 6, 6 }, /* add bl, 2 */
    { 0x0707, 17, 17 }, /* mov di, word ptr [bx + row_offsets] */
    { 0x070B, 4, 4 }, /* mov al, dh */
    { 0x070D, 2, 2 }, /* cwde */
    { 0x070E, 5, 5 }, /* add di, ax */
    { 0x0710, 18, 18 }, /* add si, word ptr [0x414] */
    { 0x0714, 4, 4 }, /* mov cx, si */
    { 0x0716, 4, 4 }, /* mov cl, ch */
    { 0x0718, 5, 5 }, /* xor ch, ch */
    { 0x071A, 12, 12 }, /* mov ax, word ptr [overlay_fill] */
    { 0x071D, 22, 22 }, /* rep stosb byte ptr es:[di], al */
    { 0x071F, 2, 2 }, /* dec bp */
    { 0x0720, 4, 16 }, /* jne loc_0700 */
    { 0x0722, 12, 12 }, /* pop si */
    { 0x0723, 19, 19 }, /* mov word ptr [overlay_fill], 0 */
    { 0x0729, 6, 6 }, /* cmp si, 0x537 */
    { 0x072D, 4, 16 }, /* jne loc_0731 */
    { 0x072F, 17, 17 }, /* jmp loc_06D9 */
    { 0x0731, 20, 20 }, /* ret */
    { 0x3726, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x3729, 5, 5 }, /* or al, al */
    { 0x372B, 4, 16 }, /* jns loc_3726 */
    { 0x5A9E, 14, 14 }, /* test word ptr [time_of_day], 1 */
    { 0x5AA4, 4, 16 }, /* je loc_5AD6 */
    { 0x5AA6, 14, 14 }, /* test byte ptr [radar_view], 0xff */
    { 0x5AAB, 4, 16 }, /* jne loc_5AD6 */
    { 0x5AAD, 4, 4 }, /* mov ax, 0 */
    { 0x5AB0, 4, 4 }, /* mov cx, 0x28 */
    { 0x5AB3, 4, 4 }, /* mov di, 0 */
    { 0x5AB6, 11, 11 }, /* mov es, word ptr [view_buf_seg] */
    { 0x5ABA, 22, 22 }, /* rep stosw word ptr es:[di], ax */
    { 0x5ABC, 4, 4 }, /* mov cx, 0x28 */
    { 0x5ABF, 4, 4 }, /* mov di, 0x1090 */
    { 0x5AC2, 22, 22 }, /* rep stosw word ptr es:[di], ax */
    { 0x5AC4, 4, 4 }, /* mov al, 0xf0 */
    { 0x5AC6, 4, 4 }, /* mov bx, 0x1090 */
    { 0x5AC9, 18, 18 }, /* or byte ptr es:[bx], al */
    { 0x5ACC, 18, 18 }, /* or byte ptr es:[bx + 0x2000], al */
    { 0x5AD1, 6, 6 }, /* sub bx, 0x50 */
    { 0x5AD4, 4, 16 }, /* jns loc_5AC9 */
    { 0x5AD6, 20, 20 }, /* ret */
    { 0x5CFC, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x5CFF, 5, 5 }, /* or al, al */
    { 0x5D01, 4, 16 }, /* jns loc_5CFC */
    { 0x5D68, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x5D6B, 5, 5 }, /* or al, al */
    { 0x5D6D, 4, 16 }, /* jns loc_5D68 */
};

#endif
