/* Natives for subphase 3.20 scenery loading (see docs/PHASE3_PLAN.md and docs/subphases/3.20.md):
 * select_scenery_area (0050:03CA), its copy loop (044E), and the two INT 13h instructions of the
 * boot-sector disk code that a load reaches (disk_reset 00F5, boot_read_track 0135).
 *
 * The scenery stream is taken from the disk image (pc->disk), not from the track buffer: the
 * byte that the original fetches from B800:BX is read from the sector of the track that the
 * last read put there. INT 13h is performed in C (the same effects as pc.c's BIOS: the buffer
 * written through cpu_write8, the status in BDA 41h, AH, CF in the stacked flags, the INT frame
 * left below SP). The game memory ends exactly as with the original, including the B800 track
 * buffer (the last track read, visible on screen until the view is redrawn), stream_pos,
 * disk_track, disk_error, the motor bits of BDA 3Fh, every register, the flags and the stack
 * words written by CALL, PUSH and INT.
 *
 * Method: the original's instructions are transliterated on the emulated registers, one C case
 * per instruction address (interp), with the cpu8086.c cost of each instruction (table
 * sceneryload_cycles.h, generated by tools/gen_sceneryload_cycles.py). An area change copies
 * 3.4 to 8.4 KB and takes 0.07 to 0.18 s of emulated time, during which the original is
 * interrupted by the timer several times. So that the timeline stays exact, a call that is not
 * nested in a logging native stops after the instruction in which the timer or the keyboard
 * falls due (irq_due, as in 3.14/3.16/3.18), leaving the CPU at that instruction boundary inside
 * the original routine. The interrupt is delivered there, as with the original; the original
 * then runs at most the rest of one stream_byte call until the copy loop reaches 044E, where
 * the next native call continues the load. A stop inside boot_read_track or disk_reset before
 * the INT reaches the INT natives, so no emulated INT 13h runs during a load.
 *
 * Every entry uses the same interpreter: it runs from the entry address until the routine that
 * was entered returns (RET with SP = entry SP + 2), leaves the code it knows (jmp 5E3D), or
 * stops for an interrupt. Under --verify (and nested in a native with a write log) it never
 * stops, so a verified call runs the whole routine. */
#include <SDL3/SDL.h>

#include "native.h"
#include "sceneryload_cycles.h"

#define REG(r) (pc->cpu.regs[R_##r])
#define SREG(r) (pc->cpu.sregs[S_##r])
#define SET_LO(r, b) (REG(r) = (uint16_t)((REG(r) & 0xFF00) | (uint8_t)(b)))
#define SET_HI(r, b) (REG(r) = (uint16_t)((REG(r) & 0x00FF) | (uint16_t)((uint8_t)(b)) << 8))
#define LO(r) ((uint8_t)REG(r))
#define HI(r) ((uint8_t)(REG(r) >> 8))

#define ENTRY_CYCLES 1
#define INT13_STUB_CYCLES (2 + 34) /* BIOS stub F000:4C: HLE trap "0F 13", IRET */
#define TRACK_BYTES 0x1000
#define TRACK_SEG 0xB800

/* ---- cycles ----------------------------------------------------------------------------- */

#define N_COST (sizeof sl_ins_cost / sizeof sl_ins_cost[0])

static const SlInsCost *ins_at(uint16_t addr)
{
    size_t lo = 0, hi = N_COST;
    while (lo < hi) {
        size_t mid = (lo + hi) / 2;
        if (sl_ins_cost[mid].addr < addr)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &sl_ins_cost[lo];
}

static void cost(Pc *pc, uint16_t at) { pc->cpu.cycles += ins_at(at)->cost; }
static void cost_taken(Pc *pc, uint16_t at) { pc->cpu.cycles += ins_at(at)->taken; }

/* ---- flags (as cpu8086.c computes them) ------------------------------------------------- */

static void set_flag(Pc *pc, uint16_t f, bool on)
{
    pc->cpu.flags = on ? (uint16_t)(pc->cpu.flags | f) : (uint16_t)(pc->cpu.flags & ~f);
}

static void set_szp(Pc *pc, uint32_t v, int w)
{
    uint32_t mask = w ? 0xFFFF : 0xFF, sign = w ? 0x8000 : 0x80;
    uint8_t p = (uint8_t)v;
    p ^= p >> 4;
    p ^= p >> 2;
    p ^= p >> 1;
    set_flag(pc, F_ZF, (v & mask) == 0);
    set_flag(pc, F_SF, (v & sign) != 0);
    set_flag(pc, F_PF, !(p & 1));
}

static uint32_t f_add(Pc *pc, uint32_t a, uint32_t b, int w)
{
    uint32_t mask = w ? 0xFFFF : 0xFF, sign = w ? 0x8000 : 0x80;
    uint32_t r = a + b;
    set_flag(pc, F_CF, r > mask);
    set_flag(pc, F_OF, ((r ^ a) & (r ^ b) & sign) != 0);
    set_flag(pc, F_AF, ((a ^ b ^ r) & 0x10) != 0);
    set_szp(pc, r, w);
    return r & mask;
}

static uint32_t f_sub(Pc *pc, uint32_t a, uint32_t b, int w)
{
    uint32_t mask = w ? 0xFFFF : 0xFF, sign = w ? 0x8000 : 0x80;
    uint32_t r = (a - b) & mask;
    set_flag(pc, F_CF, a < b);
    set_flag(pc, F_OF, ((a ^ b) & (a ^ r) & sign) != 0);
    set_flag(pc, F_AF, ((a ^ b ^ r) & 0x10) != 0);
    set_szp(pc, r, w);
    return r;
}

static uint32_t f_logic(Pc *pc, uint32_t r, int w)
{
    pc->cpu.flags &= (uint16_t)~(F_CF | F_OF | F_AF);
    set_szp(pc, r, w);
    return r & (w ? 0xFFFF : 0xFF);
}

static uint32_t f_inc(Pc *pc, uint32_t v, int w)
{
    uint16_t cf = pc->cpu.flags & F_CF;
    uint32_t r = f_add(pc, v, 1, w);
    pc->cpu.flags = (uint16_t)((pc->cpu.flags & ~F_CF) | cf);
    return r;
}

static bool flag(Pc *pc, uint16_t f) { return (pc->cpu.flags & f) != 0; }

/* ---- memory ----------------------------------------------------------------------------- */

static uint8_t rd8(Pc *pc, uint16_t seg, uint16_t off) { return cpu_read8(&pc->cpu, cpu_linear(seg, off)); }
static uint16_t rd16(Pc *pc, uint16_t seg, uint16_t off) { return mem_read16(pc, seg, off); }
static void wr8(Pc *pc, uint16_t seg, uint16_t off, uint8_t v) { cpu_write8(&pc->cpu, cpu_linear(seg, off), v); }
static void wr16(Pc *pc, uint16_t seg, uint16_t off, uint16_t v) { mem_write16(pc, seg, off, v); }

/* ---- the track buffer -------------------------------------------------------------------- */

/* Track that the last INT 13h read put into B800:0000-0FFF (-1: unknown, e.g. after a failed
 * read or a read elsewhere). It is trusted only while disk_track = track + 1, which
 * boot_read_track leaves after a good read; otherwise the buffer itself is read. */
static int buf_track = -1;
static int check_buffer = -1; /* FS1_SCENERY_CHECK=1: compare each image byte with B800 */

static uint8_t stream_fetch(Pc *pc, uint16_t seg, uint16_t off)
{
    uint8_t disk_track = rd8(pc, SREG(DS), 0x03B3);
    if (seg != TRACK_SEG || off >= TRACK_BYTES || buf_track < 0 || disk_track != (uint8_t)(buf_track + 1))
        return rd8(pc, seg, off);
    const Disk *d = pc->disk;
    const uint8_t *sec = disk_sector(d, buf_track, off / d->sector_size);
    uint8_t v = sec[off % d->sector_size];
    if (check_buffer < 0)
        check_buffer = SDL_getenv("FS1_SCENERY_CHECK") != NULL;
    if (check_buffer && v != pc->mem[cpu_linear(seg, off)])
        SDL_Log("sceneryload: B800:%04X is %02X, track %02X has %02X", off, pc->mem[cpu_linear(seg, off)], buf_track,
                v);
    return v;
}

/* ---- INT 13h ------------------------------------------------------------------------------ */

/* The BIOS service of pc.c (bios_int13), on the registers as the stub sees them. */
static void int13_service(Pc *pc)
{
    Disk *disk = pc->disk;
    uint8_t drive = LO(DX), head = HI(DX), cyl = HI(CX), sector = (uint8_t)(REG(CX) & 0x3F);
    uint8_t status = 0;
    uint8_t fn = HI(AX);
    switch (fn) {
    case 0x00: case 0x04: case 0x05:
        if (drive != 0)
            status = 0x80;
        break;
    case 0x01:
        status = pc->mem[0x441];
        break;
    case 0x02: case 0x03: {
        uint32_t buf = cpu_linear(SREG(ES), REG(BX));
        int count = LO(AX);
        if (drive != 0) {
            status = 0x80;
        } else if (head != 0 || cyl >= disk->tracks || sector == 0 || sector - 1 + count > disk->sectors_per_track) {
            status = 0x04;
        } else {
            for (int i = 0; i < count; i++) {
                uint8_t *sec = (uint8_t *)disk_sector(disk, cyl, sector - 1 + i);
                for (int b = 0; b < disk->sector_size; b++) {
                    uint32_t a = (buf + (uint32_t)i * disk->sector_size + b) & CPU_MEM_MASK;
                    if (fn == 0x02)
                        cpu_write8(&pc->cpu, a, sec[b]);
                    else
                        sec[b] = pc->mem[a];
                }
            }
        }
        if (fn == 0x02)
            buf_track = (!status && SREG(ES) == TRACK_SEG && REG(BX) == 0 && sector == 1 &&
                         count * disk->sector_size == TRACK_BYTES) ? cyl : -1;
        if (status)
            SET_LO(AX, 0);
        break;
    }
    default:
        status = 0x01;
        break;
    }
    pc->mem[0x441] = status; /* BDA, written behind cpu_write8 as pc.c does */
    SET_HI(AX, status);
    uint16_t sp = REG(SP);
    uint16_t f = rd16(pc, SREG(SS), (uint16_t)(sp + 4));
    wr16(pc, SREG(SS), (uint16_t)(sp + 4), status ? (uint16_t)(f | F_CF) : (uint16_t)(f & ~F_CF));
}

/* INT 13h at 0050:at with the BIOS vector: INT, the stub's service, IRET. Returns false (and
 * does nothing) when the vector is not the BIOS stub. */
static bool int13(Pc *pc, uint16_t at)
{
    Cpu8086 *c = &pc->cpu;
    if (rd16(pc, 0, 0x4C) != 0x004C || rd16(pc, 0, 0x4E) != 0xF000)
        return false;
    cost(pc, at);
    c->cycles += INT13_STUB_CYCLES;
    cpu_push(c, c->flags);
    cpu_push(c, SREG(CS));
    cpu_push(c, (uint16_t)(at + 2));
    int13_service(pc);
    c->ip = cpu_pop(c);
    SREG(CS) = cpu_pop(c);
    c->flags = (uint16_t)((cpu_pop(c) & 0x0FD5) | 0xF002);
    return true;
}

/* ---- interrupts ---------------------------------------------------------------------------- */

/* True when the timer (PIT channel 0) or the keyboard would raise an interrupt within n cycles
 * of the call that started at cycle `start` (the PIT is advanced only after a native returns,
 * so its state is still the one at the start). As keys.c. */
static bool irq_due(Pc *pc, uint64_t start, uint64_t n)
{
    if (pc->csched)
        return false; /* C scheduler (3.22): interrupts only come between natives */
    const PitChannel *t = &pc->pit[0];
    bool timer = pc->irq0_backlog || (t->loaded && t->count - (int64_t)((pc->pit_cycle_frac + n) / 4) <= 0);
    bool key = !pc->kbd_full && pc->kbd_head != pc->kbd_tail && start + n >= pc->kbd_next_cycle;
    return timer || key;
}

/* ---- the interpreter ----------------------------------------------------------------------- */

#define DSEG SREG(DS)
#define NEXT(n) (c->ip = (uint16_t)(at + (n)))

static void op_call(Pc *pc, uint16_t at, uint16_t target)
{
    cost(pc, at);
    cpu_push(&pc->cpu, (uint16_t)(at + 3));
    pc->cpu.ip = target;
}

static void op_jcc(Pc *pc, uint16_t at, bool cond, uint16_t target)
{
    if (cond) {
        cost_taken(pc, at);
        pc->cpu.ip = target;
    } else {
        cost(pc, at);
        pc->cpu.ip = (uint16_t)(at + 2);
    }
}

static bool jl(Pc *pc) { return flag(pc, F_SF) != flag(pc, F_OF); }
static bool jg(Pc *pc) { return !flag(pc, F_ZF) && flag(pc, F_SF) == flag(pc, F_OF); }

typedef enum { RUN_ON, RUN_RETURNED, RUN_LEFT } RunState;

/* Executes the instruction at CS:IP. */
static RunState exec(Pc *pc, uint16_t sp0)
{
    Cpu8086 *c = &pc->cpu;
    uint16_t at = c->ip;
    switch (at) {
    /* ---- disk_error / disk_reset / sub_00F8 ---- */
    case 0x00EA: cost(pc, at); wr8(pc, DSEG, 0x03C4, 1); NEXT(5); break;
    case 0x00F0: op_call(pc, at, 0x00F8); break;
    case 0x00F3: cost(pc, at); SET_HI(AX, f_logic(pc, 0, 0)); NEXT(2); break;
    case 0x00F5: case 0x0135: case 0x0146:
        if (!int13(pc, at))
            return RUN_LEFT;
        break;
    case 0x00F8: cost(pc, at); REG(AX) = (uint16_t)f_logic(pc, 0, 1); NEXT(2); break;
    case 0x00FA: cost(pc, at); SREG(DS) = REG(AX); NEXT(2); break;
    case 0x00FC: cost(pc, at); REG(AX) = rd16(pc, DSEG, 0x0120); NEXT(3); break;
    case 0x00FF: cost(pc, at); SREG(ES) = REG(AX); NEXT(2); break;
    case 0x0101: cost(pc, at); SREG(DS) = REG(AX); NEXT(2); break;
    /* ---- boot_read_track ---- */
    case 0x0104: op_call(pc, at, 0x00F8); break;
    case 0x0107: cost(pc, at); SET_HI(AX, f_logic(pc, 0, 0)); NEXT(2); break;
    case 0x0109: cost(pc, at); wr8(pc, DSEG, 0x03B2, HI(AX)); NEXT(4); break;
    case 0x010D: cost(pc, at); wr16(pc, DSEG, 0x03C2, TRACK_SEG); NEXT(6); break;
    case 0x0113: cost(pc, at); SET_LO(AX, 8); NEXT(2); break;
    case 0x0115: cost(pc, at); SET_HI(AX, f_add(pc, HI(AX), 2, 0)); NEXT(3); break;
    case 0x0118: cost(pc, at); REG(DX) = SREG(CS); NEXT(2); break;
    case 0x011A: cost(pc, at); f_sub(pc, REG(DX), 0x50, 1); NEXT(3); break;
    case 0x011D: op_jcc(pc, at, !flag(pc, F_ZF), 0x0125); break;
    case 0x011F: cost(pc, at); wr16(pc, DSEG, 0x03C0, 0); NEXT(6); break;
    case 0x0125: cost(pc, at); REG(DX) = rd16(pc, DSEG, 0x03C0); NEXT(4); break;
    case 0x0129: cost(pc, at); SET_HI(CX, rd8(pc, DSEG, 0x03B3)); NEXT(4); break;
    case 0x012D: cost(pc, at); SET_LO(CX, 1); NEXT(2); break;
    case 0x012F: cost(pc, at); SREG(ES) = rd16(pc, DSEG, 0x03C2); NEXT(4); break;
    case 0x0133: cost(pc, at); REG(BX) = (uint16_t)f_logic(pc, 0, 1); NEXT(2); break;
    case 0x0137: op_jcc(pc, at, flag(pc, F_CF), 0x00EA); break;
    case 0x0139: {
        cost(pc, at);
        uint8_t v = rd8(pc, DSEG, 0x03B2);
        uint8_t r = (uint8_t)(v >> 1);
        set_flag(pc, F_CF, v & 1);
        set_flag(pc, F_OF, (r & 0x40) != 0);
        set_szp(pc, r, 0);
        wr8(pc, DSEG, 0x03B2, r);
        NEXT(4);
        break;
    }
    case 0x013D: op_jcc(pc, at, !flag(pc, F_CF), 0x0152); break;
    case 0x013F: op_call(pc, at, 0x0157); break;
    case 0x0142: cost(pc, at); cpu_push(c, REG(AX)); NEXT(1); break;
    case 0x0143: cost(pc, at); REG(AX) = 0x0208; NEXT(3); break;
    case 0x0148: cost(pc, at); REG(CX) = cpu_pop(c); NEXT(1); break;
    case 0x0149: op_jcc(pc, at, flag(pc, F_CF), 0x00EA); break;
    case 0x014B: op_call(pc, at, 0x0157); break;
    case 0x014E: cost(pc, at); f_sub(pc, REG(AX), REG(CX), 1); NEXT(2); break;
    case 0x0150: op_jcc(pc, at, !flag(pc, F_ZF), 0x00EA); break;
    case 0x0152: cost(pc, at); wr8(pc, DSEG, 0x03B3, (uint8_t)f_inc(pc, rd8(pc, DSEG, 0x03B3), 0)); NEXT(4); break;
    /* ---- track_checksum ---- */
    case 0x0157: cost(pc, at); cpu_push(c, REG(BX)); NEXT(1); break;
    case 0x0158: cost(pc, at); SREG(ES) = rd16(pc, DSEG, 0x03C2); NEXT(4); break;
    case 0x015C: cost(pc, at); REG(BX) = 0x0FFE; NEXT(3); break;
    case 0x015F: cost(pc, at); REG(AX) = (uint16_t)f_logic(pc, 0, 1); NEXT(2); break;
    case 0x0161: cost(pc, at); REG(AX) = (uint16_t)f_add(pc, REG(AX), rd16(pc, SREG(ES), REG(BX)), 1); NEXT(3); break;
    case 0x0164: cost(pc, at); REG(BX) = (uint16_t)f_sub(pc, REG(BX), 2, 1); NEXT(3); break;
    case 0x0167: op_jcc(pc, at, !flag(pc, F_SF), 0x0161); break;
    case 0x0169: cost(pc, at); REG(BX) = cpu_pop(c); NEXT(1); break;
    /* ---- sub_016B: drive motor off ---- */
    case 0x016B: cost(pc, at); REG(DX) = 0x03F2; NEXT(3); break;
    case 0x016E: cost(pc, at); SET_LO(AX, 0x0C); NEXT(2); break;
    case 0x0170: cost(pc, at); c->bus.out8(c->bus.ctx, REG(DX), LO(AX)); NEXT(1); break;
    case 0x0171: cost(pc, at); REG(DX) = (uint16_t)f_logic(pc, 0, 1); NEXT(2); break;
    case 0x0173: cost(pc, at); SREG(ES) = REG(DX); NEXT(2); break;
    case 0x0175:
        cost(pc, at);
        wr8(pc, SREG(ES), 0x043F, (uint8_t)f_logic(pc, rd8(pc, SREG(ES), 0x043F) & 0xF0, 0));
        NEXT(6);
        break;
    /* ---- boot_stream_byte / boot_stream_word ---- */
    case 0x017C: cost(pc, at); cpu_push(c, SREG(ES)); NEXT(1); break;
    case 0x017D: cost(pc, at); REG(BX) = rd16(pc, DSEG, 0x03B0); NEXT(4); break;
    case 0x0181: cost(pc, at); REG(BX) = (uint16_t)f_inc(pc, REG(BX), 1); NEXT(1); break;
    case 0x0182: cost(pc, at); f_sub(pc, HI(BX), 0x10, 0); NEXT(3); break;
    case 0x0185: op_jcc(pc, at, flag(pc, F_ZF), 0x0195); break;
    case 0x0187: cost(pc, at); REG(AX) = TRACK_SEG; NEXT(3); break;
    case 0x018A: cost(pc, at); SREG(ES) = REG(AX); NEXT(2); break;
    case 0x018C: cost(pc, at); SET_LO(AX, stream_fetch(pc, SREG(ES), REG(BX))); NEXT(3); break;
    case 0x018F: cost(pc, at); wr16(pc, DSEG, 0x03B0, REG(BX)); NEXT(4); break;
    case 0x0193: cost(pc, at); SREG(ES) = cpu_pop(c); NEXT(1); break;
    case 0x0195: cost(pc, at); cpu_push(c, REG(CX)); NEXT(1); break;
    case 0x0196: cost(pc, at); cpu_push(c, REG(DI)); NEXT(1); break;
    case 0x0197: op_call(pc, at, 0x0104); break;
    case 0x019A: cost(pc, at); REG(BX) = (uint16_t)f_logic(pc, 0, 1); NEXT(2); break;
    case 0x019C: cost(pc, at); REG(DI) = cpu_pop(c); NEXT(1); break;
    case 0x019D: cost(pc, at); REG(CX) = cpu_pop(c); NEXT(1); break;
    case 0x019E: cost(pc, at); c->ip = 0x0187; break;
    case 0x01A0: op_call(pc, at, 0x017C); break;
    case 0x01A3: cost(pc, at); cpu_push(c, REG(AX)); NEXT(1); break;
    case 0x01A4: op_call(pc, at, 0x017C); break;
    case 0x01A7: cost(pc, at); REG(BX) = cpu_pop(c); NEXT(1); break;
    case 0x01A8: cost(pc, at); REG(AX) = (uint16_t)(REG(AX) << 8 | REG(AX) >> 8); NEXT(2); break;
    case 0x01AA: cost(pc, at); SET_LO(AX, LO(BX)); NEXT(2); break;
    /* ---- select_scenery_area ---- */
    case 0x03CA: cost(pc, at); REG(SI) = rd16(pc, DSEG, 0x30DB); NEXT(4); break;
    case 0x03CE: cost(pc, at); REG(DI) = rd16(pc, DSEG, 0x30D3); NEXT(4); break;
    case 0x03D2: cost(pc, at); REG(BX) = 0x0449; NEXT(3); break;
    case 0x03D5: cost(pc, at); SET_LO(DX, 0); NEXT(2); break;
    case 0x03D7: cost(pc, at); REG(AX) = rd16(pc, DSEG, REG(BX)); NEXT(2); break;
    case 0x03D9: cost(pc, at); f_sub(pc, REG(AX), 0xFFFF, 1); NEXT(3); break;
    case 0x03DC: op_jcc(pc, at, flag(pc, F_ZF), 0x03FB); break;
    case 0x03DE: cost(pc, at); f_sub(pc, REG(SI), REG(AX), 1); NEXT(2); break;
    case 0x03E0: op_jcc(pc, at, jl(pc), 0x03FC); break;
    case 0x03E2: cost(pc, at); f_sub(pc, REG(SI), rd16(pc, DSEG, (uint16_t)(REG(BX) + 2)), 1); NEXT(3); break;
    case 0x03E5: op_jcc(pc, at, jg(pc), 0x03FC); break;
    case 0x03E7: cost(pc, at); f_sub(pc, REG(DI), rd16(pc, DSEG, (uint16_t)(REG(BX) + 4)), 1); NEXT(3); break;
    case 0x03EA: op_jcc(pc, at, jl(pc), 0x03FC); break;
    case 0x03EC: cost(pc, at); f_sub(pc, REG(DI), rd16(pc, DSEG, (uint16_t)(REG(BX) + 6)), 1); NEXT(3); break;
    case 0x03EF: op_jcc(pc, at, jg(pc), 0x03FC); break;
    case 0x03F1: cost(pc, at); SET_LO(AX, LO(DX)); NEXT(2); break;
    case 0x03F3: {
        cost(pc, at);
        uint8_t m = rd8(pc, DSEG, 0x03BE);
        wr8(pc, DSEG, 0x03BE, LO(AX));
        SET_LO(AX, m);
        NEXT(4);
        break;
    }
    case 0x03F7: cost(pc, at); f_sub(pc, LO(AX), LO(DX), 0); NEXT(2); break;
    case 0x03F9: op_jcc(pc, at, !flag(pc, F_ZF), 0x0403); break;
    case 0x03FC: cost(pc, at); SET_LO(DX, f_inc(pc, LO(DX), 0)); NEXT(2); break;
    case 0x03FE: cost(pc, at); REG(BX) = (uint16_t)f_add(pc, REG(BX), 8, 1); NEXT(3); break;
    case 0x0401: cost(pc, at); c->ip = 0x03D7; break;
    case 0x0403: cost(pc, at); wr16(pc, DSEG, 0x0571, 0); NEXT(6); break;
    case 0x0409: cost(pc, at); wr16(pc, DSEG, 0x31E8, 0); NEXT(6); break;
    case 0x040F: cost(pc, at); wr8(pc, DSEG, 0x3628, 1); NEXT(5); break;
    case 0x0414: cost(pc, at); f_sub(pc, rd8(pc, DSEG, 0x0418), 1, 0); NEXT(5); break;
    case 0x0419: op_jcc(pc, at, !flag(pc, F_ZF), 0x041E); break;
    case 0x041B: cost(pc, at); c->ip = 0x5E3D; return RUN_LEFT;
    case 0x041E: cost(pc, at); wr8(pc, DSEG, 0x0419, 1); NEXT(5); break;
    case 0x0423: cost(pc, at); SET_LO(BX, LO(DX)); NEXT(2); break;
    case 0x0425: cost(pc, at); SET_HI(BX, f_logic(pc, 0, 0)); NEXT(2); break;
    case 0x0427: cost(pc, at); SET_LO(AX, rd8(pc, DSEG, (uint16_t)(REG(BX) + 0x03B4))); NEXT(4); break;
    case 0x042B: cost(pc, at); f_logic(pc, LO(AX), 0); NEXT(2); break;
    case 0x042D: op_jcc(pc, at, flag(pc, F_ZF), 0x03FB); break;
    case 0x042F: cost(pc, at); wr8(pc, DSEG, 0x03B3, LO(AX)); NEXT(3); break;
    case 0x0432: op_call(pc, at, 0x00F0); break;
    case 0x0435: cost(pc, at); wr16(pc, DSEG, 0x03B0, 0x0FFF); NEXT(6); break;
    case 0x043B: op_call(pc, at, 0x017C); break;
    case 0x043E: op_call(pc, at, 0x01A0); break;
    case 0x0441: cost(pc, at); REG(AX) = (uint16_t)f_sub(pc, REG(AX), 3, 1); NEXT(3); break;
    case 0x0444: cost(pc, at); REG(CX) = REG(AX); NEXT(2); break;
    case 0x0446: cost(pc, at); REG(AX) = SREG(DS); NEXT(2); break;
    case 0x0448: cost(pc, at); SREG(ES) = REG(AX); NEXT(2); break;
    case 0x044A: cost(pc, at); REG(DI) = rd16(pc, DSEG, 0x03F0); NEXT(4); break;
    case 0x044E: op_call(pc, at, 0x017C); break;
    case 0x0451:
        cost(pc, at);
        wr8(pc, SREG(ES), REG(DI), LO(AX));
        REG(DI) = (uint16_t)(REG(DI) + (flag(pc, F_DF) ? -1 : 1));
        NEXT(1);
        break;
    case 0x0452:
        REG(CX)--;
        op_jcc(pc, at, REG(CX) != 0, 0x044E);
        break;
    case 0x0454: op_call(pc, at, 0x016B); break;
    case 0x0457: cost(pc, at); wr8(pc, DSEG, 0x0419, 0); NEXT(5); break;
    /* ---- RET ---- */
    case 0x00EF: case 0x00F7: case 0x0103: case 0x0156: case 0x016A: case 0x017B:
    case 0x0194: case 0x01AC: case 0x03FB: case 0x045C:
        cost(pc, at);
        c->ip = cpu_pop(c);
        return REG(SP) == (uint16_t)(sp0 + 2) ? RUN_RETURNED : RUN_ON;
    default:
        return RUN_LEFT; /* not code of this file: the CPU continues there */
    }
    return RUN_ON;
}

static void n_entry(Pc *pc)
{
    Cpu8086 *c = &pc->cpu;
    uint64_t start = c->cycles;
    uint16_t sp0 = REG(SP);
    bool may_stop = c->write_log == NULL; /* not under --verify, not nested in a logging native */
    bool first = true;
    for (;;) {
        RunState s = exec(pc, sp0);
        if (s == RUN_LEFT && first) {
            /* the entry instruction itself cannot be done here (INT 13h with a hooked
             * vector): the CPU performs it */
            const uint8_t *map = c->hook_map;
            c->hook_map = NULL;
            cpu_step(c);
            c->hook_map = map;
        }
        first = false;
        if (s != RUN_ON)
            break;
        if (may_stop && irq_due(pc, start, c->cycles - start))
            break;
    }
    c->cycles -= ENTRY_CYCLES;
}

#define ENTRY(nm, o) \
    { .name = nm, .seg = GAME_CS, .off = o, .fn = n_entry, .enabled = true, .cycles = ENTRY_CYCLES }

NativeEntry native_sceneryload[] = {
    ENTRY("select_scenery_area", 0x03CA),
    ENTRY("scenery_load_loop", 0x044E),
    ENTRY("disk_reset_int13", 0x00F5),
    ENTRY("read_track_int13", 0x0135),
    /* 3.22: the rest of the boot-sector disk code, for check_master_disk at start-up (the same
     * interpreter; with the C scheduler there is no original code to run them) */
    ENTRY("disk_error", 0x00EA),
    ENTRY("disk_reset", 0x00F0),
    ENTRY("disk_set_ds", 0x00F8),
    ENTRY("boot_read_track", 0x0104),
    ENTRY("motor_off", 0x016B),
    ENTRY("boot_stream_byte", 0x017C),
    ENTRY("boot_stream_word", 0x01A0),
    { .name = NULL },
};
