/* Emulated cycles of each original instruction in the subphase 3.20 scenery-loading code
 * (0050:00EA-01AC, 03CA-045C), from the cpu8086.c cost model; generated by
 * tools/gen_sceneryload_cycles.py (do not edit): address, cost (for a conditional jump or
 * LOOP: when it falls through), cost when it jumps. */
#ifndef FS1_SCENERYLOAD_CYCLES_H
#define FS1_SCENERYLOAD_CYCLES_H

#include <stdint.h>

typedef struct SlInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} SlInsCost;

static const SlInsCost sl_ins_cost[] = {
    { 0x00EA, 19, 19 }, /* mov byte ptr [disk_error], 1 */
    { 0x00EF, 20, 20 }, /* ret */
    { 0x00F0, 21, 21 }, /* call sub_00F8 */
    { 0x00F3, 5, 5 }, /* xor ah, ah */
    { 0x00F5, 53, 53 }, /* int 0x13 */
    { 0x00F7, 20, 20 }, /* ret */
    { 0x00F8, 5, 5 }, /* xor ax, ax */
    { 0x00FA, 4, 4 }, /* mov ds, ax */
    { 0x00FC, 12, 12 }, /* mov ax, word ptr [0x120] */
    { 0x00FF, 4, 4 }, /* mov es, ax */
    { 0x0101, 4, 4 }, /* mov ds, ax */
    { 0x0103, 20, 20 }, /* ret */
    { 0x0104, 21, 21 }, /* call sub_00F8 */
    { 0x0107, 5, 5 }, /* xor ah, ah */
    { 0x0109, 18, 18 }, /* mov byte ptr [track_verify], ah */
    { 0x010D, 19, 19 }, /* mov word ptr [screen_seg], 0xb800 */
    { 0x0113, 4, 4 }, /* mov al, 8 */
    { 0x0115, 6, 6 }, /* add ah, 2 */
    { 0x0118, 4, 4 }, /* mov dx, cs */
    { 0x011A, 6, 6 }, /* cmp dx, 0x50 */
    { 0x011D, 4, 16 }, /* jne loc_0125 */
    { 0x011F, 19, 19 }, /* mov word ptr [disk_dx], 0 */
    { 0x0125, 17, 17 }, /* mov dx, word ptr [disk_dx] */
    { 0x0129, 17, 17 }, /* mov ch, byte ptr [disk_track] */
    { 0x012D, 4, 4 }, /* mov cl, 1 */
    { 0x012F, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x0133, 5, 5 }, /* xor bx, bx */
    { 0x0135, 53, 53 }, /* int 0x13 */
    { 0x0137, 4, 16 }, /* jb loc_00EA */
    { 0x0139, 15, 15 }, /* shr byte ptr [track_verify], 1 */
    { 0x013D, 4, 16 }, /* jae loc_0152 */
    { 0x013F, 21, 21 }, /* call track_checksum */
    { 0x0142, 15, 15 }, /* push ax */
    { 0x0143, 4, 4 }, /* mov ax, 0x208 */
    { 0x0146, 53, 53 }, /* int 0x13 */
    { 0x0148, 12, 12 }, /* pop cx */
    { 0x0149, 4, 16 }, /* jb loc_00EA */
    { 0x014B, 21, 21 }, /* call track_checksum */
    { 0x014E, 5, 5 }, /* cmp ax, cx */
    { 0x0150, 4, 16 }, /* jne loc_00EA */
    { 0x0152, 12, 12 }, /* inc byte ptr [disk_track] */
    { 0x0156, 20, 20 }, /* ret */
    { 0x0157, 15, 15 }, /* push bx */
    { 0x0158, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x015C, 4, 4 }, /* mov bx, 0xffe */
    { 0x015F, 5, 5 }, /* xor ax, ax */
    { 0x0161, 18, 18 }, /* add ax, word ptr es:[bx] */
    { 0x0164, 6, 6 }, /* sub bx, 2 */
    { 0x0167, 4, 16 }, /* jns loc_0161 */
    { 0x0169, 12, 12 }, /* pop bx */
    { 0x016A, 20, 20 }, /* ret */
    { 0x016B, 4, 4 }, /* mov dx, 0x3f2 */
    { 0x016E, 4, 4 }, /* mov al, 0xc */
    { 0x0170, 12, 12 }, /* out dx, al */
    { 0x0171, 5, 5 }, /* xor dx, dx */
    { 0x0173, 4, 4 }, /* mov es, dx */
    { 0x0175, 19, 19 }, /* and byte ptr es:[0x43f], 0xf0 */
    { 0x017B, 20, 20 }, /* ret */
    { 0x017C, 16, 16 }, /* push es */
    { 0x017D, 17, 17 }, /* mov bx, word ptr [stream_pos] */
    { 0x0181, 2, 2 }, /* inc bx */
    { 0x0182, 6, 6 }, /* cmp bh, 0x10 */
    { 0x0185, 4, 16 }, /* je loc_0195 */
    { 0x0187, 4, 4 }, /* mov ax, 0xb800 */
    { 0x018A, 4, 4 }, /* mov es, ax */
    { 0x018C, 17, 17 }, /* mov al, byte ptr es:[bx] */
    { 0x018F, 18, 18 }, /* mov word ptr [stream_pos], bx */
    { 0x0193, 14, 14 }, /* pop es */
    { 0x0194, 20, 20 }, /* ret */
    { 0x0195, 15, 15 }, /* push cx */
    { 0x0196, 15, 15 }, /* push di */
    { 0x0197, 21, 21 }, /* call boot_read_track */
    { 0x019A, 5, 5 }, /* xor bx, bx */
    { 0x019C, 12, 12 }, /* pop di */
    { 0x019D, 12, 12 }, /* pop cx */
    { 0x019E, 17, 17 }, /* jmp loc_0187 */
    { 0x01A0, 21, 21 }, /* call boot_stream_byte */
    { 0x01A3, 15, 15 }, /* push ax */
    { 0x01A4, 21, 21 }, /* call boot_stream_byte */
    { 0x01A7, 12, 12 }, /* pop bx */
    { 0x01A8, 6, 6 }, /* xchg ah, al */
    { 0x01AA, 4, 4 }, /* mov al, bl */
    { 0x01AC, 20, 20 }, /* ret */
    { 0x03CA, 17, 17 }, /* mov si, word ptr [pos_north+2] */
    { 0x03CE, 17, 17 }, /* mov di, word ptr [pos_east+2] */
    { 0x03D2, 4, 4 }, /* mov bx, 0x449 */
    { 0x03D5, 4, 4 }, /* mov dl, 0 */
    { 0x03D7, 17, 17 }, /* mov ax, word ptr [bx] */
    { 0x03D9, 6, 6 }, /* cmp ax, 0xffff */
    { 0x03DC, 4, 16 }, /* je loc_03FB */
    { 0x03DE, 5, 5 }, /* cmp si, ax */
    { 0x03E0, 4, 16 }, /* jl loc_03FC */
    { 0x03E2, 18, 18 }, /* cmp si, word ptr [bx + 2] */
    { 0x03E5, 4, 16 }, /* jg loc_03FC */
    { 0x03E7, 18, 18 }, /* cmp di, word ptr [bx + 4] */
    { 0x03EA, 4, 16 }, /* jl loc_03FC */
    { 0x03EC, 18, 18 }, /* cmp di, word ptr [bx + 6] */
    { 0x03EF, 4, 16 }, /* jg loc_03FC */
    { 0x03F1, 4, 4 }, /* mov al, dl */
    { 0x03F3, 26, 26 }, /* xchg byte ptr [cur_area], al */
    { 0x03F7, 5, 5 }, /* cmp al, dl */
    { 0x03F9, 4, 16 }, /* jne loc_0403 */
    { 0x03FB, 20, 20 }, /* ret */
    { 0x03FC, 5, 5 }, /* inc dl */
    { 0x03FE, 6, 6 }, /* add bx, 8 */
    { 0x0401, 17, 17 }, /* jmp loc_03D7 */
    { 0x0403, 19, 19 }, /* mov word ptr [demo_ptr], 0 */
    { 0x0409, 19, 19 }, /* mov word ptr [demo_script], 0 */
    { 0x040F, 19, 19 }, /* mov byte ptr [atis_idle], 1 */
    { 0x0414, 19, 19 }, /* cmp byte ptr [enter_unhooks], 1 */
    { 0x0419, 4, 16 }, /* jne loc_041E */
    { 0x041B, 17, 17 }, /* jmp loc_5E3D */
    { 0x041E, 19, 19 }, /* mov byte ptr [scenery_loading], 1 */
    { 0x0423, 4, 4 }, /* mov bl, dl */
    { 0x0425, 5, 5 }, /* xor bh, bh */
    { 0x0427, 17, 17 }, /* mov al, byte ptr [bx + area_tracks] */
    { 0x042B, 5, 5 }, /* or al, al */
    { 0x042D, 4, 16 }, /* je loc_03FB */
    { 0x042F, 12, 12 }, /* mov byte ptr [disk_track], al */
    { 0x0432, 21, 21 }, /* call disk_reset */
    { 0x0435, 19, 19 }, /* mov word ptr [stream_pos], 0xfff */
    { 0x043B, 21, 21 }, /* call boot_stream_byte */
    { 0x043E, 21, 21 }, /* call boot_stream_word */
    { 0x0441, 6, 6 }, /* sub ax, 3 */
    { 0x0444, 4, 4 }, /* mov cx, ax */
    { 0x0446, 4, 4 }, /* mov ax, ds */
    { 0x0448, 4, 4 }, /* mov es, ax */
    { 0x044A, 17, 17 }, /* mov di, word ptr [scenery_base] */
    { 0x044E, 21, 21 }, /* call boot_stream_byte */
    { 0x0451, 12, 12 }, /* stosb byte ptr es:[di], al */
    { 0x0452, 5, 17 }, /* loop loc_044E */
    { 0x0454, 21, 21 }, /* call sub_016B */
    { 0x0457, 19, 19 }, /* mov byte ptr [scenery_loading], 0 */
    { 0x045C, 20, 20 }, /* ret */
};

#endif
