/* Natives for subphase 3.19 sound (see docs/PHASE3_PLAN.md and docs/subphases/3.19.md): the
 * timer interrupt int8_timer (0050:07A0), sound_update (087F, its table handlers and the PIT
 * channel 0 programming at 0922) and speaker_tone (0944). speaker_off (3B29) is a 3.16 native
 * (editor.c) and is called from here.
 *
 * The emulated sound path stays: these routines write ports 40h, 42h and 61h through the CPU
 * bus (pc->cpu.bus.out8), so pc.c's PIT, port 61h and speaker event log see every write.
 *
 * As in 3.16 and 3.18 (editor.c, keys.c), the routines are transliterated on the emulated
 * registers, so every register, segment register and memory byte (stack words written by CALL
 * and PUSH included) ends as the original leaves it; flags are not kept (sound_update and
 * speaker_* callers do not read them; int8_timer's IRET restores them). Memory goes through
 * the generated accessors of game/state.h, on the live DS.
 *
 * Cycles: run(from, to) adds the cpu8086.c cost of every original instruction in [from, to)
 * (table sound_cycles.h, generated by tools/gen_sound_cycles.py), taken() the extra cost of a
 * conditional jump that was taken. Every entry's .cycles is ENTRY_CYCLES and is subtracted
 * again, so a call costs exactly what the original costs.
 *
 * Port timing. The clock is advanced instruction by instruction before each IN/OUT, and an
 * OUT is performed 2 cycles into its instruction, where cpu8086.c performs it; so the
 * speaker events get the same cycle stamps as with the original. Before a write to a PIT
 * port the native calls pc_sync_pit() (3.21) at the OUT instruction's start: pc.c advances
 * the PIT only once per CPU step, and a native is one step, so without it a reloaded count
 * would also lose the cycles of the native before the OUT. (3.19 added those ticks back to
 * pc->pit[n].count directly; the pc.c helper replaced that.)
 *
 * Calls out of a native (atis_tick, flight_forces, demo_step, speaker_tone, speaker_off and
 * unknown sound_table targets) run the target the way the CPU would with the natives on: an
 * enabled native through native_call(), anything else single-stepped as original code.
 *
 * Interrupts (same scheme as 3.18): a native that is not nested in another one runs with an
 * undo log; when the timer or the keyboard would have raised an interrupt within its cycles,
 * its writes are undone, the CPU and device state are restored, and the call is handed back
 * to the original (its first instruction is performed, then the CPU continues in the
 * original routine, with interrupts). int8_timer runs with IF clear, so a timer tick due
 * inside it would only be delivered after its IRET either way; but the keyboard is latched
 * by the step in which it falls due, which sets the time of the next latch, so the hand-back
 * is kept for every entry. int8_timer is also handed back when IF is set at its EOI: a callee
 * that ends with STI (atis_tick draws through blit_or) lets the original take a pending
 * interrupt between the EOI and the IRET. Under --verify (and nested in a native with a log)
 * they run plain. */
#include <SDL3/SDL.h>
#include <stddef.h>

#include "native.h"
#include "game/state.h"
#include "keys.h"
#include "sound_cycles.h"

/* ---- registers, memory ------------------------------------------------------------------ */

#define REG(r) (pc->cpu.regs[R_##r])
#define SREG(r) (pc->cpu.sregs[S_##r])
#define SET_LO(r, b) (REG(r) = (uint16_t)((REG(r) & 0xFF00) | (uint8_t)(b)))
#define SET_HI(r, b) (REG(r) = (uint16_t)((REG(r) & 0x00FF) | (uint16_t)((uint8_t)(b)) << 8))
#define AL ((uint8_t)REG(AX))
#define AH ((uint8_t)(REG(AX) >> 8))

/* ---- cycles ---------------------------------------------------------------------------- */

#define N_COST (sizeof sound_ins_cost / sizeof sound_ins_cost[0])
#define ENTRY_CYCLES 1

static const SoundInsCost *ins_at(uint16_t addr)
{
    size_t lo = 0, hi = N_COST;
    while (lo < hi) {
        size_t mid = (lo + hi) / 2;
        if (sound_ins_cost[mid].addr < addr)
            lo = mid + 1;
        else
            hi = mid;
    }
    return &sound_ins_cost[lo];
}

/* The original executes every instruction in [from, to) in order. */
static void run(Pc *pc, uint16_t from, uint16_t to)
{
    for (const SoundInsCost *i = ins_at(from); i < sound_ins_cost + N_COST && i->addr < to; i++)
        pc->cpu.cycles += i->cost;
}

/* The conditional jump at addr, already counted by run(), was taken. */
static void taken(Pc *pc, uint16_t addr)
{
    const SoundInsCost *i = ins_at(addr);
    pc->cpu.cycles += (uint64_t)i->taken - i->cost;
}

/* ---- ports ------------------------------------------------------------------------------ */

/* IN AL, port at 0050:at (the clock is at the instruction's start). */
static uint8_t in_at(Pc *pc, uint16_t at, uint16_t port)
{
    uint8_t v = pc->cpu.bus.in8(pc->cpu.bus.ctx, port);
    run(pc, at, (uint16_t)(at + 2));
    return v;
}

/* OUT port, AL at 0050:at (the clock is at the instruction's start). */
static void out_at(Pc *pc, uint16_t at, uint16_t port, uint8_t v)
{
    if (port >= 0x40 && port <= 0x43)
        pc_sync_pit(pc); /* the step so far counts down the old count (see the header) */
    pc->cpu.cycles += 2;
    pc->cpu.bus.out8(pc->cpu.bus.ctx, port, v);
    pc->cpu.cycles -= 2;
    run(pc, at, (uint16_t)(at + 2));
}

/* ---- calls ----------------------------------------------------------------------------- */

#define STEP_CAP 5000000L

/* Runs from 0050:target, as the CPU would with the natives on, until the routine returns
 * past the word on top of the stack. */
static void run_from(Pc *pc, uint16_t target)
{
    Cpu8086 *c = &pc->cpu;
    uint16_t sp0 = c->regs[R_SP];
    const uint8_t *map = c->hook_map;
    c->sregs[S_CS] = GAME_CS;
    c->ip = target;
    for (long n = 0; n < STEP_CAP; n++) {
        bool done = false;
        if (map && c->sregs[S_CS] == GAME_CS && map[c->ip])
            done = native_call(pc, c->ip);
        if (!done) {
            c->hook_map = NULL; /* stepped here, so that no nested --verify starts */
            cpu_step(c);
            c->hook_map = map;
        }
        uint16_t d = (uint16_t)(c->regs[R_SP] - sp0);
        if (d >= 2 && d < 0x8000)
            break;
    }
}

/* The near CALL (E8 rel16) at 0050:at: its cost, the push, the callee. */
static void call(Pc *pc, uint16_t at)
{
    uint16_t ret_ip = (uint16_t)(at + 3);
    uint16_t target = (uint16_t)(ret_ip + mem_read16(pc, GAME_CS, (uint16_t)(at + 1)));
    run(pc, at, ret_ip);
    cpu_push(&pc->cpu, ret_ip);
    run_from(pc, target);
}

/* RET at 0050:at. */
static void ret(Pc *pc, uint16_t at)
{
    run(pc, at, (uint16_t)(at + 1));
    native_ret(pc);
}

/* ---- 0050:3B29 speaker_off, 0944 speaker_tone ------------------------------------------- */

/* PIT channel 2 divisor = AX; port 61h bits 0-1 set (speaker driven by channel 2). */
static void b_speaker_tone(Pc *pc)
{
    run(pc, 0x0944, 0x0946);
    REG(BX) = REG(AX);
    SET_LO(AX, in_at(pc, 0x0946, 0x61));
    run(pc, 0x0948, 0x094A);
    SET_LO(AX, AL | 3);
    out_at(pc, 0x094A, 0x61, AL);
    run(pc, 0x094C, 0x094E);
    SET_LO(AX, REG(BX));
    out_at(pc, 0x094E, 0x42, AL);
    run(pc, 0x0950, 0x0952);
    SET_LO(AX, REG(BX) >> 8);
    out_at(pc, 0x0952, 0x42, AL);
    ret(pc, 0x0954);
}

/* ---- 0050:087F sound_update ------------------------------------------------------------- */

/* 0922: PIT channel 0 divisor = AX (also patched into int8_timer's ADD at 07B8, so pit_accum
 * carries 18.2 times a second whatever the rate). */
static void set_timer_rate(Pc *pc)
{
    run(pc, 0x0922, 0x0926);
    mem_write16(pc, GAME_CS, 0x07BC, REG(AX));
    out_at(pc, 0x0926, 0x40, AL);
    run(pc, 0x0928, 0x092A);
    SET_LO(AX, AH);
    out_at(pc, 0x092A, 0x40, AL);
    ret(pc, 0x092C);
}

/* 08C5: back to state 0 (engine). */
static void state_done(Pc *pc)
{
    run(pc, 0x08C5, 0x08CA);
    gs_set_sound_state(pc, 0);
    ret(pc, 0x08CA);
}

/* 08D3, state 0: engine. Channel 2 by rpm_deficit (0: off; 1..13h: 36 Hz buzz; else 24.9 kHz,
 * a near-silent hiss that holds the speaker high), the engine pattern restarted from
 * engine_sound, channel 0 at (19h - max(1, rpm >> 2)) * 100h. */
static void h_engine(Pc *pc)
{
    run(pc, 0x08D3, 0x08DB);
    uint8_t cl = gs_rpm_deficit(pc);
    SET_LO(CX, cl);
    if (cl == 0) {
        taken(pc, 0x08D9);
        run(pc, 0x08E8, 0x08EA);
        SET_LO(AX, AL & 0xFC);
    } else {
        run(pc, 0x08DB, 0x08E0);
        if ((int8_t)cl >= 0x14) {
            taken(pc, 0x08DE);
            run(pc, 0x08F5, 0x08F7);
            SET_LO(AX, AL | 3);
            out_at(pc, 0x08F7, 0x61, AL);
            run(pc, 0x08F9, 0x08FB);
            SET_LO(AX, 0x30);
            out_at(pc, 0x08FB, 0x42, AL);
            run(pc, 0x08FD, 0x08FF);
            SET_LO(AX, 0);
            out_at(pc, 0x08FF, 0x42, AL);
            goto engine_note;
        }
        run(pc, 0x08E0, 0x08E4);
        SET_LO(AX, AL | 3);
    }
    out_at(pc, 0x08EA, 0x61, AL);
    run(pc, 0x08EC, 0x08EE);
    SET_LO(AX, 0x80);
    out_at(pc, 0x08EE, 0x42, AL);
    out_at(pc, 0x08F0, 0x42, AL);
    run(pc, 0x08F2, 0x08F4);
engine_note:
    run(pc, 0x0901, 0x091B);
    REG(AX) = gs_engine_sound(pc);
    gs_set_spk_reload(pc, REG(AX));
    gs_set_spk_restart(pc, 1);
    uint8_t ah = (uint8_t)(gs_engine_rpm(pc) >> 2);
    if ((int8_t)ah >= 1) {
        taken(pc, 0x0919);
    } else {
        run(pc, 0x091B, 0x091D);
        ah = 1;
    }
    run(pc, 0x091D, 0x0922);
    REG(AX) = (uint16_t)((uint8_t)(0x19 - ah) << 8);
    set_timer_rate(pc);
}

static void b_sound_update(Pc *pc)
{
    SET_LO(AX, in_at(pc, 0x087F, 0x61));
    run(pc, 0x0881, 0x0888);
    if (!gs_editor_values_b(pc, 0)) { /* sound off */
        taken(pc, 0x0886);
        run(pc, 0x08E5, 0x08E8);
        run_from(pc, 0x3B29); /* speaker_off (a 3.16 native) */
        return;
    }
    run(pc, 0x0888, 0x0896);
    REG(BX) = (uint16_t)(gs_sound_state(pc) << 1);
    REG(CX) = gs_rd16(pc, (uint16_t)(GS_SOUND_TABLE + REG(BX)));
    uint16_t to = REG(CX);
    switch (to) {
    case 0x08D3: /* 0: engine */
        h_engine(pc);
        return;
    case 0x0896: /* 1: stall horn while stalled */
        run(pc, 0x0896, 0x089D);
        if (!gs_stalled(pc)) {
            taken(pc, 0x089B);
            state_done(pc);
            return;
        }
        run(pc, 0x089D, 0x08A0);
        REG(AX) = 0x05DC;
        call(pc, 0x08A0);
        ret(pc, 0x08A3);
        return;
    case 0x08A4: case 0x08A5: case 0x08A6: case 0x08A7: case 0x08A8: /* 2, 5-7: nothing */
        run(pc, to, 0x08A8);
        ret(pc, 0x08A8);
        return;
    case 0x08A9: /* 3: guns, engine pattern 9 at channel 0 divisor 12xxh */
        run(pc, 0x08A9, 0x08BD);
        gs_set_spk_reload(pc, 9);
        gs_set_spk_restart(pc, 1);
        gs_set_sound_state(pc, 0);
        SET_HI(AX, 0x12);
        set_timer_rate(pc);
        return;
    case 0x08BE: /* 4: bomb falling (the whistle is int8_timer's) */
        run(pc, 0x08BE, 0x08C5);
        if (gs_bomb_state(pc)) {
            taken(pc, 0x08C3);
            ret(pc, 0x08CA);
        } else {
            state_done(pc);
        }
        return;
    case 0x08C5:
        state_done(pc);
        return;
    case 0x08CB: /* 8: touchdown click */
        run(pc, 0x08CB, 0x08CE);
        REG(AX) = 0x0080;
        call(pc, 0x08CE);
        run(pc, 0x08D1, 0x08D3);
        state_done(pc);
        return;
    default:
        run_from(pc, to);
        return;
    }
}

/* ---- 0050:07A0 int8_timer ---------------------------------------------------------------- */

static bool if_at_eoi; /* set by b_int8_timer, read by entry_run */

static void b_int8_timer(Pc *pc)
{
    Cpu8086 *c = &pc->cpu;
    run(pc, 0x07A0, 0x07B2);
    cpu_push(c, REG(AX));
    cpu_push(c, SREG(DS));
    SREG(DS) = mem_read16(pc, 0, 0x0120);
    uint16_t pat = gs_spk_pattern(pc);
    gs_set_spk_pattern(pc, (uint16_t)(pat << 1 | pat >> 15));
    REG(AX) = (uint16_t)((pat >> 15) << 9); /* AH = old bit 15 in bit 1 */
    SET_LO(AX, in_at(pc, 0x07B2, 0x61));
    run(pc, 0x07B4, 0x07B6);
    SET_LO(AX, AL ^ AH);
    out_at(pc, 0x07B6, 0x61, AL);

    /* pit_accum += the channel 0 divisor (the immediate patched by sound_update) */
    run(pc, 0x07B8, 0x07C2);
    uint16_t a = gs_pit_accum(pc), b = mem_read16(pc, GAME_CS, 0x07BC);
    uint16_t r = (uint16_t)(a + b);
    gs_set_pit_accum(pc, r);
    bool of = ((a ^ r) & (b ^ r) & 0x8000) != 0, cf = r < a;
    if (of) {
        taken(pc, 0x07BE);
        c->cycles -= ins_at(0x07C0)->cost;
    } else if (!cf) {
        taken(pc, 0x07C0);
        goto eoi;
    }

    /* slow tick: 18.2 Hz times (1 + overflow share), normally 2 per 18.2 Hz period */
    run(pc, 0x07C2, 0x07D2);
    cpu_push(c, SREG(ES));
    cpu_push(c, REG(SI));
    cpu_push(c, REG(DI));
    cpu_push(c, REG(BP));
    cpu_push(c, REG(DX));
    cpu_push(c, REG(CX));
    cpu_push(c, REG(BX));
    SET_LO(AX, gs_comm_rate(pc));
    uint8_t acc = gs_atis_accum(pc);
    gs_set_atis_accum(pc, (uint8_t)(acc + AL));
    if ((unsigned)acc + AL < 0x100) {
        taken(pc, 0x07D0);
    } else {
        run(pc, 0x07D2, 0x07D9);
        if (gs_scenery_loading(pc) == 1)
            taken(pc, 0x07D7);
        else
            call(pc, 0x07D9); /* atis_tick */
    }
    run(pc, 0x07DC, 0x07E3);
    uint8_t ph = (uint8_t)(gs_tick_phase(pc) ^ 1);
    gs_set_tick_phase(pc, ph);
    if (ph) {
        REG(BX) = cpu_pop(c);
        REG(CX) = cpu_pop(c);
        REG(DX) = cpu_pop(c);
        REG(BP) = cpu_pop(c);
        REG(DI) = cpu_pop(c);
        REG(SI) = cpu_pop(c);
        SREG(ES) = cpu_pop(c);
        run(pc, 0x07E3, 0x07EA);
        goto eoi;
    }

    /* 18.2 Hz part */
    taken(pc, 0x07E1);
    run(pc, 0x07F4, 0x07FF);
    gs_set_tick18(pc, (uint16_t)(gs_tick18(pc) + 1));
    uint8_t kr = gs_key_recent(pc);
    if (!kr) {
        taken(pc, 0x07FD);
    } else {
        run(pc, 0x07FF, 0x0803);
        gs_set_key_recent(pc, (uint8_t)(kr - 1));
    }
    run(pc, 0x0803, 0x080A);
    if (gs_bomb_state(pc)) {
        /* bomb whistle: channel 2 divisor rises by 10 per tick up to 20000 */
        taken(pc, 0x0808);
        run(pc, 0x07F1, 0x07F4);
        run(pc, 0x092D, 0x0938);
        int16_t w = (int16_t)(gs_bomb_whistle(pc) + 10);
        if (w <= 0x4E20) {
            taken(pc, 0x0936);
        } else {
            run(pc, 0x0938, 0x093B);
            w = 0x4E20;
        }
        REG(AX) = (uint16_t)w;
        run(pc, 0x093B, 0x093E);
        gs_set_bomb_whistle(pc, REG(AX));
        call(pc, 0x093E); /* speaker_tone */
        run(pc, 0x0941, 0x0944);
    }
    run(pc, 0x080A, 0x0810);
    uint8_t div = (uint8_t)(gs_ff_divider(pc) - 1);
    gs_set_ff_divider(pc, div);
    if (div) {
        taken(pc, 0x080E);
    } else {
        run(pc, 0x0810, 0x0819);
        gs_set_ff_ticks(pc, (uint16_t)(gs_ff_ticks(pc) + 1));
        gs_set_ff_divider(pc, 3);
        call(pc, 0x0819); /* flight_forces */
        run(pc, 0x081C, 0x0825);
        SET_LO(AX, gs_spk_restart(pc) & gs_editor_values_b(pc, 0));
        if (!AL) {
            taken(pc, 0x0823);
        } else {
            run(pc, 0x0825, 0x082F);
            gs_set_spk_restart(pc, (uint8_t)(gs_spk_restart(pc) - 1));
            REG(AX) = gs_spk_reload(pc);
            gs_set_spk_pattern(pc, REG(AX));
        }
        run(pc, 0x082F, 0x0836);
        if (!gs_demo_mode(pc))
            taken(pc, 0x0834);
        else
            call(pc, 0x0836); /* demo_step */
    }
    REG(BX) = cpu_pop(c);
    REG(CX) = cpu_pop(c);
    REG(DX) = cpu_pop(c);
    REG(BP) = cpu_pop(c);
    REG(DI) = cpu_pop(c);
    REG(SI) = cpu_pop(c);
    SREG(ES) = cpu_pop(c);

    /* game clock: clock_frac += 0E11h per tick, carry = one second */
    run(pc, 0x0839, 0x0848);
    uint16_t cf0 = gs_clock_frac(pc);
    gs_set_clock_frac(pc, (uint16_t)(cf0 + 0x0E11));
    if (cf0 + 0x0E11u < 0x10000) {
        taken(pc, 0x0846);
    } else {
        run(pc, 0x0848, 0x0857);
        uint8_t s = (uint8_t)(gs_clock_sec(pc) + 1);
        gs_set_clock_sec(pc, s);
        gs_set_sec_ticks(pc, (uint8_t)(gs_sec_ticks(pc) + 1));
        if (s < 60) {
            taken(pc, 0x0855);
        } else {
            run(pc, 0x0857, 0x0860);
            gs_set_clock_sec(pc, 0);
            gs_set_clock_min(pc, (uint8_t)(gs_clock_min(pc) + 1));
        }
        run(pc, 0x0860, 0x0867);
        if (gs_clock_min(pc) < 60) {
            taken(pc, 0x0865);
        } else {
            run(pc, 0x0867, 0x0870);
            gs_set_clock_min(pc, 0);
            gs_set_clock_hour(pc, (uint8_t)(gs_clock_hour(pc) + 1));
        }
        run(pc, 0x0870, 0x0877);
        if (gs_clock_hour(pc) < 24) {
            taken(pc, 0x0875);
        } else {
            run(pc, 0x0877, 0x087C);
            gs_set_clock_hour(pc, 0);
        }
    }
    run(pc, 0x087C, 0x087F);

eoi:
    /* A callee that ends with STI (atis_tick draws through blit_or) leaves IF set: the
     * original then takes a pending interrupt right after the EOI, before its IRET. */
    if (c->flags & F_IF)
        if_at_eoi = true;
    run(pc, 0x07EA, 0x07EC);
    SET_LO(AX, 0x20);
    out_at(pc, 0x07EC, 0x20, AL);
    run(pc, 0x07EE, 0x07F1);
    SREG(DS) = cpu_pop(c);
    REG(AX) = cpu_pop(c);
    native_iret(pc);
}

/* ---- entries ----------------------------------------------------------------------------- */

static bool under_verify(Pc *pc) { return pc->cpu.write_log != NULL; }

#define DEV_A_START offsetof(Pc, pic_irr)
#define DEV_A_END offsetof(Pc, speaker)
#define DEV_B_START offsetof(Pc, speaker_count)
typedef struct DevState {
    uint8_t a[DEV_A_END - DEV_A_START];
    uint8_t b[sizeof(Pc) - DEV_B_START];
} DevState;

static void dev_save(const Pc *pc, DevState *d)
{
    SDL_memcpy(d->a, (const uint8_t *)pc + DEV_A_START, sizeof d->a);
    SDL_memcpy(d->b, (const uint8_t *)pc + DEV_B_START, sizeof d->b);
}

static void dev_load(Pc *pc, const DevState *d)
{
    SDL_memcpy((uint8_t *)pc + DEV_A_START, d->a, sizeof d->a);
    SDL_memcpy((uint8_t *)pc + DEV_B_START, d->b, sizeof d->b);
}

static CpuWriteLog irq_log;
static DevState dev_pre;

static bool log_ready(CpuWriteLog *l)
{
    if (!l->addr) {
        l->cap = 1u << 20;
        l->addr = SDL_malloc(l->cap * sizeof *l->addr);
        l->old = SDL_malloc(l->cap);
        if (!l->addr || !l->old) {
            SDL_free(l->addr);
            SDL_free(l->old);
            l->addr = NULL;
            l->old = NULL;
            return false;
        }
    }
    l->count = 0;
    l->overflow = false;
    return true;
}

/* True when the timer or the keyboard would have raised an interrupt within n cycles of the
 * step that started at `start`, judged on the device state saved before the call (the
 * native may have reloaded channel 0 since). */
static bool irq_due(const Pc *pc, const PitChannel *t0, uint32_t backlog, uint32_t frac, uint64_t start,
                    uint64_t n)
{
    bool timer = backlog || (t0->loaded && t0->count - (int64_t)((frac + n) / 4) <= 0);
    bool key = !pc->kbd_full && pc->kbd_head != pc->kbd_tail && start + n >= pc->kbd_next_cycle;
    return timer || key;
}

static void step_first(Pc *pc)
{
    Cpu8086 *c = &pc->cpu;
    const uint8_t *map = c->hook_map;
    c->hook_map = NULL;
    cpu_step(c);
    c->hook_map = map;
}

/* irq0: the call is int8_timer's, taken as IRQ0. Until its EOI the PIC holds IRQ0 (ISR bit 0),
 * and the handler runs with IF clear until the IRET unless if_at_eoi is set; so one timer
 * tick that falls due inside it is raised and delivered after the IRET with the native exactly
 * as with the original, and so is a backlog tick. The call is still handed back when two ticks
 * fall due inside it, or one does while ticks are in the backlog (the original moves a backlog
 * tick into the IRR right after its EOI, and a tick due after that merges into it), and when
 * the keyboard latches (3.21; before, any due timer tick or a nonzero backlog handed the call
 * back, which with the IRQ0 backlog was most calls). */
static bool timer_due_held(const PitChannel *t0, uint32_t backlog, uint32_t frac, uint64_t n)
{
    if (!t0->loaded)
        return false;
    int64_t left = t0->count - (int64_t)((frac + n) / 4);
    if (left > 0)
        return false;
    int64_t fires = 1 + (-left) / (t0->reload ? t0->reload : 0x10000);
    return fires >= 2 || backlog;
}

static void entry_run(Pc *pc, void (*body)(Pc *), bool irq0)
{
    Cpu8086 *c = &pc->cpu;
    uint64_t start = c->cycles;
    bool timer_held = irq0 && (pc->pic_isr & 1) && !(c->flags & F_IF);
    if (under_verify(pc)) {
        body(pc);
    } else if (log_ready(&irq_log)) {
        Cpu8086 pre = *c;
        PitChannel t0 = pc->pit[0];
        uint32_t backlog = pc->irq0_backlog, frac = pc->pit_cycle_frac;
        bool held_due = false;
        dev_save(pc, &dev_pre);
        c->write_log = &irq_log;
        if_at_eoi = false;
        body(pc);
        c->write_log = NULL;
        if (timer_held) {
            held_due = timer_due_held(&t0, backlog, frac, c->cycles - start);
            t0.loaded = false; /* irq_due: the keyboard only */
            backlog = 0;
        }
        if (!irq_log.overflow &&
            (if_at_eoi || held_due || irq_due(pc, &t0, backlog, frac, start, c->cycles - start))) {
            for (uint32_t i = irq_log.count; i-- > 0;)
                pc->mem[irq_log.addr[i]] = irq_log.old[i];
            *c = pre;
            dev_load(pc, &dev_pre);
            step_first(pc);
        }
    } else {
        body(pc);
    }
    c->cycles -= ENTRY_CYCLES;
}

static void n_speaker_tone(Pc *pc) { entry_run(pc, b_speaker_tone, false); }
static void n_sound_update(Pc *pc) { entry_run(pc, b_sound_update, false); }
static void n_int8_timer(Pc *pc) { entry_run(pc, b_int8_timer, true); }

NativeEntry native_sound[] = {
    { .name = "int8_timer", .seg = GAME_CS, .off = 0x07A0, .fn = n_int8_timer, .enabled = true, .far = true,
      .cycles = ENTRY_CYCLES },
    { .name = "sound_update", .seg = GAME_CS, .off = 0x087F, .fn = n_sound_update, .enabled = true,
      .cycles = ENTRY_CYCLES },
    { .name = "speaker_tone", .seg = GAME_CS, .off = 0x0944, .fn = n_speaker_tone, .enabled = true,
      .cycles = ENTRY_CYCLES },
    { .name = NULL },
};
