/* Emulated cycles of each original instruction in the subphase 3.19 sound routines
 * (0050:07A0-0955, 3B29-3B36), from the cpu8086.c cost model; generated by
 * tools/gen_sound_cycles.py (do not edit): address, cost (for a conditional jump: when it
 * falls through), cost when it jumps. */
#ifndef FS1_SOUND_CYCLES_H
#define FS1_SOUND_CYCLES_H

#include <stdint.h>

typedef struct SoundInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} SoundInsCost;

static const SoundInsCost sound_ins_cost[] = {
    { 0x07A0, 15, 15 }, /* push ax */
    { 0x07A1, 16, 16 }, /* push ds */
    { 0x07A2, 5, 5 }, /* xor ax, ax */
    { 0x07A4, 4, 4 }, /* mov ds, ax */
    { 0x07A6, 11, 11 }, /* mov ds, word ptr [0x120] */
    { 0x07AA, 15, 15 }, /* rol word ptr [spk_pattern], 1 */
    { 0x07AE, 8, 8 }, /* rcl ah, 1 */
    { 0x07B0, 8, 8 }, /* shl ah, 1 */
    { 0x07B2, 12, 12 }, /* in al, 0x61 */
    { 0x07B4, 5, 5 }, /* xor al, ah */
    { 0x07B6, 12, 12 }, /* out 0x61, al */
    { 0x07B8, 19, 19 }, /* add word ptr [pit_accum], 0x8000 */
    { 0x07BE, 4, 16 }, /* jo loc_07C2 */
    { 0x07C0, 4, 16 }, /* jae loc_07EA */
    { 0x07C2, 16, 16 }, /* push es */
    { 0x07C3, 15, 15 }, /* push si */
    { 0x07C4, 15, 15 }, /* push di */
    { 0x07C5, 15, 15 }, /* push bp */
    { 0x07C6, 15, 15 }, /* push dx */
    { 0x07C7, 15, 15 }, /* push cx */
    { 0x07C8, 15, 15 }, /* push bx */
    { 0x07C9, 12, 12 }, /* mov al, byte ptr [comm_rate] */
    { 0x07CC, 18, 18 }, /* add byte ptr [0x542], al */
    { 0x07D0, 4, 16 }, /* jae loc_07DC */
    { 0x07D2, 19, 19 }, /* cmp byte ptr [0x419], 1 */
    { 0x07D7, 4, 16 }, /* je loc_07DC */
    { 0x07D9, 21, 21 }, /* call atis_tick */
    { 0x07DC, 19, 19 }, /* xor byte ptr [0x555], 1 */
    { 0x07E1, 4, 16 }, /* je loc_07F4 */
    { 0x07E3, 12, 12 }, /* pop bx */
    { 0x07E4, 12, 12 }, /* pop cx */
    { 0x07E5, 12, 12 }, /* pop dx */
    { 0x07E6, 12, 12 }, /* pop bp */
    { 0x07E7, 12, 12 }, /* pop di */
    { 0x07E8, 12, 12 }, /* pop si */
    { 0x07E9, 14, 14 }, /* pop es */
    { 0x07EA, 4, 4 }, /* mov al, 0x20 */
    { 0x07EC, 12, 12 }, /* out 0x20, al */
    { 0x07EE, 14, 14 }, /* pop ds */
    { 0x07EF, 12, 12 }, /* pop ax */
    { 0x07F0, 34, 34 }, /* iret */
    { 0x07F1, 17, 17 }, /* jmp loc_092D */
    { 0x07F4, 12, 12 }, /* inc word ptr [tick18] */
    { 0x07F8, 14, 14 }, /* test byte ptr [key_recent], 0xff */
    { 0x07FD, 4, 16 }, /* je loc_0803 */
    { 0x07FF, 12, 12 }, /* dec byte ptr [key_recent] */
    { 0x0803, 19, 19 }, /* cmp word ptr [bomb_state], 0 */
    { 0x0808, 4, 16 }, /* jne loc_07F1 */
    { 0x080A, 12, 12 }, /* dec byte ptr [0x556] */
    { 0x080E, 4, 16 }, /* jne loc_0839 */
    { 0x0810, 12, 12 }, /* inc word ptr [0x549] */
    { 0x0814, 19, 19 }, /* mov byte ptr [0x556], 3 */
    { 0x0819, 21, 21 }, /* call flight_forces */
    { 0x081C, 12, 12 }, /* mov al, byte ptr [spk_restart] */
    { 0x081F, 18, 18 }, /* and al, byte ptr [editor_values] */
    { 0x0823, 4, 16 }, /* je loc_082F */
    { 0x0825, 12, 12 }, /* dec byte ptr [spk_restart] */
    { 0x0829, 12, 12 }, /* mov ax, word ptr [0x545] */
    { 0x082C, 12, 12 }, /* mov word ptr [spk_pattern], ax */
    { 0x082F, 19, 19 }, /* cmp byte ptr [demo_mode], 0 */
    { 0x0834, 4, 16 }, /* je loc_0839 */
    { 0x0836, 21, 21 }, /* call demo_step */
    { 0x0839, 12, 12 }, /* pop bx */
    { 0x083A, 12, 12 }, /* pop cx */
    { 0x083B, 12, 12 }, /* pop dx */
    { 0x083C, 12, 12 }, /* pop bp */
    { 0x083D, 12, 12 }, /* pop di */
    { 0x083E, 12, 12 }, /* pop si */
    { 0x083F, 14, 14 }, /* pop es */
    { 0x0840, 19, 19 }, /* add word ptr [clock_frac], 0xe11 */
    { 0x0846, 4, 16 }, /* jae loc_087C */
    { 0x0848, 12, 12 }, /* inc byte ptr [clock_sec] */
    { 0x084C, 12, 12 }, /* inc byte ptr [0x550] */
    { 0x0850, 19, 19 }, /* cmp byte ptr [clock_sec], 0x3c */
    { 0x0855, 4, 16 }, /* jb loc_0860 */
    { 0x0857, 19, 19 }, /* mov byte ptr [clock_sec], 0 */
    { 0x085C, 12, 12 }, /* inc byte ptr [clock_min] */
    { 0x0860, 19, 19 }, /* cmp byte ptr [clock_min], 0x3c */
    { 0x0865, 4, 16 }, /* jb loc_0870 */
    { 0x0867, 19, 19 }, /* mov byte ptr [clock_min], 0 */
    { 0x086C, 12, 12 }, /* inc byte ptr [clock_hour] */
    { 0x0870, 19, 19 }, /* cmp byte ptr [clock_hour], 0x18 */
    { 0x0875, 4, 16 }, /* jb loc_087C */
    { 0x0877, 19, 19 }, /* mov byte ptr [clock_hour], 0 */
    { 0x087C, 17, 17 }, /* jmp loc_07EA */
    { 0x087F, 12, 12 }, /* in al, 0x61 */
    { 0x0881, 14, 14 }, /* test byte ptr [editor_values], 0xff */
    { 0x0886, 4, 16 }, /* je loc_08E5 */
    { 0x0888, 17, 17 }, /* mov bl, byte ptr [sound_state] */
    { 0x088C, 5, 5 }, /* xor bh, bh */
    { 0x088E, 8, 8 }, /* shl bx, 1 */
    { 0x0890, 17, 17 }, /* mov cx, word ptr [bx + 0x559] */
    { 0x0894, 13, 13 }, /* jmp cx */
    { 0x0896, 19, 19 }, /* cmp byte ptr [stalled], 0 */
    { 0x089B, 4, 16 }, /* je loc_08C5 */
    { 0x089D, 4, 4 }, /* mov ax, 0x5dc */
    { 0x08A0, 21, 21 }, /* call speaker_tone */
    { 0x08A3, 20, 20 }, /* ret */
    { 0x08A4, 3, 3 }, /* nop */
    { 0x08A5, 3, 3 }, /* nop */
    { 0x08A6, 3, 3 }, /* nop */
    { 0x08A7, 3, 3 }, /* nop */
    { 0x08A8, 20, 20 }, /* ret */
    { 0x08A9, 19, 19 }, /* mov word ptr [0x545], 9 */
    { 0x08AF, 19, 19 }, /* mov byte ptr [spk_restart], 1 */
    { 0x08B4, 19, 19 }, /* mov byte ptr [sound_state], 0 */
    { 0x08B9, 4, 4 }, /* mov ah, 0x12 */
    { 0x08BB, 17, 17 }, /* jmp loc_0922 */
    { 0x08BE, 19, 19 }, /* cmp word ptr [bomb_state], 0 */
    { 0x08C3, 4, 16 }, /* jne loc_08CA */
    { 0x08C5, 19, 19 }, /* mov byte ptr [sound_state], 0 */
    { 0x08CA, 20, 20 }, /* ret */
    { 0x08CB, 4, 4 }, /* mov ax, 0x80 */
    { 0x08CE, 21, 21 }, /* call speaker_tone */
    { 0x08D1, 17, 17 }, /* jmp loc_08C5 */
    { 0x08D3, 17, 17 }, /* mov cl, byte ptr [rpm_deficit] */
    { 0x08D7, 5, 5 }, /* or cl, cl */
    { 0x08D9, 4, 16 }, /* je loc_08E8 */
    { 0x08DB, 6, 6 }, /* cmp cl, 0x14 */
    { 0x08DE, 4, 16 }, /* jge loc_08F5 */
    { 0x08E0, 6, 6 }, /* or al, 3 */
    { 0x08E2, 17, 17 }, /* jmp loc_08EA */
    { 0x08E5, 17, 17 }, /* jmp speaker_off */
    { 0x08E8, 6, 6 }, /* and al, 0xfc */
    { 0x08EA, 12, 12 }, /* out 0x61, al */
    { 0x08EC, 4, 4 }, /* mov al, 0x80 */
    { 0x08EE, 12, 12 }, /* out 0x42, al */
    { 0x08F0, 12, 12 }, /* out 0x42, al */
    { 0x08F2, 17, 17 }, /* jmp loc_0901 */
    { 0x08F5, 6, 6 }, /* or al, 3 */
    { 0x08F7, 12, 12 }, /* out 0x61, al */
    { 0x08F9, 4, 4 }, /* mov al, 0x30 */
    { 0x08FB, 12, 12 }, /* out 0x42, al */
    { 0x08FD, 5, 5 }, /* xor al, al */
    { 0x08FF, 12, 12 }, /* out 0x42, al */
    { 0x0901, 12, 12 }, /* mov ax, word ptr [engine_sound] */
    { 0x0904, 12, 12 }, /* mov word ptr [0x545], ax */
    { 0x0907, 19, 19 }, /* mov byte ptr [spk_restart], 1 */
    { 0x090C, 5, 5 }, /* xor al, al */
    { 0x090E, 17, 17 }, /* mov ah, byte ptr [engine_rpm] */
    { 0x0912, 8, 8 }, /* shr ah, 1 */
    { 0x0914, 8, 8 }, /* shr ah, 1 */
    { 0x0916, 6, 6 }, /* cmp ah, 1 */
    { 0x0919, 4, 16 }, /* jge loc_091D */
    { 0x091B, 4, 4 }, /* mov ah, 1 */
    { 0x091D, 5, 5 }, /* neg ah */
    { 0x091F, 6, 6 }, /* add ah, 0x19 */
    { 0x0922, 12, 12 }, /* mov word ptr cs:[0x7bc], ax */
    { 0x0926, 12, 12 }, /* out 0x40, al */
    { 0x0928, 4, 4 }, /* mov al, ah */
    { 0x092A, 12, 12 }, /* out 0x40, al */
    { 0x092C, 20, 20 }, /* ret */
    { 0x092D, 12, 12 }, /* mov ax, word ptr [bomb_whistle] */
    { 0x0930, 6, 6 }, /* add ax, 0xa */
    { 0x0933, 6, 6 }, /* cmp ax, 0x4e20 */
    { 0x0936, 4, 16 }, /* jle loc_093B */
    { 0x0938, 4, 4 }, /* mov ax, 0x4e20 */
    { 0x093B, 12, 12 }, /* mov word ptr [bomb_whistle], ax */
    { 0x093E, 21, 21 }, /* call speaker_tone */
    { 0x0941, 17, 17 }, /* jmp loc_080A */
    { 0x0944, 4, 4 }, /* mov bx, ax */
    { 0x0946, 12, 12 }, /* in al, 0x61 */
    { 0x0948, 6, 6 }, /* or al, 3 */
    { 0x094A, 12, 12 }, /* out 0x61, al */
    { 0x094C, 4, 4 }, /* mov al, bl */
    { 0x094E, 12, 12 }, /* out 0x42, al */
    { 0x0950, 4, 4 }, /* mov al, bh */
    { 0x0952, 12, 12 }, /* out 0x42, al */
    { 0x0954, 20, 20 }, /* ret */
    { 0x3B29, 19, 19 }, /* mov word ptr [spk_pattern], 0 */
    { 0x3B2F, 12, 12 }, /* in al, 0x61 */
    { 0x3B31, 6, 6 }, /* and al, 0xfc */
    { 0x3B33, 12, 12 }, /* out 0x61, al */
    { 0x3B35, 20, 20 }, /* ret */
};

#endif
