/* Emulated cycles of each original instruction in the subphase 3.22 routines (start-up code,
 * editor loop, frame and timer leftovers), from the cpu8086.c
 * cost model; generated by tools/gen_startup_cycles.py (do not edit): address, cost (for a
 * conditional jump or LOOP: when it falls through; for REP: with CX = 2), cost when it jumps. */
#ifndef FS1_STARTUP_CYCLES_H
#define FS1_STARTUP_CYCLES_H

#include <stdint.h>

typedef struct SuInsCost {
    uint16_t addr;
    uint8_t cost, taken;
} SuInsCost;

static const SuInsCost su_ins_cost[] = {
    { 0x01F0, 4, 16 }, /* je loc_01F5 */
    { 0x01F2, 21, 21 }, /* call store_ds_for_isr */
    { 0x01F5, 21, 21 }, /* call select_scenery_area */
    { 0x0211, 17, 17 }, /* jmp loc_0211 */
    { 0x04FB, 14, 14 }, /* test byte ptr [reality_mode], 0xff */
    { 0x0500, 4, 16 }, /* jne loc_0505 */
    { 0x0502, 17, 17 }, /* jmp loc_05C7 */
    { 0x0505, 12, 12 }, /* mov al, byte ptr [elevator+1] */
    { 0x0508, 18, 18 }, /* sub al, byte ptr [elevator_trim+1] */
    { 0x050C, 4, 16 }, /* je loc_052E */
    { 0x050E, 4, 16 }, /* jl loc_0520 */
    { 0x0510, 19, 19 }, /* sub word ptr [elevator], 0x100 */
    { 0x0516, 4, 16 }, /* jno loc_052E */
    { 0x0518, 19, 19 }, /* mov word ptr [elevator], 0x8001 */
    { 0x051E, 17, 17 }, /* jmp loc_052E */
    { 0x0520, 19, 19 }, /* add word ptr [elevator], 0x100 */
    { 0x0526, 4, 16 }, /* jno loc_052E */
    { 0x0528, 19, 19 }, /* mov word ptr [elevator], 0x7fff */
    { 0x052E, 21, 21 }, /* call elevator_update */
    { 0x0531, 12, 12 }, /* dec word ptr [0x408] */
    { 0x0535, 4, 16 }, /* jns loc_0551 */
    { 0x0537, 19, 19 }, /* mov word ptr [0x408], 0x3c */
    { 0x053D, 12, 12 }, /* mov al, byte ptr [pos_north+1] */
    { 0x0540, 18, 18 }, /* add al, byte ptr [pos_east+1] */
    { 0x0544, 6, 6 }, /* cmp al, 0x64 */
    { 0x0546, 4, 16 }, /* jae loc_0551 */
    { 0x0548, 18, 18 }, /* cmp al, byte ptr [reliability] */
    { 0x054C, 4, 16 }, /* jb loc_0551 */
    { 0x054E, 21, 21 }, /* call sub_05D4 */
    { 0x0551, 12, 12 }, /* mov ax, word ptr [altimeter_offset] */
    { 0x0554, 18, 18 }, /* cmp ax, word ptr [takeoff_spot] */
    { 0x0558, 4, 16 }, /* je loc_0563 */
    { 0x055A, 4, 16 }, /* jl loc_055F */
    { 0x055C, 6, 6 }, /* sub ax, 2 */
    { 0x055F, 2, 2 }, /* inc ax */
    { 0x0560, 12, 12 }, /* mov word ptr [altimeter_offset], ax */
    { 0x0563, 19, 19 }, /* add byte ptr [0x3f8], 0xff */
    { 0x0568, 19, 19 }, /* adc word ptr [dg_offset], 0 */
    { 0x056D, 14, 14 }, /* test word ptr [time_of_day], 1 */
    { 0x0573, 4, 16 }, /* jne loc_0589 */
    { 0x0575, 15, 15 }, /* shr byte ptr [0x41a], 1 */
    { 0x0579, 4, 16 }, /* jb loc_059D */
    { 0x057B, 19, 19 }, /* mov word ptr [0x19a6], 0x8010 */
    { 0x0581, 19, 19 }, /* cmp byte ptr [lights], 0 */
    { 0x0586, 4, 16 }, /* jne loc_0589 */
    { 0x0588, 20, 20 }, /* ret */
    { 0x0589, 14, 14 }, /* test word ptr [frame_counter], 0xffc */
    { 0x058F, 4, 16 }, /* jne loc_0596 */
    { 0x0591, 19, 19 }, /* mov byte ptr [0x41a], 0 */
    { 0x0596, 12, 12 }, /* mov ax, word ptr [0x41b] */
    { 0x0599, 12, 12 }, /* mov word ptr [0x19a6], ax */
    { 0x059C, 20, 20 }, /* ret */
    { 0x059D, 17, 17 }, /* mov cl, byte ptr [frame_counter+1] */
    { 0x05A1, 4, 4 }, /* mov ax, 0xff7f */
    { 0x05A4, 12, 12 }, /* rol al, cl */
    { 0x05A6, 18, 18 }, /* and word ptr [0x41b], ax */
    { 0x05AA, 12, 12 }, /* mov ax, word ptr [frame_counter] */
    { 0x05AD, 6, 6 }, /* and ax, 0x3ffc */
    { 0x05B0, 4, 16 }, /* jne loc_05C6 */
    { 0x05B2, 19, 19 }, /* cmp word ptr [throttle], 0x4000 */
    { 0x05B8, 4, 16 }, /* jge loc_05C6 */
    { 0x05BA, 19, 19 }, /* cmp byte ptr [season], 2 */
    { 0x05BF, 4, 16 }, /* jne loc_05C6 */
    { 0x05C1, 19, 19 }, /* mov byte ptr [carb_ice], 0x14 */
    { 0x05C6, 20, 20 }, /* ret */
    { 0x05C7, 19, 19 }, /* mov word ptr [altimeter_offset], 0 */
    { 0x05CD, 19, 19 }, /* mov word ptr [dg_offset], 0 */
    { 0x05D3, 20, 20 }, /* ret */
    { 0x05D4, 4, 4 }, /* mov si, 0x4e7 */
    { 0x05D7, 21, 21 }, /* call clear_screen */
    { 0x05DA, 21, 21 }, /* call print_str */
    { 0x05DD, 12, 12 }, /* mov al, byte ptr [frame_counter] */
    { 0x05E0, 18, 18 }, /* add al, byte ptr [altitude+1] */
    { 0x05E4, 6, 6 }, /* and ax, 0xe */
    { 0x05E7, 4, 4 }, /* mov bx, ax */
    { 0x05E9, 17, 17 }, /* mov cx, word ptr [bx + area_bounds+42] */
    { 0x05ED, 13, 13 }, /* jmp cx */
    { 0x0629, 5, 5 }, /* or bl, bl */
    { 0x062B, 4, 16 }, /* je loc_0657 */
    { 0x062D, 5, 5 }, /* xor bh, bh */
    { 0x062F, 17, 17 }, /* mov si, word ptr [bx + crash_messages] */
    { 0x0633, 21, 21 }, /* call clear_screen */
    { 0x0636, 21, 21 }, /* call print_str */
    { 0x0639, 4, 4 }, /* mov cx, 0xffff */
    { 0x063C, 72, 72 }, /* mul cl */
    { 0x063E, 72, 72 }, /* mul cl */
    { 0x0640, 72, 72 }, /* mul cl */
    { 0x0642, 5, 17 }, /* loop loc_063C */
    { 0x0644, 21, 21 }, /* call usermode_recall */
    { 0x0647, 21, 21 }, /* call editor_apply_state */
    { 0x064A, 19, 19 }, /* mov byte ptr [crash_code], 0 */
    { 0x064F, 19, 19 }, /* mov byte ptr [gear_down], 0xff */
    { 0x0654, 21, 21 }, /* call gear_drag_update */
    { 0x0657, 20, 20 }, /* ret */
    { 0x0732, 2, 2 }, /* cli */
    { 0x0733, 18, 18 }, /* mov word ptr [scenery_base], cx */
    { 0x0737, 36, 36 }, /* rep movsb byte ptr es:[di], byte ptr [si] */
    { 0x0739, 4, 4 }, /* mov ds, bp */
    { 0x073B, 12, 12 }, /* mov word ptr [0x120], ax */
    { 0x073E, 4, 4 }, /* mov ds, ax */
    { 0x0740, 2, 2 }, /* sti */
    { 0x0741, 20, 20 }, /* ret */
    { 0x0790, 21, 21 }, /* call nav_tune */
    { 0x0793, 21, 21 }, /* call com_tune */
    { 0x0796, 21, 21 }, /* call text_07c5 */
    { 0x0799, 21, 21 }, /* call clock_hm */
    { 0x079C, 21, 21 }, /* call switch_text */
    { 0x079F, 20, 20 }, /* ret */
    { 0x110C, 17, 17 }, /* mov bx, word ptr [demo_ptr] */
    { 0x1110, 5, 5 }, /* or bx, bx */
    { 0x1112, 4, 16 }, /* jne loc_1120 */
    { 0x1114, 12, 12 }, /* mov ax, word ptr [demo_script] */
    { 0x1117, 4, 4 }, /* mov bx, ax */
    { 0x1119, 12, 12 }, /* mov word ptr [demo_ptr], ax */
    { 0x111C, 5, 5 }, /* or ax, ax */
    { 0x111E, 4, 16 }, /* je loc_1131 */
    { 0x1120, 17, 17 }, /* mov al, byte ptr [bx] */
    { 0x1122, 5, 5 }, /* or al, al */
    { 0x1124, 4, 16 }, /* js loc_1132 */
    { 0x1126, 6, 6 }, /* cmp al, 0x7f */
    { 0x1128, 4, 16 }, /* je loc_1114 */
    { 0x112A, 21, 21 }, /* call key_dispatch */
    { 0x112D, 12, 12 }, /* inc word ptr [demo_ptr] */
    { 0x1131, 20, 20 }, /* ret */
    { 0x1132, 19, 19 }, /* cmp byte ptr [sound_table+23], 0 */
    { 0x1137, 4, 16 }, /* je loc_1145 */
    { 0x1139, 12, 12 }, /* dec byte ptr [sound_table+23] */
    { 0x113D, 4, 16 }, /* jne loc_1131 */
    { 0x113F, 12, 12 }, /* inc word ptr [demo_ptr] */
    { 0x1143, 17, 17 }, /* jmp demo_step */
    { 0x1145, 6, 6 }, /* sub al, 0x80 */
    { 0x1147, 12, 12 }, /* mov byte ptr [sound_table+23], al */
    { 0x114A, 17, 17 }, /* jmp loc_1139 */
    { 0x13C6, 14, 14 }, /* test word ptr [panel_mask], 0x1000 */
    { 0x13CC, 4, 16 }, /* je loc_13F9 */
    { 0x13CE, 12, 12 }, /* mov ax, word ptr [hdg_display] */
    { 0x13D1, 4, 4 }, /* mov dx, ax */
    { 0x13D3, 17, 17 }, /* mov cx, word ptr [0x6a2] */
    { 0x13D7, 18, 18 }, /* sub ax, word ptr [view_heading] */
    { 0x13DB, 18, 18 }, /* add ax, word ptr [wind_gust_offset] */
    { 0x13DF, 18, 18 }, /* add ax, word ptr [wind_dir_offset] */
    { 0x13E3, 4, 16 }, /* je loc_1446 */
    { 0x13E5, 4, 16 }, /* js loc_13FA */
    { 0x13E7, 6, 6 }, /* cmp ax, 0xa00 */
    { 0x13EA, 4, 16 }, /* jg loc_13F4 */
    { 0x13EC, 8, 8 }, /* sar cx, 1 */
    { 0x13EE, 8, 8 }, /* sar cx, 1 */
    { 0x13F0, 8, 8 }, /* sar cx, 1 */
    { 0x13F2, 8, 8 }, /* sar cx, 1 */
    { 0x13F4, 5, 5 }, /* sub dx, cx */
    { 0x13F6, 17, 17 }, /* jmp loc_1409 */
    { 0x13F9, 20, 20 }, /* ret */
    { 0x13FA, 6, 6 }, /* cmp ax, 0xf600 */
    { 0x13FD, 4, 16 }, /* jl loc_1407 */
    { 0x13FF, 8, 8 }, /* sar cx, 1 */
    { 0x1401, 8, 8 }, /* sar cx, 1 */
    { 0x1403, 8, 8 }, /* sar cx, 1 */
    { 0x1405, 8, 8 }, /* sar cx, 1 */
    { 0x1407, 5, 5 }, /* add dx, cx */
    { 0x1409, 18, 18 }, /* mov word ptr [hdg_display], dx */
    { 0x140D, 4, 4 }, /* mov ax, 0x168 */
    { 0x1410, 120, 120 }, /* mul dx */
    { 0x1412, 4, 4 }, /* mov ax, dx */
    { 0x1414, 4, 4 }, /* mov si, 0x79d */
    { 0x1417, 4, 4 }, /* mov bx, 0x79f */
    { 0x141A, 4, 4 }, /* mov dl, 0x30 */
    { 0x141C, 6, 6 }, /* cmp ax, 0x64 */
    { 0x141F, 4, 16 }, /* jl loc_1428 */
    { 0x1421, 6, 6 }, /* sub ax, 0x64 */
    { 0x1424, 5, 5 }, /* inc dl */
    { 0x1426, 17, 17 }, /* jmp loc_141C */
    { 0x1428, 18, 18 }, /* mov byte ptr [bx], dl */
    { 0x142A, 4, 4 }, /* mov dl, 0x30 */
    { 0x142C, 6, 6 }, /* cmp ax, 0xa */
    { 0x142F, 4, 16 }, /* jl loc_1438 */
    { 0x1431, 6, 6 }, /* sub ax, 0xa */
    { 0x1434, 5, 5 }, /* inc dl */
    { 0x1436, 17, 17 }, /* jmp loc_142C */
    { 0x1438, 18, 18 }, /* mov byte ptr [bx + 1], dl */
    { 0x143B, 6, 6 }, /* add al, 0x30 */
    { 0x143D, 18, 18 }, /* mov byte ptr [bx + 2], al */
    { 0x1440, 4, 4 }, /* mov cx, 0x5555 */
    { 0x1443, 21, 21 }, /* call print_str_mask */
    { 0x1446, 20, 20 }, /* ret */
    { 0x1CEC, 12, 12 }, /* mov ax, word ptr [pos_north+2] */
    { 0x1CEF, 6, 6 }, /* add ax, 0x4000 */
    { 0x1CF2, 12, 12 }, /* mov word ptr [editor_north], ax */
    { 0x1CF5, 12, 12 }, /* mov ax, word ptr [pos_east+2] */
    { 0x1CF8, 6, 6 }, /* add ax, 0x4000 */
    { 0x1CFB, 12, 12 }, /* mov word ptr [editor_east], ax */
    { 0x1CFE, 20, 20 }, /* ret */
    { 0x2EDB, 19, 19 }, /* mov word ptr [engine_sound], 0 */
    { 0x2EE1, 19, 19 }, /* mov byte ptr [rpm_deficit], 0 */
    { 0x2EE6, 19, 19 }, /* mov byte ptr [engine_running], 0 */
    { 0x2EEB, 20, 20 }, /* ret */
    { 0x3640, 21, 21 }, /* call editor_capture_state */
    { 0x3643, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x3647, 21, 21 }, /* call sub_5619 */
    { 0x364A, 21, 21 }, /* call editor_first_page */
    { 0x364D, 21, 21 }, /* call editor_get_input */
    { 0x3650, 12, 12 }, /* mov al, byte ptr [editor_typed] */
    { 0x3653, 5, 5 }, /* or al, al */
    { 0x3655, 4, 16 }, /* je loc_366A */
    { 0x3657, 21, 21 }, /* call editor_commit */
    { 0x365A, 12, 12 }, /* mov al, byte ptr [editor_page] */
    { 0x365D, 5, 5 }, /* or al, al */
    { 0x365F, 4, 16 }, /* jne loc_366A */
    { 0x3661, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x3664, 6, 6 }, /* cmp al, 2 */
    { 0x3666, 4, 16 }, /* jne loc_366A */
    { 0x3668, 17, 17 }, /* jmp loc_364D */
    { 0x366A, 12, 12 }, /* mov al, byte ptr [editor_exit] */
    { 0x366D, 5, 5 }, /* or al, al */
    { 0x366F, 4, 16 }, /* je loc_3674 */
    { 0x3671, 17, 17 }, /* jmp editor_apply_state */
    { 0x3674, 12, 12 }, /* mov al, byte ptr [editor_up] */
    { 0x3677, 5, 5 }, /* or al, al */
    { 0x3679, 4, 16 }, /* je loc_3685 */
    { 0x367B, 19, 19 }, /* mov byte ptr [editor_up], 0 */
    { 0x3680, 21, 21 }, /* call editor_prev_row */
    { 0x3683, 17, 17 }, /* jmp loc_364D */
    { 0x3685, 21, 21 }, /* call editor_next_row */
    { 0x3688, 17, 17 }, /* jmp loc_364D */
    { 0x3703, 19, 19 }, /* mov byte ptr [editor_typed], 0 */
    { 0x3708, 21, 21 }, /* call editor_row_ptr */
    { 0x370B, 19, 19 }, /* mov word ptr [editor_cell], 5 */
    { 0x3711, 19, 19 }, /* mov byte ptr [editor_ndigits], 0 */
    { 0x3716, 19, 19 }, /* mov byte ptr [editor_exit], 0 */
    { 0x371B, 4, 4 }, /* mov di, 5 */
    { 0x371E, 19, 19 }, /* mov byte ptr [di + editor_digits], 0x30 */
    { 0x3723, 2, 2 }, /* dec di */
    { 0x3724, 4, 16 }, /* jns loc_371E */
    { 0x3726, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x3729, 5, 5 }, /* or al, al */
    { 0x372B, 4, 16 }, /* jns loc_3726 */
    { 0x372D, 19, 19 }, /* mov byte ptr [editor_key], 0 */
    { 0x3732, 6, 6 }, /* and al, 0x7f */
    { 0x3734, 6, 6 }, /* cmp al, 0xd */
    { 0x3736, 4, 16 }, /* je loc_374E */
    { 0x3738, 6, 6 }, /* cmp al, 0x3d */
    { 0x373A, 4, 16 }, /* je loc_374E */
    { 0x373C, 6, 6 }, /* cmp al, 0x2d */
    { 0x373E, 4, 16 }, /* jne loc_3746 */
    { 0x3740, 12, 12 }, /* mov byte ptr [editor_up], al */
    { 0x3743, 17, 17 }, /* jmp loc_374E */
    { 0x3746, 6, 6 }, /* cmp al, 0x1b */
    { 0x3748, 4, 16 }, /* jne loc_3752 */
    { 0x374A, 12, 12 }, /* inc byte ptr [editor_exit] */
    { 0x374E, 21, 21 }, /* call editor_digits_to_bin */
    { 0x3751, 20, 20 }, /* ret */
    { 0x3752, 6, 6 }, /* cmp al, 8 */
    { 0x3754, 4, 16 }, /* jne loc_3789 */
    { 0x3756, 12, 12 }, /* mov al, byte ptr [editor_ndigits] */
    { 0x3759, 5, 5 }, /* or al, al */
    { 0x375B, 4, 16 }, /* je loc_3726 */
    { 0x375D, 12, 12 }, /* dec byte ptr [editor_ndigits] */
    { 0x3761, 4, 4 }, /* mov al, 0x20 */
    { 0x3763, 12, 12 }, /* dec word ptr [editor_cell] */
    { 0x3767, 17, 17 }, /* mov si, word ptr [editor_cell] */
    { 0x376B, 8, 8 }, /* shl si, 1 */
    { 0x376D, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x3770, 4, 4 }, /* mov di, 1 */
    { 0x3773, 17, 17 }, /* mov al, byte ptr [di + editor_digits] */
    { 0x3777, 18, 18 }, /* mov byte ptr [di + editor_ndigits], al */
    { 0x377B, 2, 2 }, /* inc di */
    { 0x377C, 6, 6 }, /* cmp di, 6 */
    { 0x377F, 4, 16 }, /* jne loc_3773 */
    { 0x3781, 19, 19 }, /* mov byte ptr [0x2031], 0x30 */
    { 0x3786, 17, 17 }, /* jmp loc_3800 */
    { 0x3789, 4, 4 }, /* mov cx, 0x30b4 */
    { 0x378C, 4, 4 }, /* mov si, 0x2916 */
    { 0x378F, 5, 5 }, /* sub cx, si */
    { 0x3791, 19, 19 }, /* mov byte ptr [disk_track], 0x26 */
    { 0x3796, 6, 6 }, /* cmp al, 0x73 */
    { 0x3798, 4, 16 }, /* jne loc_37B1 */
    { 0x379A, 21, 21 }, /* call cga_program_regs */
    { 0x379D, 21, 21 }, /* call disk_reset */
    { 0x37A0, 19, 19 }, /* mov word ptr [stream_pos], 0xffff */
    { 0x37A6, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x37A7, 21, 21 }, /* call boot_stream_put_byte */
    { 0x37AA, 5, 17 }, /* loop loc_37A6 */
    { 0x37AC, 21, 21 }, /* call sub_01DE */
    { 0x37AF, 17, 17 }, /* jmp loc_37C9 */
    { 0x37B1, 6, 6 }, /* cmp al, 0x6c */
    { 0x37B3, 4, 16 }, /* jne loc_37D0 */
    { 0x37B5, 21, 21 }, /* call cga_program_regs */
    { 0x37B8, 21, 21 }, /* call disk_reset */
    { 0x37BB, 4, 4 }, /* mov di, si */
    { 0x37BD, 19, 19 }, /* mov word ptr [stream_pos], 0xfff */
    { 0x37C3, 21, 21 }, /* call boot_stream_byte */
    { 0x37C6, 12, 12 }, /* stosb byte ptr es:[di], al */
    { 0x37C7, 5, 17 }, /* loop loc_37C3 */
    { 0x37C9, 12, 12 }, /* pop ax */
    { 0x37CA, 21, 21 }, /* call sub_016B */
    { 0x37CD, 17, 17 }, /* jmp loc_3643 */
    { 0x37D0, 6, 6 }, /* cmp al, 0x2a */
    { 0x37D2, 4, 16 }, /* jne loc_37D9 */
    { 0x37D4, 21, 21 }, /* call usermode_recall */
    { 0x37D7, 17, 17 }, /* jmp loc_37EC */
    { 0x37D9, 6, 6 }, /* cmp al, 0x11 */
    { 0x37DB, 4, 16 }, /* jne loc_37FC */
    { 0x37DD, 19, 19 }, /* cmp byte ptr [editor_usermode], 0xa */
    { 0x37E2, 4, 16 }, /* jae loc_37E9 */
    { 0x37E4, 12, 12 }, /* inc byte ptr [editor_typed] */
    { 0x37E8, 20, 20 }, /* ret */
    { 0x37E9, 21, 21 }, /* call usermode_store */
    { 0x37EC, 19, 19 }, /* mov byte ptr [editor_typed], 0 */
    { 0x37F1, 12, 12 }, /* mov al, byte ptr [editor_row] */
    { 0x37F4, 6, 6 }, /* sub al, 2 */
    { 0x37F6, 12, 12 }, /* mov byte ptr [editor_saved_row], al */
    { 0x37F9, 17, 17 }, /* jmp loc_3954 */
    { 0x37FC, 6, 6 }, /* cmp al, 0x30 */
    { 0x37FE, 4, 16 }, /* jae loc_3803 */
    { 0x3800, 17, 17 }, /* jmp loc_3726 */
    { 0x3803, 6, 6 }, /* cmp al, 0x3a */
    { 0x3805, 4, 16 }, /* jae loc_3800 */
    { 0x3807, 17, 17 }, /* mov si, word ptr [editor_cell] */
    { 0x380B, 6, 6 }, /* cmp si, 0xb */
    { 0x380E, 4, 16 }, /* je loc_3800 */
    { 0x3810, 12, 12 }, /* inc byte ptr [editor_typed] */
    { 0x3814, 12, 12 }, /* mov byte ptr [editor_digit], al */
    { 0x3817, 12, 12 }, /* mov al, byte ptr [editor_ndigits] */
    { 0x381A, 5, 5 }, /* or al, al */
    { 0x381C, 4, 16 }, /* jne loc_382E */
    { 0x381E, 4, 4 }, /* mov si, 0x18 */
    { 0x3821, 4, 4 }, /* mov al, 0x20 */
    { 0x3823, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x3826, 6, 6 }, /* sub si, 2 */
    { 0x3829, 6, 6 }, /* cmp si, 8 */
    { 0x382C, 4, 16 }, /* jne loc_3823 */
    { 0x382E, 4, 4 }, /* mov di, 4 */
    { 0x3831, 17, 17 }, /* mov al, byte ptr [di + editor_digits] */
    { 0x3835, 18, 18 }, /* mov byte ptr [di + 0x202d], al */
    { 0x3839, 2, 2 }, /* dec di */
    { 0x383A, 4, 16 }, /* jns loc_3831 */
    { 0x383C, 12, 12 }, /* mov al, byte ptr [editor_digit] */
    { 0x383F, 12, 12 }, /* mov byte ptr [editor_digits], al */
    { 0x3842, 12, 12 }, /* inc byte ptr [editor_ndigits] */
    { 0x3846, 17, 17 }, /* mov si, word ptr [editor_cell] */
    { 0x384A, 8, 8 }, /* shl si, 1 */
    { 0x384C, 18, 18 }, /* mov byte ptr es:[bx + si], al */
    { 0x384F, 12, 12 }, /* inc word ptr [editor_cell] */
    { 0x3853, 17, 17 }, /* jmp loc_3800 */
    { 0x4A82, 5, 5 }, /* xor ax, ax */
    { 0x4A84, 8, 8 }, /* sar dx, 1 */
    { 0x4A86, 8, 8 }, /* rcr ax, 1 */
    { 0x4A88, 167, 167 }, /* idiv bx */
    { 0x4A8A, 4, 4 }, /* mov bp, ax */
    { 0x4A8C, 5, 5 }, /* sub cx, si */
    { 0x4A8E, 130, 130 }, /* imul cx */
    { 0x4A90, 8, 8 }, /* shl ax, 1 */
    { 0x4A92, 8, 8 }, /* rcl dx, 1 */
    { 0x4A94, 5, 5 }, /* add si, dx */
    { 0x4A96, 4, 4 }, /* mov cx, ax */
    { 0x4A98, 12, 12 }, /* mov ax, word ptr [eye_p2+4] */
    { 0x4A9B, 18, 18 }, /* sub ax, word ptr [eye_p1+4] */
    { 0x4A9F, 130, 130 }, /* imul bp */
    { 0x4AA1, 8, 8 }, /* shl ax, 1 */
    { 0x4AA3, 8, 8 }, /* rcl dx, 1 */
    { 0x4AA5, 18, 18 }, /* add dx, word ptr [eye_p1+4] */
    { 0x4AA9, 17, 17 }, /* jmp loc_4AD2 */
    { 0x4AAB, 5, 5 }, /* xor ax, ax */
    { 0x4AAD, 8, 8 }, /* sar dx, 1 */
    { 0x4AAF, 8, 8 }, /* rcr ax, 1 */
    { 0x4AB1, 167, 167 }, /* idiv bx */
    { 0x4AB3, 4, 4 }, /* mov bp, ax */
    { 0x4AB5, 5, 5 }, /* sub cx, si */
    { 0x4AB7, 130, 130 }, /* imul cx */
    { 0x4AB9, 8, 8 }, /* shl ax, 1 */
    { 0x4ABB, 8, 8 }, /* rcl dx, 1 */
    { 0x4ABD, 5, 5 }, /* add si, dx */
    { 0x4ABF, 4, 4 }, /* mov cx, ax */
    { 0x4AC1, 12, 12 }, /* mov ax, word ptr [eye_p1+4] */
    { 0x4AC4, 18, 18 }, /* sub ax, word ptr [eye_p2+4] */
    { 0x4AC8, 130, 130 }, /* imul bp */
    { 0x4ACA, 8, 8 }, /* shl ax, 1 */
    { 0x4ACC, 8, 8 }, /* rcl dx, 1 */
    { 0x4ACE, 18, 18 }, /* add dx, word ptr [eye_p2+4] */
    { 0x4AD2, 4, 4 }, /* mov di, ax */
    { 0x4AD4, 4, 4 }, /* mov bp, 0x10 */
    { 0x4AD7, 4, 4 }, /* mov ax, dx */
    { 0x4AD9, 6, 6 }, /* add ah, 0x10 */
    { 0x4ADC, 6, 6 }, /* cmp ah, 0x1f */
    { 0x4ADF, 4, 16 }, /* ja loc_4AF6 */
    { 0x4AE1, 4, 4 }, /* mov ax, si */
    { 0x4AE3, 6, 6 }, /* add ah, 0x10 */
    { 0x4AE6, 6, 6 }, /* cmp ah, 0x1f */
    { 0x4AE9, 4, 16 }, /* ja loc_4AF6 */
    { 0x4AEB, 8, 8 }, /* shl di, 1 */
    { 0x4AED, 8, 8 }, /* rcl dx, 1 */
    { 0x4AEF, 8, 8 }, /* shl cx, 1 */
    { 0x4AF1, 8, 8 }, /* rcl si, 1 */
    { 0x4AF3, 2, 2 }, /* dec bp */
    { 0x4AF4, 4, 16 }, /* jne loc_4AD7 */
    { 0x4AF6, 20, 20 }, /* ret */
    { 0x4DC6, 4, 4 }, /* mov ax, dx */
    { 0x4DC8, 5, 5 }, /* xor ax, bx */
    { 0x4DCA, 4, 4 }, /* mov ax, 0x7fff */
    { 0x4DCD, 4, 16 }, /* jns loc_4DD1 */
    { 0x4DCF, 5, 5 }, /* neg ax */
    { 0x4DD1, 2, 2 }, /* sti */
    { 0x4DD2, 34, 34 }, /* iret */
    { 0x5600, 4, 4 }, /* mov bx, 0x399c */
    { 0x5603, 17, 17 }, /* mov dl, byte ptr [bx] */
    { 0x5605, 5, 5 }, /* or dl, dl */
    { 0x5607, 4, 16 }, /* je loc_5618 */
    { 0x5609, 2, 2 }, /* inc bx */
    { 0x560A, 5, 5 }, /* xor dh, dh */
    { 0x560C, 6, 6 }, /* add dx, 0x3d0 */
    { 0x5610, 17, 17 }, /* mov al, byte ptr [bx] */
    { 0x5612, 4, 4 }, /* mov ah, dh */
    { 0x5614, 2, 2 }, /* inc bx */
    { 0x5615, 12, 12 }, /* out dx, al */
    { 0x5616, 17, 17 }, /* jmp loc_5603 */
    { 0x5618, 20, 20 }, /* ret */
    { 0x5619, 4, 4 }, /* mov bx, 0x39db */
    { 0x561C, 17, 17 }, /* jmp loc_5603 */
    { 0x5AD7, 16, 16 }, /* push es */
    { 0x5AD8, 21, 21 }, /* call sub_5B1D */
    { 0x5ADB, 5, 5 }, /* xor al, al */
    { 0x5ADD, 4, 4 }, /* mov di, bp */
    { 0x5ADF, 18, 18 }, /* and byte ptr es:[di], dl */
    { 0x5AE2, 2, 2 }, /* inc di */
    { 0x5AE3, 4, 4 }, /* mov cl, ah */
    { 0x5AE5, 5, 5 }, /* xor ch, ch */
    { 0x5AE7, 22, 22 }, /* rep stosb byte ptr es:[di], al */
    { 0x5AE9, 18, 18 }, /* and byte ptr es:[di], dh */
    { 0x5AEC, 21, 21 }, /* call sub_5B76 */
    { 0x5AEF, 4, 16 }, /* jne loc_5ADD */
    { 0x5AF1, 14, 14 }, /* pop es */
    { 0x5AF2, 20, 20 }, /* ret */
    { 0x5AF3, 16, 16 }, /* push es */
    { 0x5AF4, 16, 16 }, /* push ds */
    { 0x5AF5, 21, 21 }, /* call sub_5B1D */
    { 0x5AF8, 5, 5 }, /* not dx */
    { 0x5AFA, 11, 11 }, /* mov ds, word ptr [view_buf_seg] */
    { 0x5AFE, 4, 4 }, /* mov di, bp */
    { 0x5B00, 4, 4 }, /* mov si, bp */
    { 0x5B02, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x5B03, 5, 5 }, /* and al, dl */
    { 0x5B05, 18, 18 }, /* or byte ptr es:[di], al */
    { 0x5B08, 2, 2 }, /* inc di */
    { 0x5B09, 4, 4 }, /* mov cl, ah */
    { 0x5B0B, 5, 5 }, /* xor ch, ch */
    { 0x5B0D, 36, 36 }, /* rep movsb byte ptr es:[di], byte ptr [si] */
    { 0x5B0F, 15, 15 }, /* lodsb al, byte ptr [si] */
    { 0x5B10, 5, 5 }, /* and al, dh */
    { 0x5B12, 18, 18 }, /* or byte ptr es:[di], al */
    { 0x5B15, 21, 21 }, /* call sub_5B76 */
    { 0x5B18, 4, 16 }, /* jne loc_5AFE */
    { 0x5B1A, 14, 14 }, /* pop ds */
    { 0x5B1B, 14, 14 }, /* pop es */
    { 0x5B1C, 20, 20 }, /* ret */
    { 0x5B1D, 17, 17 }, /* mov ax, word ptr [bx] */
    { 0x5B1F, 4, 4 }, /* mov cl, ah */
    { 0x5B21, 5, 5 }, /* xor ch, ch */
    { 0x5B23, 8, 8 }, /* shr cx, 1 */
    { 0x5B25, 8, 8 }, /* shr cx, 1 */
    { 0x5B27, 4, 4 }, /* mov di, cx */
    { 0x5B29, 6, 6 }, /* and ax, 0x3ff */
    { 0x5B2C, 4, 4 }, /* mov cx, ax */
    { 0x5B2E, 6, 6 }, /* and cx, 7 */
    { 0x5B32, 8, 8 }, /* shr ax, 1 */
    { 0x5B34, 8, 8 }, /* shr ax, 1 */
    { 0x5B36, 8, 8 }, /* shr ax, 1 */
    { 0x5B38, 4, 4 }, /* mov bp, ax */
    { 0x5B3A, 17, 17 }, /* mov bx, word ptr [bx + 2] */
    { 0x5B3D, 4, 4 }, /* mov si, bx */
    { 0x5B3F, 5, 5 }, /* xor bh, bh */
    { 0x5B41, 8, 8 }, /* shl bx, 1 */
    { 0x5B43, 18, 18 }, /* add bp, word ptr [bx + row_offsets] */
    { 0x5B47, 4, 4 }, /* mov ax, si */
    { 0x5B49, 4, 4 }, /* mov bx, cx */
    { 0x5B4B, 17, 17 }, /* mov dl, byte ptr [bx + 0x39f8] */
    { 0x5B4F, 5, 5 }, /* neg bl */
    { 0x5B51, 6, 6 }, /* add bl, 8 */
    { 0x5B54, 5, 5 }, /* sub ah, bl */
    { 0x5B56, 5, 5 }, /* xor al, al */
    { 0x5B58, 6, 6 }, /* sub ah, 8 */
    { 0x5B5B, 4, 16 }, /* jb loc_5B61 */
    { 0x5B5D, 5, 5 }, /* inc al */
    { 0x5B5F, 17, 17 }, /* jmp loc_5B58 */
    { 0x5B61, 6, 6 }, /* xchg ah, al */
    { 0x5B63, 6, 6 }, /* add al, 8 */
    { 0x5B65, 4, 4 }, /* mov bl, al */
    { 0x5B67, 5, 5 }, /* xor bh, bh */
    { 0x5B69, 17, 17 }, /* mov dh, byte ptr [bx + 0x39f8] */
    { 0x5B6D, 5, 5 }, /* not dh */
    { 0x5B6F, 11, 11 }, /* mov es, word ptr [screen_seg] */
    { 0x5B73, 4, 4 }, /* mov bx, di */
    { 0x5B75, 20, 20 }, /* ret */
    { 0x5B76, 6, 6 }, /* cmp bp, 0x2000 */
    { 0x5B7A, 4, 16 }, /* jge loc_5B82 */
    { 0x5B7C, 6, 6 }, /* add bp, 0x2000 */
    { 0x5B80, 17, 17 }, /* jmp loc_5B86 */
    { 0x5B82, 6, 6 }, /* add bp, 0xe050 */
    { 0x5B86, 2, 2 }, /* dec bx */
    { 0x5B87, 20, 20 }, /* ret */
    { 0x5C9F, 5, 5 }, /* xor ax, ax */
    { 0x5CA1, 4, 4 }, /* mov ds, ax */
    { 0x5CA3, 11, 11 }, /* mov ds, word ptr [0x120] */
    { 0x5CA7, 21, 21 }, /* call cga_program_regs */
    { 0x5CAA, 21, 21 }, /* call hook_int9 */
    { 0x5CAD, 21, 21 }, /* call sub_6254 */
    { 0x5CB0, 21, 21 }, /* call sub_6265 */
    { 0x5CB3, 21, 21 }, /* call startup_menus */
    { 0x5CB6, 21, 21 }, /* call cga_program_regs */
    { 0x5CB9, 21, 21 }, /* call hook_int8 */
    { 0x5CBC, 21, 21 }, /* call usermode_recall */
    { 0x5CBF, 21, 21 }, /* call editor_apply_state */
    { 0x5CC2, 21, 21 }, /* call set_reloc_args */
    { 0x5CC5, 19, 19 }, /* cmp byte ptr [enter_unhooks], 1 */
    { 0x5CCA, 17, 17 }, /* jmp loc_01F0 */
    { 0x5CCD, 4, 4 }, /* mov ax, 0x5c70 */
    { 0x5CD0, 8, 8 }, /* shr ax, 1 */
    { 0x5CD2, 8, 8 }, /* shr ax, 1 */
    { 0x5CD4, 8, 8 }, /* shr ax, 1 */
    { 0x5CD6, 8, 8 }, /* shr ax, 1 */
    { 0x5CD8, 2, 2 }, /* inc ax */
    { 0x5CD9, 4, 4 }, /* mov bx, cs */
    { 0x5CDB, 5, 5 }, /* add ax, bx */
    { 0x5CDD, 4, 4 }, /* mov es, ax */
    { 0x5CDF, 4, 4 }, /* mov cx, 0x3a84 */
    { 0x5CE2, 5, 5 }, /* xor si, si */
    { 0x5CE4, 5, 5 }, /* xor di, di */
    { 0x5CE6, 5, 5 }, /* xor bp, bp */
    { 0x5CE8, 20, 20 }, /* ret */
    { 0x5CE9, 19, 19 }, /* mov byte ptr [cga_mode_ctrl], 0x1a */
    { 0x5CEE, 19, 19 }, /* mov byte ptr [editor_active], 1 */
    { 0x5CF3, 21, 21 }, /* call clear_screen */
    { 0x5CF6, 4, 4 }, /* mov si, 0x3a24 */
    { 0x5CF9, 21, 21 }, /* call print_str_list */
    { 0x5CFC, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x5CFF, 5, 5 }, /* or al, al */
    { 0x5D01, 4, 16 }, /* jns loc_5CFC */
    { 0x5D03, 19, 19 }, /* mov byte ptr [editor_key], 0 */
    { 0x5D08, 6, 6 }, /* and al, 0x7f */
    { 0x5D0A, 6, 6 }, /* cmp al, 0x61 */
    { 0x5D0C, 4, 16 }, /* je loc_5D18 */
    { 0x5D0E, 6, 6 }, /* cmp al, 0x62 */
    { 0x5D10, 4, 16 }, /* je loc_5D1D */
    { 0x5D12, 6, 6 }, /* cmp al, 0x63 */
    { 0x5D14, 4, 16 }, /* je loc_5D27 */
    { 0x5D16, 4, 16 }, /* jne loc_5CFC */
    { 0x5D18, 4, 4 }, /* mov si, 0x4075 */
    { 0x5D1B, 17, 17 }, /* jmp loc_5D2A */
    { 0x5D1D, 4, 4 }, /* mov si, 0x408b */
    { 0x5D20, 19, 19 }, /* mov byte ptr [cga_mode_ctrl], 0x1e */
    { 0x5D25, 17, 17 }, /* jmp loc_5D2A */
    { 0x5D27, 4, 4 }, /* mov si, 0x408b */
    { 0x5D2A, 5, 5 }, /* xor bx, bx */
    { 0x5D2C, 17, 17 }, /* mov ax, word ptr [bx + si] */
    { 0x5D2E, 18, 18 }, /* mov word ptr [bx + display_colours], ax */
    { 0x5D32, 6, 6 }, /* add bx, 2 */
    { 0x5D35, 6, 6 }, /* cmp bx, 0x16 */
    { 0x5D38, 4, 16 }, /* jne loc_5D2C */
    { 0x5D3A, 19, 19 }, /* cmp byte ptr [backup_option], 1 */
    { 0x5D3F, 4, 16 }, /* jne loc_5D57 */
    { 0x5D41, 21, 21 }, /* call check_master_disk */
    { 0x5D44, 4, 16 }, /* jae loc_5D5F */
    { 0x5D46, 19, 19 }, /* mov byte ptr [0x3a22], 1 */
    { 0x5D4B, 21, 21 }, /* call clear_screen */
    { 0x5D4E, 4, 4 }, /* mov si, 0x3b14 */
    { 0x5D51, 21, 21 }, /* call print_str_list */
    { 0x5D54, 17, 17 }, /* jmp loc_5D68 */
    { 0x5D57, 21, 21 }, /* call check_master_disk */
    { 0x5D5A, 4, 16 }, /* jae loc_5D5F */
    { 0x5D5C, 17, 17 }, /* jmp loc_6311 */
    { 0x5D5F, 21, 21 }, /* call clear_screen */
    { 0x5D62, 4, 4 }, /* mov si, 0x3b7f */
    { 0x5D65, 21, 21 }, /* call print_str_list */
    { 0x5D68, 12, 12 }, /* mov al, byte ptr [editor_key] */
    { 0x5D6B, 5, 5 }, /* or al, al */
    { 0x5D6D, 4, 16 }, /* jns loc_5D68 */
    { 0x5D6F, 19, 19 }, /* mov byte ptr [editor_key], 0 */
    { 0x5D74, 6, 6 }, /* and al, 0x7f */
    { 0x5D76, 6, 6 }, /* cmp al, 0x61 */
    { 0x5D78, 4, 16 }, /* je loc_5D92 */
    { 0x5D7A, 6, 6 }, /* cmp al, 0x62 */
    { 0x5D7C, 4, 16 }, /* je loc_5DA0 */
    { 0x5D7E, 19, 19 }, /* cmp byte ptr [0x3a22], 1 */
    { 0x5D83, 4, 16 }, /* jne loc_5D68 */
    { 0x5D85, 19, 19 }, /* cmp byte ptr [backup_option], 1 */
    { 0x5D8A, 4, 16 }, /* jne loc_5D68 */
    { 0x5D8C, 6, 6 }, /* cmp al, 0x63 */
    { 0x5D8E, 4, 16 }, /* je loc_5D9D */
    { 0x5D90, 4, 16 }, /* jne loc_5D68 */
    { 0x5D92, 12, 12 }, /* inc byte ptr [demo_request] */
    { 0x5D96, 17, 17 }, /* jmp loc_5DA0 */
    { 0x5D9D, 21, 21 }, /* call disk_backup */
    { 0x5DA0, 19, 19 }, /* mov byte ptr [editor_active], 0 */
    { 0x5DA5, 20, 20 }, /* ret */
    { 0x5DA6, 2, 2 }, /* cli */
    { 0x5DA7, 5, 5 }, /* xor ax, ax */
    { 0x5DA9, 4, 4 }, /* mov es, ax */
    { 0x5DAB, 4, 4 }, /* mov bx, cs */
    { 0x5DAD, 4, 4 }, /* mov ax, 0x970 */
    { 0x5DB0, 26, 26 }, /* xchg word ptr es:[0x24], ax */
    { 0x5DB5, 26, 26 }, /* xchg word ptr es:[0x26], bx */
    { 0x5DBA, 12, 12 }, /* mov word ptr [old_int9], ax */
    { 0x5DBD, 18, 18 }, /* mov word ptr [old_int9+2], bx */
    { 0x5DC1, 2, 2 }, /* sti */
    { 0x5DC2, 20, 20 }, /* ret */
    { 0x5DC3, 2, 2 }, /* cli */
    { 0x5DC4, 5, 5 }, /* xor ax, ax */
    { 0x5DC6, 4, 4 }, /* mov es, ax */
    { 0x5DC8, 4, 4 }, /* mov bx, cs */
    { 0x5DCA, 4, 4 }, /* mov ax, 0x7a0 */
    { 0x5DCD, 26, 26 }, /* xchg word ptr es:[0x20], ax */
    { 0x5DD2, 26, 26 }, /* xchg word ptr es:[0x22], bx */
    { 0x5DD7, 12, 12 }, /* mov word ptr [old_int8], ax */
    { 0x5DDA, 18, 18 }, /* mov word ptr [old_int8+2], bx */
    { 0x5DDE, 4, 4 }, /* mov al, 0x80 */
    { 0x5DE0, 12, 12 }, /* out 0x42, al */
    { 0x5DE2, 12, 12 }, /* out 0x42, al */
    { 0x5DE4, 19, 19 }, /* mov word ptr [timer_hooked], 1 */
    { 0x5DEA, 2, 2 }, /* sti */
    { 0x5DEB, 14, 14 }, /* test byte ptr [0x557], 0xff */
    { 0x5DF0, 4, 16 }, /* je loc_5E1B */
    { 0x5DF2, 16, 16 }, /* push ds */
    { 0x5DF3, 19, 19 }, /* mov byte ptr [0x557], 0 */
    { 0x5DF8, 5, 5 }, /* xor ax, ax */
    { 0x5DFA, 4, 4 }, /* mov es, ax */
    { 0x5DFC, 11, 11 }, /* mov es, word ptr es:[0x122] */
    { 0x5E01, 4, 4 }, /* mov ax, 0xb800 */
    { 0x5E04, 4, 4 }, /* mov ds, ax */
    { 0x5E06, 4, 4 }, /* mov si, 0xfa0 */
    { 0x5E09, 4, 4 }, /* mov di, si */
    { 0x5E0B, 4, 4 }, /* mov cx, 0x7d0 */
    { 0x5E0E, 36, 36 }, /* rep movsw word ptr es:[di], word ptr [si] */
    { 0x5E10, 4, 4 }, /* mov si, 0x2fa0 */
    { 0x5E13, 4, 4 }, /* mov di, si */
    { 0x5E15, 4, 4 }, /* mov cx, 0x7d0 */
    { 0x5E18, 36, 36 }, /* rep movsw word ptr es:[di], word ptr [si] */
    { 0x5E1A, 14, 14 }, /* pop ds */
    { 0x5E1B, 19, 19 }, /* mov word ptr [clear_words], 0x848 */
    { 0x5E21, 19, 19 }, /* mov word ptr [draw_colour], 0xf00f */
    { 0x5E27, 19, 19 }, /* mov word ptr [blit_words0], 0x848 */
    { 0x5E2D, 19, 19 }, /* mov word ptr [blit_words1], 0x848 */
    { 0x5E33, 21, 21 }, /* call obi_readout */
    { 0x5E36, 21, 21 }, /* call controls_redraw */
    { 0x5E39, 21, 21 }, /* call sub_0790 */
    { 0x5E3C, 20, 20 }, /* ret */
    { 0x6254, 16, 16 }, /* push ds */
    { 0x6255, 5, 5 }, /* xor ax, ax */
    { 0x6257, 4, 4 }, /* mov ds, ax */
    { 0x6259, 11, 11 }, /* mov word ptr [2], cs */
    { 0x625D, 19, 19 }, /* mov word ptr [0], 0x4dc6 */
    { 0x6263, 14, 14 }, /* pop ds */
    { 0x6264, 20, 20 }, /* ret */
    { 0x6265, 16, 16 }, /* push ds */
    { 0x6266, 5, 5 }, /* xor ax, ax */
    { 0x6268, 4, 4 }, /* mov ds, ax */
    { 0x626A, 4, 4 }, /* mov ax, 0x7f0 */
    { 0x626D, 12, 12 }, /* mov word ptr es:[0x28], ax */
    { 0x6271, 11, 11 }, /* mov word ptr es:[0x2a], cs */
    { 0x6276, 12, 12 }, /* mov word ptr es:[0x2c], ax */
    { 0x627A, 11, 11 }, /* mov word ptr es:[0x2e], cs */
    { 0x627F, 12, 12 }, /* mov word ptr es:[0x30], ax */
    { 0x6283, 11, 11 }, /* mov word ptr es:[0x32], cs */
    { 0x6288, 12, 12 }, /* mov word ptr es:[0x34], ax */
    { 0x628C, 11, 11 }, /* mov word ptr es:[0x36], cs */
    { 0x6291, 12, 12 }, /* mov word ptr es:[0x3c], ax */
    { 0x6295, 11, 11 }, /* mov word ptr es:[0x3e], cs */
    { 0x629A, 14, 14 }, /* pop ds */
    { 0x629B, 20, 20 }, /* ret */
    { 0x6311, 21, 21 }, /* call clear_screen */
    { 0x6314, 4, 4 }, /* mov si, 0x3dfe */
    { 0x6317, 21, 21 }, /* call print_str_list */
    { 0x631A, 17, 17 }, /* jmp loc_631A */
};

#endif
