"""Generate src/natives/sound_cycles.h: the emulated cost of every original instruction in the
subphase 3.19 sound routines (int8_timer, sound_update, speaker_tone: 0050:07A0-0955, and
speaker_off 3B29-3B36), for the natives in src/natives/sound.c.

usage: python tools/gen_sound_cycles.py

Same method and requirements as tools/gen_editor_cycles.py (whose harness this reuses). The
sound_update table targets 0896-08A8 and 08CB-08D2 are listed as data in extracted/fs1.asm
(no trace session reached them), so their instructions are given here by hand.
"""
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_editor_cycles as ged  # noqa: E402

ROOT = ged.ROOT
OUT = os.path.join(ROOT, "src", "natives", "sound_cycles.h")
ged.RANGES = [(0x07A0, 0x0955), (0x3B29, 0x3B36)]

# Untraced code inside 0896-08D2: (address, length, text).
EXTRA = [
    (0x0896, 5, "cmp byte ptr [stalled], 0"),
    (0x089B, 2, "je loc_08C5"),
    (0x089D, 3, "mov ax, 0x5dc"),
    (0x08A0, 3, "call speaker_tone"),
    (0x08A3, 1, "ret"),
    (0x08A4, 1, "nop"),
    (0x08A5, 1, "nop"),
    (0x08A6, 1, "nop"),
    (0x08A7, 1, "nop"),
    (0x08A8, 1, "ret"),
    (0x08CB, 3, "mov ax, 0x80"),
    (0x08CE, 3, "call speaker_tone"),
    (0x08D1, 2, "jmp loc_08C5"),
]


def main():
    ins = sorted(ged.instructions() + EXTRA)
    gcc = shutil.which("gcc") or r"C:\msys64\mingw64\bin\gcc.exe"
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "h.c")
        exe = os.path.join(tmp, "h.exe")
        open(src, "w").write(ged.HARNESS)
        env = dict(os.environ)
        env["PATH"] = os.path.dirname(gcc) + os.pathsep + env.get("PATH", "")
        subprocess.run([gcc, "-O1", "-I", os.path.join(ROOT, "src"), src, os.path.join(ROOT, "src", "cpu8086.c"),
                        "-o", exe], check=True, env=env)
        inp = "".join(f"{a:x} {(a + n) & 0xFFFF:x}\n" for a, n, _ in ins)
        r = subprocess.run([exe, ged.MEM], input=inp, capture_output=True, text=True, check=True, env=env)
    costs = {}
    for line in r.stdout.split("\n"):
        if line.strip():
            a, f, j = line.split()
            costs[int(a, 16)] = (int(f), int(j))
    lines = []
    for a, _, text in ins:
        f, j = costs[a]
        if f < 0:
            f = j  # unconditional transfer: one cost
        if j < 0:
            j = f
        lines.append(f"    {{ 0x{a:04X}, {f}, {j} }}, /* {text} */")
    hdr = (
        "/* Emulated cycles of each original instruction in the subphase 3.19 sound routines\n"
        " * (0050:07A0-0955, 3B29-3B36), from the cpu8086.c cost model; generated by\n"
        " * tools/gen_sound_cycles.py (do not edit): address, cost (for a conditional jump: when it\n"
        " * falls through), cost when it jumps. */\n"
        "#ifndef FS1_SOUND_CYCLES_H\n#define FS1_SOUND_CYCLES_H\n\n#include <stdint.h>\n\n"
        "typedef struct SoundInsCost {\n    uint16_t addr;\n    uint8_t cost, taken;\n} SoundInsCost;\n\n"
        "static const SoundInsCost sound_ins_cost[] = {\n")
    open(OUT, "w", newline="\n").write(hdr + "\n".join(lines) + "\n};\n\n#endif\n")
    print(f"wrote {OUT}: {len(lines)} instructions")


if __name__ == "__main__":
    sys.exit(main())
