"""Generate src/natives/startup_cycles.h: the emulated cost of every original instruction in the
subphase 3.22 routines (start-up code, editor_main / editor_get_input, the remaining frame and
timer routines), for the natives in src/natives/startup.c.

usage: python tools/gen_startup_cycles.py

Same method and requirements as tools/gen_editor_cycles.py (whose harness this reuses). For a REP
string instruction the table holds the cost with CX = 2; startup.c derives the per-element cost.
"""
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_editor_cycles as ged  # noqa: E402

ROOT = ged.ROOT
OUT = os.path.join(ROOT, "src", "natives", "startup_cycles.h")
ged.RANGES = [(0x01F0, 0x01F8), (0x04FB, 0x05EF), (0x0629, 0x0658), (0x0732, 0x0742), (0x0790, 0x07A0),
              (0x110C, 0x114C), (0x13C6, 0x1447), (0x1CEC, 0x1CFF), (0x2EDB, 0x2EEC), (0x3640, 0x368A),
              (0x3703, 0x3855), (0x4A82, 0x4AF7), (0x4DC6, 0x4DD3), (0x5600, 0x561E), (0x5AD7, 0x5B88),
              (0x5C9F, 0x5E3D), (0x6254, 0x629C), (0x0211, 0x0213), (0x6311, 0x631C)]

EXTRA = []


def main():
    ins = sorted(ged.instructions() + EXTRA)
    gcc = shutil.which("gcc") or r"C:\msys64\mingw64\bin\gcc.exe"
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "h.c")
        exe = os.path.join(tmp, "h.exe")
        open(src, "w").write(ged.HARNESS)
        env = dict(os.environ)
        env["PATH"] = os.path.dirname(gcc) + os.pathsep + env.get("PATH", "")
        subprocess.run([gcc, "-O1", "-I", os.path.join(ROOT, "src"), src, os.path.join(ROOT, "src", "cpu8086.c"), os.path.join(ROOT, "src", "cpu_core.c"),
                        "-o", exe], check=True, env=env)
        inp = "".join(f"{a:x} {(a + n) & 0xFFFF:x}\n" for a, n, _ in ins)
        r = subprocess.run([exe, ged.MEM], input=inp, capture_output=True, text=True, check=True, env=env)
    costs = {}
    for line in r.stdout.split("\n"):
        if line.strip():
            a, f, j = line.split()
            costs[int(a, 16)] = (int(f), int(j))
    lines = []
    for a, _, text in ins:
        f, j = costs[a]
        if f < 0:
            f = j  # unconditional transfer: one cost
        if j < 0:
            j = f
        lines.append(f"    {{ 0x{a:04X}, {f}, {j} }}, /* {text} */")
    hdr = (
        "/* Emulated cycles of each original instruction in the subphase 3.22 routines (start-up code,\n"
        " * editor loop, frame and timer leftovers), from the cpu8086.c\n"
        " * cost model; generated by tools/gen_startup_cycles.py (do not edit): address, cost (for a\n"
        " * conditional jump or LOOP: when it falls through; for REP: with CX = 2), cost when it jumps. */\n"
        "#ifndef FS1_STARTUP_CYCLES_H\n#define FS1_STARTUP_CYCLES_H\n\n#include <stdint.h>\n\n"
        "typedef struct SuInsCost {\n    uint16_t addr;\n    uint8_t cost, taken;\n} SuInsCost;\n\n"
        "static const SuInsCost su_ins_cost[] = {\n")
    open(OUT, "w", newline="\n").write(hdr + "\n".join(lines) + "\n};\n\n#endif\n")
    print(f"wrote {OUT}: {len(lines)} instructions")


if __name__ == "__main__":
    sys.exit(main())
