"""Generate src/natives/editor_cycles.h: the emulated cost of every original instruction in the
subphase 3.16 routines (editor, presets, start-up disk check), for the natives in
src/natives/editor.c.

usage: python tools/gen_editor_cycles.py

Needs extracted/fs1.asm (tools/fs1dis.py) and extracted/boot_mem.bin (tools/pc_loadstream.py),
and gcc (MSYS2 MinGW on Windows). Each instruction is single-stepped on src/cpu8086.c with
several flag and CX settings; the cost when it falls through and the cost when it jumps are
recorded (for a conditional jump or LOOP). The cpu8086.c cost model does not depend on data for
any instruction in these ranges (no REP, no shift by CL).
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, "extracted", "fs1.asm")
MEM = os.path.join(ROOT, "extracted", "boot_mem.bin")
OUT = os.path.join(ROOT, "src", "natives", "editor_cycles.h")

# [lo, hi) offsets in segment 0050
RANGES = [(0x00BE, 0x0170), (0x017C, 0x01A0), (0x01AD, 0x01E8), (0x3640, 0x3CC0), (0x60F8, 0x6113), (0x629C, 0x62D2)]

HARNESS = r"""
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpu8086.h"
static uint8_t in8(void *c, uint16_t p) { (void)c; (void)p; return 0; }
static void out8(void *c, uint16_t p, uint8_t v) { (void)c; (void)p; (void)v; }
static void hle(void *c, uint8_t s) { (void)c; (void)s; }
int main(int argc, char **argv)
{
    static uint8_t mem[CPU_MEM_SIZE];
    FILE *f = fopen(argv[1], "rb");
    if (!f || fread(mem, 1, CPU_MEM_SIZE, f) == 0) return 1;
    fclose(f);
    static uint32_t la[65536]; static uint8_t lo[65536];
    CpuWriteLog log = { la, lo, 0, 65536, false };
    static const uint16_t fl[] = { 0x0000, 0x0001, 0x0040, 0x0080, 0x0800, 0x0880, 0x08C1, 0x00C1, 0x0041 };
    unsigned addr, next;
    while (scanf("%x %x", &addr, &next) == 2) {
        int fall = -1, jump = -1;
        for (int cx = 1; cx <= 2; cx++)
            for (unsigned k = 0; k < sizeof fl / sizeof fl[0]; k++) {
                Cpu8086 c;
                memset(&c, 0, sizeof c);
                c.mem = mem;
                c.rom_start = CPU_MEM_SIZE;
                c.bus = (CpuBus){ NULL, in8, out8, hle };
                c.write_log = &log;
                log.count = 0;
                c.regs[R_AX] = 1; c.regs[R_CX] = (uint16_t)cx; c.regs[R_DX] = 0;
                c.regs[R_BX] = 0x100; c.regs[R_SI] = 0x100; c.regs[R_DI] = 0x100; c.regs[R_BP] = 0x100;
                c.regs[R_SP] = 0x400;
                c.sregs[S_CS] = 0x0050; c.sregs[S_DS] = 0x0618; c.sregs[S_ES] = 0x0618; c.sregs[S_SS] = 0;
                c.ip = (uint16_t)addr;
                c.flags = (uint16_t)(0xF002 | fl[k]);
                int used = cpu_step(&c);
                for (uint32_t i = log.count; i-- > 0;)
                    mem[log.addr[i]] = log.old[i];
                if (c.ip == next) fall = used; else jump = used;
            }
        printf("%x %d %d\n", addr, fall, jump);
    }
    return 0;
}
"""


def instructions():
    out = []
    for line in open(ASM, encoding="utf-8"):
        m = re.match(r"    ([0-9A-F]{4})  ((?:[0-9A-F]{2} )+)\s+(\S.*?)\s*;", line)
        if not m:
            continue
        a = int(m.group(1), 16)
        if any(lo <= a < hi for lo, hi in RANGES):
            out.append((a, len(m.group(2).split()), m.group(3).strip()))
    return out


def main():
    ins = instructions()
    gcc = shutil.which("gcc") or r"C:\msys64\mingw64\bin\gcc.exe"
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "h.c")
        exe = os.path.join(tmp, "h.exe")
        open(src, "w").write(HARNESS)
        env = dict(os.environ)
        env["PATH"] = os.path.dirname(gcc) + os.pathsep + env.get("PATH", "")
        subprocess.run([gcc, "-O1", "-I", os.path.join(ROOT, "src"), src, os.path.join(ROOT, "src", "cpu8086.c"),
                        "-o", exe], check=True, env=env)
        inp = "".join(f"{a:x} {(a + n) & 0xFFFF:x}\n" for a, n, _ in ins)
        r = subprocess.run([exe, MEM], input=inp, capture_output=True, text=True, check=True, env=env)
    costs = {}
    for line in r.stdout.split("\n"):
        if line.strip():
            a, f, j = line.split()
            costs[int(a, 16)] = (int(f), int(j))
    lines = []
    for a, _, text in ins:
        f, j = costs[a]
        if f < 0:
            f = j  # unconditional transfer: one cost
        if j < 0:
            j = f
        lines.append(f"    {{ 0x{a:04X}, {f}, {j} }}, /* {text} */")
    hdr = (
        "/* Emulated cycles of each original instruction in the subphase 3.16 routines, from the\n"
        " * cpu8086.c cost model; generated by tools/gen_editor_cycles.py (do not edit): address,\n"
        " * cost (for a conditional jump or LOOP: when it falls through), cost when it jumps. */\n"
        "#ifndef FS1_EDITOR_CYCLES_H\n#define FS1_EDITOR_CYCLES_H\n\n#include <stdint.h>\n\n"
        "typedef struct EdInsCost {\n    uint16_t addr;\n    uint8_t cost, taken;\n} EdInsCost;\n\n"
        "static const EdInsCost ed_ins_cost[] = {\n")
    open(OUT, "w", newline="\n").write(hdr + "\n".join(lines) + "\n};\n\n#endif\n")
    print(f"wrote {OUT}: {len(lines)} instructions")


if __name__ == "__main__":
    sys.exit(main())
