"""Generate src/natives/mainloop_cycles.h: the emulated cost of every original instruction in the
subphase 3.21 routines (main_loop 01F8-02CA, the crash delay 0639-0643, view_overlay_marks
0658-0731, the key-wait loops 3726, 5CFC, 5D68 and draw_view_frame 5A9E-5AD6), for the natives in
src/natives/mainloop.c.

usage: python tools/gen_mainloop_cycles.py

Same method and requirements as tools/gen_editor_cycles.py (whose harness this reuses). For a REP
string instruction the table holds the cost with CX = 2; mainloop.c derives the per-element cost.
"""
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_editor_cycles as ged  # noqa: E402

ROOT = ged.ROOT
OUT = os.path.join(ROOT, "src", "natives", "mainloop_cycles.h")
ged.RANGES = [(0x01F8, 0x02CB), (0x0639, 0x0644), (0x0658, 0x0732), (0x3726, 0x372D), (0x5A9E, 0x5AD7),
              (0x5CFC, 0x5D03), (0x5D68, 0x5D6F)]

EXTRA = []


def main():
    ins = sorted(ged.instructions() + EXTRA)
    gcc = shutil.which("gcc") or r"C:\msys64\mingw64\bin\gcc.exe"
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "h.c")
        exe = os.path.join(tmp, "h.exe")
        open(src, "w").write(ged.HARNESS)
        env = dict(os.environ)
        env["PATH"] = os.path.dirname(gcc) + os.pathsep + env.get("PATH", "")
        subprocess.run([gcc, "-O1", "-I", os.path.join(ROOT, "src"), src, os.path.join(ROOT, "src", "cpu8086.c"),
                        "-o", exe], check=True, env=env)
        inp = "".join(f"{a:x} {(a + n) & 0xFFFF:x}\n" for a, n, _ in ins)
        r = subprocess.run([exe, ged.MEM], input=inp, capture_output=True, text=True, check=True, env=env)
    costs = {}
    for line in r.stdout.split("\n"):
        if line.strip():
            a, f, j = line.split()
            costs[int(a, 16)] = (int(f), int(j))
    lines = []
    for a, _, text in ins:
        f, j = costs[a]
        if f < 0:
            f = j  # unconditional transfer: one cost
        if j < 0:
            j = f
        lines.append(f"    {{ 0x{a:04X}, {f}, {j} }}, /* {text} */")
    hdr = (
        "/* Emulated cycles of each original instruction in the subphase 3.21 routines (main loop,\n"
        " * crash delay, view_overlay_marks, key-wait loops, draw_view_frame), from the cpu8086.c\n"
        " * cost model; generated by tools/gen_mainloop_cycles.py (do not edit): address, cost (for a\n"
        " * conditional jump or LOOP: when it falls through; for REP: with CX = 2), cost when it jumps. */\n"
        "#ifndef FS1_MAINLOOP_CYCLES_H\n#define FS1_MAINLOOP_CYCLES_H\n\n#include <stdint.h>\n\n"
        "typedef struct MlInsCost {\n    uint16_t addr;\n    uint8_t cost, taken;\n} MlInsCost;\n\n"
        "static const MlInsCost ml_ins_cost[] = {\n")
    open(OUT, "w", newline="\n").write(hdr + "\n".join(lines) + "\n};\n\n#endif\n")
    print(f"wrote {OUT}: {len(lines)} instructions")


if __name__ == "__main__":
    sys.exit(main())
