"""Generate src/natives/sceneryload_cycles.h: the emulated cost of every original instruction in
the subphase 3.20 scenery-loading code (the boot-sector disk routines 0050:00EA-01AC and
select_scenery_area 03CA-045C), for the natives in src/natives/sceneryload.c.

usage: python tools/gen_sceneryload_cycles.py

Same method and requirements as tools/gen_editor_cycles.py (whose harness this reuses). An
INT 13h is listed with the cost of the INT instruction alone; sceneryload.c adds the BIOS stub
(HLE trap and IRET).
"""
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_editor_cycles as ged  # noqa: E402

ROOT = ged.ROOT
OUT = os.path.join(ROOT, "src", "natives", "sceneryload_cycles.h")
ged.RANGES = [(0x00EA, 0x01AD), (0x03CA, 0x045D)]


def main():
    ins = sorted(ged.instructions())
    gcc = shutil.which("gcc") or r"C:\msys64\mingw64\bin\gcc.exe"
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "h.c")
        exe = os.path.join(tmp, "h.exe")
        open(src, "w").write(ged.HARNESS)
        env = dict(os.environ)
        env["PATH"] = os.path.dirname(gcc) + os.pathsep + env.get("PATH", "")
        subprocess.run([gcc, "-O1", "-I", os.path.join(ROOT, "src"), src, os.path.join(ROOT, "src", "cpu8086.c"), os.path.join(ROOT, "src", "cpu_core.c"),
                        "-o", exe], check=True, env=env)
        inp = "".join(f"{a:x} {(a + n) & 0xFFFF:x}\n" for a, n, _ in ins)
        r = subprocess.run([exe, ged.MEM], input=inp, capture_output=True, text=True, check=True, env=env)
    costs = {}
    for line in r.stdout.split("\n"):
        if line.strip():
            a, f, j = line.split()
            costs[int(a, 16)] = (int(f), int(j))
    lines = []
    for a, _, text in ins:
        f, j = costs[a]
        if f < 0:
            f = j  # unconditional transfer: one cost
        if j < 0:
            j = f
        lines.append(f"    {{ 0x{a:04X}, {f}, {j} }}, /* {text} */")
    hdr = (
        "/* Emulated cycles of each original instruction in the subphase 3.20 scenery-loading code\n"
        " * (0050:00EA-01AC, 03CA-045C), from the cpu8086.c cost model; generated by\n"
        " * tools/gen_sceneryload_cycles.py (do not edit): address, cost (for a conditional jump or\n"
        " * LOOP: when it falls through), cost when it jumps. */\n"
        "#ifndef FS1_SCENERYLOAD_CYCLES_H\n#define FS1_SCENERYLOAD_CYCLES_H\n\n#include <stdint.h>\n\n"
        "typedef struct SlInsCost {\n    uint16_t addr;\n    uint8_t cost, taken;\n} SlInsCost;\n\n"
        "static const SlInsCost sl_ins_cost[] = {\n")
    open(OUT, "w", newline="\n").write(hdr + "\n".join(lines) + "\n};\n\n#endif\n")
    print(f"wrote {OUT}: {len(lines)} instructions")


if __name__ == "__main__":
    sys.exit(main())
